### ISSUE TITLE
renameDestDir fails if dir doesn't exist

### ISSUE THREAD

**Issue by anthon** [expressjs/multer#100]
Loving the new `renameDestDir` option, but it fails when trying to save to a dir which doesn't exist yet.

Adding a `if(!fs.existsSync(newFileDir)) fs.mkdirSync(newFileDir);` before creating the WriteStream, perhaps?

**Comment by anthon** [comment]
My bad. A check like that might just as well go in the option func.

**Comment by jpfluger** [comment]
Cool.
