### ISSUE TITLE
Not stable at all

### ISSUE THREAD

**Issue by alexandressartori** [expressjs/multer#1000]
I'm getting really frustrated at the instability of multer... I'm trying to send a multipart formdata with a file AND a body with information relative to the user... sometimes it gets the body but not the file, sometimes it gets the file but not the body, sometimes I dont have none of those. It's completely random. I haven't changed the code at all and I keep getting random results. I tried upload.single('file'), upload.any(), upload.array('file')... and each time I look for "how to send body with multipart formData" I found a LOT of users getting the same error and the solutions are quite random... I lost an entire day looking for a solution but everytime I get the same random results.

here is my code:

```
const util = require("util");
const multer = require("multer");
const fs = require("fs");
const maxSize = 12 * 1024 * 1024;

`let storage = multer.diskStorage({`
    destination: (req, file, cb) => {
        console.log(req.file)
        console.log(file)
        if (!(fs.existsSync("./resources/static/assets/uploads/"+req.body.id))) {
            fs.mkdirSync("./resources/static/assets/uploads/"+req.body.id)
        }
        cb(null, "./resources/static/assets/uploads/"+req.body.id);
    },
    filename: (req, file, cb) => {
        cb(null, file.originalname);
    },
});

let uploadFile = multer({
    storage: storage,
    limits: { fileSize: maxSize },
}).single("file"); //tried any(), array, single...

let uploadFileMiddleware = util.promisify(uploadFile);
module.exports = uploadFileMiddleware; 
```
I'm calling this in a file controller:

```
const uploadFile = require("../middleware/upload");

const upload = async (req, res) => {
    try {
        await uploadFile(req, res);
         if (req.file == undefined) {
             return res.status(401).send({ message: "Please upload a file!" });
         }

        res.status(200).send({
            message: "Uploaded the file successfully: " + req.body.id,
        });
    } catch (err) {
        console.log(err)
        console.log(req.file)
        res.status(500).send({
            message: `Could not upload the file: ${req.file}. ${err}`,
        });
    }
};
...
module.exports = {
    upload,
    getListFiles,
    download,
};
```
Looks like the upload.any() looks for the first object it finds in req (body or file) and then ignore the rest of the object. If that is the case, It should be reported as a bug.

**Comment by LinusU** [comment]
Hmm, I've never seen Multer randomly behaving different. Would you be able to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that I can test?

**Comment by alexandressartori** [comment]
I Kind of found the problem... Turns out that if I add the file first when creating the formData object, multer only gets the file and ignore the rest of the formData. I have to be careful now when creating the formData to include all the body content before I can add the file(s). Is this a bug?

**Comment by LinusU** [comment]
It seems like you are trying to read the body fields at the point where the file is just coming in. If the fields aren't added before the file, then the browser will not have sent the fields to us at that point and thus we cannot give them to you. So this is simply how form data works...

If you need to have the fields available at the point where the file comes in you need to make sure that the browser sends them before the file. Happy hacking!
