### ISSUE TITLE
NPM still serving version 0.1.7

### ISSUE THREAD

**Issue by tripolet333** [expressjs/multer#101]
Tried to update multer to the latest version (0.1.8) but NPM is still serving up 0.1.7. Can somebody update NPM to serve the latest version? For now I'll just grab from the repo, but just in case anyone else runs into this.

Thanks!

**Comment by jpfluger** [comment]
@hacksparrow  or @Fishrock123 will need to update the npm.

**Comment by hacksparrow** [comment]
Published - https://www.npmjs.com/package/multer
