### ISSUE TITLE
Is Multer 2.0 still alive?

### ISSUE THREAD

**Issue by pubmikeb** [expressjs/multer#1011]
Multer has been shifted to the 2.0.0 RC2 since March 2020.
Nowadays it's June 2021, but no RC3/RTM is released.
Moreover, Multer is not compatible with the latest official version of Node.js (16.x.x) anymore.

The question, is Multer project still alive, or should we be switching to alternative solutions?

Thanks.

**Comment by ddsultan** [comment]
What are the alternatives? Thanks.

**Comment by pubmikeb** [comment]
Good question, currently I've made a fork/patched version of Multer due to incompatibility with Node.js 16.x.x.
Hopefully, Multer's team will finish the Multer 2.0 project, it's in RC2 stage now.

**Comment by ddsultan** [comment]
@pubmikeb, thanks for the response. It looks like last change on the RC was done ~1,25 years ago:

![image](https://user-images.githubusercontent.com/2477698/124597799-2db71080-de64-11eb-8334-a86f15a8e33a.png)

**Comment by pubmikeb** [comment]
> @pubmikeb, thanks for the response. It looks like last change on the RC was done ~1,25 years ago:
> 
> ![image](https://user-images.githubusercontent.com/2477698/124597799-2db71080-de64-11eb-8334-a86f15a8e33a.png)

Yes, you're right and that's pity. It used to be a good project but now it doesn't support Node.js 16.x+

**Comment by sosnik** [comment]
> 
> 
> What are the alternatives? Thanks.

The alternatives are, in no particular order:

* [node-formidable/formidable](github.com/node-formidable/formidable) - in the same state as this project, [npm is at 1.2.2](https://www.npmjs.com/package/formidable) and hasn't been updated for years; they have 2.x and 3.x branches. 2.0.0 is ready-ish for release and [available as an npm canary build](https://registry.npmjs.org/-/package/formidable/dist-tags), while 3.x is still in beta. The package maintainer / person with npm access hasn't been available for a number of months at the time of writing this. 
* [pillarjs/multiparty](github.com/pillarjs/multiparty) - they claim to be slower than busboy, but the benchmark is from 2013!
* [mscdex/busboy](github.com/mscdex/busboy) - which this package is based on, but you'd need to re-write the middleware yourself.

These are the packages with 100k+ weekly downloads on npm; there may be other, less active, ones available. 

FWIW I'm tempted to go with the 3rd option.

**Comment by pubmikeb** [comment]
I would go with `node-formidable/formidable`, it seems like there is some activity in the repo and there are good chances to get a 3.0 in Q3-Q4 2021. The version 3.0 has a new API with modern JS, so if I would adopt the `node-formidable/formidable`, I would go definitely with the version of 3.0 and not 1.2.x which is already deprecated or 2.0, which I assume is a temporarily release.

Generally, in case an external storage is used (e.g. Dropbox, AWS, etc.), it is better to use their native API and forward an uploading stream directly to the storage, without proxying it through the application server to save RAM, CPU, traffic. No API access token exposure required.

**Comment by sosnik** [comment]
> 
> 
> I would go with `node-formidable/formidable`, it seems like there is some activity in the repo and there are good chances to get a v.3.0 in Q3-Q4 2021. The version 3.0 has a new API with the modern JS, so if I would adopt `node-formidable/formidable`, I would go definitely with the version 3.0 and not v.1.2.x which is already deprecated or 2.0, which, I assume, is a temporarily release.
> 
> Generally, in case an external storage is used (e.g. Dropbox, AWS, etc.), it is better to use a native API of a storage service and forward an uploading stream directly to the storage, without proxying it through the application server to save RAM, CPU, and traffic. No storage API access token exposure required.

This project has a very convenient `limit()` function that doesn't have a counterpart in other projects, including `formidable`. Which is why I'm holding out hope for both to release updates so I can compare. 

Native async/await support would be good though.

**Comment by pubmikeb** [comment]
> This project has a very convenient `limit()`

Are you talking about `mscdex/busboy`?

BTW, `async`/`await` support is coming to `node-formidable/formidable` v.3.0.

**Comment by LinusU** [comment]
I just published rc.3 with support for Node.js 16 🚀 

Read more about it here: https://github.com/expressjs/multer/pull/399#issuecomment-889331085

Also, I will close this with the answer "yes", but feel free to ask me any more specific questions and I shall answer!
