### ISSUE TITLE
[docs] [question] Why does the readme use var in place of let / const ?

### ISSUE THREAD

**Issue by YashKumarVerma** [expressjs/multer#1012]
Multer is a **very** popular library, and the readme is even imported in other reputed projects (like express.js docs, link:http://expressjs.com/en/resources/middleware/multer.html).

Is there any particular reason we're using var in the readme? Almost all editors and linters would beserk out on this.

Should we change it to const/let as applicable?

**Comment by LinusU** [comment]
Sorry for the late reply on this.

I agree, we should change it. PR welcome 👍
