### ISSUE TITLE
Multer : req.body is null

### ISSUE THREAD

**Issue by ii02735** [expressjs/multer#1023]
Hello,

I'm trying to upload a file through an express API.
However when I try to fetch the body content, among the file, it gaves the following value : `[Object: null prototype] {}`

Here is the request that I've made with Postman :
![Capture d’écran_2021-08-04_17-47-07](https://user-images.githubusercontent.com/33719388/128212221-9b7d0908-ba92-4542-ba60-e6e29136c443.png)

As you can see, the file is the last element to be sent, it shouldn't be a problem.

Here is my backend code : 

```js
app.post("/register/supplier",(req, res) => {

    const storage = multer.diskStorage({
        destination: (req,res,cb) => cb(null,__dirname + '/../files/kbis/'),
        filename: (req,file,cb) => cb(null, file.name)
    })
    
    const upload = multer({ storage }).single('kbis')
    
    upload(req,res,(err) => {
        console.log(req.body,req.files)
    })

    
    return res.status(200).json({ message: 'testing' })

});
```
I know that a few people met this `req.body` issue, and I tried to follow the proposed leads, but it didn't resolve my issue.
Any ideas ? Thank you for your help !

**Comment by LinusU** [comment]
It seems like you are returning a response before reading up the body. Also, you are recreating the Multer instance on every request.

Could you try changing your code to:

```js
const storage = multer.diskStorage({
    destination: (req,res,cb) => cb(null,__dirname + '/../files/kbis/'),
    filename: (req,file,cb) => cb(null, file.name)
})
    
const upload = multer({ storage }).single('kbis')

app.post("/register/supplier", upload, (req, res) => {
    console.log(req.body,req.files)

    return res.status(200).json({ message: 'testing' })

});
```

**Comment by ii02735** [comment]
Ah thank you for your quick answer @LinusU !

Indeed, I'm recreating the instance on every request, my bad.

I tried what you suggested me, but I have the same result unfortunately.
Here is the logs :
```
 [Object: null prototype] {} {
   kbis: {
     name: '281e67b0-baa8-4933-9282-77258eb3d985.png',
     data: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 04 b1 00 00 03 c9 08 06 00 00 00 ed 69 ba 76 00 00 20 00 49 44 41 54 78 9c ec dd 07 d4 6d 57 59 ... 19146 more bytes>,
     size: 19196,
     encoding: '7bit',
     tempFilePath: '',
     truncated: false,
     mimetype: 'image/png',
     md5: 'fb4eb4e2c3244ccb3894a328ba2aac96',
     mv: [Function: mv]
   }
 }
```

**Comment by LinusU** [comment]
Hmmm, which version of Multer are you using? 🤔 

I can see a `mv` function there in the log which, as far as I know, isn't added by neither Multer 1.x nor 2.x 🤔

**Comment by ii02735** [comment]
I'm using Multer 1.4.2.

About the mv function, hmm I don't know how it came unfortunately :thinking:

**Comment by ii02735** [comment]
In order to find an answer about this `mv` function, I tried to create a simple express server like this :

```js
const express = require('express');
const fileUpload = require('express-fileupload')
const app = express();

app.use(fileUpload())

const multer = require('multer');

const upload = multer().single('kbis')

app.post("/register/supplier", upload, (req, res) => {
    console.log(req.body, req.files)

    return res.status(200).json({ message: 'testing' })

});

app.listen(4000,() => console.log("listening"))
```
And I have the same logs :thinking: 

```
[Object: null prototype] {} {
  kbis: {
    name: '1607423280230.jpeg',
    data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 03 02 02 03 02 02 03 03 03 03 04 03 03 04 05 08 05 05 04 04 05 0a 07 07 06 ... 5665 more bytes>,
    size: 5715,
    encoding: '7bit',
    tempFilePath: '',
    truncated: false,
    mimetype: 'image/jpeg',
    md5: '17632e428e46544f117fd0621e0133dc',
    mv: [Function: mv]
  }
}
```

**Comment by LinusU** [comment]
You are importing and using `express-fileupload` before Multer. So Multer doesn't have any data to work on, since the stream have already been consumed. Removing `express-fileupload` should fix your problems: 

```js
const express = require('express');
const app = express();

const multer = require('multer');

const upload = multer().single('kbis')

app.post("/register/supplier", upload, (req, res) => {
    console.log(req.body, req.files)

    return res.status(200).json({ message: 'testing' })

});

app.listen(4000,() => console.log("listening"))
```

**Comment by ii02735** [comment]
Hello @LinusU 

Thank you for your reply, I didn't know that it could by an issue.
So, I removed `express-fileupload` as you suggested.

But now I have the opposite of my issue :sweat_smile: 
`req.body` is filled as expected, but `req.files` is undefined as the logs tell me :

```js
[Object: null prototype] {
  name: 'hello',
  company: 'workgroup',
  email: 'hello@dev2.com',
  password: 'helloworld',
  currency: '€'
} undefined
```

**Comment by LinusU** [comment]
Since you are using `.single(...)` the file will live at `req.file` (no `s`)

```
const express = require('express');
const app = express();

const multer = require('multer');

const upload = multer().single('kbis')

app.post("/register/supplier", upload, (req, res) => {
    console.log(req.body, req.file)

    return res.status(200).json({ message: 'testing' })

});

app.listen(4000,() => console.log("listening"))
```

**Comment by ii02735** [comment]
Oh you're absolutely right, I didn't pay attention !

Well, it works totally as expected, thank you a lot for your help :smile:
