### ISSUE TITLE
Error: No such built-in module: node:stream/promises in 2.0.0-rc.3

### ISSUE THREAD

**Issue by eashish93** [expressjs/multer#1025]
I'm getting error : `Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/promises` in latest 2.0.0-rc.3. This can be related to : https://github.com/expressjs/multer/blob/explore-new-api/lib/read-body.js#L2

According to node.js doc, `node:stream/promises` added in v15 while 2.0.0-rc.3 support  > 14.13.
I'm using node v14.16.0

**Comment by LinusU** [comment]
Thanks for the report, we should be able to work around this by using `promisify(pipeline)` and importing pipeline from `node:stream`...

**Comment by LinusU** [comment]
Fixed here: ddc1727

**Comment by jonchurch** [comment]
This would have been caught in CI, right? 

@LinusU are you interested in seeing github workflows added here for CI?

**Comment by jonchurch** [comment]
@LinusU Hahha okay I see [`ba4e105` (#399)](https://github.com/expressjs/multer/pull/399/commits/ba4e105ec68ba23a79aff9fc8edbb636fdef05b3) with workflow support!

**Comment by LinusU** [comment]
Hehe, yeah, I think our Travis CI stopped working because we were on the old .org plan...
