### ISSUE TITLE
Seemingly redundant code in fileStream error handler

### ISSUE THREAD

**Issue by jasson15** [expressjs/multer#103]
The following code in  [Line 151-151](https://github.com/expressjs/multer/blob/master/index.js#L151) seems redundant:

```javascript
fileStream.on('error', function(error) {
  // trigger "file error" event
  if (options.onError) { options.onError(error, next); }
  else next(error);
});
```
Because in [Line 167-170](https://github.com/expressjs/multer/blob/master/index.js#L167), we got `fileStream.on('error', ...)` again. No matter `options.inMemory` is `true` or not, `fileStream.on('error', ...)` always works with the same error handler.

``` javascript
if (options.inMemory)
  fileStream.on('error', onFileStreamError );
else 
  ws.on('error', onFileStreamError );
```

Is this simply a miss or is there any reason to do `fileStream.on('error', ...)` twice?

**Comment by jpfluger** [comment]
Hmm... you did spot something: `fileStream` is the read-stream;  `ws` is the write-stream. That means line 167-168 is redundant. All streams will be read but only the write-to-disk stream will go to disk. I think you can have separate errors for read or writes.

**Comment by jasson15** [comment]
So if `fileStream` and `ws` both crash, `onError` will be fired twice, right?

Would it be better if we rename and duplicate `onError` to `onReadFileStreamError` and `onWriteFileStreamError`?

**Comment by jpfluger** [comment]
I don't know without testing. It's true that the writestream handles the filestream, so I would guess the writestream would emit one error. If that's true, then the code segment at 151 goes away but then leave lines 167-170.

**Comment by LinusU** [comment]
All code is rewritten as of `1.0.0`, this should be solved now :)
