### ISSUE TITLE
Expo / Node.JS Single upload

### ISSUE THREAD

**Issue by yonjuukyuu** [expressjs/multer#1032]
Hi there currently trying to upload a image to my server no erros shown, file gets uploaded but doesnt have a file type ,png/.jpg, 

On RN frontend app running on Expo App:
  
           `let formData = new FormData();
            let fileNAme = result.uri;
            let finalName = fileNAme.substr(fileNAme.lastIndexOf("/") + 1);

            let uriParts = result.uri.split(".");
            let fileType = uriParts[uriParts.length - 1];
 
            formData.append("photo", { uri: result.uri, name: finalName, type: `image/${fileType}` });`

 FormData return  an Array of photo, and a object like so:
`
{
          "name": "6DC0B83B-D2E7-4BD4-9CD4-F172C26F4DD0.png",
          "type": "image/png",
          "uri": "file:///var/mobile/Containers/Data/Application/310548E8-EBA2-4A04-A3C9-6604DFF828E6/Library/Caches/ExponentExperienceData/%2540anonymous%252Fsesameapp-0d1a9b89-a091-4fbd-937b-835f87723af0/ImagePicker/6DC0B83B-D2E7-
4BD4-9CD4-F172C26F4DD0.png",
        },`

So here the type and path is correct.

On the backend: 

`
router.post("/editProfile", [auth, upload.single("photo")], async (req,res) =>   {
     const errors = validationResult(req);

      const { imgURl } = req.body;
      const { path } = req.file;

      console.log({ fileName: req.file, body: req.body })
      await User.findOneAndUpdate(
          {"_id": req.user.id,},
          {
            "avatar": {
              _id: path

            }
          }, {new: true, useFindAndModify: false});

      const user = await User.findById(req.user.id).select("-password");
      res.json(user);
 });
`

the Req.File return the photo object and image is upload to folder. but here we see that the path already doesnt end up with the correct typefile 
`{
  fileName: {
    fieldname: 'photo',
    originalname: 'C24DFDB5-7AD3-4F82-9D98-F8F791975A41.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'uploads/',
    filename: 'f71a2bffeca8463c4f68bb296ea19184',
    path: 'uploads\\f71a2bffeca8463c4f68bb296ea19184',
    size: 6109164
  },
  body: [Object: null prototype] {}
}
`

**Comment by LinusU** [comment]
This is expected, and discussed here: https://github.com/expressjs/multer/issues/439

I'm open to a PR that clarifies this in the readme ☺️
