### ISSUE TITLE
acces res.locals.something in multer.diskStorage

### ISSUE THREAD

**Issue by TiduTidu** [expressjs/multer#1033]
After creating the user I want to use the ObjectID from the user to name the image saved by Multer.   
This is how my route looks like
`router.post('/create', upload.any(), createUser, upload.single('userImage'));`
and then the code

        var savedUser = await user.save();
        var createdUserId = savedUser._id;  // use this to add to the profile Image's name 

        var imgExtension = path.extname(req.body.userImage)
        var imgPath = `./images/profileImages/${createdUserId}_profileImage${imgExtension}`
        
        //now update the newly created user with its image 
        await userModel.updateOne({_id: createdUserId},{
            image: {
                path: imgPath,
                contentType: `image/${imgExtension}`  
            }
        });
        // to use in Multer middleware
        res.locals.imgName = String(`${createdUserId}_profileImage${imgExtension}`) 

        res.status(201).json({
            message: "User has been saved",
            userId: createdUserId
        });        
        
        next()

Here the multer.diskStorage

    var storage = multer.diskStorage({
        destination: (req, file, cb) =>{
            cb(null, './images/profileImages')
        },
        filename: (req , file, cb) => {
            const imgName = req.res.locals.imgName // HERE LIES THE PROBLEM
            cb(null, `${imgName}`)
        }
    });`
    export var upload = multer({ storage: storage});

#620 This is the only similar Issue I have found, @LinusU there you said that `res.locals` can be accessed via `req.res`
I have tried every combination from `req.res.imgName` to `req.res.res.locals.imgName` nothing seems to work. 
One important thing the Image does get saved but as undefined, if I add the right image extention I can view it.
I need help :(

**Comment by LinusU** [comment]
You said you tried `req.res.imgName` and `req.res.res.locals.imgName`, but did you try `req.res.locals.imgName` which should be the correct one?

Most importantly though, it seems like you are adding Multer middleware twice, and the first one before `createUser` which means that Multer will run _before_ `createUser`, and thus the value won't be available. Can you try this change?

```diff
- router.post('/create', upload.any(), createUser, upload.single('userImage'));
+ router.post('/create', createUser, upload.single('userImage'));
```
