### ISSUE TITLE
Multer only works with dest

### ISSUE THREAD

**Issue by OmkoBass** [expressjs/multer#1038]
The only way i can get multer to work is with

This gets the image in req.file
```javascript
const upload = multer({ dest: "uploads/" });
```

Here's my original code that won't get the image
```javascript
const postStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, `./thoughts`),
  filename: (req, file, cb) => cb(null, `${file.originalname}-${Date.now()}`),
});

const fileFilter = (req, file, cb) => {
  if (file.mimetype === "image/*") {
    cb(null, true);
  } else {
    cb(null, false);
  }
};

const upload = multer({
  storage: postStorage,
  limits: {
    fileSize: 1024 * 1024 * 5,
  },
  fileFilter: fileFilter,
});
```

It's amazing how a library that once worked is now broken, extremely unreliable. Do you really think only having dest will be good enough for most developers ? This is an embarassement!

**Comment by LinusU** [comment]
The `fileFilter` that you have specified will filter out all files since the `mimetype` will never be `"image/*"`. If you want to accept all mime types starting with `image/` use something like:

```
  fileFilter: (req, file, cb) => cb(null, file.mimetype.startsWith('image/'))
```

-----

> It's amazing how a library that once worked is now broken, extremely unreliable. Do you really think only having dest will be good enough for most developers ? This is an embarassement!

This kind of language is not welcome here. If you want further help you'll have to cut that out...

**Comment by OmkoBass** [comment]
That's smart. Thanks 👍

Someone should put an example like in the documentation, there will be way less repeating issues like this and simmilar. Most of the people don't know that it will break without permissions or that the dir won't be created automatically and simmilar.

**Comment by LinusU** [comment]
From the readme: 

> **Note:** You are responsible for creating the directory when providing `destination` as a function.

-----

> Most of the people don't know that it will break without permissions [...]

Do you have any suggestion on how we might word that? and where to put it?

**Comment by OmkoBass** [comment]
That's a good question, I'd create an examples dir here on this repo. It would contain a few examples like the ones we did and I'd say Examples: 'link to these examples'.
