### ISSUE TITLE
add domain error control

### ISSUE THREAD

**Issue by ashareye** [expressjs/multer#104]
the functions in options, such as changeDest, onFileUploadData, haven't 'next' arguments and can't be caught by onError, so I'd like add  domain-error control And then Error can be thrown in options function and caught by onError or next error handler.

```javascript
 var domain =require('domain'); 
……
……
var doMulter = function(){ 
    // code in 'if (is(req, ['multipart'])) {  } ' originally
}

       if (is(req, ['multipart'])) {
            var dm = domain.create();
            dm.add(options);
            dm.on('error', function (err) {
                console.log('domain caught!');
                if (options.onError) { options.onError(err, next); }
                else next(err);
            });
            dm.run(doMulter);
        }
        else { return next(); }
```

**Comment by jpfluger** [comment]
The [Domain API](https://nodejs.org/api/domain.html) is considered "unstable".  (See [definitions](https://nodejs.org/api/documentation.html) here). I don't know what @hacksparrow's policy (the creator) is very using "unstable" code. As for myself, I'd like to find an alternative solution. Also please see my comments on issue #72.

**Comment by ashareye** [comment]
unstable? some times 'domain' not contains the asynchronous object or functions, but here it works! 
in options:
changeDest: function(dest, req, res) {
        try {
            if (!fs.existsSync(dest)) fs.mkdirSync(dest);
        } catch(err) {
            throw new Error('dest not found');
            return false;
        };
        return dest;
    },
    onFileUploadStart: function (file, req, res) {
        if (file.extension !== 'jpg') {
            throw new Error('wrong file extension!');
            return false;
        };
        return true;
    },
    onFileSizeLimit: function (file) {
        throw new Error('file too big to upload')
        fs.unlink('./' + file.path) // delete the partially written file
    },
    onError: function (err, req, res, next) {
        // here get all error 
        console.log('emit onError!');
        return next(err);
    }

**Comment by LinusU** [comment]
The api discussed in #131 have all callbacks take an optional error parameter so that you can always signal an error.

**Comment by LinusU** [comment]
The api that is now live with multer `1.0.0` always gives you a callback parameter where you can signal an error. Please reopen if you still consider this to be an issue.
