### ISSUE TITLE
have fileStream reference in file parameter of onFileUploadStarts 

### ISSUE THREAD

**Issue by sidorares** [expressjs/multer#105]
I'd like to stream file upload without saving to local fs. Currently easiest option (correct me if I'm wrong) is to listen for  onFileUploadStarts / onFileUploadData / onFileUploadEnd and manually pass chunks to a steam on user side, and we already have readable stream in the first place. Maybe make it accessible from onFileUploadStarts by adding `stream: fileStream` to https://github.com/expressjs/multer/blob/master/index.js#L93 ? Happy to send pr with tests if you think it's a good idea

**Comment by jpfluger** [comment]
We're trying to figure out piping to the cloud, making it generic and independent. We welcome your input. Related to https://github.com/expressjs/multer/pull/102 and https://github.com/expressjs/multer/issues/123.

**Comment by LinusU** [comment]
Storage engine support is released! :fireworks: 

Read the documentation on how to implement one here: https://github.com/expressjs/multer/blob/master/StorageEngine.md
