### ISSUE TITLE
I there any way to make different storage for each field?

### ISSUE THREAD

**Issue by najamulsaqib** [expressjs/multer#1050]
I want to save pdf files in pdf named folder and images in the image named folder, Is there any way to do that?

**Comment by LinusU** [comment]
Unfortunately, there is no great way to do this with the model that is used in Mutler 1.x.

However, with the 2.x version this should be very easy! You can try it out and provide feedback in #399.

Closing this since it cannot really be solved in the library for 1.x...

**Comment by najamulsaqib** [comment]
Well, @LinusU I solved this using file.filedname
if(file.fieldname === "image"){
  cb(null, "./uploads/images");
} else if (file.fieldname === "pdf"){
  cb(null, "./uploads/pdf");
}

**Comment by LinusU** [comment]
Ah, I thought you wanted to detect the file type and then act. Yes, the solution you posted will work great for your use case 👍
