### ISSUE TITLE
Buffer usage deprecated

### ISSUE THREAD

**Issue by gabbloquet** [expressjs/multer#1052]
Hi folks (and thanks a lot for this amazing work),

I still have the issue about :
`(node:11843) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` 
I found it https://github.com/expressjs/multer/issues/918 but still have the issue.

I use Multer v1.4.3, and have a basic configuration : 

``` 
import multer from 'multer';

export const FILE_MAX_SIZE = 5242880; // 5MB

const upload = multer({
  limits: { fileSize: FILE_MAX_SIZE },
});
```

Any advice about how to deal with it ? Am I alone to have this warning ?
Thanks a lot 👌🏻

**Comment by LinusU** [comment]
From the linked issue:

> We cannot drop support for Node.js 0.10 without making a new major version. However, this is already adressed in the Multer v2.x beta 👍 

In order for this to be fixed in 1.x you'll need to ask the author of `busboy` to release a `0.2.x` version with the deprecations fixed, without breaking compatibility with Node.js 0.10.

**Comment by gabbloquet** [comment]
Thanks @LinusU :) 
Have a nice day!
