### ISSUE TITLE
Pass metadata to Multer

### ISSUE THREAD

**Issue by derMani** [expressjs/multer#107]
Hello! 

Is it possible to post some metadata of a file to the Multer middleware? 

I have a scenario, where i am using Multer to pass files to MongoDB's Gridfs. 

The onFileUploadStart option is used for this

    onFileUploadStart:function(file){
       //set upload with WritableStream        
       this.upload = gfs.createWriteStream({
           filename:file.originalname,
           mode:"w",
           chunkSize:1024*4,
           content_type:file.mimetype,
           root:"fs",
           metadata: {} // put some crazy meta data in here
       });
    },

As you can see, it is possible to attach some metadata to a GridFS File object. I think in the current implementation of Multer, there is no direct way pass those metadata, right? It would be nice to pass a metadata object to Multer, which we can use e.g. as a property of the file parameter. 

The meta data is also available in the form, so it would also be sufficient for me to have access to the body params inside the onFileUploadStart function

**Comment by jpfluger** [comment]
Cool. This extra meta-data is relevant to the discussion. We're trying to figure out piping to the cloud, making it generic and independent. Feel free to chime in on links #102 and #123... and to a lesser extent to https://github.com/expressjs/multer/issues/105 and a MongoDb issue at https://github.com/expressjs/multer/issues/77.

**Comment by LinusU** [comment]
The correct way to implement this now that `1.0.0` is released is to implement a GridFS storage engine.

Documentation:
https://github.com/expressjs/multer/blob/master/StorageEngine.md
