### ISSUE TITLE
Node 17.5+ fetch API - No boundary / res.file undefined

### ISSUE THREAD

**Issue by MCrawleyHomeOffice** [expressjs/multer#1077]
I'm unsure if this should be considered an issue with Node or Multer, but I'm seeing it manifest in Multer.

When you use the new fetch API in the latest version of Node (17.5 onwards), no boundary is generated in the content-type header automatically which then results in Multer rejecting the upload when calling .single().

Presumably if you're running in a browser and you specify an undefined content-type, it will be generated for you but this doesn't appear to be the case in Node's fetch API (ref: https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post)

I've tried pulling the header out of the original broswer request and adding this to the fetch request which bypassed the boundary check in Multer, but unfortunately it must still be failing somewhere else down the line as req.file remains undefined.

Any advice would be great.

Update: Further to this, I've found that removing the Content-Type header completely does help, undici (which fetch is built on top of) then provides a Content-Type header along with a boundary. I am then noticing however that the busbody.on('file'...) is never called, instead it assumes the file data I'm trying to upload is a 'field', which results in the req.body being populated but not the req.file. After checking the headers, it looks like the content-disposition doesn't contain a filename whereas if I send the request using RequestJS then it does.

This is how I'm calling the API which works fine with RequestJS and Multer:

var request = {
    url: myUploadUrl,
    method: 'POST',
    formData: {
        document: {
          value: data,
          options: {
            filename: 'MyFile',
            contentType: mimeType
          }
        }
    }
};
fetch(reqConf, (err, data) => {
            ....
});

**Comment by LinusU** [comment]
I don't think that there is anything that we could do in Multer here. The boundary needs to be provided in the header in order to pass the request body, otherwise we won't be able to know where to cut up the different parts.

Similarly, if content-disposition doesn't contain a filename we cannot really do anything in Multer either since that means that it's a field and not a file according to the specification.

I think that you need to open issues on Node.js and Undici...

**Comment by MCrawleyHomeOffice** [comment]
Appreciate the response and apologies to re-open for the sake of a dumb question. 

Just for my own sanity and to ensure I'm raising this correctly and with the right people, can you confirm something.

In order for the filename to be received by Multer in the content-disposition header (such is the issue right now), should this be specified by the developer when calling Node's fetch() function, or is this something that Node/Undici's fetch logic should generate internally when the request is sent?

I have my doubts whether the API is being called correctly in the first place so thought I'd clarify before I raise with undici.

**Comment by LinusU** [comment]
Are you passing a `FormData` instance to the `fetch` function? Does this `FormData` come from Undici?

**Comment by MCrawleyHomeOffice** [comment]
Well as shown in my original issue, I'm just passing the same request structure I was previously passing to RequestJS (before we switched to Node's Fetch). We're then doing an upload.single('document') on the Multer side.

var request = {
url: myUploadUrl,
method: 'POST',
formData: {
document: {
value: data,
options: {
filename: 'MyFile.txt',
contentType: mimeType
}
}
}
};

fetch(request, (err, data) => {
....
});

I did also try pulling in and using form-data (https://www.npmjs.com/search?q=form-data) but I had the same issue with this.

**Comment by LinusU** [comment]
`fetch` doesn't have a `formData` option that works the same way as RequestJS does, so you need to adapt you code to pass a `FormData` instance as the `body` parameter...

**Comment by abadrangui** [comment]
Note if you're using Firebase Functions,

Turns out multer doesn't work with Firebase functions like forever ([stackoverflow](https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase))

So you need to use other packages.
I'm using express-multipart-file-parser for now
