### ISSUE TITLE
Submit hang

### ISSUE THREAD

**Issue by kuselanonline** [expressjs/multer#108]
Hi,

I'm writing a route in express js to save to some data to db with optional file upload. Multer handle file upload nicely. However, if there are no files  and only formdata submitted, it hangs at onParseStart. Is there a way to fix it?

**Comment by jasson15** [comment]
How about show us your code? Because it won't hang at `onParseStart` w/ or w/o files, at least in my experience. :)

**Comment by kuselanonline** [comment]
app.post('/posts',
    [multer({
        dest: '/tmp', includeEmptyFields: true,
        rename: function (fieldname, filename) {
            console.log('rename')
        },
        onFileUploadStart: function (file) {
            console.log('Upload starting for filename: ' + file.originalname);
        },
        onFileUploadData: function (file, data) {
            console.log(data.length + ' of ' + file.fieldname + ' arrived')
        },
        onParseStart: function () {
            console.log()
        },
        onParseEnd: function (req, next) {
            console.log('Form parsing completed at: ', new Date());
            next();
        },
        onFileUploadComplete: function (file) {
            console.log(file.fieldname + ' uploaded to  ' + file.path);
        },
        onFileSizeLimit: function (file) {
            console.log('Failed: ', file.originalname)
        },
        onFilesLimit: function () {
            console.log('Crossed file limit!')
        },
        onFieldsLimit: function () {
            console.log('Crossed fields limit!')
        },
        onPartsLimit: function () {
            console.log('Crossed parts limit!')
        },
        onError: function (error, next) {
            console.log("Error occurred while uploading the file!!");
            next(error);
        }
    }), function (req, res) {
        var data;
        if (req.files.upload) {
            data = {
                'name': req.files.upload.originalname,
                'mimetype': req.files.upload.mimetype,
                'size': req.files.upload.size,
                'file': req.files.upload.name
            };
        }
        data.post = decodeURIComponent(req.body.post);
        data.timestamp = new Date().toISOString();
        var recipient = decodeURIComponent(req.body.recipient).split(',');

        var collections = {write: ['posts', 'walls']};
        var action = String(function (params) {
            var db = require('org/arangodb').db;
            var f = db.posts.save(params.data);
            for (var i = 0; i < params.recipient.length; i++) {
                db.walls.save(f._id, params.recipient[i], {});
            }
            return f
        });
        var params = {data: data, recipient: recipient};
        db.transaction(collections, action, params, function (err, result) {
            if (err) {
                res.status(err.code).send({'errorNum': err.errorNum});
            }
            else {
                delete result.error;
                res.header('Etag', result._rev);
                res.header('Location', result._id);
                res.status(201).json(result)
            }
        });

    }]);

**Comment by jpfluger** [comment]
Could be related to other hanging issues. See https://github.com/expressjs/multer/issues/53 and https://github.com/expressjs/multer/issues/72

**Comment by LinusU** [comment]
I believe this to be fixed with multer `1.0.0`, please reopen if this is still a problem :)
