### ISSUE TITLE
Dependency minimist vulnerability "Prototype Pollution in minimist"

### ISSUE THREAD

**Issue by ruanpotgieter95** [expressjs/multer#1080]
The minimist dependency being used throws an audit vulnerability.
![Screenshot 2022-03-23 at 15 57 44](https://user-images.githubusercontent.com/36186702/159716392-fdada549-cab5-4604-bb63-6413931162dd.png)

**Comment by guicompeng** [comment]
minimist is used by the mkdirp dependency. I already created a pull request to update mkdirp which updates minimist
https://github.com/expressjs/multer/pull/1079

**Comment by guicompeng** [comment]
minimist is used by the mkdirp dependency. I already created a pull request to update mkdirp which updates minimist
https://github.com/expressjs/multer/pull/1079
