### ISSUE TITLE
single upload improve

### ISSUE THREAD

**Issue by supercutcat** [expressjs/multer#1083]
``` js
const storage = multer.diskStorage({
  destination(req: Request, _file: Express.Multer.File, cb) {
    cb(null, `uploads/`);
  },
  filename(req: Request, file: Express.Multer.File, cb) {
    cb(null, `${Date.now()}-${file.originalname}`);
  },
})

export const upload = multer({
  storage
});

router.post("/", upload.single("avatar"), createAvatarHandler)
```

When I use the wrong upload field name, such as post, how can I return an error message from the interface instead of getting multerError: Unexpected field?

**Comment by LinusU** [comment]
Please see [the error handling section](https://github.com/expressjs/multer#error-handling) of the documentation to see how to return custom responses in the face of errors.
