### ISSUE TITLE
req.file is undefined for larger files only when deployed

### ISSUE THREAD

**Issue by NathanHazout** [expressjs/multer#1089]
I am using

```
import multer from 'multer';
const storage = multer.memoryStorage();
const upload = multer({storage: storage, limits: {fieldSize: 20 * 1024 * 1024, fileSize: 20 * 1024 * 1024}});
router.post('/do', upload.single('image'), async function (req, res) {
    try {
        console.log('uploading file');
        console.log(req.file);
        console.log(req.files);
        console.log(req.body);
});
```

On localhost, everything works fine.  

Once I deploy the application (on kubernetes, with ingress nginx) something strange happens.  
Small files (~75k) work file, but larger files (500k) silently remove the file. `req.file` is undefined.  
I don't know the exact size threshold at which it starts breaking.

Any idea what could lead to this behavior?

**Comment by LinusU** [comment]
Seems like this has something to do with Nginx or Kubernetes? I think that Nginx places a limit on the request body by default?

Since it works locally, I don't see that it's a bug in this library? But if it turns out that there is, I'd be very happy to reopen this!
