### ISSUE TITLE
Need to iterate form file array to convert image to base64 without uploading to folder

### ISSUE THREAD

**Issue by mpkumar87** [expressjs/multer#109]
Hi,
I am using multiple image upload in the form.. Once form submitted, need to iterate all the files object and convert to base64 string.
I tried to iterate the files object , but showing error,
Sample node code:
req.files['myfile[0]'];
req.files.myfile[0];
and html code is
<input type="file" name="myfile[]" id="file1 />
<input type="file" name="myfile[]" id="file2 />
Please guide me to solve this issue..

Thanks,
Premkumar M

**Comment by LinusU** [comment]
It seems like your html code wasn't posted, but my guess is that you should make sure to have these two settings set:

```javascript
inMemory: true,
putSingleFilesInArray: true
```

Than you can find the array like this:

```javascript
req.files['myfile']
```

E.g. converting all files to base64 strings:

```javascript
var strings = req.files['myfile'].map(function (file) {
  return file.buffer.toString('base64')
})

// strings is now an array with base64 encoded strings
```
