### ISSUE TITLE
multer.diskStorage - problem with upload file to folder

### ISSUE THREAD

**Issue by robokonk** [expressjs/multer#1098]
I have a problem with uploading files to the server with multi.
I read documentation and wrote code according to with documentation, but files still are not upload to folder images

My code:
```
const express = require("express");
const app = express();
const path = require("path");

const multer = require("multer");
const storage = multer.diskStorage({
  desination: "images",
  filename: (req, file, cb) => {
    console.log(file);
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const upload = multer({ storage: storage });

app.set("view engine", "ejs");

app.get("/upload", (req, res) => {
  res.render("upload");
});

app.post("/upload", upload.single("image"), (req, res) => {
  res.send("Image Uploaded");
});

app.listen(3001);
console.log("3001 is the port");
```

**Comment by LinusU** [comment]
Are you receiving any error? Does the `images` directory exist relative to the CWD where you are running the app?

**Comment by ramonpaolo** [comment]
> I have a problem with uploading files to the server with multi. I read documentation and wrote code according to with documentation, but files still are not upload to folder images
> 
> My code:
> 
> ```
> const express = require("express");
> const app = express();
> const path = require("path");
> 
> const multer = require("multer");
> const storage = multer.diskStorage({
>   desination: "images",
>   filename: (req, file, cb) => {
>     console.log(file);
>     cb(null, Date.now() + path.extname(file.originalname));
>   },
> });
> 
> const upload = multer({ storage: storage });
> 
> app.set("view engine", "ejs");
> 
> app.get("/upload", (req, res) => {
>   res.render("upload");
> });
> 
> app.post("/upload", upload.single("image"), (req, res) => {
>   res.send("Image Uploaded");
> });
> 
> app.listen(3001);
> console.log("3001 is the port");
> ```
`destination` and not `desination`
