### ISSUE TITLE
Question about behavior of .none() middleware

### ISSUE THREAD

**Issue by ErkanKayhan** [expressjs/multer#1099]
Good day,

I have a question about the behavior of multer middlewares, say I take the example at the beginning of the readme:(the code i am referencing add to the example would be in **Bold** and as bullet points

const express = require('express')
const multer  = require('multer')
const upload = multer({ dest: 'uploads/' })

1. **app.use(upload.none())** // added by me , not in initial example

app.post('/profile', **middleware1, middleware2**,upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file
  // req.body will hold the text fields, if there were any
})

This allows to upload a file with a fieldName called 'avatar', but lets say I have multiple endpoints, and only 2 of them can upload files. By using, multipart/form-data, bodyParser cannot parse as it does not support multipart/form-data, so to get the body , upload.none() must be called. i have middlewares prior to the multer one_(second bold area)_, body will be empty. so my question is: 
if i use upload.none() middleware globally with app.use() _(figure 1.)_  so that body is parsed everytime, even when i don't want to handle a file, Does calling a upload.(single/array/fields/...) in the ENDPOINT MIDDLEWARE(second bold section) "override" the middleware from app.use FOR THAT "overriden" endpoint ?

Thanks in advance for your answer

**Comment by LinusU** [comment]
The way express works it will execute the `.none()` instance before the other, and it won't have any knowledge that there will be a later call to another Multer instance. Thus, the setup you are describing won't work.
