### ISSUE TITLE
v2 Busboy patch without ESM requirement?

### ISSUE THREAD

**Issue by christinachimi** [expressjs/multer#1113]
This is really a question - we have been using multer 2 via @koa-multer without issue. When the dicer/busboy vulnerability came up, we saw that the only way to stay on 2 would be to move to ESM (or at least for the koa package to do so). We tried downgrading to v1 but realized that we have been relying on the fact that v2 doesn't require filenames. It seems like our only choice at this point is to go back to the vulnerable version - is there any interest in a v2 patch that wouldn't be tied to the ESM requirement?

**Comment by LinusU** [comment]
There is a version `1.4.5-lts.1` which drops support for older versions of Node.js, but uses a newer Busboy that isn't vulnerable.

If anyone can take the time to backport the fix in a non-breaking manner I would be happy to merge that, and release it in the regular 1.x release line.
