### ISSUE TITLE
changeDest throwing 'Arguments to path.join must be strings'

### ISSUE THREAD

**Issue by karan-kapoor90** [expressjs/multer#112]
I attempted to use the changeDest method as follows:

    changeDest:function(dest,req,resp){
        
        mkdirp('./uploads/'+'test/', function(err) {
            if (err){
                console.log('Error creating directory ',err);
                //throw err;
            }else {
                return '/home/ubuntu/workspace/uploads/'+'test/';
            }
        });
    

as well as 

    changeDest:function(dest,req,resp){
        
        var stat = null;
          try {
              stat = fs.statSync('./uploads/'+'test');
          } catch(err) {
              console.log('folder exists checking error ',err);
              // for nested folders, look at npm package "mkdirp"
              fs.mkdirSync('./uploads/'+'test');
              return './uploads/'+'test';
          }
          if (stat && !stat.isDirectory()) {
              // Woh! This file/link/etc already exists, so isn't a directory. Can't save in it. Handle appropriately.
              throw new Error('Directory cannot be created because an inode of a different type exists at "' + dest + '"');
          }

but in either cases, the directory gets created, but I get the error message : 

    Arguments to path.join must be strings

the other methods right after are 

    onFileUploadStart:function(file,data,req,res){
        console.log('onFileUploadStart');
        
        //console.log('****** Data ********\n',data.body,'\n ****** of File ******\n',file.originalname,'\n****************************')
    },
    onFileUploadComplete:function(file,req,res){
        console.log('onFileUploadComplete called');
        res.status(200).send({
           message:'File uploaded successfully' 
        });
    }

Because of this issue, I can't create any new directories even though I know the changeDir method is working once I create the directory structure manually before I run this.

**Comment by karan-kapoor90** [comment]
Fixed this issue by pulling the return statement out of the else as follows :

    changeDest:function(dest,req,resp){

    mkdirp('./uploads/'+'test/', function(err) {
        if (err){
            console.log('Error creating directory ',err);
            //throw err;
        }
    })
    return '/home/ubuntu/workspace/uploads/'+'test/';

But now, giving a dummy folder such as 'test' is working, but a folder path such as `return dest+req.body.username` fails without any error, even though printing req.body.username right before issuing the return or the mkdirp does return the username.

**Comment by acanimal** [comment]
Note you are using `mkdirp` asynchronously so it can happen multer tries to save the file before the directory was created.

`changeDest` is invoked synchronously within multer (see https://github.com/expressjs/multer/blob/master/index.js#L90) so you need to return the path to be used at the end of the method.

An alternative is to upload files to a temporary folder, process them asynchronously (changing name, creating subfolders, etc) and then remove or simply move from temp folder.

**Comment by jpfluger** [comment]
For the next major release, we may look at handling the mkdirp call internal to multer... or at least provide a mkdirp example... thoughts?  Or maybe we just let this lie -- it is what it is.

**Comment by LinusU** [comment]
This shouldn't be a problem in `1.0.0` no more, please reopen if you have any more problems with this.
