### ISSUE TITLE
Update the readme in regards to unfinished req.body

### ISSUE THREAD

**Issue by javascrewpt** [expressjs/multer#113]
I've already asked here, but didn't get the desired response: http://stackoverflow.com/questions/29452651/express-js-and-multer-how-to-know-when-the-files-are-all-uploaded

basically, if I mount multer in app.js, like here:
```javascript
app.use(multer({ 
        dest: './uploads/',
        rename: function (fieldname, filename) {
            return filename.replace(/\W+/g, '-').toLowerCase() + Date.now();
        },
        putSingleFilesInArray: true       
        })
);
```
how will I be able to notify upload.js that uploads have been completed?
```javascript
router.route('/')
    .get(function(req, res){
        res.render('uploads');
    })
    .post(function(req, res){
        //how to wait here for the file to upload?
    });
```

Thank you for your patience and response.

**Comment by LinusU** [comment]
It's quite unclear from the text but this is only for the different event-handlers (the `on*` options). It won't hand it over to the next middleware until all the fields and files have been parsed.

**Comment by LinusU** [comment]
I'm keeping this open until we have clarified it in the readme

**Comment by LinusU** [comment]
This should be fixed now, thanks!
