### ISSUE TITLE
Conflic express-fileupload

### ISSUE THREAD

**Issue by lupca** [expressjs/multer#1136]
Flow:
- npm i express-fileupload
- npm i multer
```js
const express = require('express');
const fileUpload = require('express-fileupload');

const app = express();
app.use(fileUpload());
```
- Use `upload.single('file_field')` in middleware but not save file

=> Error: not file in `req.file`

Issue

- Use express-fileupload in config
- If remove `app.use(fileUpload());` => req.file was get file from client

**Comment by LinusU** [comment]
Yes, this is because in Express only one middleware can use the body.

The solution is to only one of the packages.

Or if you need both, only install one middleware per route, and no global middleware.

**Comment by lupca** [comment]
Thank you @LinusU 

> if you need both, only install one middleware per route, and no global middleware.
