### ISSUE TITLE
Cannot get req body from previous middleware - Please Help

### ISSUE THREAD

**Issue by ShaikRehan123** [expressjs/multer#1145]
I am trying to upload a video but before that, I am saving it and sending uploadPath in req.body.uploadPath.
But the problem is I cannot access it in multerFilter and multerStorage.

Router:
![router](https://user-images.githubusercontent.com/83860384/193449319-746c9814-8822-4664-8ac1-e4ac99c8c7a1.png)

Multer Config:
![multer](https://user-images.githubusercontent.com/83860384/193449371-5d3f388f-f7f0-477b-8391-e38f03350bb4.png)

Controller:
![controller](https://user-images.githubusercontent.com/83860384/193449377-a7b79454-46da-4816-afa9-e4e42862cdb8.png)

Please Help ME.

**Comment by LinusU** [comment]
`req.body` is where Multer will store the fields that it parses, you cannot use that to send information in to Multer.

In your `uploadMovie` function, save things on e.g. `req.myAppThings` instead of `req.body`. Than you should be able to access that from your Multer functions.

**Comment by ShaikRehan123** [comment]
@LinusU Thanks.
But I'm still not able to get that data so I decided to write the path itself in multerfile function.

**Comment by LinusU** [comment]
That's strange, that should work. If you can provide a small example where it doesn't work I'd be happy to take a look a it.

Otherwise doing it in the Multer function works as well 👍
