### ISSUE TITLE
Not working with other router issue

### ISSUE THREAD

**Issue by windmaomao** [expressjs/multer#115]
I had this issue for couple of my projects in the past. For some reason, if I call app.use(multer after any router call, ex. app.use('/abc', router), the multer middleware will be bypassed. 

I know this is strange, but i found it very consistent, since I can move the location of multer to be before or after other router setup. 

Please let me know if this is due to my lack of understanding of middleware.

**Comment by vko-online** [comment]
i think it's because multer doesn't path `next()` further. It takes only `function (req, res)`

**Comment by jpfluger** [comment]
Typically `app.use(multer)` is placed before the router call or inside the router call, such as `app.use('/abc', multer, router)`.  If the middleware is placed after the router call, then the router function itself should call `next()`.

**Comment by LinusU** [comment]
That is how expressjs is supposed to work, add your middleware before your router.

Anyhow, the handling of this is changed in `1.0.0` and if you are following the new recommended way to upload this won't be a problem for you :)
