### ISSUE TITLE
package dosent work for minio s3 compatible

### ISSUE THREAD

**Issue by m0x31h0x64i** [expressjs/multer#1150]
i used minio configuration like the following to create a config :
```
const Minio = require('minio')
const s3= new Minio.Client({
    endPoint,
    useSSL: true,
    accessKey,
    secretKey
})
module.exports = s3
```
and then i used this configuration in the multer-s3 to create a storage for multer :

```
const s3 = require('../../configs/up.config')
const multer = require('multer')
const multerS3 = require('multer-s3')

const storage = multerS3({
    s3,
    bucket: 'test',
    acl: 'public-read',
    contentType: multerS3.AUTO_CONTENT_TYPE,
    metadata: function (req, file, cb) {
      cb(null, {fieldName: file.fieldname});
    },
    key: function (req, file, cb) {
      cb(null, Date.now().toString())
    }
})
const upload = multer({ storage })
module.exports = upload.single('image')
```
but it dosent work and throws an error :

```
C:\Users\user\Desktop\example\node_modules\multer-s3\index.js:210
    var upload = this.s3.upload(params)
                         ^

TypeError: this.s3.upload is not a function
    at S3Storage.<anonymous> (C:\Users\user\Desktop\example\node_modules\multer-s3\index.js:210:26)
    at C:\Users\user\Desktop\example\node_modules\multer-s3\index.js:84:10
```

**Comment by dougwilson** [comment]
Thank you for your report, however you filed on the wrong issue tracker by accident. You will want to file your issue on the multer-s3 issue tracker https://github.com/anacronw/multer-s3/issues

**Comment by m0x31h0x64i** [comment]
> Thank you for your report, however you filed on the wrong issue tracker by accident. You will want to file your issue on the multer-s3 issue tracker https://github.com/anacronw/multer-s3/issues

its already there, can you help me solve this problem ?

**Comment by dougwilson** [comment]
No, we don't have any ability to change the code to fix the issue in that repo.
