### ISSUE TITLE
Consider using semver-compatible version specifiers for LTS releases

### ISSUE THREAD

**Issue by ccharles** [expressjs/multer#1155]
[It appears that][1] the latest LTS releases, which I understand to be extensions of the 1.x development line, are not compatible with semver as implemented in the NPM ecosystem.

Version constraints like `^1.4.2`, `1.4`, and `1` [do not match][2] versions `1.4.4-lts.1` or `1.4.5-lts.1`:

![image](https://user-images.githubusercontent.com/37932/197779615-79cc57be-a486-4444-9683-b8954369e45b.png)

I think the `-lts.1` suffix is understood as [a prerelease][3]. This has two consequences:

1. NPM requires that an exact version specifier be used:

    ![image](https://user-images.githubusercontent.com/37932/197780170-8511762a-decf-4b82-9574-dbd281e80655.png)

1. These versions sort _before_ the non-LTS tags e.g.:

    ![image](https://user-images.githubusercontent.com/37932/197780494-1fbaf17e-f6e1-4c09-bf53-21edfa21dc48.png)

    ![image](https://user-images.githubusercontent.com/37932/197780604-fb9b9cea-cec9-4a50-928b-06d9f5ee6c84.png)

[1]: https://stackoverflow.com/q/74167128/354577
[2]: https://semver.npmjs.com/
[3]: https://github.com/npm/node-semver#prerelease-tags

**Comment by LinusU** [comment]
The `1.4.5-lts.1` version contains breaking changes which is why we haven't released it as just `1.4.6`. The breaking change is that support for older versions of Node.js is now broken. If anyone contributes a patch so that we can address the security issue without breaking compatibility I'll be happy to merge and release that as `1.4.6`!

**Comment by ccharles** [comment]
@LinusU, great, thanks for responding!

In that case, "LTS" feels like a strange name for these releases. Would `-beta` or `-pre` or something be more intuitive?

**Comment by LinusU** [comment]
I'm not sure about `-beta` or `-pre`, since this is neither a beta or a pre-release. If you have any other suggestions I'm open to hearing them, but `-lts` has been in use for a while now and I'm not sure that it would be worth the churn...

**Comment by nbkhope** [comment]
If you have a breaking change, the major version should be bumped. If you are afraid of conflicting with an existing development of the new major version, then in my opinion the breaking change should not have been made for the v1 series.

**Comment by bwobbones** [comment]
@LinusU can you link the issue that describes the breaking change?
