### ISSUE TITLE
How to change the destination of diskStorage ?

### ISSUE THREAD

**Issue by yucai233** [expressjs/multer#1162]
```
const storage = multer.diskStorage({
    destination: function(req, file, cb) {
        cb(null, currentPath)
    },
    filename: function(req, file, cb) {
        cb(null, file.originalname)
    }
})
```
> How could I change the `currentPath` in runtime ?

**Comment by sarfaraz-mohammad** [comment]
you can do like this 
`const storage = multer.diskStorage({
	destination: function (req, file, cb) {
		cb(null, '/var/nodejs/images');
	},
	filename: function (req, file, cb) {
		cb(null, file.originalname)
	}
})`
