### ISSUE TITLE
Depends on vulnerable versions of busboy -- High

### ISSUE THREAD

**Issue by RashadTanjim** [expressjs/multer#1164]
node_modules/busboy    
multer  <=2.0.0-rc.3 
Depends on vulnerable versions of busboy

**
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available

**Comment by LinusU** [comment]
This is adressed in https://github.com/expressjs/multer/pull/1097

You can use version `1.4.5-lts.1` if you are on Node.js 10.x or newer, for older versions of Node.js there is currently no solution...
