### ISSUE TITLE
Looking for private communication channel

### ISSUE THREAD

**Issue by das7pad** [expressjs/multer#1178]
Hello,

I am looking for a private communication channel to disclose a potential security vulnerability.
I've emailed @LinusU twice using the email-address from the package.json, but did not receive any reply yet.

Thanks in advance,
Jakob

**Comment by LinusU** [comment]
<img width="629" alt="Screenshot 2023-01-19 at 10 38 36" src="https://user-images.githubusercontent.com/189580/213349849-cfe79cef-1bbe-4402-b31e-16ff6207f3c1.png">

Unfortunately, your messages had been marked as spam so I hadn't seen them...

I'll send you a message shortly

**Comment by das7pad** [comment]
Thanks for your message, @LinusU. Did you get my reply?

**Comment by das7pad** [comment]
@LinusU A gentle reminder to take a look at this thread. Thanks in advance! :slightly_smiling_face:

**Comment by das7pad** [comment]
@LinusU @dougwilson Did you receive my messages last week?

**Comment by dougwilson** [comment]
Hi @das7pad I did, sorry I didn't reply. I have gotten two other vulnerability reports for some other things that are unfortunately consuming my time there. I may have to leave it to Linus due to your timeline constraints.
