### ISSUE TITLE
How to set charset for multer to unicode

### ISSUE THREAD

**Issue by moosaviamir** [expressjs/multer#119]
Hello
Thank you for this project. I wonder if you could tell me how to set charset in multer to unicode so i can receive files with Unicode character names.

regards

**Comment by LinusU** [comment]
I just added a test for this that works in the breaking-changes branch, this bug should be closed when #131 is merged.

**Comment by LinusU** [comment]
This is now fixed in multer `1.0.0`. You don't have to set any encoding at all, it should work out of the box.
