### ISSUE TITLE
Drop dependency on `xtend`

### ISSUE THREAD

**Issue by mcmxcdev** [expressjs/multer#1190]
https://socket.dev/npm/package/xtend is flagged as unmaintained and it's functionality can be easily achieved nowadays with the spread operator if I am not mistaken: https://masteringjs.io/tutorials/fundamentals/merge-two-objects

**Comment by Doc999tor** [comment]
The Nodejs version officially supported by Multer is [0.10](https://github.com/expressjs/multer/blob/master/package.json#L42) 
Spread operator is supported only from [5.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility)
Until the old Nodejs version are not dropped, `xtend` or some another kind of polyfill has to be used

**Comment by LinusU** [comment]
It's removed in the 2.x branch, and as said we need it in 1.x
