### ISSUE TITLE
req.body is empty when changeDest occurs

### ISSUE THREAD

**Issue by rkurbatov** [expressjs/multer#121]
I need to send subdirectory name to store files from client to server, so I send it as a parameter via post query, but when I try to read req.body in changeDest function req.body is empty. 

req.body populated only at parseEnd stage but it's too late - all files should be renamed and replaced at that point.

**Comment by rkurbatov** [comment]
I've understood. It's because my fields are located after the files in request.

**Comment by jpfluger** [comment]
Yes, you are correct. You could optionally append the subdirectory name as a url param and get it from req.query.

**Comment by rkurbatov** [comment]
My uploading component can pass extraData in upload request, but it places it only after the files in request. And I can't even change url after it's initialization, so can't pass needed url param. So need to do it manually.

**Comment by LinusU** [comment]
Just out of curiosity, which uploading component are you using?

**Comment by rkurbatov** [comment]
LinusU, bootstrap-fileinput
