### ISSUE TITLE
How about having storage engines?

### ISSUE THREAD

**Issue by LinusU** [expressjs/multer#123]
I think that adding storage engine could simplify the api a lot, whilst still adding functionality. It could replace both `inMemory` and `rename` with instead having configurable storage.

We could ship two storage engines by default: `MemoryStorage` and `FileStorage`.

`MemoryStorage` would work like `inMemory` does today. It would simply create `Buffer`s out of every stream that comes its way.

`FileStorage` would work store the files to disk. When instantiating, the user could specify a `rename` function here.

It would then be easy for someone to make, for example, a `GridFsStorage` that uploads the files directly to GridFS on MongoDB and then returns the uuid.

Either the engine would be tasked with returning one value that would be populated to `file.handle` (or something similar) or it could be allowed to set whatever properties it wants on the `file` object. Personally I would prefer the former, I like being strict.

This would of course be a breaking change and we would have to release this as a new major version.

**Comment by hacksparrow** [comment]
I am of the opinion that multer should be just a parser - it parses data and makes it ready for consumption, that's it. It should not come baked in with anything which would not be used by some / most developers.

These storage engines should be independent modules, which multer users can load and use, if they need to.

**Comment by LinusU** [comment]
Yes, I definitely think that they should be independent modules! But since we provide both memory and file storage today I thought it was a bad idea to remove them.

All the other modules would be separate packages.

**Comment by jpfluger** [comment]
Sounds like a good plan. 

As an fyi, beware of `inMemory` speed and large-memory issues in multer. See https://github.com/expressjs/multer/issues/65 and https://github.com/expressjs/multer/issues/76. I'm curious in performance tests between when (1) a file is piped directly to the cloud without touching disk versus (2) pipe to disk, disk to cloud, delete from disk, rather than have it run all in-memory.  Current speed tests are easily figured out by running mocha tests on multer. There'll be a section for `inMemory` only and these run times are 8x to 10x slower than when piped to disk.

**Comment by LinusU** [comment]
Yes it will be very interesting. It might be better to touch the file system if the client is uploading lots of data very fast, and the connection to wherever you want to upload it is slower, thus building up memory usage while we need to buffer the file.

Provided that all our streams are correctly implemented all the way down I actually think that this might be able to get solved with `pause`, `resume`, `lowWatermark` and `highWatermark`. If I understand it correctly it could use tcp congestion control to tell the client to upload slower? Well, well, we won't know for sure until we've tested it :)

**Comment by LinusU** [comment]
This is now fixed in multer `1.0.0`
