### ISSUE TITLE
Should multer be an EventEmitter?

### ISSUE THREAD

**Issue by LinusU** [expressjs/multer#124]
To me it dosen't seem to follow best practice inside the Node.js community to have a lot of fields starting with `on` in the option-object. Wouldn't it be more clean to let the middleware function also be an event emitter that would emit the events instead?

If you want to check if an event has been handled, you would just check the return value from `emit`. It returns `false` if no listeners where fired, and `true` if any listener did fire.

If #123 gets implemented we maybe could scale back on the number of events as well :)

**Comment by hacksparrow** [comment]
Open to any change, if it is for the better.

**Comment by LinusU** [comment]
I'm glad to hear it, hopefully I will have some time to have a look at this over the weekend :)

**Comment by hacksparrow** [comment]
👍

**Comment by jpfluger** [comment]
Go for it.
