### ISSUE TITLE
multer fields array returned only first file

### ISSUE THREAD

**Issue by Webb-orbit** [expressjs/multer#1269]
The issue with Multer's .fields() method returning only the first file in the array

For example:
```
const upload = multer({ dest: 'uploads/' });

app.post('/upload', upload.fields([
  { name: 'images' },
  { name: 'documents' }
]), (req, res) => { });
```

req.files returns only first value on the object 

please fixed the problem

**Comment by Doc999tor** [comment]
Can you show the `form data` from the request? Is it possible that a single file is being sent?

**Comment by Webb-orbit** [comment]
i use postman form-data to request. i send two files but in response only one file show 
in middleware: 
``` JAVASCRIPT 
router.route("/createuser").post(uploadfile.fields([{name: 'logo'}, {name: 'banner'}]), createuser)
```

``` console.log(req.files); ```
  when i print this i found only logo array 

HOW TO FIXED THIS???

**Comment by Doc999tor** [comment]
Can you please attach the curl from Postman? (right panel in Postman with `</>` icon)

```bash
curl --location 'http://localhost:9000/settings/files' \
--form 'phone="0654065"' \ -- text field
--form 'logo=@"/dishonored.jpg"' \ -- single file 
--form 'cover=@"/1_1920x1080.jpg"' \
--form 'gallery=@"/dl2_exclusive_poster.jpg"' \ -- multiple files per filename
--form 'gallery=@"/dl2_exclusive_poster2.jpg"' \
--form 'gallery=@"/dl2_exclusive_poster3.jpg"' \
--form 'gallery=@"/dl2_exclusive_poster4.jpg"' \
--form 'gallery=@"/dl2_location_conceptart.jpg"' 
```

```javascript
req.files
{logo: Array(1), cover: Array(1), gallery: Array(5)}
```

**Comment by Webb-orbit** [comment]
thanks thanks thanks Doc999tor your recommendation helps me!
i think the main problem is my postman vscode extension,  now i use postman desktop app and it work's  perfectly
