### ISSUE TITLE
Multer: how to name files after req.body parameters

### ISSUE THREAD

**Issue by ayhoung** [expressjs/multer#134]
I'm trying to upload a file with a form such as below
```html
<input type="file" name="collateral" />
<input type="hidden" name="id" value="ABCDEFG" />
<input type="submit" value="Upload Image" name="submit">
```
and I would like to rename to file to the name in the id input (ABCDEFG). As I can't access the req.body through the rename: function(fieldname, filename), I was wondering how I would achieve this?

**Comment by ayhoung** [comment]
the documentation also states that accessing req.body is not allowed in this function, so any idea of how this would be achieved?

**Comment by LinusU** [comment]
Using the code in #131 you should be able to read `req.body`, if the browser sends it before the file. The easiest way to achieve that would be to place the hidden field above the file input.

Actually it probably should work already, as long as you don't use any brackets in the field names.

**Comment by brutalhonesty** [comment]
I noticed this as well.
Sending the fields first allows my rename to trigger as expected. I will get ```1111111111``` for the ```onFileUploadStart``` function.
![screen shot 2015-05-06 at 4 22 19 pm](https://cloud.githubusercontent.com/assets/1609870/7505820/2716d7a4-f40c-11e4-8f93-68d669131cdf.png)
![screen shot 2015-05-06 at 4 23 19 pm](https://cloud.githubusercontent.com/assets/1609870/7505837/5160c34e-f40c-11e4-91c8-430009251153.png)


If they are file first, then field, I get undefined within the ```onFileUploadStart``` function.

**Comment by LinusU** [comment]
This is how it will always be since we can't change the order in which the browsers sends the data.

If you cannot place the file-input later in the DOM, you could use javascript on the client side to construct your own [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) with the files added last.
