### ISSUE TITLE
req.files is Undefined in onParseEnd

### ISSUE THREAD

**Issue by moosaviamir** [expressjs/multer#135]
Hi
I have a Multipart  request from android app witch is actually user register form.
It's body contains some fields + one image file and i just want to insert into my sql server. its fine if i don't upload image at all (put insert command in onParseEnd:function(req, next)) or force users to upload image in register form (put insert command in onFileUploadComplete). but here is my problem!
I want to user profile picture be optional. some users want to upload file in register form, some user not. So how can i do it?
my source is:

```javascript
var express=require("express");
var db = require('./DBOP');
var multer  = require('multer');
var o2x = require('object-to-xml');
var app=express();
var bodyParser = require('body-parser');
var done=false;

app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies

app.use(multer({ dest: './uploads/',
 rename: function (fieldname, filename) {
    //return filename + Date.now();
    return Date.now();
  },
onFileUploadStart: function (file) {
  console.log(file.originalname + ' is starting ...')
},

onFileUploadComplete: function (file, req, res) {
  console.log(file.fieldname + ' uploaded to ' + file.path);
  db.tbl_worker_insert(req.body["name"],file.path, function(r) {
      if (r) {
          console.log("comment Inserted with profile picture!");
      }
      else {
          console.log("comment NOT Inserted!!!");
      }
  });
  done=true;
},

onParseEnd:function(req, next){
  console.log("req.files" + req.files);  // is undef

  db.tbl_worker_insert(req.body["name"],req.body["comment"],null, function(r) {
      if (r) {
          console.log("on parse end inserted!");
      }
      else {
          console.log("comment NOT Inserted!!!");
      }
  });
  
  done=true;
  next();
}
}));

app.post('/api/photo',function(req,res){
  if(done==true){
    console.log(req);
    console.log(req.files);
    res.end("File uploaded successfully!");
    res.sendStatus(200);
  }
});

app.listen(3000,function(){
    console.log("Working on port 3000");
});
```

Problem with my code is when user uploads a profile picture record inserts twice in database, one with profile picture in it and one with null profile picture.

**Comment by LinusU** [comment]
When the middleware has passed on control to the next function (the router in your case), all of the files and fields will have been processed. You can then read exactly what you want there bu utilising `req.body` and `req.files`.

What you want to do is remove both `onFileUploadComplete` and `onParseEnd`. Then in `app.post('/api/photo', ...` you do the actual uploading to mysql.

Also, your `done` variable is global (i.e. shared by all connections) and never gets set back to `false`. Just don't use it at all.

Also, why are `db.tbl_worker_insert` returning a `success` parameter. Node.js best practice is to **always** have an `err` argument as the first one to signal errors. If `err` is `null` or `undefined` the call is assumed to have succeeded.

I would suggest something like this:

```javascript
var multer  = require('multer')
var express=require('express')
var bodyParser = require('body-parser')

var db = require('./DBOP')
var app=express()

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.use(multer({ dest: './uploads/' }))

app.post('/api/photo', function (req, res, next) {
  var info = {
    name: req.body.name,
    comment: req.body.comment
  }

  if (req.files.profileImage) {
    info.imagePath = req.files.profileImage.path
  }

  db.tbl_worker_insert(info, function (err) {
    if (err) return next(err)

    res.end('File uploaded successfully')
  })
})

app.use(function (err, req, res, next) {
  res.status(500)
  res.end('Error handling your request')
})

app.listen(3000, function () {
  console.log('Listening on port 3000')
})
```

**Comment by moosaviamir** [comment]
Thank you LinusU.
Great answer.
Just let me check it out. I'll let you know if there was any problem.

**Comment by moosaviamir** [comment]
Dear LinusU.
Thank you for your response again. I did exactly what you said before and my problem solved but another problem appeared. it sends me  404 status code back and i don't know where it comes from! This is my full code:

```javascript
var express=require("express");
var db = require('./DBOP');
var multer  = require('multer');
var o2x = require('object-to-xml');
var app=express();
var bodyParser = require('body-parser');
var done=false;

app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies
/*Configure the multer.*/

app.use(multer({ dest: './uploads/',
 rename: function (fieldname, filename) {
    //return filename + Date.now();
    return Date.now();
  },
onFileUploadStart: function (file) {
  console.log(file.originalname + ' is starting ...')
}
}));

app.post('/', function (req, res, next) {
  
  if (req.files.image) {
    imagePath = req.files.image.path
  }  

db.tbl_worker_insert(req.body["name"],req.body["comment"],imagePath, function(err) {
    if (err) return next(err)
    res.end("File uploaded successfully");
  });
  next();
});

app.listen(3000,function(){
    console.log("Working on port 3000");
});
```

**Comment by LinusU** [comment]
An endpoint handler is supposed to do one of two things; send a response, or call `next`. Your handler currently tries to do both, and since the call to `next` will happen before `res.end("File up...")` it will instead send you a 404 back.

The solution is really simple, remote the call to next from the function body.

Also, `imagePath` is a global :fearful:, which in your case causes a major bug. If one user successfully uploads a profile image than *any user that submits the form* without a profile picture will get the *first users profile picture*.

The solution for that is also straight forward, add in a var statement in the endpoint handler.

```diff
 app.post('/', function (req, res, next) {
+  var imagePath

   if (req.files.image) {
     imagePath = req.files.image.path
   }  
 
 db.tbl_worker_insert(req.body["name"],req.body["comment"],imagePath, function(err) {
     if (err) return next(err)
     res.end("File uploaded successfully");
   });
-   next();
 });
```

Also, while we're doing code review :) you are mixing semicolon- and non-semicolon-terminated lines. I would suggest to always omit them. Have a look at [feross/standard](https://github.com/feross/standard) for an excellent style standard.

**Comment by moosaviamir** [comment]
Thank you LinusU. 
Your a life saver. Sorry for idiotic questions :)!
I'm just trying to learn node js. its awesome but a little hard to understand.

Regards

**Comment by LinusU** [comment]
No problem, every one is new at one point, I'm glad to help!
