### ISSUE TITLE
How can I check permission before write file?

### ISSUE THREAD

**Issue by truonguit2010** [expressjs/multer#141]
Hello,
When I upload a photo, I will check permission for a user to upload file. I do:

1. Check permission in onFileUploadStart. I call APIs to check.
2.  onFileUploadComplete
But I see, I am always in onFileUploadComplete before my checking is completed. How can I pending upload process to check permission.

Can you suggest me any other way to check permission for upload file.

Thank you.

**Comment by misgina** [comment]
I do not think this is possible unless your access check API is a promise.

**Comment by LinusU** [comment]
This could be done by having a middleware in front on multer, like this:

```javascript
var express = require('express')
var multer = require('multer')

var app = express()
var upload = multer({ dest: 'uploads/' })
var auth = function (req, res, next) {
  if (req.headers['x-token'] !== 'xyz') {
    res.status(403).end('Not authenticated')
  }

  next()
}

app.post('/upload-profile-picture', auth, upload, function (req, res) {
  // update database with req.files.*
  res.end('Success :)')
})
```

**Comment by LinusU** [comment]
Please reopen if you feel that your issue wasn't resolved

**Comment by gcaraciolo** [comment]
I'm trying to do this, however there is some odds things happening in my code:
   1. When I use an auth middleware, fileFilter function is not called
   2. When I use an auth middleware, req.body fields are cleaned.

**Comment by LinusU** [comment]
Please post your code
