### ISSUE TITLE
Validation control

### ISSUE THREAD

**Issue by Tito47875** [expressjs/multer#142]
Hello,
     I added validation control on first received bytes, for example if an uploaded file starts with "%PDF", upload is aborted. Also I found a clean way to abort upload.

Anyone interested?

**Comment by LinusU** [comment]
Indeed we are :) please share

**Comment by Tito47875** [comment]
Should you see a pull request. I edited index.js

Regards!

**Comment by LinusU** [comment]
Discussion picked up in #155, thanks for sharing!
