### ISSUE TITLE
Multer Hanging on Multiple Image upload

### ISSUE THREAD

**Issue by adzample** [expressjs/multer#151]
Hey guys,
Let me start by saying multer has made my life that much easier and it's a fantastic module. However, I am having some issues on file uploads (100-500 images ~1-3mb each) in which the uploads hang on both my mac and deployed on AWS. The last lines logged are 
```
****.jpg is starting ...
file uploaded to  packages/theme/public/assets/img/uploads/115.jpg
****.jpg is starting ...
file uploaded to  packages/theme/public/assets/img/uploads/114.jpg
****.jpg is starting ...
file uploaded to  packages/theme/public/assets/img/uploads/113.jpg
file uploaded to  packages/theme/public/assets/img/uploads/112.jpg
```

and after a set period of time of waiting it automatically attempts to reupload the images but halts in exactly the same place. 

For clarity I have removed the emitters from my code but no errors are registered and I have no limits on file size/ number of files. If I set inMemory to true the upload works every time without fail - but due to the huge size of the upload it isn't exactly feasible. Wondering if you knew a fix or why this may be happening.. thank you so much for your time. Adam
```javascript
exports.create = function(req, res, next) {
  var handler = multer({
    dest: 'packages/theme/public/assets/img/uploads/',
    onFileUploadStart: function (file) {
      console.log(file.originalname + ' is starting ...');
    },
    rename: function (fieldname, filename, req, res) {
      req.body.num--;
      var username = req.body.num
      if(req.body.num<10){
        username = '0'+req.body.num
      }
      return username;
    },
    onFileUploadComplete: function (file, req, res) {
      console.log(file.fieldname + ' uploaded to  ' + file.path);
    }
  })
  handler(req, res, next)
};
```

**Comment by LinusU** [comment]
Hi @adzample,

Would you mind testing again with the newly released multer `1.0.0`, thanks!
