### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by LinusU** [expressjs/multer#152]
Should we provide any special means for error handling?

**Scenario** Sometimes you want to handle errors from multer by telling your user that "something went wrong with your file upload please try again". You need a way to treat errors from multer differently than errors from other middleware.

**Solution A** Have an option called error handling which can be either `automatic` or `manually`. When set to `automatic` the error will be delegated to express via `next(err)`; same as any other middleware. When it is set to `manual` the error will be set as `req.uploadError` and `next` will be called without an error; as far as express is concerned everything went fine, it's then up to the user to check `req.uploadError` on every request.

```javascript
var upload = multer({ errorHandling: 'manual' }).single('avatar')

app.post('/profile', upload, function (req, res) {
  if (req.uploadError) {
    return res.end('Error uploading your new avatar')
  }

  res.end('You new avatar is uploaded')
})
```

**Solution B** Don't do anything special. If users want to handle errors from multer separately, they'll have to invoke the middleware manually. E.g.

```javascript
var upload = multer().single('avatar')

app.post('/profile', upload, function (req, res) {
  upload(req, res, function (err) {
    if (err) {
      return res.end('Error uploading your new avatar')
    }

    res.end('You new avatar is uploaded')
  }
})
```

**My standpoint** I actually prefer solution B. It's less code for us to maintain, but more importantly: it's consistent with other middleware. This is the way to single out errors from specific middleware, at least until express provides any other means of doing so. If we add this, then every other middleware should do so as well.

**Comment by jpfluger** [comment]
I support an app that creates a website from configuration file(s).  The config file ties together middleware and response handlers to build a full route. 

```javascript
// ... from config file A, readin `upload` function
// ... from config file B, readin `validate` function
// ... from config file C, readin `save` function
// ... from config file D, readin `responsehandler` function

// piece together the route:
app.post('/profile', upload, validate, save, responsehandler);
```
With `manual`, `validate` will be invoked and I can handle the error there easily by looking at `uploadError`.  Alternatives?

**Comment by LinusU** [comment]
I would propose catching it in the middleware returned from config file A. You can than report however you like, e.g. putting it on the request object.

```javascript
function readConfigA () {
  var upload = multer(cfgFromFile).fields(fieldsFromFile)

  function middleware (req, res, next) {
    upload(req, res, function (err) {
      req.uploadError = err
      next()
    })
  }

  return middleware
}
```

The benefit of this is that our users are free to report the error however they see fit. Since we can't anticipate exactly how it will be used, providing two options might still be to little to the guy who wants a third option.

I could imagine someone wanting to emit an event when hitting an upload error. This could easily be accomplished with this approach, instead of us also adding an option to emit an error event instead of `upoadError` or `next(err)`.

**Comment by jpfluger** [comment]
Just tested it -- that solution worked. Thanks!  That was the primary use case I had for `manual` mode. I have no objection to getting rid of `manual`.

**Comment by LinusU** [comment]
Cool!

**Comment by LinusU** [comment]
Fixed in `1.0.0`

**Comment by Jakobud** [comment]
I don't understand this syntax:

```
var upload = multer().single('avatar')

app.post('/profile', upload, function (req, res) {
  upload(req, res, function (err) {
    if (err) {
      return res.end('Error uploading your new avatar')
    }

    res.end('You new avatar is uploaded')
  }
})
```

You have this callback
```
function(err){
  if (err) {
     return res.end('Error uploading your new avatar')
  }

  res.end('You new avatar is uploaded')
}
```

But `req` and `res` aren't passed to that callback... Only `err` is. So why are you accessing `res` in that callback? Why isn't the syntax like this

```
app.post('/profile', upload, function (req, res) {
  upload(function(err, req, res) {
    if (err) {
      return res.end('Error uploading your new avatar')
    }

    res.end('You new avatar is uploaded')
  }
})
```

**Comment by LinusU** [comment]
> But req and res aren't passed to that callback... Only err is. So why are you accessing res in that callback?

`req` and `res` is coming from the closure above. If you have trouble grasping this concept I would recommend this read: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

> Why isn't the syntax like this

Because in your example `upload` wouldn't have any request to accept the upload from, it needs to be passed the `req` parameter in order to receive the upload. And it doesn't have any other parameters than `err` to the callback since that's how middleware works in express, and also, they are simply not needed.

**Comment by Jakobud** [comment]
Oh I get it now. That makes a lot more sense. Thanks,
