### ISSUE TITLE
Release proposal: 1.0.0

### ISSUE THREAD

**Issue by LinusU** [expressjs/multer#153]
I propose that we release [breaking-changes](https://github.com/expressjs/multer/tree/breaking-changes), b04b97e47e412bfc08129908628c6639e471bccb, as version 1.0.0.

This will include breaking changes, but since this is a major version point, no one will be updated automatically.

This release fixes most of the open issues, and my intention is to go thru them all and close them as soon as this is released.

The pull request to be merged would be #131.

**Comment by LinusU** [comment]
ping @jpfluger @hacksparrow

**Comment by hacksparrow** [comment]
Looks good to me, awaiting confirmation from @jpfluger.

**Comment by jpfluger** [comment]
Go for it @hacksparrow.

**Comment by LinusU** [comment]
Nice! Merging into master now!

**Comment by LinusU** [comment]
@hacksparrow or @jpfluger, I would appreciate if you could add me on npm :)

I have tagged a release in git, all that is missing is `npm publish`

**Comment by jpfluger** [comment]
Hey @hacksparrow, I don't need to be on npm unless you both want backups. I'd like to stay as a multer contributor, though, and can help be a sounding board for proposed changes and answer issues from time-to-time.

**Comment by hacksparrow** [comment]
I'll add you both. Please share your usernames.

**Comment by LinusU** [comment]
`linusu`, same as on github

**Comment by jpfluger** [comment]
`jpfluger`, like github

**Comment by LinusU** [comment]
Multer 1.0.0 released :tada: :birthday: :clap:

**Comment by hacksparrow** [comment]
Yoohooo! :tada: :birthday: :clap: Excellent job, guys.

**Comment by gabeio** [comment]
:+1: :tada: !

**Comment by jpfluger** [comment]
Happy 1st :birthday:   :tada: :clap:
