### ISSUE TITLE
upload a file, and the multer saved two files

### ISSUE THREAD

**Issue by lokiiart** [expressjs/multer#154]
thanks for sharing the awesome module.
the question is I used the XMLHttpRequest upload a file  on my web client, and it saved two files on my server. 
I haven't tested with the usual form submit.
one is the right file as it shown in the "path", the other one is from no where. but it is the copy of the first one.

anyone has the same question?

**Comment by LinusU** [comment]
Could you please try this again with the newly released multer `1.0.0`, thanks!
