### ISSUE TITLE
Cant get the middleware work in express 4

### ISSUE THREAD

**Issue by daffa2** [expressjs/multer#159]
I am just following the readme tutorial and encountered the problem of 

```text
Error: Unexpected field 
    at makeError (*\node_modules\multer\lib\make-error.js:12:13)
```

my code look like this:
```javascript
var express = require('express');
var app = express();

var multer = require('multer');
var upload = multer({ dest: './uploads/'});

app.post('/image',upload.single('avatar'), function (req, res) {
    var image = req.body;
    res.status(204).end()
});
```

my client is angular from the tutorial :https://uncorkedstudios.com/blog/multipartformdata-file-upload-with-angularjs

I cant find the solution can you help me?

**Comment by LinusU** [comment]
What is the field name of the file uploaded?  `<input type="file" name="THISVALUE" />`

The code you are using is expecting it to be `avatar`.

**Comment by LinusU** [comment]
The new version of multer requires the fields of the uploaded files to be specified beforehand. Please refer to the readme on how to use this.

Please reopen if you require further assistance, I'd be happy to help!

**Comment by dmreinoso** [comment]
Hi Linus,

I have a related problem.

    var express = require('express');
    var multer  = require('multer');
    var upload = multer().single('file');
    
    var app = express();
    
    app.post('/profile', function (req, res) {
      upload(req, res, function (err) {
        if (err) {
            console.log(req.file);
            console.log(err);
            return;
        }
    
        res.send('Profile ok');
      });
    });
    
    app.listen(3000);

Did my tests with a correct field name, in my cade "file" and this is the result:

    { fieldname: 'file',
      originalname: 'profile__.csv',
      encoding: '7bit',
      mimetype: 'application/vnd.ms-excel',
      size: 268381 }
    
    { [Error: Unexpected field]
      code: 'LIMIT_UNEXPECTED_FILE',
      field: 'file',
      storageErrors: [] }

**Comment by gabeio** [comment]
@dmreinoso
so in your code their it says `.single('file')` meaning one file allowed under the field name `file`...

your html should have a line to `<input type="file" name="file"` if the `name="file"` is not `file` that is your issue, otherwise you might have 2 `<input type="file"` and with `.single()` you are telling it only 1 should exist...

if all of the above conditions are satisfied then there is an issue let us know! :smiley:

**Comment by dmreinoso** [comment]
You are rigth, I made a simple web form with one "file" input and it worked.

It appears that "Advanced Rest Client" a Chorme extension is sending more than one "file" field.

**Comment by LinusU** [comment]
Thanks for the help @gabeio :+1:

**Comment by gabeio** [comment]
no problem @LinusU :+1: now that I understand what's going on a bit better :laughing: and made a bunch of these mistakes already LOL

**Comment by samsonayalew** [comment]
As a note i had the same error when i was running node on node-debug but when i start node with npm start there an error related to other module(mongodb).

**Comment by rakeen** [comment]
Hi,  
I ran into similar problem. I'm getting this error:  

```
{
  "code": "LIMIT_UNEXPECTED_FILE",
  "field": "file",
  "storageErrors": []
}
```

In the back-end I'm trying to access the data like this:  

```
var upload = multer({
        dest: '/data/profile_pic/'
    }).single('profile_pic');
```  

My markup is:  

```
<input class="form-control" type="file" id="profile_pic" name="profile_pic">
```

Notice that both `req.file` and `req.files` are `undefined`.  
```
upload(req,res,function(err){
  if(err){
    console.log(req.file,req.files);
    res.status(500).send(err);
  }
}
```

**Comment by LinusU** [comment]
It seems like multer thinks that there is a file named "file" being uploaded. Could you post your entire `<form>` markup?

**Comment by rakeen** [comment]
Got it.
I was using [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) to send the XHR request. By default they set the name of all the fields to `file`.

**Comment by LinusU** [comment]
Nice :raised_hands:

**Comment by jpesquibel** [comment]
Got mine working.  It was the "name" of the file element what was causing problems.  Good work.

**Comment by vishesh1king** [comment]
app.use(multer({dest: __dirname+'/uploads'}).single('image'));


Using .single(file) it works but while downloading its not downloading as image file so i changed it to .single(image). Then this error appears ...

Error: Unexpected field
    at makeError (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/multer/lib/make-error.js:12:13)
    at wrappedFileFilter (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/multer/index.js:39:19)
    at Busboy.<anonymous> (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/multer/lib/make-middleware.js:113:7)
    at emitMany (events.js:108:13)
    at Busboy.emit (events.js:182:7)
    at Busboy.emit (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/busboy/lib/main.js:31:35)
    at PartStream.<anonymous> (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:77:13)
    at PartStream.emit (events.js:169:7)
    at HeaderParser.<anonymous> (/media/ionixx/532076ac-c1eb-44fc-9544-fc152199537c/nodejs_samples/node_modules/dicer/lib/Dicer.js:51:16)

**Comment by wiill** [comment]
Hi there!
Sorry to reopen, but I get the exact same error as @daffa2, but only when I'm using a mobile browser, seems to have some issues depending on the browser agent: 

- Safari Desktop OK
- Safari iPad OK
- Safari iPhone KO
- Chrome Desktop OK
- Chrome mobile KO
- Chrome mobile faking desktop ("View desktop version of page"): no error but no upload neither

I'll edit upon more tests...

**Comment by Skillnter** [comment]
I am getting the same LIMIT_UNEXPECTED_FILE error...
But the condition is lil' weird...
I am using angular as frontend....
I made a form and upload the file.... it works... 
Form/page isn't refreshed... use the same form...change the file and submit again.... error....
And the problem is.... when i refresh the page/form... it works again....
I checked the data sent too...
Its single file....
What could be the possible reason for this?

**Comment by simzzz** [comment]
@rakeen  You should have mentioned how you solved it. I'm struggling with the exact same problem, req.file is undefined. when I do `.upload('file')` it says it's done but doesn't add the file anywhere since it's undefined :(

**Comment by wiill** [comment]
I was having 2 problems:

- I have a duplicate form on my page, but duplicated field was using a different ID, so it was mixing up and throwing the error mentioned in the title of the issue. Getting the same field ID in both forms solved the error

- the Chrome Mobile faking desktop issue: no error but no upload either
`req.file.mimetype`
may be "csv" or "comma-separated-values" depending on the browser, and in my code, when other than "csv", router method did what it was supposed to do, i.e. nothing at all! so correcting the condition to
`filename.contains('csv')`
instead of checking the mime type did the trick

So @Skillnter, about your issue, I'm no angular expert, but maybe angular's changing the file field's ID once uploaded (setting some flag of some sort for whatever readon), I suggest you inspect the file input element after upload before refreshing?

**Comment by kunalp-scalex** [comment]
Still getting error : {
  "code": "LIMIT_UNEXPECTED_FILE",
  "field": "file",
  "storageErrors": []
}.

Below is my code-
1)  knowledgeHubRoute.post('/upload_image', upload.single('upload'), (req, res) => {
    try {
        res.status(200).send('Image Uploaded Successfully');
    } catch (error) {
        res.status(400).send({
        message: error.message,
      });
    }

});


2)  import { CONFIG } from '../config';
import { s3 } from '../aws-sdk/s3/index';
import  multer  from 'multer';
import  multerS3  from 'multer-s3';

const bucket = CONFIG.AWS.AWS_BUCKET_NAME;
const upload = multer({
  storage: multerS3({
    s3: s3,
    bucket,
    acl: 'public-read',
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    contentType: multerS3.AUTO_CONTENT_TYPE,
    key: function (req, file, cb) {
      var newFileName = Date.now() + '-' + file.originalname;
      var fullPath = 'knowledge_hub/media/' + newFileName;
      cb(null, fullPath); // Use a unique filename or any other logic you prefer
    },
  }),
});

module.exports = upload;

3) From postman I am sending request:
![image](https://github.com/expressjs/multer/assets/114995211/631ae3e2-1b4f-462e-a4b3-cc3d96e043cb)

@LinusU could you or any one can help here ?
