### ISSUE TITLE
Error after upgrade to 1.0.0

### ISSUE THREAD

**Issue by chrisvdb** [expressjs/multer#161]
Since upgrading to Multer 1.0.0 I get the following error:

20 Jul 11:38:36 - [nodemon] starting `node app.js`
/home/chrisvdb/project/Code/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/home/chrisvdb/project/Code/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/chrisvdb/project/Code/app.js:75:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
20 Jul 11:38:40 - [nodemon] app crashed - waiting for file changes before starting...

I call Multer as follows:

app.use(multer({ dest: path.join(__dirname, 'uploads') }));

Any idea on how to solve this?

**Comment by jpfluger** [comment]
Version 1.0.0 is a breaking-changes version. For an example of calling multer the new way, please look at the example at the top of the [README](https://github.com/expressjs/multer/blob/master/README.md).

```javascript
var express = require('express')
var multer  = require('multer')
var upload = multer({ dest: 'uploads/' })

var app = express()

app.post('/profile', upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file
})

app.post('/photos/upload', upload.array('photos', 12), function (req, res, next) {
  // req.files is array of `photos` files
})

var cpUpload = upload.fields([{ name: 'avatar', maxCount: 1 }, { name: 'gallery', maxCount: 8 }])
app.post('/cool-profile', cpUpload, function (req, res, next) {
  // req.files is an object (String -> Array) where fieldname is the key, and the value is array of files
  //
  // e.g.
  //  req.files['avatar'][0] -> File
  //  req.files['gallery'] -> Array
})
```

**Comment by jpfluger** [comment]
Also see my comments in #162.

**Comment by chrisvdb** [comment]
Super, thanks a lot of the detailed explanation.

**Comment by arefm** [comment]
Hi @jpfluger , events lile onFileUploadStart, onFileUploadData and onFileUploadComplete not work in new version ? if this version support them may I ask how can I implement them ?

**Comment by LinusU** [comment]
@arefm They have been removed, what you need them for?

**Comment by iamsmarts** [comment]
going through an older course example this put me back in track, Thanks!
