### ISSUE TITLE
File Extensions Missing on Rename

### ISSUE THREAD

**Issue by sgulgas** [expressjs/multer#164]
While i've got a workaround for the time being, i've noticed that when i jumped to 1.0.0 that my rename function (once ported over to use diskStorage) doesn't append the extension like it simply did... Am i doing something wrong or is this a missing feature

**Comment by LinusU** [comment]
The disk storage no longer magically appends the previous extension for you. The reasoning for this is because it made it impossible to change the extension which many of our users wanted to do.

I'll add a clarification of this to the documentation.

**Comment by LinusU** [comment]
Fixed with 29edf852680950a2291101de9086e12a81fadc95
