### ISSUE TITLE
in memory storage with mongoose-crate-s3

### ISSUE THREAD

**Issue by freeeal** [expressjs/multer#175]
has any one tried to use in memory storage of multer with mongoose-crate-s3 (https://github.com/achingbrain/mongoose-crate-s3)? for some reason, mongoose-crate-s3 only works when multer is used with the disk storage option. when using the in memory option, i get the following error: "No file exists at C:\Users\Alan\AppData\Local\Temp\.."

if anyone's encountered such issues, i'd appreciate your correspondence. thanks!

**Comment by LinusU** [comment]
Ehh, as far is I can tell you give that library the path to the file. If you are using the memory storage, than there isn't any path to the file since it only exists in memory. You instead have a `Buffer` instance.

Maybe I'm missing something, could you share some code?

**Comment by freeeal** [comment]
Hmm, well I opened up the same issue on the mongoose-crate-s3 repo. In the second link, you can find some snippets:

https://github.com/achingbrain/mongoose-crate-s3/issues/6

Maybe I'm just failing on the implementation of multer's memory storage option.. thanks!

**Comment by LinusU** [comment]
As I said in the other thread this is a limitation in that library which we cannot fix on our end. Your getting a strange error though and I think that is because you're using an old version of multer.

Could you please updated to multer `1.x` and see if you get a more descriptive error?

**Comment by freeeal** [comment]
Yup, you're right. And updating to multer 1.x gives me the right error --> Error: Attachment has no path property!

Do you have any suggestions for making mongoose-crate-s3's .attach() support buffer objects, as you mentioned in the other post?

**Comment by LinusU** [comment]
I've left some pointers in the other thread :)
