### ISSUE TITLE
app.use() requires middleware functions

### ISSUE THREAD

**Issue by CrackerakiUA** [expressjs/multer#176]
![screenshot 2015-07-23 19 48 47](https://cloud.githubusercontent.com/assets/6815721/8859017/66ba6d26-3183-11e5-9668-d2f9d61ec362.png)
Hello, i have above error after latest update. Below very simple code to reproduce the problem:
//
var express = require('express');
var app = express();
var multer = require('multer');
app.use(multer({
	inMemory: true
}));
app.listen(2548);
//
I run it under windows 7 x64.

**Comment by gabeio** [comment]
version 1.0.0 has now changed the way you should be using multer please read the updated readme for more details. comment again if you have any more trouble cheers!
