### ISSUE TITLE
Migration to 1.0.1

### ISSUE THREAD

**Issue by CrackerakiUA** [expressjs/multer#177]
My error below, after i switch to new version:
![multer](https://cloud.githubusercontent.com/assets/6815721/8861126/15247fc0-3191-11e5-9feb-68fb114cd847.png)
I am uploading my files the same way i was uploading it before, with https://github.com/danialfarid/ng-file-upload, my code is:

```javascript
var multer = require('multer');
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
app.post('/api/uploadImage', upload.single('image'), function (req, res) {
  console.log(req.file);
  console.log(req.body);
  console.log(req.files);
});
```

**Comment by LinusU** [comment]
That error indicates that you are either receiving a file with a fieldname other than `image`, or that you are receiving more than one file with the fieldname `image`.

Could you add the following to your code:

```javascript
app.use(function (err, req, res, next) {
  console.log(err) // <-- this should show you the fieldname of the offending file
  console.log(err.stack)
})
```

This should give you output similar to this:

```text
{ [Error: Unexpected field] code: 'LIMIT_UNEXPECTED_FILE', fieldname: 'avatar' }
Error: Unexpected field
  at makeError ...
```

**Comment by CrackerakiUA** [comment]
Yeah, that fix the error, but req.file, req.files, req.image comes empty.

**Comment by LinusU** [comment]
Hmm, that's very strange. The following code works for me:

```javascript
var multer = require('multer')
var express = require('express')

var app = express()
var storage = multer.memoryStorage()
var upload = multer({ storage: storage })

app.get('/', function (req, res) {
  res.writeHeader(200, { 'Content-Type': 'text/html' })
  res.write('<form action="/api/uploadImage" enctype="multipart/form-data" method="POST">')
  res.write('<input type="file" name="image" />')
  res.write('<input type="submit" />')
  res.end('</form>')
})

app.post('/api/uploadImage', upload.single('image'), function (req, res) {
  console.log(req.file)
})

app.listen(3000)
```

Output:
```text
{ fieldname: 'image',
  originalname: 'tiny1.dat',
  encoding: '7bit',
  mimetype: 'application/octet-stream',
  buffer: <Buffer 3c 6f 29 29 29 3c 3c>,
  size: 7 }
```

**Comment by gabeio** [comment]
@CrackerakiUA are you sure you are sending the file using `<form enctype='multipart/form-data'` otherwise multer will not be able to understand the file being sent...

**Comment by CrackerakiUA** [comment]
@gabeio not sure how to check that, when i place this plagin https://github.com/danialfarid/ng-file-upload into form with multipart it's not working, also when i add all those attributes in that form the same. Perhaps i should use other plugin.

**Comment by CrackerakiUA** [comment]
Ok, i build one without any plugin and it worked out.

**Comment by LinusU** [comment]
Glad that you solved it :)
