### ISSUE TITLE
can we stop changing the way multer setup please ? im banging my head 

### ISSUE THREAD

**Issue by dtuyenle** [expressjs/multer#179]
This used to work inside a route now it is no longer working 

```javascript
var handler = multer({

		    	dest: __base + 'uploads/images/',

			    onFileUploadStart: function (file) {
			      	// You now have access to req
			      	console.dir(req);
			      	console.log(file.fieldname + ' is starting ...')
			    },

			    onFileUploadComplete: function (file) {
			      	console.log(file.fieldname + ' uploaded to  ' + file.path)
			      	var asset = new Asset();
					asset.path			= req.files.file ? req.files.file.path.replace('uploads','') : '';
					asset.type			= req.params.type;
					asset.base64_data 	= req.body.base64_data ? req.body.base64_data : '';

					asset.save(function(err, asset_data) {
						if (err)
							res.send(err);

						res.json({ message: 'Asset created!', asset_data: asset_data });
					});
			    }

		  	});
		  	
		  	handler(req, res);
```

**Comment by gabeio** [comment]
The point behind having major version number changes is that it is *not backwards compatible* if you wish to use the older version we are not stopping you. But there are significant benefits to upgrading including that I by myself can not DoS your server by filling your hard drive in (your available hard drive space/your internet speed). As such these changes need a different API which you will need to learn, if you are not willing to learn new APIs when they change I can not help you.

**Comment by LinusU** [comment]
Additionally, if you got upgraded automatically, it's because you've added `"multer": "*"` to your dependencies. This basically means, whatever the latest version is, give it to me. You should always specify your dependencies so that you follow semver. In your case that would have been `"multer": "^0.1.8"`, which wouldn't have automatically upgraded you to this version.

I would recommend you to upgrade to the latest version and use the new syntax, but you are free to do however you like. The readme contains instructions for how to use the latest version.

**Comment by LinusU** [comment]
You could upgrade your code to something like this:

```javascript
var upload = multer({ dest: 'uploads/images/' })

app.post('/asset/:type', upload.single('file'), function (req, res, next) {
  var asset = new Asset()

  asset.path = req.file.path.replace('uploads','')
  asset.type = req.params.type
  asset.base64_data = (req.body.base64_data ? req.body.base64_data : '')

  asset.save(function (err, asset_data) {
    if (err) return next(err)

    res.json({ message: 'Asset created!', asset_data: asset_data })
  })
})
```

**Comment by JTallis** [comment]
The readme still mentions about overriding the "rename" function despite it no longer working. I to, was stuck and found myself here. Actually, I still am stuck. This is my use case:

    app.use(multer({
      dest: './photos/',
      rename: function(fieldname, filename){
        console.log('test');
        return uuid.v4();
      },
      onFileUploadStart: function(file, req, res){
        console.log('File upload starting...');
        if (!allowed(req.ip)) {
          return false;
        }
      },
      onFileUploadComplete: function(file){
        console.log('File upload complete...');
      }
    }).single('userPhoto'));

I only need onFileUploadStart to block file uploads as I only want the post request to be allowed by  certain ips. I can very well do it like in the readme but not sure how to rename the file, and implement by little ip whitelist (allowed).

What is "Asset" in the above code?

**Comment by LinusU** [comment]
@JTallis 

> The readme still mentions about overriding the "rename" function

Where? I can't find it, but I would be happy to update it.

*1)* `fileFilter` is indeed the correct way to filter files from being uploaded. Although I might be able to recommend a better way for the ip filtering. The way you have it now will still allow anyone to hit the route, the only difference is that the file won't be allowed. Maybe having a completely separate middleware would suite you better.

*2)* Using a storage engine would be the correct way of specifying where you want the files to be stored.

```javascript
// 2
var storage = multer.diskStorage({
  destination: './photos/',
  filename: function (req, file, cb) {
    var ext = file.mimetype === 'image/png' ? 'png' : 'jpg'

    cb(null, uuid.v4() + '.' + ext)
  }
})

var upload = multer({
  storage: storage,
  fileFilter: function (req, file, cb) {
    cb(null, (file.mimetype === 'image/jpeg' || file.mimetype === 'image/png'))
  }
})

// 1
function restrictIps (req, res, next) {
  if (allowed(req.ip)) return next()

  var err = new Error('You are not allowed at this route')
  err.statusCode = 403
  next(err)
}

app.post('/upload', restrictIps, upload.single('userPhoto'), function (req, res) {
  res.setHeader('Content-Type', 'text/plain')
  res.send('File uploaded.')
})
```

**Comment by JTallis** [comment]
Brilliant! What's the benefit of diskStorage?

    By default, Multer will rename the files so as to avoid naming conflicts. The renaming function can be customized according to your needs.

I gathered this meant the rename function?

**Comment by LinusU** [comment]
You were actually using `DiskStorage` all along :)

```javascript
multer({ dest: './photos/' })
```

is a shorthand for

```javascript
multer({ storage: multer.diskStorage({ destination: './photos/' }) })
```

Ahh, I understand. It really refers to the `filename` parameter to the `diskStorage` function. Should probably clarify that.
