### ISSUE TITLE
knowing if a file upload is complete

### ISSUE THREAD

**Issue by freeeal** [expressjs/multer#180]
i am using multer-s3 (https://www.npmjs.com/package/multer-s3) in conjunction with multer to store images in an s3 bucket. however, for some reason when i log 'req.file', i get that the size is "undefined." -- so, i am wondering if the file is not completely being uploaded to cause a case like this... please let me know what you think.

(i realize that version 1.x got ride of the option for onFileUploadComplete, etc.)

**Comment by LinusU** [comment]
This is actually a bug in S3FS which multer-s3 uses, see RiptideElements/s3fs#29. The bug only affects the reporting of file size, so even thought it is `undefined` it has actually uploaded the entire file.

I also opened badunk/multer-s3#2 to fix some other issues with the module.

Feel free to reopen if you have any more questions/problems with this.
