### ISSUE TITLE
Cannot make the simple example to work

### ISSUE THREAD

**Issue by ningji** [expressjs/multer#189]
was following this
https://codeforgeek.com/2014/11/file-uploads-using-node-js/#comment-29091
The only change is added "single()".

```javascript
app.use(multer({ dest: './uploads/',
 rename: function (fieldname, filename) {
    return filename+Date.now();
  },
onFileUploadStart: function (file) {
  console.log(file.originalname + ' is starting ...')
},
onFileUploadComplete: function (file) {
  console.log(file.fieldname + ' uploaded to  ' + file.path)
  done=true;
}
}).single('userPhoto'));
```

but doesn't work, file does uploaded successfully, but never hit `onFileUploadStart`, `onFileUploadcomplete`.

ubuntu 12.04, node 0.12.7, express 4.13.1, multer 1.0.1.

Any help appreciated. Thanks !

**Comment by gabeio** [comment]
because those `onX` functions were removed in the new `1.0.0` version [see here](https://github.com/expressjs/multer/issues/179#issuecomment-125101000) about fixing it.

**Comment by LinusU** [comment]
Also, having a global variable named `done` that all requests share and that never gets reset back to `false` will cause all kinds of hell. I would strongly urge you not to do it.

Rewriting the example for 1.0:

```javascript
/*Define dependencies.*/
var express = require('express')
var multer = require('multer')

/*Configure the app */
var app = express()
var upload = multer({ dest: './uploads/' })

/*Handling routes.*/
app.get('/', function (req, res) {
  res.sendfile('index.html')
})

app.post('/api/photo', upload.single('userPhoto'), function (req, res) {
  console.log(req.files)
  res.end('File uploaded.')
})

/*Run the server.*/
app.listen(3000, function () {
    console.log('Listening on port 3000')
})
```

**Comment by ningji** [comment]
Thank you verrrrrry much !!!!!

**Comment by LinusU** [comment]
No problem! Happy hacking :beers:
