### ISSUE TITLE
after enter an Error in fileFilter,it doesn't work

### ISSUE THREAD

**Issue by zyf0330** [expressjs/multer#192]
```javascript
function fileFilter (req, file, cb) {

  // The function should call `cb` with a boolean
  // to indicate if the file should be accepted

  // To reject this file pass `false`, like so:
  cb(null, false)

  // To accept the file pass `true`, like so:
  cb(null, true)

  // You can always pass an error if something goes wrong:
  cb(new Error('I don\'t have a clue!'))

}
```

This line within 'new Error' works not well.
Though 

```javascript
res.render('error', {
      message: err.message,
      error: err
    });
```
has been executed in app.js error handle,but the page shows it is uploading file.

**Comment by LinusU** [comment]
Hmm, I think that this is the same bug as in #168. I really need to get this fixed, hopefully I can get at least a workaround commited when I get home tonight.

Thank you for your patience.

**Comment by zyf0330** [comment]
@LinusU Thanks,I have seen #168 and I think it is the same question also.
If you need some extra info about it, I am willing to help.

**Comment by LinusU** [comment]
Thank you :+1: 

I don't have time to try anything at the moment, but if you want to experiment a bit, this is the lines where I think we need to change something: [lib/make-middleware.js L36-42](https://github.com/expressjs/multer/blob/d480e5f14de09067b5a6d747c02e9dc458379422/lib/make-middleware.js#L36-L42)

When we `unpipe` the `req`, the browser never gets to send all of it's data. I tried adding a `req.resume()` but for some reason that didn't help. I don't know if it's because busboy is doing something strange.

Maybe something like this could work:

```diff
 function done (err) {
   if (isDone) return
   isDone = true
-  req.unpipe(busboy)
   busboy.removeAllListeners()
-  next(err)
+  busboy.on('finish', function () {
+    next(err)
+  })
}
```

**Comment by zyf0330** [comment]
@LinusU it doesn't work,and the line 'next(err)' in callback is not went into.

**Comment by LinusU** [comment]
Should be fixed by dfa2095f76966eb7ea2cee6b446f2e7de710fb48, please reopen if issue persists.

**Comment by zyf0330** [comment]
@LinusU My problem is not about file size limit,and that don't fit me.

when I throw a error at FileFilter, line 95 in the make-middleware.js is ran into.
```javascript```
if (err) {
          appender.removePlaceholder(placeholder)
          return abortWithError(err)
        }
```
then I don't know it do what!

**Comment by LinusU** [comment]
Oh shit, I thought that it would be solved by that same bug. I'll take another look at this.

**Comment by LinusU** [comment]
@zyf0330 Could you try the following in [make-middleware.js L95-98](https://github.com/expressjs/multer/blob/32590b66a26b778f0cc207d7cdc0f170356c7e7a/lib/make-middleware.js#L95-L98)

```diff
         if (err) {
           appender.removePlaceholder(placeholder)
+          fileStream.resume()
           return abortWithError(err)
         }
```

**Comment by zyf0330** [comment]
@LinusU it doesn't work too.What happened is that chrome shows the file is uploading after the error has been handled. So uploading stream needs to be closed,is it?

**Comment by LinusU** [comment]
Hmm, could you try adding this in addition to the change that you already made.

[make-middleware.js L31-37](https://github.com/expressjs/multer/blob/32590b66a26b778f0cc207d7cdc0f170356c7e7a/lib/make-middleware.js#L31-L37)

```diff
     function done (err) {
       if (isDone) return
       isDone = true
       req.unpipe(busboy)
+      req.resume()
       busboy.removeAllListeners()
       next(err)
     }
```

**Comment by zyf0330** [comment]
it can't do.uploading is continuing

**Comment by zyf0330** [comment]
I write req.on('end') before req.resume(),but it can not run into.
As for busboy,I don't know it ,so I can't give some advice.

**Comment by LinusU** [comment]
Okay, I'm pretty sure that this is a bug in Node.js itself :crying:

See joyent/node#25823

**Comment by zyf0330** [comment]
I will put my eye on this issue.

**Comment by LinusU** [comment]
Possible fix here: nodejs/node#2323. Haven't had the time to test yet thought...

**Comment by zyf0330** [comment]
Let me have a look.wait.

**Comment by zyf0330** [comment]
I change _stream_readable.js like the fix #2323 above,but nothing runs into lines which are changed and result is the same.
Maybe I do something wrong,after all I don't know many.

**Comment by LinusU** [comment]
You still need this change to multer (I think), might be something more thought...


[make-middleware.js L31-37](https://github.com/expressjs/multer/blob/32590b66a26b778f0cc207d7cdc0f170356c7e7a/lib/make-middleware.js#L31-L37)

```diff
     function done (err) {
       if (isDone) return
       isDone = true
       req.unpipe(busboy)
+      req.resume()
       busboy.removeAllListeners()
       next(err)
     }
```

**Comment by zyf0330** [comment]
Could you tell me if I should alter the multer\node_modules\busboy\node_modules\readable-stream\lib\_stream_readable.js?

**Comment by LinusU** [comment]
Hmm, I don't think so. It should be the stream from the builtin `http` module that exhibits the problem.

**Comment by zyf0330** [comment]
Do you mean I need to alter that file and rebuild nodejs.exe?
Is it true?

**Comment by LinusU** [comment]
I'm not sure on the specifics but, yeah, probably. That's why it's a bit of a pain to test it...

**Comment by zyf0330** [comment]
That is a challenge for me...I think I need to think about it .

**Comment by LinusU** [comment]
@zyf0330 Could you try #205 and see if it fixes it for you?

**Comment by zyf0330** [comment]
I will

Linus Unnebäck <notifications@github.com>于2015年8月15日周六 07:26写道：

> @zyf0330 <https://github.com/zyf0330> Could you try #205
> <https://github.com/expressjs/multer/pull/205> and see if it fixes it for
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expressjs/multer/issues/192#issuecomment-131266683>.
>
-- 

追随

**Comment by LinusU** [comment]
This should be fixed by #205 and released on npm as version `1.0.5` :rocket: 

Please reopen if issue persists.

**Comment by tibortru** [comment]
I still have this issue. I am using multer 1.0.6 and node 0.12.7

i've got 

```
fileFilter: function (req, file, cb) {

        if (file.mimetype !== 'image/png'
            && file.mimetype !== 'image/jpg'
            && file.mimetype !== 'image/jpeg'
            && file.mimetype !== 'image/gif') {
            console.log('Got file of type', file.mimetype);
            return cb(new Error('Only image files are allowed!'));
        }

        // To accept the file pass `true`, like so:
        cb(null, true);

    }
```
the function executes, but request goes Pending in Chrome,

**Comment by zyf0330** [comment]
@tibortru May you can try node v4.0 version.

**Comment by tibortru** [comment]
@zyf0330 Ye, same thing... I actually don't know how I got this ancient version of Node installed... but after I reinstalled node to version 4.1.2 I still have same issue... Do I explicitly need 4.0 version of node?

**Comment by BruceHem** [comment]
guys is there a way to get res object inside fileFilter function arguments?

**Comment by LinusU** [comment]
Why would you need that? It's purposely not included since you shouldn't respond to the request from the fileFilter function... Interested to hear your use case

**Comment by MrFlish** [comment]
Hey there
