### ISSUE TITLE
Partially uploaded files are not removed when fileSize kicks in

### ISSUE THREAD

**Issue by qqilihq** [expressjs/multer#194]
I'm using the `fileSize` property to set a maximum upload size limit. In case, the uploaded file size exceeds the specified `fileSize` limit, the transfer is interrupted (as expected), but the partially uploaded file still exists on disk. 

I feel, that such files should be removed automatically (also concerning the fact, that there seems to be no way of retrieving the path of partially uploaded files within my callback methods).

**Comment by LinusU** [comment]
I think I might have squashed that bug last night, or maybe not... Which version of multer are you using?

**Comment by qqilihq** [comment]
Hey Linus, thank you for your feedback; I've just updated to 1.0.3, and now the file is deleted in case it exceeds the `fileSize` limit. 

However: The solution which you were describing in #186 for custom error handling does not work any longer with 1.0.3:

    var upload = multer({ limits: { fileSize: 1024 * 1024 * 1024 } });
    
    app.post('/upload', upload.single('file'), function (req, res) {
      // will now also be called in case the limit was reached
      res.send({ result: 'ok' });
    });
    
    app.use(function (err, req, res, next) {
      if (err.code === 'LIMIT_FILE_SIZE') {
        // will not be reached any more :(
      }
    });

As I was also relying on the custom error handling: Any solution on getting that fixed?

**Comment by PokerCurve** [comment]
I am having the same issue as @qqilihq where the err.code is not being set to 'LIMIT_FILE_SIZE' when the limit file size is exceeded in 1.0.3.

A workaround is to perform the following check

    if(typeof req.file.filename == "undefined")  {
       // There was an error with the upload		
    }

**Comment by qqilihq** [comment]
@PokerCurve Thank you for the suggestion, however in that case I cannot distinguish between the cases where (1) the limit was exceeded or (2) no file was attached at all. And I would really like to do that for better error messaging.

**Comment by LinusU** [comment]
This should absolutely work, I'm sorry to have broke it.

This is very related to nodejs/io.js#2323 which there is a proposed fix for. Unfortunately I'm on vacation on a remote island with very bad internet connection and limited time to devote to this.

-----

Sorry, I just found this message sitting in the textbox, I forgot to hit "comment" :confused:

**Comment by qqilihq** [comment]
Hi Linus, I've fixed the issue and sent you a pull request. Enjoy your vacation.

**Comment by LinusU** [comment]
@qqilihq Could you try #205 and see if it fixes it for you?

**Comment by qqilihq** [comment]
@LinusU Yes, I can confirm that it solves the issue in my case.

**Comment by LinusU** [comment]
This should be fixed by #205 and released on npm as version `1.0.5` :rocket: 

Please reopen if issue persists.

**Comment by terwi** [comment]
Hi,
is there a way to stop uploading if the size of the FOLDER not the file is exceeding a defined limitation
