### ISSUE TITLE
Using Multer with a CSRF middleware in Express

### ISSUE THREAD

**Issue by PokerCurve** [expressjs/multer#195]
I need to parse the form before my csrf middleware so it can access the value of req.body._csrf before proceeding with the upload. Is this possible with the newest version of Multer? See below

index.jade:

    form(method="post" action="/profile" enctype="multipart/form-data")
      input(type='hidden', name='_csrf', value=_csrf) 
      input(name="avatar" type="file" accept="image/*")
      button(type="submit") Submit

app.js: I need to parse the body to get the _csrf value before here

    app.use(lusca({
      csrf: true 
    }));

profile.js:
   
    app.post('/profile', upload.single('avatar'), function (req, res, next) {
    })

My understanding is that since the encoding type of the form is enctype="multipart/form-data", the csrf middleware is currently unable to access the value.

**Comment by LinusU** [comment]
You should be able to get some pointers in #184 

Basically it boils down to using it similar to:

```js
app.post('/profile', upload.single('avatar'), lusca({ csrf: true }), function (req, res, next) {
})
```

**Comment by PokerCurve** [comment]
Thanks for the suggestion @LinusU.

I opted  for @gabeio's solution in #184 to attach the csrf token to the url as a query variable while using csrf middleware globally. 

I was able to get the _csrf token before the csrf middleware by doing this:

    form(method="post" action="/profile?_csrf=" + _csrf enctype="multipart/form-data")
     input(name="avatar" type="file" accept="image/*")
     button(type="submit") Submit

I added my own middleware before the csrf middleware to get the csrf token from the query string. Since lusca checks in the body for the csrf token (there isn't an option to make lusca check the req.query for it as far as I am aware).

    app.use(function (req, res, next) {
	  req.body._csrf = req.query._csrf || req.body._csrf;
	  next();
    });

    app.use(lusca({
      csrf: true 
    }));

I am not sure if this is good practice though?

**Comment by LinusU** [comment]
I don't really know why lusca doesn't support reading from the querystring, it's standard in [expressjs/csurf](https://github.com/expressjs/csurf). As discussed in the other thread, there shouldn't be any security concerns with supplying it on the query string.

**Comment by jasisk** [comment]
Hi there. I help out on [lusca](https://github.com/krakenjs/lusca) and @gabeio brought this thread to my attention.

> I don't really know why lusca doesn't support reading from the querystring, it's standard in expressjs/csurf.

You can see [the thread](https://github.com/krakenjs/lusca/issues/61) in our repo about this concern for rationale, however the short version is that [OWASP recommends against it](https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet#Disclosure_of_Token_in_URL) (and I trust OWASP more than I trust myself).

[csurf](https://github.com/expressjs/csurf) has query-string parsing by default however we've opted for a slightly more-strict model as `referer` leakage is a concern for us.

That said, I'll take a look at this and see if we can come up with a better compromise. If not, I'm not entirely opposed to adding query parsing behind a config.

**Comment by LinusU** [comment]
Hmm, I kind of think that the best way would be to have it run after `multer` and thus utilising the POST-body.

```javascript
var csrf = lusca({ csrf: true })
var upload = multer({ _ })

app.post('/profile', upload.single('avatar'), csrf, function (req, res, next) {

})
```

-----

*Maybe* a way of solving this would be to add an option to multer to run something after each request, although I'm not sure that this is the correct place to solve this.

I think that the problem with adding manually is that it's not as easy as dropping lusca into the global middleware. On the other hand, it should it really be run for every request? Doesn't it make more sense to only validate the token when uploading forms, and only generate a token when presenting forms.

Or maybe the problem is on different levels of abstraction. There could be a library above lusca and multer that just fixes everything automatically. It's just a matter of running one before the other.

**Comment by gabeio** [comment]
I was trying to think of a way to do something like:
```
var csrf = lusca({ csrf: true })
var upload = multer({ _ })

postParse = function(req,res,next){
  upload(req,res,next);
  csrf(req,res,next);
}

app.post('/profile', postParse, function (req, res, next) {

})
```
but postParse would need to be able to supply the `.single` `.array` etc.

**Comment by LinusU** [comment]
Written in ES2015 because I'm lazy :sunglasses: 

```javascript
class PostParser {
  constructor (upload, csrf) {
    this.upload = upload
    this.csrf = csrf
  }
  _wrap (fn, args) {
    var multipart = this.upload[fn](args)

    return (req, res, next) => {
      multipart(req, res, (err) => {
        if (err) return next(err)

        this.csrf(req, res, next)
      })
    }
  }
  single (...args) { return this.wrap('single', args) }
  array (...args) { return this.wrap('array', args) }
  fields (...args) { return this.wrap('fields', args) }
}
```
