### ISSUE TITLE
api call for multer file upload calls automatoically

### ISSUE THREAD

**Issue by sprakashg** [expressjs/multer#196]
I have configured multer on node with express and front end being Angular.
The issue am facing is when ever the app is started, my app crashes and this is the error message
"Route.post() requires callback functions but got a [object Object] "
am not able to get why this call is being called without invoking it from UI. 
Any suggestion

**Comment by LinusU** [comment]
Have you adjusted for the new syntax in version 1.x? Please see the [documentation](https://github.com/expressjs/multer#usage) on how to use multer.

**Comment by sprakashg** [comment]
This is the code I use, to upload the file to amazon s3 via multer. 

function uploadToS3(file, destFileName, callback) {
  destFileName = destFileName +"."+ file.extension;
  s3.upload ({
    ACL: 'public-read', 
    Body: fs.createReadStream(file.path), 
    Key: destFileName.toString(),
    ContentType: 'application/octet-stream' // force download if it's accessed as a top location
  }).send(callback);
}

var file_name = "";
  app.post('/admin/uploadImagetoS3', multer({
    limits: {fileSize:10*1024*1024},
      rename: function (fieldname, filename,req, res) {
        file_name = req.body.username + "_" + Date.now() ;
      },
    }), function (req, res) {
    var file = req.files.file;
    if(done == true){
      res.end("File uploaded.");
    }

  uploadToS3(file, file_name, function (err, data) {
    if (err) {
      console.error(err);
      return res.status(500).send('failed to upload to s3').end();
    }
    return res.status(200).send(data).end();
  })
});

**Comment by LinusU** [comment]
That won't work with the latest version of `multer`. The good news is that you can now stream directly to S3 without touching the disk thought :fireworks: 

One option for this is [badunk/multer-s3](https://github.com/badunk/multer-s3).

Whichever option you choose, the code should be updated to something like this:

```javascript
var path = require('path')
var multer = require('multer')

var limits = { fileSize: 10 * 1024 * 1024 }
var storage = multer.diskStorage({})
var upload = multer({ limits: limits, storage: storage })

function uploadToS3 (req, file, cb) {
  var ext = path.extname(file.originalname)
  var base = req.body.username + '_' + Date.now()

  s3.upload ({
    ACL: 'public-read', 
    Body: fs.createReadStream(file.path), 
    Key: base + ext,
    ContentType: 'application/octet-stream' // force download if it's accessed as a top location
  }).send(cb)
}

app.post('/admin/uploadImagetoS3', upload.single('file'), function (req, res, next) {
  uploadToS3(req, req.file, function (err, data) {
    if (err) return next(err)

    res.end(data)
  })
})
```

Also, your code uses global variables that would cause all kinds of problems if two users are uploading files at the same time.

**Comment by LinusU** [comment]
If you are using e.g. `multer-s3` or similar, you would remove the `uploadToS3` function and change `var storage = ...`.

**Comment by sprakashg** [comment]
Thanks Linus, it worked. Am not able to find the working demo for multer-s3?

**Comment by LinusU** [comment]
Didn't this work?

```javascript
var multer = require('multer');
var s3 = require('multer-s3');

var upload = multer({
  storage: s3({
    dirname: 'uploads/photos',
    bucket: 'some-bucket',
    secretAccessKey: 'some secret',
    accessKeyId: 'some key',
    region: 'us-east-1'
  })
})
```

**Comment by sprakashg** [comment]
I used it this way. 
var multer = require('multer');
var s3 = require('multer-s3');

var upload = multer({
  storage: s3({
    dirname: 'uploads/photos',
    bucket: 'testing-bucket-yousa',
    secretAccessKey: 'abcd',
    accessKeyId: 'zz',
    region: 'us-east-1'
  })
})

app.post('/admin/uploadImagetoS3', upload.array('file'), function (req, res, next) {
        console.log(res)
})

Please clarify me why is dirname required, I don’t want to store the data on my local machine and how to capture the response from s3, if it was successful or not?

**Comment by sprakashg** [comment]
Do let me know

**Comment by LinusU** [comment]
`dirname` is a prefix that will be added to the key of the files that you are uploading. It's the dir name on s3, not on your local machine.

If the response is not successful, the error will be reported to express just like all other errors.

**Comment by sprakashg** [comment]
Cool got it.
I checked the s3 console on amazon s3 and images are uploaded to this bucket, thank god :)
Have two issues in my code : 
How to rename the file before upload to s3 and how to capture the response amazon s3 the url of the uploaded image to s3.

var upload = multer({
  storage: s3({
    dirname: '/',
    bucket: 'asdf',
    secretAccessKey: 'abcd',
    accessKeyId: 'zz',
    region: 'us-east-1'
  })
})

app.post('/admin/uploadImagetoS3', upload.single('file'), function (req, res, next) {
//I can get response in console.log(req)
})

**Comment by zishon89us** [comment]
Here is how to set file name and at the bottom there is a link to a repo that has latest working code.

`var upload = multer({
    storage: s3({
        dirname: '/',
        bucket: 'bucket-name',
        secretAccessKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        accessKeyId: 'XXXXXXXXXXXXXXX',
        region: 'us-east-1',
        filename: function (req, file, cb) {
            cb(null, file.originalname); //HERE IS HOW TO RENAME FILE BEFORE UPLOAD
        }
    })
});
`
For complete running example clone [express_multer_s3](https://github.com/zishon89us/node-cheat/tree/master/aws/express_multer_s3) repo and run `node app`.
