### ISSUE TITLE
Multer mimeType is not correct,not real type

### ISSUE THREAD

**Issue by tomoat** [expressjs/multer#204]
Multer get mimeType is not correct, the file type is not the real type of file

How should I get the true type of it？

```json
{ fieldname: 'images',
  originalname: '1aba9ccec3fc1758f12d6ce593a0d80e',
  encoding: '7bit',
  mimetype: 'application/octet-stream',
  destination: './public/uploads/images/',
  filename: '42f118bf230557c4ddf4bb175bcbfe67_1439517173399.bin',
  path: './public/uploads/images/42f118bf230557c4ddf4bb175bcbfe67_1439517173399.bin',
  size: 72112 }
```
orignal file should is a pictures , it's type should is  " mimetype: 'image/jpeg',"

**Comment by LinusU** [comment]
That mimetype is sent by the user, you shouldn't trust it. You can use [jshttp/mime-types](https://github.com/jshttp/mime-types) to find the actual mimetype.
