### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by tomoat** [expressjs/multer#206]
```javascript
DiskStorage.prototype._removeFile = function _removeFile (req, file, cb) {
  var path = file.path

  delete file.destination
  delete file.filename
  delete file.path

  fs.unlink(path, cb)
}
```
error:

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.unlink (fs.js:878:11)
    at DiskStorage._removeFile (/node_modules/multer/storage/disk.js:63:6)

**Comment by tomoat** [comment]
delete file.path ago path not exisits

**Comment by LinusU** [comment]
When are you seeing this? It should be impossible for the path not to exist at that point.

Can you share the code that are setting up multer and receiving requests.

**Comment by tomoat** [comment]
added the code :
```javascript
fileFilter: function (req, file, cb) {
    //console.log(req.files.length);
    if(req.files.length > 3) {
      //cb(null, false);
      //cb(new Error('I don\'t have a clue!'))
    }
}
```

**Comment by LinusU** [comment]
What do you mean by prompt the user? You can use `upload.array('images')` to allow any number of images.

**Comment by tomoat** [comment]
Only allows users to upload pictures, and only allows uploading 3, when users upload 4 or more than 4, how should I warn users
ex.
res.json({err: 400, msg: 'You uploaded the pictures more than 3 sheets'})

**Comment by LinusU** [comment]
```javascript
app.post('/save', upload.array('images', 3), function (req, res) {
  res.end('Success, your images was uploaded.')
})

app.use(function (err, req, res, next) {
  if (err.code === 'LIMIT_UNEXPECTED_FILE') {
    res.end('You uploaded more than 3 images.')
    return
  }

  next()
})
```

**Comment by tomoat** [comment]
Thank @LinusU  for your help.
