### ISSUE TITLE
decode received image from base64 before saving

### ISSUE THREAD

**Issue by moosaviamir** [expressjs/multer#216]
Hello
I send jpg file encoded in base64 and i want to decode my file from base64 on recieve before saving to hard disk. where i can put my decode function on data?
please help.

best regards

**Comment by diosney** [comment]
+1

**Comment by LinusU** [comment]
There is a number of different ways to this but to be honest it seems like it would be smarter to do it before you are uploading the file. Why use base64?

The easiest way would be to use the memory store and then decode + save manually.

```javascript
```

**Comment by moosaviamir** [comment]
Thank you Linus
but i use base64 encoding because my client side code is C++.

**Comment by LinusU** [comment]
No problem

**Comment by Valonix** [comment]
I have same problem, but after saving i can`t open the image. just black background and error...

**Comment by chanakaDe** [comment]
@LinusU Brother,
When using memoryStorage like this `var upload = multer({ storage: multer.memoryStorage({}) })` , how does it affect to memory / RAM ? I have a 4GB RAM in my server. 
Let's imagine I am saving 4 images one by one. 
When i'm saving 4th image, does 1st , 2nd and 3rd images exists in the RAM ? Or does previous images removing automatically when adding new image ?

` api.post('/upload_image', upload.single('v_img'), function (req, res, next) { ..............`

I have this code. Imagine 2 users are using this method to upload 2 different images at same time.
How does affect with `memoryStorage` ?

**Comment by LinusU** [comment]
> Imagine 2 users are using this method to upload 2 different images at same time.

Both images would then exist in the memory at the same time. I would only recommend using `memoryStorage` if you have very low limits on file max size.

**Comment by aungkkyaw** [comment]
```app.post('/upload',  function (req, res, next) {
  var imageBuffer = new Buffer.from(req.body.base64Str, 'base64');

  fs.writeFile('/tmp/myfile.png', imageBuffer , function (err) {
    if (err) return next(err)

    res.send('Successfully saved')
  })
})```
