### ISSUE TITLE
Run fileFilter before checking fields.

### ISSUE THREAD

**Issue by fjhixiuxiu** [expressjs/multer#217]
Hi, I'm using multer and sendgrid to get parsed emails and store the email in my own system. I'm just wondering is there a way to ignore the attachments in the email and just get the body/text of the email? I was using multer().single() to handle email datas from sendgrid but if there are any attachments in the emails, it throws an Unexpected field exception. Thanks

**Comment by LinusU** [comment]
Have you tried using the `fileFilter` to only accept the file you want? I don't remember if the filter runs before or after the `single` filter.

I think it should work :rocket:

**Comment by fjhixiuxiu** [comment]
@LinusU Thanks for your reply. I tried to use ```multer({ fileFilter: function (req, file, cb) { cb(null, false) } }).single()``` as a middleware in my route but if I attach some file in my email, it still throws a Unexpected field error. How should I do it to just ignore all the files?

**Comment by LinusU** [comment]
Yep, shit, it checks it the other way...

Hmm, I think that the correct fix would be to change the order. That should fix it for you.

As a short term solution, do you know what field names that the attachments have beforehand?

**Comment by fjhixiuxiu** [comment]
Yes. The field name of the file is simply attachmentX, where X is the order of the file. If there is one attachment in the email, the file field name would be ```attachment1```. If there are two attachments, it would be two field ```attachment1``` and ```attachment2```. The thing is I wouldn't know the number of attachments in the email if the email is sent by other people. I tried using ```multer().fields([{ name: 'attachment1', maxCount: 1 }, { name: 'attachment2', maxCount: 1 }])```, but if you only attach one file in the email, the middleware will go into next method in the router twice, which calls my api twice for one email.

**Comment by LinusU** [comment]
> but if you only attach one file in the email, the middleware will go into next method in the router twice, which calls my api twice for one email.

Could you elaborate on this? That definitely sounds like a bug.

**Comment by fjhixiuxiu** [comment]
Oh sorry I think the middleware works fine. I test it again with a clean url to get the emails, and i defined four fields ```multer().fields([{ name: 'attachment1', maxCount: 1 }, { name: 'attachment2', maxCount: 1 }, { name: 'attachment3', maxCount: 1 }, { name: 'attachment4', maxCount: 1 }])```, and then I attached three files in the email, the req.body that returned by multer seems fine
```
{ headers: ***,
  dkim: 'none',
  to: 'Jianhao Fang <fjhixiuxiu@gmail.com>',
  html: '<div dir="ltr">qwe</div>\n',
  from: '"Jianhao (Eric) Fang" <ericfang@mavencare.com>',
  text: 'qwe\n',
  sender_ip: '209.85.223.177',
  envelope: '{"to":["update@devmcp.mavencare.com"],"from":"ericfang@mavencare.com"}',
  attachments: '3',
  subject: 'qwe',
  'attachment-info': '{"attachment2":{"filename":"fang.jpg","name":"fang.jpg","type":"image/jpeg"},"attachment3":{"filename":"fat.jpg","name":"fat.jpg","type":"image/jpeg"},"attachment1":{"filename":"cat.jpeg","name":"cat.jpeg","type":"image/jpeg"}}',
  SPF: 'fail',
  charsets: '{"to":"UTF-8","html":"UTF-8","subject":"UTF-8","from":"UTF-8","text":"UTF-8"}' }
```
I think the problem I described was caused by the bouncing of the emails in the system that makes me think it returns the request multiple time. Sorry about it.
So I think for a short term solution, I'll just define 10 file fields from attachment1 to attachment10 that at least make it working. 
Thanks for your help. And maybe I could just ignores the files in the request after some patch. :)

**Comment by LinusU** [comment]
Cool, glad to hear that you got it working. I'll keep this bug open so that we can make sure that the `fileFilter` is run after the `.single()` filter.

**Comment by twogood** [comment]
@fjhixiuxiu  I used multer().any() to support the SendGrid webhook, but maybe it didn't exist when this issue was created?

**Comment by LinusU** [comment]
Yes, `multer().any()` should work and wasn't merged when this was opened, good catch!
