### ISSUE TITLE
Is there a way to handle random file fields names

### ISSUE THREAD

**Issue by gyzerok** [expressjs/multer#221]
Hi there! I have a single endpoint (GraphQL) which handles forms submissions. But file fileds in form may differ. So I want to handle all those. I need something like
```javascript
multer().singleOrArray('*')
```
How to achieve this?

**Comment by BigstickCarpet** [comment]
+1

**Comment by LinusU** [comment]
Duplicate of #215

**Comment by LinusU** [comment]
This can be fixed by #229
