### ISSUE TITLE
Error: Multer always store my uploaded file in temp folder?

### ISSUE THREAD

**Issue by tampham47** [expressjs/multer#222]
I don't know why, but I am using multer like that, and it always store my file in temp folder. How can I fix that. Many thanks :smile: 

``` javascript
app.use('/upload/contact', multer({
  // specify the destination directory to not store files in temp dir
  dest: '/uploads'
}));
```

**Comment by LinusU** [comment]
It doesn't look like you are using the latest version of multer. Could you please try with 1.x?

**Comment by tampham47** [comment]
I am using v1.0.3

**Comment by LinusU** [comment]
The code you posted would give `TypeError: app.use() requires middleware functions`

**Comment by LinusU** [comment]
You are not using the correct syntax for 1.x, please see the readme on how to get up and running.

Feel free to reopen if you have any more questions/issues.

**Comment by tampham47** [comment]
Yes, thank for your support ^^
