### ISSUE TITLE
Child FormData not parsed

### ISSUE THREAD

**Issue by alexkavon** [expressjs/multer#231]
I am passing a child FormData object like so:

var fd1 = new FormData()
var fd2 = new FormData()
fd1.append('value1', 'value1')
fd2.append('value3', 'value3')
fd1.append('value2', fd2)

When I submit to my server and console.log the req.body I receive:

{
value1: 'value1',
value2: [object FormData]
}

It seems that multer is only parsing and transforming the first level of the sent formData object. Am I doing something wrong?

**Comment by LinusU** [comment]
I don't think you can do that, the protocol just doesn't support it. Have you looked at the data over the wire to see how it looks? I'm pretty sure that it's your client that writes `[object FormData]`.

**Comment by alexkavon** [comment]
I've solved this, it is indeed the append that does this.

Solution:
~~~
var fd = new FormData()
fd.append('value1', 'value1')
fd.append('value2', JSON.stringify({value3: 'value3'}))
~~~

Basically, anything that comes up as an object needs to be stringified. Here's a more real word application:

~~~
var obj = {
  name: 'Bob',
  friends: [{name: 'Jimmy'}, {name: 'Sarah'}]
}

var fd = new FormData()
for (var key in obj) {
  if (typeof obj[key] === 'object') {
    fd.append(key, JSON.stringify(obj[key]))
  } else {
    fd.append(key, obj[key])
  }
}
~~~

**Comment by LinusU** [comment]
Are you uploading files as well? If not, I would recommend using the standard body-parser with just json, it should save you some bandwidth and some headache.

Otherwise you could have one field which is the json.

```javascript
fd.append('data', JSON.stringify(obj))
```

**Comment by alexkavon** [comment]
Yes I'm uploading files.
