### ISSUE TITLE
How do I rename?

### ISSUE THREAD

**Issue by LunaticoCR** [expressjs/multer#233]
Hello,

The documentation says:
"By default, Multer will rename the files so as to avoid naming conflicts. The renaming function can be customized according to your needs."

However it does not give any details of how to use and this function works.

Could someone give me an example please?

Basically, I want the file to be named like the original, with some minor changes to it like removing special characters.

Thanks,
Daniel.

**Comment by LinusU** [comment]
Scroll down to [DiskStorage](https://github.com/expressjs/multer#diskstorage)

We should probably add a link :)

**Comment by hacksparrow** [comment]
Maybe a FAQ.

**Comment by LunaticoCR** [comment]
Oh I see it now! I assumed the function name would be "rename".

Thanks a lot guys!
