### ISSUE TITLE
request object access issues in rename fucntion

### ISSUE THREAD

**Issue by madhavabk** [expressjs/multer#235]
Hi,

When i try to access other field names through request object in multer rename even some time it works and some time it does not.
basically i wanted to rename file with the name from other fields which i am not able to do it.

**Comment by LinusU** [comment]
Please post code demonstrating what you are doing, thank you

**Comment by LinusU** [comment]
Ahh, actually I understand what you are trying to do now. That will not work and we cannot make it work since we are just parsing things in the same order that they are arriving, which is dependent on in which order the browser sends them.

This has come up a number of times before, e.g. #146 where a workaround is outlined.

**Comment by madhavabk** [comment]
thanks,
i can get text field contents now but i am not able to get 'Select' input type contents.

Madhva:$> node upload-multer.js
thumbnail:12020277_10205962512035207_206140952_o
{ username: 'Test', password: 'test' }
12020277_10205962512035207_206140952_o.jpg is starting ...
{ username: 'Test',
  password: 'test',
  city: 'Bangalore' }

ar app = express()
app.use(multer({dest : './uploads/',
	rename: function(file, filename, req, res) {
		console.log(file + ":" + filename );
		console.log(req.body);
		return file.originalname;
	},
		    onFileUploadStart: function (file) {
        console.log(file.originalname + ' is starting ...');
    }}));
app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

app.post('/file-upload', function(req, res, next){

    console.log(req.body) // form fields
    console.log(req.file) // form fields
    res.send("Thanks for uploading the image");
});

**Comment by LinusU** [comment]
It depends on which order your browser sends it, and any browser is free to send the data in any order they like. If you want to work around it you need to submit the form via javascript, see the issue I linked.
