### ISSUE TITLE
Multi upload

### ISSUE THREAD

**Issue by ficristo** [expressjs/multer#236]
We are using https://github.com/leon/angular-upload to upload files.
With the multiupload the param name of the file upload are: `file[0], file[1], file[2], ...`
Is there a way to handle them, or do I need to wait for #229 or #201?

**Comment by gabeio** [comment]
Those issues relate to non-array multi uploads: filename1 filename2 filename3. You are talking about an array file with array size of 3. You just need https://github.com/expressjs/multer#arrayfieldname-maxcount.

**Comment by LinusU** [comment]
Actually we don't handle any kinds of special characters in the field names of files at the moment :confounded: 

I don't know exactly what's the best approach here, it has been discussed before and there is a lot of security concerns that we need to think of to get it right...

**Comment by ficristo** [comment]
@gabeio In my testing `array` doesn't work because it expect an array with name `file`.
Instead I receive an array like this: the first item has name `file[0]`, the second `file[1]` and so on.
If I use the `fields` I should write all possible combinations: `file[0]`, `file[1]` and so on which is impractical.

**Comment by LinusU** [comment]
Fixed by #229, released as `1.1.0` :tada:

**Comment by ficristo** [comment]
@LinusU thank you.

**Comment by LinusU** [comment]
No problem :)
