### ISSUE TITLE
Upgrade to v1.0 broken

### ISSUE THREAD

**Issue by snapptop** [expressjs/multer#239]
Hello - thank you for the great work. I had multer working perfectly using < 1.0, is it possible for you to suggest how to get this working using the new syntax? I'm using jquery fileupload on client and here is what I had previously:

Client:
```
<input id="fileupload" type="file" name="files[]" multiple />

$input.fileupload({
	dataType: 'json',
	//need this to be able to keep uploading
	replaceFileInput: false,
	url: '/upload',
	dropZone: $dropCtnr,
	multipart: true,
	//formData: { userId: "test" },
	drop: function (e, data) {
		self.trigger('drop', e, data);
	},
	change: function (e, data) {
		self.trigger('change', e, data);
	},
	add: function (e, data) {
		self.trigger('add', e, data);
		data.formData = { "id": "1234", "folder": "this/is/a/test" };
		data.submit();
	},
	progress: function (e, data) {
		self.trigger('progress', e, data);
	},
	done: function (e, data) {
		self.trigger('done', e, data);
	}
});
```

Server:
```
app.use(multer({
	dest: './uploads/',
	rename: function (fieldname, filename) {
		return filename;
	},
	changeDest: function (dest, req, res) {
		var newdest = common.getAccountPath(req.body.id, req.body.folder);
		return newdest;
	},
	onFileUploadStart: function (file, req, res) {
		//block unwanted file types
		if (_ext.isNotAllowed(file.originalname)) {
			return false;
		}
		console.log('onFileUploadStart: STARTING: ' + file.originalname);
	},
	onFileUploadData: function (file, data, req, res) {
		console.log('onFileUploadData: ' + file.originalname);
	},
	onFileUploadComplete: function (file, req, res) {
		console.log('onFileUploadComplete: ' + file.fieldname + ' uploaded to  ' + file.path);
	},
	onParseStart: function () {
		console.log('onParseStart');
	},
	onParseEnd: function (req, next) {
		console.log('onParseEnd');
		var file = req.files['files[]'];
		if (!file) return next();
		createThumbs(req.body.id, file)
			.on('done', function (outfile) {
				next();
			})
			.on('error', function (err) {
				next();
			});
	}
}));

app.post('/upload', function (req, res) {
	var form = {
		body: req.body,
		files: req.files
	}
	res.send(form);
});
```

**Comment by LinusU** [comment]
This seems to pretty straight forward, have you tried reading the `README.md`?

**Comment by snapptop** [comment]
Yes of course. Do I use the storage options here? or array? Do you still have 'onParseStart' or 'onParsend' functionality ? I've tried these different options but now get errors

**Comment by snapptop** [comment]
thank you for your guidance .. you've been most useful after changing the api to your library

**Comment by LinusU** [comment]
Glad you managed to figure it out, please feel free to ask more questions if there is something that is unclear :)

**Comment by snapptop** [comment]
Thank you for wasting my time

**Comment by LinusU** [comment]
lol, do you really think that it's my job to update *your* code so that it's compatible with the latest version of a library that I help maintain? If you don't feel like updating than use the old version, no one is forcing you to update.

I feel that it is very easy to get started with the documentation that we have. If you feel otherwise than please post *the specifics of what you are struggling with,* and I'd be happy to help you.

What I won't do for you is to rewrite your code for you when it seems like the only thing that you have tried is to run the same code with the new api.

**Comment by snapptop** [comment]
lol, I wasn't asking for a rewrite, just a tip to get me started in the right direction that would have taken you just as long as writing "have you read the manual" and saved me an hour .. something like.. oh.. use multer({storage:multer.diskStorage({..})}) and make sure to .array('..') or .single('..') .  I upgraded by mistake and thought it would be a 10 second fix only to find out the interface had changed.. Apologies for the frustration and thank you for the lib.
