### ISSUE TITLE
File type check gives me strange errors.

### ISSUE THREAD

**Issue by dobromir-hristov** [expressjs/multer#240]
I'm new to Node and I'm still learning.
I'm trying to make a basic upload Avatar form with file type check. I'm not sure if I'm implementing something wrong, but If I try to upload the Wrong file type I get errors that I cant control. 
```javascript
var express = require('express'),
User = require('../../models/user'),
apiRouter = express.Router(),
_ = require('lodash'),
helpers = require('../../helpers'),
middlewares = require('../middlewares'),
multer  = require('multer'),
path = require('path');

var uploadStorage = multer.diskStorage({
    destination: 'public/uploads/avatars',
    filename: function (req, file, next) {
        next(null, file.fieldname + '-' + Date.now() + path.extname(file.originalname));
    }
});

var upload = multer({ 
    storage: uploadStorage, 
    limits: {fileSize: 1000000, files:1}, 
    fileFilter: function (req, file, next) {
        var ext = path.extname(file.originalname);

        if(_.indexOf(['.jpg', '.png'], ext) !== -1) {
            return next(null, true);
        }
        next(new Error('Wrong file type!'));

    }
}).single('avatar');

apiRouter.route('/:username').put(upload,function (req, res) {
    console.log(req.file);
    console.log(req.body);
  });

module.exports = apiRouter;

```
When I upload something I just get an Error 500 and the error jade rendered as a response and thats it. Maybe i`m not using the plugin as it is suppose to ?

**Comment by LinusU** [comment]
What error do you get, could you post it?

**Comment by dobromir-hristov** [comment]
"NetworkError: 500 Internal Server Error - http://localhost:3000/api/users/hristov" Is what I get from the browser. The node console doest say anything.

**Comment by dobromir-hristov** [comment]
I am trying to upload a .txt at the moment to trigger the fileCheck. .jpg and .png work fine and get uploaded. I just wanted to know how I could return some sort of Error to the frontend via Json to tell the user that there is an issue with his file.

**Comment by LinusU** [comment]
Add an express error handler to catch the error that you are throwing (`Wrong file type!`).

```javascript
app.use(function (err, req, res, next) {
  // do something with err here
})
```

**Comment by dobromir-hristov** [comment]
I have something like that:
```javascript
app.use(function (err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});
```

**Comment by LinusU** [comment]
That is where your error will end up then

**Comment by dobromir-hristov** [comment]
Error.jade
```jade
html
   head
      title Error
   body
      h1 An error occurred!
      block content
```
500.jade
```jade
extends error
block content
   h1= title
   p #{message}
```
And I get the content of error.jade but not the explanation that is in 500.jade. I`m probably missing something really simple here...

**Comment by LinusU** [comment]
You are doing `.render('error'` and not `.render('500'` so that's probably why.

Reopen if you have more problems :)
