### ISSUE TITLE
diskstorage filename function

### ISSUE THREAD

**Issue by ersensen** [expressjs/multer#242]
Hi,

When using diskstorage if we omit the filename function multer creates a unique filename. But if we define the filename function a unique filename is not created and the file name creation becomes the developers reponsibility. But this time we have to generate a unique name for the file.

Can you still create that unique name when filename function is defined so that we have a unique name?

	filename: function (req, file, cb) {
		var name = file.filename + path.extname(file.originalname); // file.filename is undefined
		cb(null, name)
	}

**Comment by alfredopacino** [comment]
is path defined?

**Comment by LinusU** [comment]
@alfredopacino `var path = require('path')`

@ersensen I'm not sure that that is multers responsibility, and it's very easy to do it yourself.

```javascript
var crypto = require('crypto')

function filename (req, file, cb) {
  crypto.pseudoRandomBytes(16, function (err, raw) {
    if (err) return cb(err)

    cb(null, raw.toString('hex') + path.extname(file.originalname))
  })
}
```

**Comment by alfredopacino** [comment]
very thanks
