### ISSUE TITLE
If the file with same name and size already exists its not uploading the new file.

### ISSUE THREAD

**Issue by arsinawaz** [expressjs/multer#247]
Hi all,

In my case the file name should be same for every uploaded file means there will be only one image on that folder. If an image with same file name already exists then the new file is not uploaded and also i get uploadDone = true. My code is below:

```javascript
var profilePicMulter = multer({
                dest: './uploads',
                rename: function (fieldname, filename) {
                        return "pic";
                },
                changeDest: function(dest, req, res) {
                        dest += req.query.picPath;
                        mkdirp(dest, function(err) {
                                if (err)        console.log('Error creating directory ',err);
                        });
                        return dest;
                },
                onFileUploadStart: function (file) {
                        console.log(file.originalname + ' is starting ...')
                },
                onFileUploadComplete: function (file) {
                        console.log(file.fieldname + ' uploaded to  ' + file.path)
                        uploadDone = true;
                },
                onError: function (error, next) {
                        console.log(error)
                        next(error)
                }
    });
```

Any help would be really appreciated. Thanks in advance!

**Comment by LinusU** [comment]
Could you try with the latest version of multer? An 1.x release

**Comment by arsinawaz** [comment]
I am using version "multer": "~0.1.8"

**Comment by arsinawaz** [comment]
i have updated to version 1.0.6 and still the same issue happens.

**Comment by marypreethi12** [comment]
@LinusU do you mean if i upload a file and the same file name already exists in the folder, it should replace it ? 
in my code i dont see the file is getting replaced

**Comment by panjigemilang** [comment]
> @LinusU do you mean if i upload a file and the same file name already exists in the folder, it should replace it ?
> in my code i dont see the file is getting replaced

but i want it to replace it ;(((. So how do you do that?
