### ISSUE TITLE
How to use req.body in destination

### ISSUE THREAD

**Issue by juniorkid** [expressjs/multer#250]
I want to use value req.body to specify what destination i want to save file how can i do it ??

**Comment by LinusU** [comment]
This will only work if your web browser sent the field you want to read before the actual file.

In your file naming function you can access req.body, req is the first parameter sent to that function.

**Comment by juniorkid** [comment]
thank you for your suggestion

**Comment by LinusU** [comment]
No problem, this has come up a number of times before, e.g. #146 where the workaround is further outlined.
