### ISSUE TITLE
Does multer work happily beside bodyParser in an Express 3.x app?

### ISSUE THREAD

**Issue by k00k** [expressjs/multer#251]
I'm using Express 3.3.8 and bodyParser on an existing project and trying to add multer's current (1.0.6) and having issues. Trying to use per route middleware like:

```
var multer  = require('multer');
var upload = multer({ dest: 'uploads/' });
app.post('/api/contact', upload.single('screenshot'), func(req, res, next...
```

This gives me an empty `req.body` object, guessing it's due to passing req through bodyParser and then to multer, or something of the sort. 

I don't want to remove bodyParser (yet), need to upgrade the app to Express 4 and then I'll switch everything over, but just need to get this form working for the time being.

Ideas?

**Comment by LinusU** [comment]
How does you bodyParser code look? AFAIK it shouldn't catch multipart uploads...

One option would be to only add body-parser per route, as you are doing with multer.

**Comment by k00k** [comment]
Just standard: `app.use(express.bodyParser());`

Comes before multer and the routes.

**Comment by k00k** [comment]
And I should note that removing `bodyParser` makes `multer` work just fine. But again, I've got `bodyParser` being used throughout and I'd need to do a lot of refactoring.

**Comment by LinusU** [comment]
You really should upgrade from that old version of express, but you can do this in the meantime:

```diff
- app.use(express.bodyParser())
+ app.use(express.json())
+ app.use(express.urlencoded())
```

**Comment by k00k** [comment]
Thanks for the assistance.

**Comment by LinusU** [comment]
No problem :+1:
