### ISSUE TITLE
fileFilter problem

### ISSUE THREAD

**Issue by zioworkscom** [expressjs/multer#252]
```javascript
var formData = new FormData(this);
					$.ajax({
						url: formUrl
						,type: "POST"
						,data: formData
						,mimeType: "multipart/form-data"
						,contentType: false
						,cache: false
						,xhr: function() {
							var myXhr = $.ajaxSettings.xhr();
							if(myXhr.upload){
									myXhr.upload.addEventListener("progress",setFileManagementProgress, false);
							}
							return myXhr;
						}
						,processData: false		
,beforeSend : function(){
							
						}
						,success: function(data) {
							alert(data);								
						}
						,error: function(jqXHR, textStatus, errorThrown) {
							
						}						
					});
					e.preventDefault();
					formObj.unbind(e);
```

I'm using ajax xhr upload function at client.

fileFilter is working fine. But, It's not pass false files.

It's looks like upload every file and then not write or remove false files after write.

xhr pregress bar working like all files exist and uploading.

For example, If I choose 1000mb file with 1kb file. and 1000mb file is filtered. But xhr working like all file uploding. fileFilter working properly There is no 1000mb file when upload finished.

**Comment by LinusU** [comment]
I have a hard time understanding what your problem is. `fileFilter` is run on the server so the client will still show a progress bar working like all files is uploaded.

Could you post your server side code and try to clarify your problem?

**Comment by zioworkscom** [comment]
Sorry about my english. That's my best. 

Codes working perfect. I want to pass upload progress from multipled input file if I set false in fileFilter.  Is it possible?

It's still upload to buffer though passed from fileFilter server code. But not on disk. only buffer. So, I have to wait until all files uploaded even I filtered.

This is server code. below,
----------------------------------
var express = require("express")
	,router = express.Router()
	,multer = require("multer")
	,storage = multer.diskStorage({
		destination: function(req, file, cb)
		{					
			cb(null, somewhere);
		}
		,filename: function(req, file, cb)
		{ 			
			cb(null, file.originalname);
		}		
	});

router.post("/upload", [multer(
	{ 
		storage : storage 
		,fileFilter: function(req, file, cb)
		{			
			var filter = req.body.realFileList;
			if(filter.indexOf("\""+ file.originalname +"\"") === -1)			
				return cb(null, false);			
			else
				return cb(null, true);
		}
	}).array("fileListInputControl"),function(req, res, next)
	{			
		res.writeHead(200, {"Content-Type": "text/plain"});
		res.end("_test(\'{\"message\": \"done.\"}\')");
	}]
);

module.exports = router;

**Comment by LinusU** [comment]
Since the filtering is done on the server, the browser has no choice but to upload everything. It won't know if the server keeps it or throws it away.

What you could do is to do the filtering on the client as well and just not upload large files at all.

Hope that helped.

**Comment by zioworkscom** [comment]
thanks.
