### ISSUE TITLE
404 Not Found; even image successfully saved in uploads directory

### ISSUE THREAD

**Issue by srkimir** [expressjs/multer#253]
It seems that multer middleware from some reasons does not call route handler, even middleware successfully saved image in uploads directory.
```
Request URL:http://localhost:8080/account/image
Request Method:POST
Status Code:404 Not Found
```

```javascript
// html
<input type="file" id="my_image" name="my_image">
// server
var multer = require('multer');
var uploads = multer({ dest: 'uploads/' });
app.post('/account/image', uploads.single('my_image'), function(err, req, res) {...});
```

**Comment by LinusU** [comment]
Is that your exact code? What is `err` doing in the parameter list to the route handler. Express only calls error routes when there is an error occurring.

**Comment by srkimir** [comment]
my mistake thank you, closed
