### ISSUE TITLE
Ask about destination in diskStorage

### ISSUE THREAD

**Issue by juniorkid** [expressjs/multer#254]
My code in node js is

```javascript
var storage = multer.diskStorage({


  destination: function (req, file, cb) {

    path_files_upload_temp = '/home/bright/Desktop/Project/webserver/Upload/' + "temp" + '/';
    cb(null, path_files_upload_temp) 
   
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname)
  }
})

var upload = multer({  storage: storage })

app.post('/api/uploadPHR', upload.single('file'), function (req, res, next) {
....
});
```

I want to use req.body in /api/uploadPHR to set destination to storage . How can i do it ?
And I don't understand about req in destination what is it ?

Sorry for my poor english

**Comment by LinusU** [comment]
`req` is the first argument that get's passed to that function, you can just access `req.boy`. This only works if the web browser sends the field you want before the file, which might not be the case.

This has come up a number of times before, e.g. #146 where the workaround is further outlined.
