### ISSUE TITLE
Can multer handle if page refresh but upload is not completed

### ISSUE THREAD

**Issue by juniorkid** [expressjs/multer#255]
I want to ask that multer can handle of check  if user refresh page when file has uploaded .

sorry in my  poor english

**Comment by gabeio** [comment]
I see you may have already figured out the answer. In any case, handling page refreshes you would have to do on the client side, the server can not handle a page refresh (no matter what) without the client holding open the upload.

**Comment by juniorkid** [comment]
Thank you for you comment.
