### ISSUE TITLE
How can cancel upload during file is uploading ?

### ISSUE THREAD

**Issue by juniorkid** [expressjs/multer#256]
I want to cancel upload during file is uploading .
How can i do it ?

**Comment by LinusU** [comment]
I'm guessing that you want to cancel the upload from the client-side. It would depend on which library you are using.

`XMLHttpRequest` has an [`abort` function](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#abort()).

Feel free to reopen if you need more help.
