### ISSUE TITLE
There is no file size info.

### ISSUE THREAD

**Issue by zioworkscom** [expressjs/multer#257]
Hello.

I saw this documentation. below
[
API

File information

Each file contains the following information:

Key	Description	Note
fieldname	Field name specified in the form	
originalname	Name of the file on the user's computer	
encoding	Encoding type of the file	
mimetype	Mime type of the file	
size	Size of the file in bytes	
-----------------------------------
destination	The folder to which the file has been saved	DiskStorage
filename	The name of the file within the destination	DiskStorage
path	The full path to the uploaded file	DiskStorage
buffer	A Buffer of the entire file	MemoryStorage
]
But, there is no file.size info. How can I get that info?

```javascript
var storage = multer.diskStorage(
{
	destination: function(req, file, cb)
	{	
		....
	}
	,filename: function(req, file, cb)
	{ 	
		console.log("file.size: "+JSON.stringify(file));
	}		
});


file.size: {"fieldname":"singleFile","originalname":"issues.pdf","encoding":"7bit","mimetype":"application/pdf"}
```

**Comment by LinusU** [comment]
The file size will only be available after the file has been uploaded, this won't change unless the browsers start sending this information in the multipart headers.
