### ISSUE TITLE
multer 1.1.0 Cannot upload files from superagent

### ISSUE THREAD

**Issue by ieow** [expressjs/multer#261]
Hi,
Does anyone success to upload file from superagent for mutler 1.10?
I tried many ways but still unsuccessful. 

i tried using  code below

```javascript
//client code
request
      .post('/api/v1/upload')
      .set('Authorization', 'Bearer '+ Store.getToken())
      .field( 'id' , opts.id  )
      .attach('image', opts.image ) // , 'slip.png')
      .end(function ( err ,res ){ }
```

```
// server code
var upload = multer({ dest: './uploads' })

app.post('/api/v1/upload' , upload.any() , function (req,res,next) {
  console.log(req)
  console.log(req.body)
  console.log(req.files)

  console.log('done')
  //next
}
```

`req.files` has 0 array.

**Comment by LinusU** [comment]
Have you looked at #212?

**Comment by ieow** [comment]
Yes, I did. It seems stated that it was fixed on 1.0.5
I am having the same issue on 1.1.0 . 
The issue submitter seems like haven't respond on it.
BTW, this it the header when i log the 'req'

 rawHeaders: 
   [ 'Host',
     'localhost:50000',
     'Connection',
     'keep-alive',
     'Content-Length',
     '238',
     'User-Agent',
     'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
     'Origin',
     'http://localhost:50000',
     'Authorization',
     'Bearer eQiOjE0NDY1MzMyNDl9.XI32PGn0PbSX7Nguh755onwVZKgj7UQk',
     'Content-Type',
     'multipart/form-data; boundary=----WebKitFormBoundaryrG42IBXvzJAgXAcw',
     'Accept',
     '*/*',
     'Referer',
     'http://localhost:50000/',
     'Accept-Encoding',
     'gzip, deflate',
     'Accept-Language',
     'en-US,en;q=0.8' ],

**Comment by ieow** [comment]
one more thing,
i got the file's path via FileReader

var reader = new FileReader
reader.readAsDataURL(this.refs.uploadedImg.getDOMNode().files[0])
reader.onloadend = function () {
		that.setState({
		uploadedImgPath :reader.result,
		disableUpload : false,
		})

it return reader.result like 
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgoAAAC3CAIAAAD8aOGAAAAAA3NCS…F4AAAAHogHAADggXgAAAAeiAcAAOCBeAAAAB6IBwAA4PEf3RfXz6gS2xwAAAAASUVORK5CYII=

I was using multer 0.x before and it was working before

**Comment by ieow** [comment]
I am able to upload now by passing the object directly instead of readAsDataURL.
Not sure what is changed in multer and superagent.

**Comment by LinusU** [comment]
Glad that you was able to solve it!

It seems very weird to pass in an data-url to superagent, passing the file directly seems like the right thing to do™.
