### ISSUE TITLE
POST / - - ms - -

### ISSUE THREAD

**Issue by davidgatti** [expressjs/multer#262]
I have this code 

```
router.post('/', Upload.single('pdf'), function(req, res, next) {
    console.log('File name: ' + req.file.originalname + ' with Reference ID: ' + req.body.referenceId);
    //console.log(req.body);
})
```

and it works well, but after a while in my logs I see `POST / - - ms - -` any idea what is causing this?

**Comment by LinusU** [comment]
I have a very hard time believing that this comes from multer. It seems like you are using a library to log your requests, I would suggest opening an issue with them.

**Comment by LinusU** [comment]
Please reopen if you can provide more info, at this point I believe the error to be outside of multer.

**Comment by benoror** [comment]
@davidgatti I have the very same issue, I use [expressjs/morgan](https://github.com/expressjs/morgan) for logging

**Comment by benoror** [comment]
@davidgatti Do you happen to use https://github.com/leon/angular-upload for the frontend?

**Comment by davidgatti** [comment]
No. no Angular for me :) and it happens in a aground process where there is no fronted active.

**Comment by benoror** [comment]
Thanks, I found the issue

**Comment by davidgatti** [comment]
mind sharing? :)

**Comment by benoror** [comment]
Really stupid mistake :astonished:, I was loading my upload route as:

```
var app = express();
var api_upload = require('./routes/api_upload');
//...
app.use('/api/upload', api_upload);
```

For some reason, while initial prototyping, I saved my file as `/routes/api_upload` (no extension), then I continued working on it and later saved it as `/routes/api_upload.js`

https://twitter.com/benoror/status/664943791447474176

**Comment by davidgatti** [comment]
Wired, because if you use expressJS, you save with the extension, but can load without one.

**Comment by myzhibie** [comment]
remove `app.use(logger('dev'));` in your app.js
