### ISSUE TITLE
How to catch the error raised by the options limit.fileSize?

### ISSUE THREAD

**Issue by chenzl25** [expressjs/multer#263]
```javascript
limits: {
    fieldNameSize: 100,
    fileSize: 1024*1,
    files: 1,
    fields: 100
  }
```

I use the options limit , and then upload a file which fileSize > 1024 bytes, but I don't know how to catch the error. Also the the file in fileFilter(req, file, cb), only has 4 properties

>fieldname
originalname
encoding
mimetype

I couldn't use the property fileSize to filter the file.
```text
{ [Error: File too large] code: 'LIMIT_FILE_SIZE', field: 'image', storageErrors: [] }
Error: File too large
```

**Comment by LinusU** [comment]
Follow the [Express error handling guide](http://expressjs.com/guide/error-handling.html).

**Comment by nazmul-solutionspin** [comment]
exactly same issue, could you solve the problem?
