### ISSUE TITLE
Set filename to MD5 or SHA sum of file

### ISSUE THREAD

**Issue by rightaway** [expressjs/multer#264]
Using the diskStorage storage type for example, it would be great to be able to set the filename to the hash of the file (including reasons like de-duplication of files). (This question is related but different I believe to https://github.com/expressjs/multer/issues/248.) Is this currently possible, or could such functionality be added?

**Comment by LinusU** [comment]
That would be impossible without first storing the file at a temporary location and then moving it. We can't calculate the hash of the file before we have the file.

Use the `diskStorage` to store the files, than hash and move them.
