### ISSUE TITLE
Documentation for which functions can be passed to options

### ISSUE THREAD

**Issue by rightaway** [expressjs/multer#267]
In this article https://codeforgeek.com/2014/11/file-uploads-using-node-js/ I discovered there were some functions like onFileUploadStart, onFileUploadComplete, rename that can be passed as options. Would be great if all the available functions that can be provided were documented somewhere, as they are actually quite useful functions and I might have missed them if not for that article.

**Comment by LinusU** [comment]
That article is for an old version of multer, `0.x`. Those options are no longer present.
