### ISSUE TITLE
How to stream files directly elsewhere?

### ISSUE THREAD

**Issue by rightaway** [expressjs/multer#268]
How can I stream files directly to somewhere else as they're being uploaded, rather than having to first receive the whole file from the upload then transfer it elsewhere (as it would be much more efficient that way)?

In the example at the `knox` Amazon S3 client https://www.npmjs.com/package/knox, it shows a way of doing it with a http.get request, where it streams `res` directly from the download stream to S3. Is there a way of doing this with multer, where you can stream the upload stream directly somewhere?

```js
http.get('http://google.com/doodle.png', function(res){
  var headers = {
      'Content-Length': res.headers['content-length']
    , 'Content-Type': res.headers['content-type']
  };
  client.putStream(res, '/doodle.png', headers, function(err, res){
    // check `err`, then do `res.pipe(..)` or `res.resume()` or whatever. 
  });
});
```

What would I replace `res` with in `client.putStream(res, '/doodle.png', headers, ...` to get streaming to work with multer?

**Comment by LinusU** [comment]
You want to implement an [Storage Engine](https://github.com/expressjs/multer/blob/master/StorageEngine.md) or use an [existing one](https://github.com/badunk/multer-s3/).

**Comment by ArturPrzybysz** [comment]
@rightaway 
Hey, have you succeeded? I want to achieve the same thing you described but can't find a way to implement the storage engine.

**Comment by LinusU** [comment]
@ArturPrzybysz have you read this document? It should give you the pieces you need to build one.

https://github.com/expressjs/multer/blob/master/StorageEngine.md

**Comment by barakbd** [comment]
https://stackoverflow.com/questions/30262290/streaming-an-uploaded-file-to-an-http-request
