### ISSUE TITLE
How to save an image from Angular directive ng-file-upload. 

### ISSUE THREAD

**Issue by Valonix** [expressjs/multer#269]
Hello i use this https://github.com/danialfarid/ng-file-upload/blob/master/README.md#node

In my route i have this code

``` javascript
var express = require('express');
var router = express.Router();
var multer  = require('multer');
var upload = multer({ dest: __dirname + '/public/uploads/' });

router.post('/', upload.single('file'), function(req, res) {
    console.log(req.file);
    res.status(200).json({ file: req.file});
});
module.exports = router;
```

But i saving not image. How i can save an image file? I mean some decode function or what?
I am new in node js :)
Thanks.

**Comment by i22bonij** [comment]
Hi,

I have the same problem as you, you solved it?

**Comment by Spaarw** [comment]
Same problem for me !

**Comment by senturkzuhtu11** [comment]
> [``]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]( #1 #554 #554 
[app.pdf](https://github.com/expressjs/multer/files/1767226/app.pdf)
)))))))))))))))))

**Comment by ryhinchey** [comment]
have you all set `enctype="multipart/form-data"` in the `form` element of your angular forms?   Looking at the demo [here](https://angular-file-upload.appspot.com/), I don't see that it's added by default.

**Comment by ryhinchey** [comment]
I'm going to go ahead and close this due to inactivity.  Feel free to reopen if this is still an issue!
