### ISSUE TITLE
diskStorage not a function

### ISSUE THREAD

**Issue by thmoeller** [expressjs/multer#270]
Hi, i have following code

```
var express = require('express');        // call express
var app = express();
var multer  = require('multer');

var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '/software/')
  },
  filename: function (req, file, cb) {
    cb(null, 'test.tar.gz')
  }
})

var upload = multer({ storage: storage })

.....
```

This gives me following error while compiling:

```
var storage=multer.diskStorage({
                   ^

TypeError: multer.diskStorage is not a function
    at Object.<anonymous> (D:\Harvester\proxy\proxy.js:34:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Tried all variations but it gives me always the same error. Using node 5.0

Any idea??

**Comment by LinusU** [comment]
Which version of multer is installed? Please make sure it's the latest...

**Comment by thmoeller** [comment]
Hi Linus,

thanks for your hint. Found an old reference in my package.json. Updated multer and works fine now.

Moe

**Comment by LinusU** [comment]
:ok_hand:

**Comment by rahul7156** [comment]
thanks LinusU

**Comment by GuntukuChaitanya** [comment]
It is not working for me :(

**Comment by MasterKanade** [comment]
Hi I have the same error, I am using the latest multer version "multer": "^1.4.5-lts.1". 
Any Idea? why I am getting error: multer.diskStorage is not a function.
Hi @thmoeller could you tell me which multer version are you using?

**Comment by M-Shadil** [comment]
hi , i also have latest version but is not working anytell me the version?

**Comment by patooz** [comment]
Latest version ( "multer": "^1.4.5-lts.1") but still gives the same error

**Comment by Haroun-Azoulay** [comment]
I have the same error too...

**Comment by Haroun-Azoulay** [comment]
I fixthe solution => I think with multer's version 1.4.5-lts.1 the diskStorage method is moved or depreciated

i should uninstall multer and install another version, try npm view multer versions and you can install for example multer 1.4.4 so => ​​npm install multer@1.4.4. that's what works for me.

best regards
