### ISSUE TITLE
New to multer where to use fileFilter 

### ISSUE THREAD

**Issue by vasuvanka** [expressjs/multer#277]
hi,
i can't find proper source , where to use fileFilter in multer..?

**Comment by LinusU** [comment]
To the [`multer(opts)`](https://github.com/expressjs/multer#multeropts) function.

```javascript
const multer = require('multer')
const upload = multer({ fileFilter: _, dest: 'uploads/' })

app.post('/profile', upload.single('avatar'), (req, res, next) => {
  // req.file is the file
})
```

**Comment by vasuvanka** [comment]
is there any callback to know wheather file uploaded or not ?

**Comment by LinusU** [comment]
How do you mean? If you want to know if any error happen, use [standard express error handling](http://expressjs.com/guide/error-handling.html). If you want to know wether a file was filtered or not, just use the value that you supplied to the callback.

**Comment by vasuvanka** [comment]
Thanks linusU...
