### ISSUE TITLE
Add .none() to allow multipart but explicitly deny file uploading

### ISSUE THREAD

**Issue by Soviut** [expressjs/multer#278]
I'm using FormData objects as part of my AJAX POST and PUT operations. `xhr.send(new FormData(myForm))` will automatically set the `Content-Type: multipart/form-data`. I'm only sending plain text fields but I still need to parse the multipart body. I've managed to get it working by doing:

```javascript
var upload = multer({dest: __dirname + '/uploads'});
app.put('/whatever', upload.single('SOME_FAKE_FIELD_NAME'), function(req, res) {
    // ...
}
```
I could also use the `.fields()` to set a max count of 0 to fully ensure no files are uploaded, but it would be more convenient is if file uploading could be outright ignored with the following

```javascript
app.put('/whatever', upload.none(), function(req, res) {
```

**Comment by LinusU** [comment]
The cleanest workaround right now probably is `upload.fields([])`.

I remember this being discussed before, I'm on mobile now though so won't start looking.

Right now I feel okay with including this, I would like to know how the other maintainers feel though.

**Comment by aristidesfl** [comment]
+1
