### ISSUE TITLE
Where does multer({ dest: 'path' }); reference from?

### ISSUE THREAD

**Issue by feniixx** [expressjs/multer#279]
I mean, does it reference from `server.js`?

I have splitted the server logic, I'm calling multer from `/server/rest-api/uploads/product-images.js`
and that script is inside a folder as a module (uploads), so, if I want to save my files to `/client/public/img/` what is the right path?

Also, if I'm using `Express.Router()` to define the routes, how do I add the middleware?
For example:

```javascript
var express          = require( 'express' ),
    router           = express.Router(),
    multer           = require( 'multer' ),
    dest             = multer( { dest: './client/public/docs/transactions/' } ),
    transaction_docs = require( './transaction-docs' );

router.route( '/upload/transaction-docs' )
    .post( transaction_docs.post );//Shall I just add the `dest` variable before `transaction_docs.post`?
```

**Comment by LinusU** [comment]
Relative paths will be resolved from the current working directory. That typically means the directory that you where in when running `node blah.js`. I would recommend using `path.join(__dirname, ...)` to get an absolute path.

You can add the middleware by appending it to the `.post` call. E.g. `.post(dest.single('avatar'), transaction_docs.post)`

**Comment by LinusU** [comment]
Please reopen if you need more help
