### ISSUE TITLE
How do I change filename of the file?

### ISSUE THREAD

**Issue by feniixx** [expressjs/multer#280]
I'd like to change the file name to other that's send as a property of the data object, here's the json of the file:
```javascript
{ fieldname: 'file',
  originalname: 'db.pdf',
  encoding: '7bit',
  mimetype: 'application/pdf',
  destination: './client/public/docs/transactions/',
  filename: '8a3fe7cb7369d9cffa8e17b162ec3d6b',
  path: 'client\\public\\docs\\transactions\\8a3fe7cb7369d9cffa8e17b162ec3d6b',
  size: 9179145 }
```

Client side upload with `ng-file-upload`:

```javascript
Upload
    .upload( {
        url: '/api/v1/upload',
        data: {
            file: vm.pdf,
            new_name: vm.new_pdf_name //This is the name I want for the file
        }
    } )
    .then(
        function ( response ) { ... }
    );
```

I'm using `diskStorage` but the `request` of `filename` property function doesn't receive `new_file_name` property...

```javascript
var storage = multer.diskStorage(
    {
        destination: './uploads/',
        filename: function ( req, file, cb ) {
            //req.body is empty...
            cb( null, file.originalname );
        }
    }
);
```
How could I send the `new_file_name` through that `req.body`?

**Comment by LinusU** [comment]
If `req.body` is empty, it means that the client sent the file before sending the `new_file_name` field. There is nothing we can do about it in `multer`.

This has come up a number of times before, e.g. #146 where the workaround is further outlined.

**Comment by feniixx** [comment]
Emmm, acually `req.body` at the endpoint contains it, but the `req.body` I mean is this:
```js
var storage = multer.diskStorage(
    {
        destination: './uploads/',
        filename: function ( req, file, cb ) {
            //req.body is empty... here is where req.body.new_file_name doesn't exists
            cb( null, file.originalname );
        }
    }
);
```

But in this `req.body` it exists:
```js
var upload = multer( { storage: storage } );

router.route( '/upload' )
    .post( upload.single( 'file' ), function ( req, res ) {
        
        console.log( req.body.new_file_name );
        //Prints the value sent from the client...
        
        res.json({message:'File Uploaded!'});
    } );
```

**Comment by LinusU** [comment]
Yes that is the expected behaviour, the `filename` function is called whenever a file is detected on the wire. It needs to run before the file is actually consumed since it determines where to save it.

Your request from the client looks like this:

```text
<header> | file | new_file_name
           ^ filename function fired
```

You need to send it as such:
```text
<header> | file | new_file_name
           ^ filename function fired
```

**Comment by feniixx** [comment]
I don't really understand what you're trying to tell me... I only need to know how to get the `new_file_name` value at:
```js
filename: function ( req, file, cb ) {
            cb( null, req.body.new_file_name );
        }
```

**Comment by LinusU** [comment]
I understand, but at that point in time the information about `new_file_name` haven't arrived at the server yet.

**Comment by feniixx** [comment]
Then how could I set a custom name to the file sent from the client?

**Comment by vergissberlin** [comment]
Take a look on #170 . I prefer the way with the ``mime`` module.

**Comment by av1m** [comment]
> Then how could I set a custom name to the file sent from the client?

To "fix" this problem, you can pass information in the URL directly (as params).
Then, you will retrieve without the `req.body`, which is empty when needed ...

**Comment by vsalguero** [comment]
One solution is to upload the file with a fixed name and then change it using the `fs` class by accessing the `req.body` from the `router.post`

Add the fs

`const fs = require('fs');`

```
router.post('/upload', upload.single('photo'), (req, res) => {
    //Here change the file name file.pdf for the new value in req.body.field_name + original ext of file
    fs.renameSync(req.file.path, req.file.path.replace('file.pdf', 
    req.body.field_name + path.extname(req.file.originalname)));
    if(req.file) { 
        res.json(req.file);
    }
    else throw 'error';
});
```

Read more in [https://stackoverflow.com/questions/53487001/nodejs-multer-change-filename-depending-on-request-attributes/67881371#67881371](https://stackoverflow.com/questions/53487001/nodejs-multer-change-filename-depending-on-request-attributes/67881371#67881371)

**Comment by kartik1195** [comment]
If you want to upload Passport image as a front and back side then pass parameter from frontend like this **user:"username"** and **type:"front"** OR **type:"back"** then Use it in node side like this

`const upload = multer({
    const storage = multer.diskStorage({
        destination: function (req, file, cb) {
            cb(null, 'uploads/passport/');
        },
        filename: function (req, file, cb) {
            cb(null, req.body.user+"-"+req.body.type+".jpg");
        }
    })
});`

**Comment by turkmenbeyvolkan** [comment]
If you are appending your file to formData at the end and filename at the first in your client side, you will get your filename in server side in multer so you can
get what yoou want it worked for me.

at the client side:
let formData = new FormData();
formData.append("title", fieldValues["title"]);
formData.append("file", fieldValues.upload.file.originFileObj);
console.log(formData);
dispatch(createVideo(formData));

at the serverside:

const multer=require('multer');
const path=require('node:path');

const storage = multer.diskStorage({
destination: function (req, file, cb) {
cb(null, path.join("/app","/uploads"));
},
filename: function (req, file, cb) {
console.log("file",file);
console.log("req.body:",req.body)
cb(null, req.body.title+"."+file.mimetype.split("/")[1]);
},
});

const upload = multer({ storage: storage });

module.exports = upload;

**Comment by novexir** [comment]
> Ha a kliens oldalon a formData-hoz csatolja a fájlt a végén, a fájlnevet pedig az elején, akkor a multerben a szerveroldalon kapja meg a fájlnevét, így megkaphatja, amit akar, és nekem bevált.
> 
> a kliens oldalon: legyen formData = new FormData(); formData.append("cím", mezőÉrtékek["cím"]); formData.append("fájl", fieldValues.upload.file.originFileObj); console.log(formData); dispatch(createVideo(formData));
> 
> a szerver oldalon:
> 
> const multer=require('multer'); const path=require('node:path');
> 
> const storage = multer.diskStorage({ cél: function (req, file, cb) { cb(null, path.join("/app","/uploads")); }, fájlnév: function (req, file, cb) { console.log("file",file); console.log("req.body) cb,bnull. req.body.title+"."+file.mimetype.split("/")[1] }, });
> 
> const upload = multer({ tárhely: tárhely });
> 
> modul.exports = feltöltés;


turkmenbeyvolkan válasza segített nekem. Ez a jó megoldás. Köszönöm!
