### ISSUE TITLE
Upload has no method 'single'

### ISSUE THREAD

**Issue by LeeKyungMoon** [expressjs/multer#283]
My code is below:
	

        var multer = require('multer');
	var upload = multer({ dest: 'uploads/' });
	var app = express();
	//app.use(bodyParser.json());
	//app.use(app.router);
	//app.use(express.json());
	//app.use(express.urlencoded());
	//app.use(multer({dest:'./uploads/'}));

	app.post('/upload',upload.single('puzzle'),function(req,res){

		console.log(req.file);
	});

But when running app.js, there is an error that 'has no method 'single'
I installed multer without any accident what's wrong with that?

Please be my savior

**Comment by LinusU** [comment]
What version of multer is installed? Probably an pre 1.x one
