### ISSUE TITLE
How can I set filename? I already read docs

### ISSUE THREAD

**Issue by LeeKyungMoon** [expressjs/multer#284]
What I've done is below:

        var uploader = multer({dest:'./uploads/'});
	var upload = multer({ storage: storage });
	var app = express();
	app.use(app.router);
	app.post('/upload', uploader.single('puzzle'), function (req, res, next) {
	    console.log(req.file);
	});

So log is like this (below):
```text
     ** { fieldname: 'puzzle',
       originalname: '스크린샷 2015-11-19 오후 7.07.05.png',
  encoding: '7bit',
  mimetype: 'image/png',
  destination: './uploads/',
  filename: '4da1f7f86a36372c4c3d75842255c496',
  path: 'uploads/4da1f7f86a36372c4c3d75842255c496',
  size: 104970 }**
```

and at upload foler , the file is stored very wel...
But I want to file name like **'4da1f7f86a36372c4c3d75842255c496.png'** not **'4da1f7f86a36372c4c3d75842255c496'**

So I read docs, at docs, there is something for me.
```javascript
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '/tmp/my-uploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})
 
var upload = multer({ storage: storage })
```

But in this case, how can I use variable 'upload'?
my case , upload is used like this:

	var upload = multer({ storage: storage });  : decide where the image file is stored

&&

	app.post('/upload', uploader.single('puzzle'), function (req, res, next) {
	    console.log(req.file);
	}); : decide what the field name is.

But at docs,
it looks like it does do set filename and help storage...
But in this case how can I decide the field name ?

I don't see the 'interface' or 'intermediate point' to migrate two code blocks

**Comment by LinusU** [comment]
Do you want to keep the file extension? See if this issue can help you: #170

**Comment by LeeKyungMoon** [comment]
@LinusU  Thank you, that perfectly helps me so I got the file with the format I wanted. but when I access to 'http://0.0.0.0:63586/uploads/a539d27fd99be4274fa3e2eb22b520b21449498122507.png' , what I see is that ''Cannot GET /uploads/a539d27fd99be4274fa3e2eb22b520b21449498122507.png"... I'm new to develop web... Would you explain me why and how to do as I want??

**Comment by LinusU** [comment]
You need to also serve the files, which is beyond the scope of multer. Have a look at this one http://expressjs.com/en/starter/static-files.html

**Comment by srikantmatihali** [comment]
HI LinusU, Followed you method. Even after that, still unable to retain the original filename.  Saw the issue https://github.com/expressjs/multer/issues/170. It still doesnt work for me, and shows up hex named files without file extensions. 

I believe the callback ==> cb(null, file.fieldname + '-' + Date.now()) is not working. I tested using this code.  cb(null, raw.toString('hex') + path.extname(file.originalname)). It doesnt work.

**Comment by LinusU** [comment]
@srikantmatihali Can you post complete code and I'll take a look?

**Comment by srikantmatihali** [comment]
@LinusU, I got to know that it was issue with the package I was using. 

{
  "name": "fileupload",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
   ** "express": "~4.13.1",**
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "multer": "^1.1.0",
    "serve-favicon": "~2.3.0",
	"busboy": "^0.2.11"
  }
}

A friend of mine, helped me with new package file

{
  "name": "file_upload",
  "version": "0.0.1",
  "dependencies": {
   ** "express": "4.13.3",**
    "multer": "1.1.0"
  },
  "devDependencies": {
    "should": "~7.1.0",
    "mocha": "~2.3.3",
    "supertest": "~1.1.0"
  }
}

I had used latest expressjs and multer installations. I think it was issue with Expressjs version.

Anyways thanks for responding.

**Comment by LinusU** [comment]
Cool, glad it worked!
