### ISSUE TITLE
why onFileUploadStart removed

### ISSUE THREAD

**Issue by mavericklin** [expressjs/multer#285]
Hi there, I notice that you have remove the onFileUploadStart interface. Is there any alternative way to do it? My case is that I want to check authentication before uploading the file by passing a token. Thank you!

**Comment by LinusU** [comment]
Yes, have a look at `fileFilter`

**Comment by mavericklin** [comment]
Looks cool! Thank you! 
However, can I do something after upload completed, like recording the upload completed time so that I can use it to identify my file?

**Comment by LinusU** [comment]
Not really, how do you mean identify your file?

When the route is triggered all the files will be uploaded and stored on disk/in memory
