### ISSUE TITLE
Node.js multer issue

### ISSUE THREAD

**Issue by ankitbaid11326** [expressjs/multer#286]
i dont know how to post full code here
Please check this error here:

http://stackoverflow.com/questions/34037111/node-js-multer-file-uploading-error

**Comment by KillerCodeMonkey** [comment]
like the answer on that topic --> if you are using
.single --> req.file is the one and only uploaded file
.arrray --> req.files is the array of uploaded files
.fields --> req.files is an object with key = fieldname and value = array of files

**Comment by bwong199** [comment]
I have the same problem as ankitbald11326. I specified single and 'mainimage' as my input name. When I tried saving the post and the appended image, only 'noimage.png' goes into my mongodb. 

App.js
app.use(multer({ dest: './public/images/uploads' }).single('mainimage'));

addpost.jade

form(method="post", action="/posts/add", enctype="multipart/form-data")
		.form-group
			label Title:
			input.form-control(name="title", type="text")
		.form-group
			label Category
			select.form-control(name="category")
				each category, i in categories
					option(value="#{category.title}") #{category.title}
		.form-group
			label Body
			textarea.form-control(name="body", id="body")
		.form-group
			label Main Image:
			input.form-control(name="mainimage", type="file")
		.form-group
			label Author:
			select.form-control(name="author")
				option(value="Ben Wong") Ben wong
				option(value="John Doe") John Doe
		input.btn.btn-default(name="submit", type="submit", value="Save") 
posts.js

router.post('/add', function(req, res, next){
	console.log(req.file);

	var title = req.body.title;
	var category = req.body.category;
	var body = req.body.body;
	var author = req.body.author;
	var date = new Date();

	if(req.files){
		var mainImageOriginalName = req.files.mainimage.originalname;
		var mainImageName = req.files.mainimage.name;
		var mainImageMime = req.files.mainimage.mimetype;
		var mainImagePath = req.files.mainimage.path;
		var mainImageExt = req.files.mainimage.extension;
		var mainImageSize = req.files.mainimage.size;
	} else {
		var mainImageName = 'noimage.png';

	}

	req.checkBody('title', 'Title field is required').notEmpty();
	req.checkBody('body', 'Body field is required');

	var errors = req.validationErrors();

	if(errors){
		res.render('addpost', {
			'errors': errors, 
			'title': title, 
			'body': body,  
		});
	} else {
		var posts = db.get('posts');

		posts.insert({
			'title': title, 
			'body': body, 
			'category': category, 
			'date': date, 
			'author': author,
			'image': mainImageName
		}, function(err, post){
			if (err){
				res.send('There was an issue submitting the post');
			} else {
				req.flash('success', 'Post Submitted');
				res.location('/');
				res.redirect('/');
			}
		});
	}
});

**Comment by LinusU** [comment]
@bwong199 Since you are using `.single` you should look for the file in `req.file`, not `req.files`.

**Comment by bwong199** [comment]
@LinusU Thanks for responding. 

I changed up posts.js to read the following: 

router.post('/add', function(req, res, next){
	console.log(req.file);

	var title = req.body.title;
	var category = req.body.category;
	var body = req.body.body;
	var author = req.body.author;
	var date = new Date();

	if(req.file){
		var mainImageOriginalName = req.file.originalname;
		var mainImageName = req.file.name;
		var mainImageMime = req.file.mimetype;
		var mainImagePath = req.file.path;
		var mainImageExt = req.file.extension;
		var mainImageSize = req.file.size;
	} else {
		var mainImageName = 'noimage.png';

	}


When I console.log(req.file), this comes out: 

{ fieldname: 'mainimage',
  originalname: 'IMG_20151126_193003.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  destination: './public/images/uploads',
  filename: '64c66e49b4e69cddfda32d3c497d202e',
  path: 'public/images/uploads/64c66e49b4e69cddfda32d3c497d202e',
  size: 3233969 }

But when I check my mongodb, it says null for image: 

{
	"_id" : ObjectId("56689eaafabc7ca99805cae6"),
	"title" : "sup sup",
	"body" : "<p>dadfdaf</p>\r\n",
	"category" : "Technology",
	"date" : ISODate("2015-12-09T21:35:38.344Z"),
	"author" : "Ben Wong",
	"image" : null
}

**Comment by LinusU** [comment]
Well the multer part is working since `req.file` looks exactly like it should.

Can you `console.log` `mainImageName` just before `post.insert`?

**Comment by KillerCodeMonkey** [comment]
@bwong199 

mainImageName = req.file.name; is wrong.... req.file.filename is the thing you are looking for

**Comment by bwong199** [comment]
@KillerCodeMonkey Yes, you are right. req.file.filename is the one I should be using. Thanks so much for that. 

@LinusU Thanks for the help too. After I changed mainImageName = req.file.filename, it logs properly. When it was req.file.name, it logged undefined.

**Comment by LinusU** [comment]
Glad you got it working :)

**Comment by ankitbaid11326** [comment]
Thnks bro
now my code is working
but can u tell me how to upload multiple images

**Comment by KillerCodeMonkey** [comment]
take a look in the docu or at my first comment in this issue.
there are three methods to upload files.

if you want to upload an array (multiple files for the same field name) you can simply use .array() (https://github.com/expressjs/multer#arrayfieldname-maxcount)
or you can mix up multiple files with the .fields() (https://github.com/expressjs/multer#fieldsfields) method.

The fields-method accepts an array of objects with the keys: name --> field name and maxCount --> how many files the field can have.

The array-method takes 2 arguments --> first the field name and the second one the maxmal number of files
