### ISSUE TITLE
'end_parsed' event only called on first upload

### ISSUE THREAD

**Issue by nicekiwi** [expressjs/multer#291]
I have a form submitted by jQuery which posts to an expressJS route then resets the form. I can't post the form more than once and trigger the `end_parsed` event. 

I have a callback on the event calling a console log, it will only call once, no matter how many times I upload a file (any file). Even refreshing the page doesn't fix it, I have to restart my ExpressJS server for it to work again. 

The file uploads successfully and the correct `req.file` data shows up every-time, but the event is only called the first time. 

The file sizes are very small, usually not more than 10kb. 

Is it because I'm using `upload.single` in my route? I'm uploading only one file at a time, but need to be able to do it over and over.

**Comment by LinusU** [comment]
Could you share some code please? I'm not aware of any `end_parsed` event.

**Comment by nicekiwi** [comment]
Whoops, I think I've made a booboo. By my own admission the file uploads perfectly every-time. :tongue:  Created issue with the wrong project.

**Comment by LinusU** [comment]
Hehe, no problem :)
