### ISSUE TITLE
ECONNRESET with large files

### ISSUE THREAD

**Issue by thmoeller** [expressjs/multer#292]
Hi,

got an file upload working well with small to medium files. Now i have a larger file ( ~ 70 MB and not the fastest storage) where upload takes a little longer and  i always run into ECONNRESET.

Upload is done via http.request functionality built in node.

Is there a way to avoid it? 

All settings are default. Using latest express/multer/node versions.

Cheers

**Comment by LinusU** [comment]
Seems like you have a timeout somewhere...

Is there any keep alive options on `http.request`?

**Comment by thmoeller** [comment]
Hi Linus,

was the hint in the right. Thanks for that. 

Econnreset is now gone. But now Express server is timing out with default 120000 ms. Perhaps you now a way to extend that in Express server config??? Could not find anything in the docs. 

Cheers

Thorsten

**Comment by thmoeller** [comment]
Adjusted server timeout with following code:

```
app.use(function(req, res, next){
    res.setTimeout(480000, function(){ // 4 minute timeout adjust for larger uploads
        console.log('Request has timed out.');
            res.send(408);
        });

    next();
});
```

**Comment by LinusU** [comment]
Cool, glad you managed to fix it :+1:

**Comment by fradelg** [comment]
Thanks!! I was facing the same problem!

Do you know if there is a way to extend the response timeout for just a route / method (not for the whole server)?

**Comment by LinusU** [comment]
Indeed there is:

```javascript
function extendTimeout (req, res, next) {
  res.setTimeout(480000, function () { /* ... */ })
  next()
})

app.post('/my-route', extendTimeout, upload.single('avatar'), /* ... */)
``

**Comment by fradelg** [comment]
Thanks LinuxU!

I was just trying the same approach right now, even using the same name for the callback function which can be concatenated in express.

I wish that this issue was included in the documentation of muster. I think it could be helpful for other users too.

**Comment by fastman** [comment]
check out this: https://github.com/nodejs/node/issues/5899
