### ISSUE TITLE
onError not working?

### ISSUE THREAD

**Issue by Jakobud** [expressjs/multer#293]
Is the undocumented `onError` option still a thing? I'm doing this:

```
var multerOptions = {
	dest: 'uploads/',
	fileFilter: fileFilter,
	limits: {
		files: 1,
		fileSize: 10000
	},
	onError: function(err, next){
		console.log("error", err);
		next(err);
	}
}

var upload = multer(multerOptions);
router.post('/upload', upload.single('file'), function(req, res){
  // code here
});
```

When I upload a file that is > 10kb I get Express's error view being fired but I don't see my `console.log error` in the terminal. So is `onError` not being used anymore?

**Comment by LinusU** [comment]
`onError` is not still a thing, it was removed in version `1.0.0`. Please see the [error handling section of the readme](https://github.com/expressjs/multer#error-handling) for information on how to handle errors.

**Comment by Jakobud** [comment]
Ah I didn't know it was removed. Thank you!

**Comment by LinusU** [comment]
No problem :)
