### ISSUE TITLE
Problem renaming files

### ISSUE THREAD

**Issue by dpswtf** [expressjs/multer#294]
Hi, I'm sorry for asking this, because from what I've searched here, there's several related questions to this, and I've also read the docs but I can't still rename uploaded files.

Here's what I'm doing (I'm using v1.1.0):

    var multer = require('multer');
    var storage = multer.diskStorage({
      destination: function (req, file, cb) {
        cb(null, '/tmp/picture/')
      },
      filename: function (req, file, cb) {
        cb(null, "hey-" + Date.now())
      }
    });
    var multerUpload = multer({ storage });

    app.post('/upload', multerUpload.single('file'), function(req,res){
  
    });

I've tried several other methods but to no result. Essentially every file is still being upload to /tmp/ with the default naming conventions. I can't even change destination folder, it's always on /tmp/. Is there something I'm doing wrong? I've read and re-read the docs but still nothing. What I guess it's happening is that the storage is completely being ignored, but I have no idea why.

Additionally, I've tried using 'dest:' but it still doesn't change from the /tmp/ directory. Any help is appreciated, thanks.

**Comment by Jakobud** [comment]
Don't you have to do `var multerUpload = multer({ storage: storage });` ?

**Comment by dpswtf** [comment]
Hi, yes you do, my mistake. I fixed it now but still the same though, it's not working.

Even if that was the error, why doesn't this work?

var multerUpload = multer({ dest: 'uploads/' });

All it does is create the directory ../uploads/, but it doesn't really upload the file there, still to /tmp/

**Comment by dpswtf** [comment]
Hi again, managed to fix it. The problem was I was using express 3.X and not 4.X. After I migrated it, it worked fine. I was actually receiving deprecated issues but I was simply ignoring them (see issue [#137](https://github.com/expressjs/multer/issues/137)).

Thanks for the help, closing issue.

**Comment by LinusU** [comment]
Glad that you fixed it!

> Don't you have to do `var multerUpload = multer({ storage: storage });` ?

Actually, node supports the ES2015 feature property shorthands which makes `{ storage }` functionally equivalent to `{ storage: storage }` :+1:
