### ISSUE TITLE
Unable to return file object back to controller

### ISSUE THREAD

**Issue by RushikeshMEAN** [expressjs/multer#296]
Hello, 

I am facing issue while sending request response back to the controller of angular.
It upload the file correctly, even log response in console but not parse to controller.The request response contains information about the file which is uploaded.
 I want to get that information for further process in controller.

HERE is code

HTML CODE : 

<form id="uploadForm" enctype="multipart/form-data" method="post" action="/upload">
      <input type="file" name="userPhoto" />
      <input type="submit" value="Upload Image" name="submit" ng-click="uploadFile()">
      <span id = "status"></span>
    </form>

Inside Controller : 

var angularApp = angular.module('HousingApp');

angularApp.controller('UploadController', function($scope,$http) {
    $scope.uploadFile = function(){

```
     $http.post('/upload', $scope.formData)
    .success(function(result) {
        console.log("Success");
    })
    .error(function(data) {
        console.log('Error: ' + data);
    });
};
```

});

In Server.js :

var multer  = require('multer');

var storage = multer.diskStorage({
  //console.log("inside storage");
  destination: function (req, file, callback) {
    callback(null, 'E:/HousingProject/HousingApp/uploads/zx');
  },
  filename: function (req, file, callback) {
    //callback(null, file.fieldname + '-' + Date.now());
    callback(null, file.originalname )//+ '-' + Date.now());
  }
});

var upload = multer({ storage : storage}).single('userPhoto');

app.post('/upload',function(req,res){
  upload(req,res,function (err,docs) {
    if(err) {
      return res.end("Error uploading file.");
    }else{

```
  valuess = JSON.stringify(req.file);
console.log(valuess);
res.send(valuess);

}
 });
```

  });

Please specify how do i achieve this

**Comment by gireeshpunathil** [comment]
@RushikeshMEAN - is this still an issue ?

**Comment by RushikeshMEAN** [comment]
@gireeshpunathil  We stopped working with multer anymore.... In fact no more working with angular JS 1.X ...

**Comment by gireeshpunathil** [comment]
acknowledged.
