### ISSUE TITLE
Any example to read an excel using memoryStorage?

### ISSUE THREAD

**Issue by jdnichollsc** [expressjs/multer#297]
Hi guys!

I want to upload a file and read the excel without save in disk storage. Exist any example? Using the buffer?

Thanks in advance

**Comment by LinusU** [comment]
It looks like `XLSX.read(buffer)` with the [SheetJS XLSX library](https://github.com/SheetJS/js-xlsx) could work. I haven't tried it though and it's not really within the scope of this module to do anything with the uploaded data. Best of luck.
