### ISSUE TITLE
Ability to customize renaming function (still)?

### ISSUE THREAD

**Issue by scarabdesign** [expressjs/multer#298]
The current documentation states:

>By default, Multer will rename the files so as to avoid naming conflicts. The renaming function can be customized according to your needs.

...and, this was the case in 0.1.8, but now I'm needing to upgrade and I'm not finding details on how this can be accomplished.

**Comment by LinusU** [comment]
Use the `filename` parameter to the `DiskStorage` constructor.

e.g.

```javascript
var multer = require('multer')
var storage = multer.diskStorage({
  destination: 'uploads/',
  filename: function (req, file, cb) {
    cb(null, 'whatever-name-you-want')
  }
})
var upload = multer({
  storage: storage
})

// ...

app.post('/test', upload.single('avatar'), function (req, res, next) {
  // req.file
})
```

[Here it is in the docs](https://github.com/expressjs/multer#diskstorage)

**Comment by scarabdesign** [comment]
Thanks!
