### ISSUE TITLE
unable to send multiple files using node, getting Error: unexpected field

### ISSUE THREAD

**Issue by mroker242** [expressjs/multer#301]
I am using Angular ng-file-upload to upload files. When sending here is the html, but I am getting error 'Error: Unexpected field' and from the client getting Internal Error 500. Can you please assist with this issue?

```html
<div class="button btn btn-danger" ngf-select ng-model="files" name="files" ngf-multiple="true">Select</div>
  <button type="submit" ng-click="submit()">submit</button>
```

Angular as follows

```javascript
if($scope.files){
      	console.log('upload multiple works');
      	console.log($scope.files);
      	$scope.uploadFiles($scope.files);
      }
    };

$scope.uploadFiles = function (files) {
      if (files && files.length) {
        for (var i = 0; i < files.length; i++) {
          Upload.upload({
          	url: 'api/admin/photos',
          	data: {file: files}
          }).then(function(resp){
          	console.log('Successfully ' + resp.config.data.file.name);
          	$scope.myPic = resp.config.data.file.name;
          },
          function(resp){
          	console.log('Error status: ' + resp.status);
          },
          function(evt){
          	var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
          	 console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
          })
          }
        }
       
      };
```

and using node

```javascript
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'public/img')
  },
  filename: function (req, file, cb) {
    //cb(null, file.originalname + '-' + Date.now())
    cb(null, file.originalname )
  }
});

var upload = multer({ storage: storage });

//upload photos
apiRoutes.post('/admin/photos',upload.array('files'),function(req,res){

	console.log(req);


	//save to database
	


	console.log(req);
	 console.log(req.file.originalname);
	console.log(req.file.originalname);
	 res.json(req.file[0]);

});
```

**Comment by LinusU** [comment]
The field is named `file` in the browser: `data: {file: files}`. But it's named `files` on the server: `upload.array('files')`. Change them to match up.

Also, since you are receiving multiple files (`upload.array(...)`) you should look at `req.files` instead of `req.file`.

**Comment by mroker242** [comment]
I've made the changes to data: {files: files} and I also did something with the errors...

```javascript
app.use(function (err, req, res, next) {
  console.log(err) 
  console.log(err.stack)
})
```

I got the following error while doing this.

    { [Error: Unexpected field]
    code: 'LIMIT_UNEXPECTED_FILE',
     field: 'files[0]',
     storageErrors: [] }

No luck so far.

**Comment by gronel** [comment]
i got same issue in ng-file-upload

**Comment by LinusU** [comment]
The problem is that the clients you are using are appending `[n]` to the field names, which we currently don't handle...

**Comment by gronel** [comment]
@LinusU its that bug of ng-file-upload?

**Comment by LinusU** [comment]
Well, it's hard to say. As far as I know, there isn't any specification saying how you *should* name the fields. I think that they are compatible with how it works in php.

It would certainly be good if it where configurable though, I would file an issue to them about that.

**Comment by shivam1401** [comment]
Change your code.
**from :**
```
Upload.upload({
            url: 'api/admin/photos',
            data: {file: files}
 })
```

**to:**
```
Upload.upload({
            url: 'api/admin/photos',
            arrayKey: '',
            data: {file: files}
          })
```
It should work.

**Comment by LinusU** [comment]
Thank you @shivam1401 for that solution 👍

**Comment by xitman78** [comment]
Thanks a lot @shivam1401! Finally it works for me! 👍

**Comment by tianshilei1992** [comment]
@shivam1401 Hi, can you explain why should add this 'arrayKey' field?

**Comment by leoparis89** [comment]
Thanks @shivam1401!

**Comment by JacoboDB** [comment]
The reason for the error is that multer currently does not support the array syntax that ng-file-upload uses by default which is files[0], files[1], files[2], etc. multer is expecting a series of files with the same field name.

The easiest solution is to set ng-file-upload's arrayKey option like so to avoid appending the [index] part

**Comment by usos0k** [comment]
@shivam1401  genius!

**Comment by shivam1401** [comment]
@usos0k @leoparis89 @xitman78 @LinusU : Happy To Help guys..  (y)

**Comment by khurdra** [comment]
arrayKey: '', solves the error Unexpected Field
But it leads to another problem
I am trying to send json object along with multiple files
JSON object 
{
    name: xyz,
        data : [
            { k1: v1, k2: v2 },
            { k1: v3, k2: v4 }
        ]
}

But on server side it is received as
{
    name: xyz,
        data : {
            k1: [v1, v3], k2: [v2, v4]
    }
} 

If I remove arrayKey, correct JSON object received at server

**Comment by josduj** [comment]
Just use `any()` instead of `array('file')`.

When using `array('file')`, multer throws error because it expects all fields to be named `file`, while ng-file-upload names them `file[0]`, `file[1]` etc..
I wouldn't recommend using `arrayKey: ''` because it's basically a hack, and messes up serialization of other arrays if you are sending additional data.

Another option is to use `files()`, and do something like:
```javascript
upload.files([
    { name: 'file[0]', maxCount: 1 },
    { name: 'file[1]', maxCount: 1 },
    ...
])
```
But then `req.files` is object with arrays of files.

**Comment by gronel** [comment]
Thanks guys

**Comment by prajwalgreenway** [comment]
const express = require('express')
const multer = require('multer')
const router = express.Router()
const model = require('../model/schema')
const TRUCK = require('../model/truck')
const path=require('path');

const storage = multer.diskStorage({
	destination:function(req,res,cb){
		cb(null,'./upload/')

	},
	filename: function(req, file, cb){
    cb(null,file.fieldname + '-' + Date.now() +path.extname(file.originalname));
  } 
})

const upload = multer({storage:storage})
const photo = upload.fields([{name : 'registration_copy' , name:'driver_license'}])



router.post('/truck' ,photo, async(req,res)=>{
	const truck1 = new TRUCK({
		truck_number             :     req.body.truck_number,
		driver_name              :     req.body.driver_name,
		contact_number           :     req.body.contact_number,
		alternate_contact_number :     req.body.alternate_contact_number,
		logistic_partner_name    :     req.body.logistic_partner_name,
		driver_license           :     req.file.path,
		registration_copy        :     req.file.path,
		eway_bill_number         :     req.body.eway_bill_number,
		additional_information   :     req.body.additional_information
	})
	try{
		const truck2 = await truck1.save()
		res.json(truck2)
	}
	catch(err)
	{
		res.json('errror')
	}
})
router.get('/d', async(req,res)=>{
	try{
	const j1 = await TRUCK.find()
	res.json(j1)
}
catch(err)
{
	res.json('errr')
}
})


module.exports = router




showing error 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>MulterError: Unexpected field
            <br> &nbsp; &nbsp;at wrappedFileFilter (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\multer\index.js:40:19)
            <br> &nbsp; &nbsp;at Busboy.&lt;anonymous&gt; (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\multer\lib\make-middleware.js:114:7)
            <br> &nbsp; &nbsp;at Busboy.emit (events.js:315:20)
            <br> &nbsp; &nbsp;at Busboy.emit (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\busboy\lib\main.js:38:33)
            <br> &nbsp; &nbsp;at PartStream.&lt;anonymous&gt; (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\busboy\lib\types\multipart.js:213:13)
            <br> &nbsp; &nbsp;at PartStream.emit (events.js:315:20)
            <br> &nbsp; &nbsp;at HeaderParser.&lt;anonymous&gt; (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\Dicer.js:51:16)
            <br> &nbsp; &nbsp;at HeaderParser.emit (events.js:315:20)
            <br> &nbsp; &nbsp;at HeaderParser._finish (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\HeaderParser.js:68:8)
            <br> &nbsp; &nbsp;at SBMH.&lt;anonymous&gt; (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\HeaderParser.js:40:12)
            <br> &nbsp; &nbsp;at SBMH.emit (events.js:315:20)
            <br> &nbsp; &nbsp;at SBMH._sbmh_feed (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\streamsearch\lib\sbmh.js:159:14)
            <br> &nbsp; &nbsp;at SBMH.push (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\streamsearch\lib\sbmh.js:56:14)
            <br> &nbsp; &nbsp;at HeaderParser.push (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\HeaderParser.js:46:19)
            <br> &nbsp; &nbsp;at Dicer._oninfo (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\Dicer.js:197:25)
            <br> &nbsp; &nbsp;at SBMH.&lt;anonymous&gt; (C:\Users\PRAJWAL JASWAL\Desktop\dispatch\node_modules\dicer\lib\Dicer.js:127:10)
        </pre>
    </body>
</html>
