### ISSUE TITLE
Permissions when saving files in temporary directory

### ISSUE THREAD

**Issue by emil-alexandrescu** [expressjs/multer#304]
Multer seems saving file as 0544 permission. And weirdly it doesn't let me delete the file and saying I have no permission to do that.

**Comment by gireeshpunathil** [comment]
@emil-alexandrescu -

file permissions are dictated by `umask` - https://en.wikipedia.org/wiki/Umask , not multer

hope this helps!

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
