### ISSUE TITLE
Ajax upload

### ISSUE THREAD

**Issue by ChristianRich** [expressjs/multer#305]
I'm struggling getting this working with jQuery ajax upload. Would you have any examples at hand?

**Comment by LinusU** [comment]
This tutorial seems very good, it was my first hit on google for "ajax file upload".

http://blog.teamtreehouse.com/uploading-files-ajax

One important thing though, they are setting the file name to `image[]`, this is currently not supported in multer. When they write this:

    formData.append('photos[]', file, file.name);

Instead write this:

    formData.append('photos', file, file.name);

Then on the server you can use the `array` function to receive the files.

    app.post('/upload', upload.array('photos'), function (req, res, next) { // ...

Hope that this helps!

**Comment by daslicht** [comment]
I get anytime : unexpected field,  hm

**Comment by bigtotorouk** [comment]
i hvae the err. same code. it's a bug.
