### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by ChristianRich** [expressjs/multer#306]
I'm using multer to upload files via Ajax and it works very well. However, I can't seem to tap into the upload progress so I can feed that back to the client and display a progress bar. Is this possible?

**Comment by LinusU** [comment]
It's actually possible on both sides, although I would recommend doing it on the client side to avoid the feeding back step.

Use the [`progress` event](https://developer.mozilla.org/en-US/docs/Web/Events/progress) to get info about how much stuff is uploaded.

Using it together with the [`<progress> element`](https://css-tricks.com/html5-progress-element/) is super easy.

```javascript
var req = new XMLHttpRequest()
var progress = document.createElement('progress')

// ...

req.upload.addEventListener('progress', function (ev) {
  if (!ev.lengthComputable) return

  progress.max = ev.total
  progress.value = ev.loaded
})
```

**Comment by LinusU** [comment]
Please reopen if you need more assistance

**Comment by iscorporacion** [comment]
you have a server side example?

**Comment by LinusU** [comment]
@iscorporacion you can look at the incoming request and hook up data notifications before passing the stream to Multer. This is not specific to Multer so I would recommend making a StackOverflow post if you need more assistance, but basically, it would work something like this:

- Add a middleware to express that reads the `Content-Length` and sets up a spy on the `data` and `end` events.
- On every `data` event, calculate the progress by summing earlier events and this event's payload length

**Comment by guiprav2** [comment]
It looks like `multer` with default settings won't send `Content-Length` back early enough for `progress` events to be fired before the end of the upload. Could someone confirm this still works for them and share a working example, please?
