### ISSUE TITLE
req in filename of diskStorage not working

### ISSUE THREAD

**Issue by yswhynot** [expressjs/multer#308]
I'm trying to rename the file to the id of my form field but find that req is not working for filename of diskStorage.
Here's the code:
```javascript
var storage =   multer.diskStorage({
  destination: function (req, file, callback) {
    callback(null, './storage');
  },
  filename: function (req, file, callback) {
  	console.log('multer: ' + req.body.formid);
    callback(null, file.originalname);
  }
});
var upload = multer({ storage : storage});
```

and later I have:
```javascript
router.post('/change', upload.single('image'), function(req, res, next) {
	var elementID = req.body.formid;
	console.log('elementID: ' + elementID);
});
```
and got an output at console of:

> multer: undefined
elementID: 56acc7fd3a6be5bc79f58962

**Comment by LinusU** [comment]
If that's the case, the client is sending the file before the fields. See #146 for a workaround...

There is unfortunately nothing we can do about this in Multer, you'll have to fix it in your client (in this case, the browser)...
