### ISSUE TITLE
How to upload through rest api?

### ISSUE THREAD

**Issue by zhouhao27** [expressjs/multer#310]
Is it possible to upload through an api instead of from a form? How? Thanks.

**Comment by zhouhao27** [comment]
What should I pass to single() through my api? Thanks

**Comment by zhouhao27** [comment]
Any idea? Thanks

**Comment by zhouhao27** [comment]
In another word how can I create a **file** object without using <input type="file">, instead from my program.

**Comment by cjduncana** [comment]
How about you post a [MVC](http://stackoverflow.com/help/mcve)?

**Comment by HarshithaKP** [comment]
@zhouhao27 is this still an issue for you ?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
