### ISSUE TITLE
Creating disk storage with default options

### ISSUE THREAD

**Issue by sebastian-nowak** [expressjs/multer#311]
Quite often I want to create a disk storage with default options. The obvious way is:

```
multer({ storage: multer.diskStorage() })
```

However it throws an exception, it requires options to be explicitly passed, so we have to use:

```
multer({ storage: multer.diskStorage({}) })
```

It's not really intuitive, `options` should default to `{}` when not defined.

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
