### ISSUE TITLE
The next callback not exec with multer when network is slow

### ISSUE THREAD

**Issue by fiture** [expressjs/multer#313]
here is the example:

``` javascript
router.post('/upload', multer({ dest: 'dest' }).any(), function(req, res, next){
    console.log('this line not be fired, when the network is slow');
});

```

express log show this:

```
POST /upload - - ms - -
POST /upload - - ms - -
```

and msg in chrome console:

```
POST http://remote-server.addr:8000/upload net::ERR_CONNECTION_RESET
```

**Comment by jordonias** [comment]
Are you sending a reaponse? Add `res.end() after `console.log`

**Comment by LinusU** [comment]
You probably need to increase your timeouts, see #292

**Comment by fiture** [comment]
So I've found some file in the 'dest' directory，but it haven't been uploaded completely ( It's size is much smaller than the file i picked to uplaod)
bb16269a63ab24b8717bde1a2ee569b0

@jordonias  of course~

the code blow works in normal condition,  But when the network is slow(50kb/s)  and file size is lager than  20M，then error occurred.

```javascript
router.post('/upload', multer({ dest: 'dest' }).any(), function(req, res, next){
    console.log('this line not be fired, when the network is slow');
    res.json({msg: 'uploaded'})
});
```

@LinusU   Yeah, I guess this is the timeout problem too，I'm going to have a try~

Thx

**Comment by Dev-rahul** [comment]
Did you find a solution to this problem? , im facing the same issue with large file uploads using multer

**Comment by jonchurch** [comment]
@fiture @Dev-rahul Did increasing timeouts help you?

**Comment by fiture** [comment]
> @fiture @Dev-rahul Did increasing timeouts help you?

yes
