### ISSUE TITLE
Error: ENOENT, no such file or directory '"/Users/files/51ea3b5c60edd03023c9da46b15e3d95"'

### ISSUE THREAD

**Issue by charyorde** [expressjs/multer#315]
But the file is there...

File uploaded successfully (can find it in specified directory). However, for reasons I can't understand, the file is not found. Here's the code snippet:

```
var upload = multer({ dest: __dirname + '/../files' })
router.post('/upload-sheet', upload.single('filedata'), function(req, res, next) {
  var form = {
      body: req.body,
      file: req.file
    }
    var file = form.file
      , filedata = file
      
  if(require('fs').statSync(filedata.path).isFile()) {
    new CsvStream(filedata.path)
    return res.status(200).send('OK')
  }
  else {
    return res.status(404).send("File not found")
  }
})
```
Using `curl` client:
`curl -i -F name=data -F filedata=@/tmp/data.csv  http://localhost:3006/v1/upload-sheet`

**Env**
- Node v0.12.5
- Express ^4.13.4
- Multer v1.1.0

**Comment by LinusU** [comment]
Could you post the stack-trace? I suspect your error is in `CsvStream`...

**Comment by charyorde** [comment]
Ah. You're right. I removed the line `new CsvStream(filedata.path)` and boom, it works!

Thanks for saving me debug time.

**Comment by LinusU** [comment]
No problem :+1:
