### ISSUE TITLE
save filename in db

### ISSUE THREAD

**Issue by alfredopacino** [expressjs/multer#316]
Hi, I have 2 beginner questions:
- I want to upload the file and then save the file name in a db, how can I get the final filename saved?. 
- I'm ok with the unique multer file destination name, but I need to keep the extension file, how can I do that?

**Comment by LinusU** [comment]
Have you read the documentation? Each file has a `path` property which contains the full path.

Regarding keeping the extension, see #170

**Comment by alfredopacino** [comment]
that's my attemp to use DiskStorage, honestly I don't find the docs about that so much clear :)
I get the error "ENOENT: no such file or directory.."
(currently I'm on win7 I don't think it's a permission issue)
```
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, path.join(__dirname, 'upload','pdf'))
    },
    filename: function (req, file, cb) {
        crypto.pseudoRandomBytes(16, function (err, raw) {
            if (err) return cb(err)
            cb(null, raw.toString('hex') + path.extname(file.originalname))
        })
    }
})
var upload = multer({
    storage: storage,
    onFileUploadComplete: function (file) {
        console.log(file.originalname + ' uploaded to  ' + file.path);
        //here I should save the filename to db
    }}).single('displayImage')
app.post('/upload', upload, function (req, res, next) {
    console.log('req.file')
    console.log(req.file);
    res.send('file upload')
})
```

**Comment by LinusU** [comment]
Is there a folder `upload/pdf` created? Multer won't do that for you...

I'm sorry about your problems with the docs, do you have any suggestions on how to make them better?

**Comment by alfredopacino** [comment]
ok, I made the dumbest mistake you can imagine: the folder was named "uploads".
By the way I noticed using dest (without diskStorage) the folder is automatically created.

About the docs: I'm very glade you're open to suggestions :+1: 
In my opinion some advanced (and complete) example of diskStorage would be very helpful. The basic example
```
app.post('/profile', upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file
  // req.body will hold the text fields, if there were any
})
```
it's way too 'basic' for a real production usage.
Currently, for example, I'm not clear where I have to define the fileSize value and the fileFilter function :)
