### ISSUE TITLE
req.files is always undefined

### ISSUE THREAD

**Issue by ktkaushik** [expressjs/multer#317]
hey, i've tried different ways - 

__package.json__

```javascript
"express": "~4.13.1",
"multer": "^1.1.0"
```

```javascript
var upload = multer({ dest: '../uploads/', inMemory: true, includeEmptyFields: true});

router.post('/upload', upload.single('img'), function (req, res, next) {
   // do something here
  console.log(req.file)
  console.log(req.files)
})
```

```html
<input type="file"  id="image-upload" multiple name="img">
```

The `file` variable is coming in from the `change` event on the input element above

```javascript
var data = new FormData();
data.append('img', file);

$.ajax({
    type: 'POST',
    url: "http://localhost:3000/products/upload",
    contentType: false,
    processData: false,
    data: data,
    cache: false
})
.done(function (data) {
    alert(data);
})
.fail(function (data) {
    alert('faile.')
    console.error(data);
})
```

**Comment by ktkaushik** [comment]
I've also tried --

```javascript
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '../uploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})

var upload = multer({storage: storage, 
    onFileUploadStart: function (file) {
      console.log(file.originalname + ' is starting ...')
    },
})
```

No luck though.

I've tried with images which are 1Mb and those with 3Kb. No idea what next though.

**Comment by arthurspa** [comment]
I'm with the same problem. Can't get the original or generated file name, although the file is saved normally.

**pachage.json**
```
"express": "^4.13.1",
"multer": "^1.0.6"
```

I noticed that inside the callback after call upload, req is always undefined:

```
 upload(req, res, function (uploadError) {
    if (uploadError) {
      return res.status(400).send({
        message: 'Erro message'
      });
    } else {
      // here req is undefined
      res.json({});
    }
  });
```

Maybe there is some incompatibility with express 4?

**Comment by damkraw** [comment]
Do you have `enctype="multipart/form-data"` on your form ?

**Comment by ktkaushik** [comment]
@arthurspa I am not seeing any uploads at all.

@damkraw yes, i do.

**Comment by ayyappaappana** [comment]
Any Fixes found. I am also facing this issue.

**Comment by hanaarena** [comment]
Have you try append `.single('img')`, like below

```javascript 
var upload = multer({storage: storage, 
    onFileUploadStart: function (file) {
      console.log(file.originalname + ' is starting ...')
    },
}).single('img');
```

**Comment by hanaarena** [comment]
Or maybe relate #210 :)

**Comment by ktkaushik** [comment]
@hacksparrow i doubt if it would relate to https://github.com/expressjs/multer/issues/210 man

**Comment by hacksparrow** [comment]
@LinusU dude, mind taking a look, please?

**Comment by LinusU** [comment]
@ktkaushik It seems like you are uploading a `FormData` with jQuery. This is not supported with jQuery and it won't send anything at all.

Could you try if it works with a simple html-example first?

**Comment by ktkaushik** [comment]
@LinusU It should work with simple HTML.

why doesn't it work with jQuery ? it won't work with any xhr requests is it ?

**Comment by LinusU** [comment]
It works with XHR Requests, the problem is that the jQuery api simply doesn't support passing a `FormData` instance to it. Seems like there is a workaround available though: http://stackoverflow.com/a/8244082/148072

**Comment by ktkaushik** [comment]
@LinusU Yup, i've tried this one already. Sadly, it doesn't seem to work at all.

**Comment by LinusU** [comment]
Do you need to use jQuery? Could you use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)?

```javascript
var data = new FormData()
data.append('img', file)

var url = 'http://localhost:3000/products/upload'
var opts = {
  method: 'POST',
  body: data
}

fetch(url, opts)
  .then(res => res.text())
  .then(data => {
    alert(data)
  })
  .catch(err => {
    alert('failed')
  })
```

**Comment by ktkaushik** [comment]
@LinusU Fetch seem to have worked. Thanks.

XHR wasn't working for me. Not sure why, didn't put too much time into it though.

:+1:
