### ISSUE TITLE
error 404 in the view 

### ISSUE THREAD

**Issue by neomadara** [expressjs/multer#323]
Hello people! i have a problem when i try to see the imagen in the view, the image actually stored in the address I give.

**addnew.js**

`var multer  = require('multer');
var storage = multer.diskStorage({
  destination: function(req, file, cb){
    cb(null,'public/uploads');
  },
  filename: function (req,file,cb) {
    cb(null, file.originalname)
  }
});
var upload = multer({ storage: storage });

module.exports = function(app){
  app.use('/', router);
};

router.get('/addnew', function(req, res){
  res.render('addnew');
});

router.post('/addnew',upload.single('img'), function(req, res){
  var url = req.body.titulo.replace(' ','-');
  var nuevoRegistro = new Noticia({
    titulo: req.body.titulo,
    contenido: req.body.contenido,
    url: url,
    imgpath: req.file.path
  });
  console.log(req.file);
  nuevoRegistro.save(function(err){
    console.log(err);
  });

  res.redirect('/');
});`

and the view **noticia.jade**
`extends layout

block content
  header
    h1 Las Mejores Noticias
  div.container
    div.row
        div.col-md-10.col-md-offset-1
          h1=titulo
          div.content
            =contenido
          img(src='#{imgpath}')
    a(href="/editar/#{_id}") Editar
    br
    a(href="/") Volver al Home

  include footer
`
and here its the error 
[error](http://imgur.com/YfQbASX)
maybe its a rookie mistake but I can find the error

**Comment by LinusU** [comment]
It seems like you don't have anything that is serving the files. I'm on mobile now ant can't link but take a look at `express.static`...

**Comment by neomadara** [comment]
i have the express.js a have
`app.use("/uploads", express.static(__dirname+'/public/uploads')); //para las imagenes`

and in the controller of the view i have
`var multer  = require('multer');
var storage = multer.diskStorage({
  destination: function(req, file, cb){
    cb(null,'public/uploads');   //revisar esta linea si guarda en uploads
  },
  filename: function (req,file,cb) {
    cb(null, file.originalname)
  }
});
`

**Comment by LinusU** [comment]
And what url are you trying to access the file from?

**Comment by LinusU** [comment]
Looking at the first error you posted, the problem is that you are linking to the file wrong.

You are trying to access it as `/noticia/public/uploads/filename.jpg`
When you should in fact use `/uploads/filename.jpg`

Either change how you store the path, or change where you mount `express.static` (`app.use('/noticia/public/uploads', express.static(__dirname + '/public/uploads'))` would work)...

**Comment by neomadara** [comment]
@LinusU a change the code but i still say the same message

[error](http://imgur.com/VlS3Dfu)

**Comment by neomadara** [comment]
@LinusU you have a right, the express.static was the problem, many thanks!!!

**Comment by LinusU** [comment]
No problem :+1:
