### ISSUE TITLE
Multer doesn't call its "next" callback

### ISSUE THREAD

**Issue by sherifnada** [expressjs/multer#325]
I'm trying to handle a photo upload by the user as such: 

```
var multer = require('multer');

router.post("/uploadPhoto", isAuthenticated, function(req, res, next){
    console.log("Authentication test passed");
    next();
}, function(req, res, next){
    console.log("Uploading!");
    multer().single('userPhoto')(req, res, function(err){
          if(err) console.log(err);
          else console.log("No problem!");
    });
}
);
```

My output is 

```
Authentication test passed
Uploading!
```

But it doesn't seem that multer is dropping into the provided callback? I have the same problem when I include multer as a middleware: 

```
router.post("/uploadPhoto", isAuthenticated, multer().single("userPhoto"), function(req, res){
     console.log("HERE!");
});
```

I don't get the "HERE!" message. 

My apologies if this is in the docs somewhere. I have been looking around but couldn't find what the expected behavior should be here. Any help would be very appreciated.

**Comment by sherifnada** [comment]
I tried making simple upload requests through postman and the callbacks were being invoked. However, I'm currently making these requests from my iOS application, and those requests (the ones from iOS) aren't invoking the callbacks.

**Comment by LinusU** [comment]
Since it works with postman and not with your iOS client, it seems like the problem is with your iOS client. What library are you using and how are you using it?

**Comment by sherifnada** [comment]
I figured out the problem: in my iOS client, my POST request looked something like 

```
Content-type: multipart/form-data; boundary="--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87"
--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87

Content-Disposition: form-data; name="userPhoto";

<PLXPCShMemData: 0x13cd02830> bufferLength=32768 dataLength=29025

--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87--

```

But I forgot to add a few things: 
`charset=utf8` in the `Content-type` header
`Conent-type` in the body of the request
`filename` in the `Content-Disposition` part of the request

```
Content-type: multipart/form-data; charset=utf8; boundary="--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87"
--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87

Content-Disposition: form-data; name="userPhoto"; filename="image.jpg"

Content-type: image/jpeg

<PLXPCShMemData: 0x13cd02830> bufferLength=32768 dataLength=29025

--Boundary-8F6C36F3-A273-4FF8-AED2-1098C7C5BD87--
```

So my problem is solved, thankfully. But do you think this should trigger some error message from Multer or no? Would greatly help debugging.

Thank you for your time.

**Comment by LinusU** [comment]
Hmm, this is probably a problem in [busboy](https://github.com/mscdex/busboy) then, would you mind opening an issue there?
