### ISSUE TITLE
Multiple fiels uploading not working

### ISSUE THREAD

**Issue by diegoaguilar** [expressjs/multer#329]
I've tried `upload.array('accomodation_pictures', 5)` and even `upload.any()` but with any of them only first file is taken:

![image](https://cloud.githubusercontent.com/assets/2483678/13863329/a65becfc-ec5e-11e5-8d15-e0599777d0d7.png)

```
router.post('/',
  controllers.requireAuthorization,
  multer.any(),
  function (request, response, next) {
    console.log(request.files.length);
    console.log(request.body);
    next();
  },
  controllers.sitters.validate,
  controllers.sitters.create,
  controllers.sitters.serialize
);

```

Is always logging 1

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
