### ISSUE TITLE
TypeError: Cannot read property 'img' of undefined

### ISSUE THREAD

**Issue by OussOuss** [expressjs/multer#331]
Hello,
I try to upload a simple file but i got an erreor TypeError: Cannot read property 'img' of undefined.

here is my route.js : 
```
var express = require('express'),
router = express.Router(),
home = require('../controllers/home'),
image = require('../controllers/image'),
multer = require('multer'),
path = require('path'),
upload=multer({ dest: path.join(__dirname,'../public/upload/temp')});


module.exports = function(app) {
router.get('/', home.index);
router.get('/images/:image_id', image.index);
router.post('/images',upload.single('img'),  image.create);
router.post('/images/:image_id/like', image.like);
router.post('/images/:image_id/comment', image.comment);
app.use(router);
};
```

and my form : 
```
<form method="post" action="/images" enctype="multipart/formdata">
<div class="panel-body form-horizontal">
<div class="form-group col-md-12">
<label class="col-sm-2 control-label" for="file">Parcourir:</label>
<div class="col-md-10">
<input class="form-control" type="file" name="img" id="file">
</div>
</div>
```
...
 
my image  controller : 

```
create: function(req, res) {
var saveImage = function() {
	var possible = 'abcdefghijklmnopqrstuvwxyz0123456789',
imgUrl = '';
for(var i=0; i < 6; i+=1) {
imgUrl += possible.charAt(Math.floor(Math.random() *
possible.length));
}

console.log(req.body);
var tempPath = req.file.img.path,
ext = path.extname(req.file.img.name).toLowerCase(),
targetPath = path.resolve('./public/upload/' + imgUrl + ext);
.... 
```

please if someone can help me

**Comment by LinusU** [comment]
Since you are using `.single()` the file will be available at simply `req.file`, not `req.file.img`, could you try and change to that?

**Comment by OussOuss** [comment]
I change it but i have the same problem :(

**Comment by OussOuss** [comment]
for me when i use console.log() the req.file req.body is undefined

**Comment by LinusU** [comment]
The `enctype` should be `multipart/form-data` (note the added `-`)

**Comment by OussOuss** [comment]
Thx a lot you are Genius :D

**Comment by LinusU** [comment]
Glad it helped :)

**Comment by praditya19** [comment]
mport React, { Component } from "react";
import styled from "styled-components";
import { ProductConsumer } from "./Context";
import { ButtonContainer } from "./Button";
import { Link } from "react-router-dom";
export default class Modal extends Component {
  render() {
    return (
      <ProductConsumer>
        {value => {
          const { modalOpen, closeModal } = value;
          const { img, title, price } = value.modalProduct;
          if (!modalOpen) {
            return null;
          } else {
            return (
              <ModalContainer>
                <div className="container">
                  <div className="row">
                    <div
                      className="col-8 mx-auto col-md-6 col-lg-4 p-5 text-center text-capitalize"
                      id="modal"
                    >
                      <h5>item added to cart</h5>
                      <img src={img} className="img-fluid" alt="" />
                      <h5>{title}</h5>
                      <h5 className="text-muted">price : ${price}</h5>
                      <Link to="/">
                        <ButtonContainer
                          onClick={() => {
                            closeModal();
                          }}
                        >
                          Continue Shopping
                        </ButtonContainer>
                      </Link>
                      <Link to="/cart">
                        <ButtonContainer
                          cart
                          onClick={() => {
                            closeModal();
                          }}
                        >
                          Go To Cart
                        </ButtonContainer>
                      </Link>
                    </div>
                  </div>
                </div>
              </ModalContainer>
            );
          }
        }}
      </ProductConsumer>
    );
  }
}


when run it appears TypeError: Cannot read property 'img' of undefined

**Comment by xiao-ma-nong** [comment]
解决了吗
