### ISSUE TITLE
TypeError: upload.array is not a function

### ISSUE THREAD

**Issue by hexinatgithub** [expressjs/multer#338]
There is a problem in release 1.1.0 .
if i type below code, node will complain:TypeError: upload.array is not a function

```javascript
app.post('/profile', upload.array(), function (req, res, next) {
  console.log(req.body);
  res.json(req.body);
});
```

It cann't work, but with release 1.0.5 it will work well.

**Comment by LinusU** [comment]
What is `upload`, can you show more of the code?

**Comment by hexinatgithub** [comment]
Sorry, i don't explain the detail.
I follow the example in expressJS,and type the follow code:

var app = require('express')();
var bodyParser = require('body-parser');
var multer = require('multer'); // v1.0.5
var upload = multer(); // for parsing multipart/form-data

app.use(bodyParser.json()); // for parsing application/json
app.use(bodyParser.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded

app.post('/profile', upload.array(), function (req, res, next) {
  console.log(req.body);
  res.json(req.body);
}); 

If I download multer v1.0.5, it will work, no error.
But strange thing happen in v1.1.0 .
TypeError: upload.array is not a function, Don't know why.

**Comment by LinusU** [comment]
Your exact code works for me. Are you sure that you are only running that code, and nothing else?

**Comment by RyoheiTomiyama** [comment]
<input type="file" name="inputname">

upload.array('inputname')
