### ISSUE TITLE
Responding with the name of the file saved

### ISSUE THREAD

**Issue by Nokel81** [expressjs/multer#340]
It there a way to send back in the response the name of the file that was determined by the multer.diskStorage({filename: function (req, file, next)}); function?

**Comment by Ra1d3n** [comment]
You have a reference to the req object, where you can save the name of the file and respond with it down the chain like `req.mycustomdata.filename = myfile` or similar.

**Comment by LinusU** [comment]
The information is available on the `file` object, e.g. `req.file.filename`. Please refer to the [File Information](https://github.com/expressjs/multer#file-information) section of the readme...

**Comment by bkimminich** [comment]
__In the response__ you do not get back the `filename` or `path` of the stored file, only its original name on the client:

```
File {name: "file.pdf", lastModified: 1473504669829, lastModifiedDate: Sat Sep 10 2016 12:51:09 GMT+0200 (Mitteleuropäische Sommerzeit), webkitRelativePath: "", size: 113911…}
```

I tried to pass additional data in using `res.status(204).json(path: req.file.path)` but in the final response the `data` object is always `""`. The status code is set correctly, so it seems like my `res.data` gets overwritten later in the process.

**Comment by LinusU** [comment]
Where are you logging that? `req.file` from Multer doesn't have any fields named `lastModified`, `lastModifiedDate` or `webkitRelativePath`...

**Comment by bkimminich** [comment]
Might be `ng-file-upload` magic fairy dust? Here's my code:

* https://github.com/bkimminich/juice-shop/blob/develop/app/js/controllers/ComplaintController.js
* https://github.com/bkimminich/juice-shop/blob/develop/app/views/Complaint.html
* https://github.com/bkimminich/juice-shop/blob/develop/server.js (Line 131)

Am 11. September 2016 18:32:09 MESZ, schrieb "Linus Unnebäck" <notifications@github.com>:
