### ISSUE TITLE
Upload only to some resources

### ISSUE THREAD

**Issue by Aspie96** [expressjs/multer#341]
It would be helpful to be always able to read `multipart/form-data` parameters and to upload files only to one resource.

I wrote something like:
```javascript
// ...
var upload = multer({ dest: tempDir });

app.use(upload.array());

// ...

app.use("/fileUpload", upload.single("myFile"), function(req, res) {
	// ...
});
```

But it throws:
`Error: Unexpected field at makeError`

Is there any way to do that?

Thank you very much in advance!

**Comment by LinusU** [comment]
Remove this line:

```javascript
app.use(upload.array());
```

**Comment by Aspie96** [comment]
It's not gonna do the job: other resources would not be able to use `multipart/form-data` encoded `POST` fields.

**Comment by LinusU** [comment]
Well, you can't have more than one multer middleware since the body stream will already have been consumed by the time the other one kicks in. Can you add `upload.array()` only to the routes that needs it?

**Comment by Aspie96** [comment]
Basically all routes need it, in that router.
A solution would indeed be to call `upload.array()` on every route.
It'd not be a very elegant solution, but it would work.

Is there any better solution?
Thank you very much.

**Comment by LinusU** [comment]
Unfortunately we cannot give an more elegant solution from multers side since the request body can only be consumed once. Sorry for the inconvenience...

**Comment by Aspie96** [comment]
Ok, thank you very much for your help.

**Comment by LinusU** [comment]
No problem, thank you for using multer!

**Comment by Aspie96** [comment]
I found a pretty trivial solution.
It was stupid of me not to think of it earlier, but I want to share it, just in case someone else will be wondering the same problem.

All one has to do is defining first the resource which uplaods the file and **then** call `app.use(upload.array());`, like that:
```javascript
var upload = multer({ dest: tempDir });

// myMiddleware is a middleware I always have to call.

app.use("/fileUpload", myMiddleware, upload.single("myFile"), function(req, res) {
    // ...
});

app.use(upload.array());
app.use(myMiddleware);

// I define all my other resources here.

```

This will do the trick.
Of course, this will change the structure of the code, but in my case it was the best solution (I also had another middleware to be always called after multer, since it used POST params, so there would have been quite a bit of duplicated code).
