### ISSUE TITLE
Unable to find the File whose size is more than the max size. File uploading first to server which leads to timeout.

### ISSUE THREAD

**Issue by dhana-kony** [expressjs/multer#346]
Hi All,
         I am writing code where I use multer to send a max of 5 files and each file can be a max of 1MB in size.In the process the validation is working fine and even if one of the files is more than 1MB size, an error is thrown. Also no file is added to the destination. Nevertheless the problem is it is not able to identify which file exceeded the max file size. I want to display it on my console.

The other problem I see in the code is when a large file for example one with size 3GB is uploaded to the server, I see that first the file is getting uploaded to destination location in my case C://Multer.
However it is not completely copied onto hardisk. Only the first 1MB content of the file is copied to the destination.But the server is waiting till the 3GB is getting copied which is leading to server timeout.How can I resolve this issue without server timeout.

Sometimes I get the following which is quite sporadic. 

> binding.unlink(pathModule._makeLong(path), req);
>           ^
> 
> TypeError: path must be a string
>     at TypeError (native)
>     at Object.fs.unlink (fs.js:927:11)
>     at DiskStorage._removeFile (C:\Learning\LearningPassportStrategies\node_modules\multer\storage\disk.js:61:6)
>     at remove (C:\Learning\LearningPassportStrategies\node_modules\multer\lib\make-middleware.js:64:19)
>     at handleFile (C:\Learning\LearningPassportStrategies\node_modules\multer\lib\remove-uploaded-files.js:10:5)
>     at removeUploadedFiles (C:\Learning\LearningPassportStrategies\node_modules\multer\lib\remove-uploaded-files.js:25:3)
>     at EventEmitter.<anonymous> (C:\Learning\LearningPassportStrategies\node_modules\multer\lib\make-middleware.js:67:9)
>     at EventEmitter.g (events.js:260:16)
>     at emitNone (events.js:72:20)
>     at EventEmitter.emit (events.js:166:7)
>     at EventEmitter.decrement (C:\Learning\LearningPassportStrategies\node_modules\multer\lib\counter.js:15:32)
>     at C:\Learning\LearningPassportStrategies\node_modules\multer\lib\make-middleware.js:159:25
>     at WriteStream.<anonymous> (C:\Learning\LearningPassportStrategies\node_modules\multer\storage\disk.js:43:9)
>     at emitNone (events.js:72:20)
>     at WriteStream.emit (events.js:166:7)
>     at finishMaybe (_stream_writable.js:468:14)

Appreciate your help.

```
var multer  = require('multer');

var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'C://Multer')
  },
  filename: function (req, file, cb) {
    var destinationFile = "xyz"+ "_" + file.originalname;
    console.log("Destination file is " + destinationFile);
    cb(null, destinationFile);
  }
});

var limits = {files: 5, fileSize: 1000000};
var upload = multer({storage: storage, limits: limits}).array("attachment");

module.exports = function(app, passport) {
    app.post('/posts', ensureAuthenticated, function(req, res, next) {
        upload(req, res, function(err) {
            if (err) {
                console.error("error is " + err.message + " and error code is " + err.code);
                next(err);
            } else {
                console.log("No problems.");
                res.status(204).end();
            }
        });

    });
};

// Simple route middleware to ensure user is authenticated.
function ensureAuthenticated(req, res, next) {
    if (req.isAuthenticated()) {
        return next();
    }
    res.redirect('/');
}
```

**Comment by gireeshpunathil** [comment]
@dhana-kony - is this still outstanding?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
