### ISSUE TITLE
Hi, please I can't resize my photos after uploading them

### ISSUE THREAD

**Issue by masbleIncHub** [expressjs/multer#364]
hello, I uploaded my images using multer successfully into my uploads folder, but i cannot resize it when i am rendering it on the view, i have tried using html's width and height attributes on the img tag, i have also tried using express-processimage.  The images just dont respond to resizing.  Please i need urgent help.

**Comment by gurumelo** [comment]
Can you paste your code?

**Comment by khawarali971** [comment]
well in my case i just made a class in img field and then called it in css file and set the width and height paste your code here  so people can help you

**Comment by LinusU** [comment]
Closing since you haven't responded to the people trying to help you. You need to post more info for us to be able to help you...
