### ISSUE TITLE
how to access req.body before upload

### ISSUE THREAD

**Issue by gurumelo** [expressjs/multer#365]
Hello, sorry for the question.

I need to access req.body before upload. Because there is a field with a password. is it possible? Thanks.

**Comment by LinusU** [comment]
From the documentation:

> Note that `req.body` might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

I wish I had an easy solution for you but the only thing I can recommend is to manually reorder the fields with javascript to make sure that fields are sent before files.

This has come up a number of times before, e.g. #146 where the workaround is outlined...

**Comment by gurumelo** [comment]
Thank you very much @LinusU .  Can i do that?

```
fileFilter: function (req, file, cb) {

                        //console.log(req);
    if (req.body.contrasena == "12345") {
                        if (file.mimetype !== 'image/jpeg' || file.originalname !== 'imagen.jpg') {
                                //req.fileValidationError = 'error';
                                return cb(null, false);
                        }
                        cb(null, true);
    } else {
        return cb(null, false);
    }
}
```
