### ISSUE TITLE
Install broke my nodemon server

### ISSUE THREAD

**Issue by Ankiewicz** [expressjs/multer#366]
Greetings, I didn't do a good job recording the issue.

(I do want to note prior to coding this evening, I was prompted to update ZSH: )

Installed Multer looking for a way to receive post data from an angular form. 
To much of a noob to understand the documentation on the proper way to use it.
Uninstalled Multer 
returned to my nodemon server run(removed all required tags and traces of multer from the script)
ISSUE BEGAN
Server kept crashing saying it couldn't locate multer node_module. (no mention of in packages.json, or scripts.)
Couldn't run anything because the local server kept repeating the issue.
Had to go as far as uninstall home brew, node, npm etc.. and reinstall it. 
upon reinstall of everything, npm install: cannot find nodemon, even after install.
nodemon has crashed and I can't figure out how to get it back up.
(Also, I have uninstalled ZSH and reinstalled) 

**tired of working on this moving onto try another day

**Comment by LinusU** [comment]
> Server kept crashing saying it couldn't locate multer node_module. (no mention of in packages.json, or scripts.)

Could it be that one of the dependencies that you are using, are in turn using multer and that when you removed it you broke that dependency. You should get a stack trace that indicates which file was trying to require multer.

The thing I always do when I ran into troubles like this is to remove the `node_modules` folder and then run `npm install` again. That should give you a fresh `node_modules` folder with everything needed installed.

Anyhow, this is not a problem with `multer` and I think that you will get more help if you post a question to StackOverflow where you _include the output of the error_.
