### ISSUE TITLE
Not saving to home folder (~) under Linux

### ISSUE THREAD

**Issue by sansjunk** [expressjs/multer#369]
```javascript
var multer = require('multer');
var upload = multer({
  // dest: '~/uploads/' --> Does not  work
  dest: '/home/santosh/uploads/' // --> Works
});
```
Multer actually ends up creating a folder named "~" under the app root folder.

**Comment by LinusU** [comment]
This is expected behaviour and is how all other `fs`-functions work in Node.js.

Can I recommend you to use the [untildify](https://www.npmjs.com/package/untildify) package to solve this?

```js
const multer = require('multer')
const untildify = require('untildify')

const upload = multer({
  dest: untildify('~/uploads')
})

// ...
```

**Comment by sansjunk** [comment]
@LinusU thanks. I was not aware of that.

**Comment by jpfluger** [comment]
For more info...

See this [discussion](https://github.com/nodejs/node/issues/684) which contains links to even more discussions.

Also, [untildify](https://github.com/sindresorhus/untildify/blob/master/index.js) references the home dir that will replace the tilde via the `os` module.

```javascript
const os = require('os');
const home = os.homedir();
```
