### ISSUE TITLE
[Error: Multipart: Boundary not found]

### ISSUE THREAD

**Issue by starock** [expressjs/multer#370]
I wanna post the file with AJAX. 

My JQuery code is:

```js
 $.ajax({
                    type: 'POST',
                    url: '/uploadPhoto',
                    data: $('#fileUp').attr('files'),
                    cache: false,
                    //contentType: 'multipart/form-data',  //removed
                    processData: false,
                   dataType: "text",
                    success: function(data){
                        alert(data);
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown) {
                        console.log(XMLHttpRequest.status);
                        console.log(XMLHttpRequest.readyState);
                        console.log(textStatus);
                    }
                });
```

When I was post like this, the Nodejs's console show"[Error: Multipart: Boundary not found]".

What's the problem? How can I fix it? Anybody help~~~

**Comment by LinusU** [comment]
See [this StackOverflow post](http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax) on how to make multipart uploads with jQuery.

**Comment by jaman99** [comment]
var img=document.getElementById("input-img");
            var video=document.getElementById("input-video-id-fv41");
             
               var formdata = new FormData();
               formdata.append('img',img.files[0]);
               formdata.append('video',video.files[0]);

**Comment by coucoseth** [comment]
facing this in my nodejs api, help?

**Comment by anirudh711** [comment]
Facing the same issue
