### ISSUE TITLE
Express timeout kicks in while upload is active

### ISSUE THREAD

**Issue by TomMettam** [expressjs/multer#373]
Express has a default timeout of 120 seconds.

Increasing this timeout is a security risk (a DDoS attack vector), however, this prevents large files from being uploaded with Express/Multer.

The behaviour I would expect is for Multer to automatically extend this timeout when data is received. If no data is received for $timeout seconds, it should expire.

**Comment by LinusU** [comment]
> Express has a default timeout of 120 seconds.

Are you sure? Where is this documented?

Using the timeout method on the underlying socket should yield the behavior that you are suggesting, and I think that that is the only default timeout provided...

**Comment by Simran-B** [comment]
> The number of milliseconds **of inactivity** before a socket is presumed to have timed out.

https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_timeout

Unless your upload gets stalled for 2 minutes, then I doubt that it's a socket timeout.

**Comment by LinusU** [comment]
Closing this
