### ISSUE TITLE
upload succeed but destroy user session

### ISSUE THREAD

**Issue by satriani04** [expressjs/multer#375]
hello.
i'm currently playing around with express js since last month. my app need user to be able to upload file.
and it work fine, but it destroy my session.

```javascript
var multer  =   require('multer');
var storage =   multer.diskStorage({
	destination: function (req, file, callback) {
		callback(null, './upload');
	},
	filename: function (req, file, callback) {
		callback(null, file.fieldname + '-' + Date.now()+'.png');
	}
});
```

this is my route
```javascript
var upload = multer({ storage : storage}).single('photos');
router.post('/upload', session, upload, function(req, res, next){
	res.redirect("/other-route/");
});
```
after redirect, it restarted my dev server. so..user have to login again to proceed

can anyone give me solution without breaking my session?
thankyou

**Comment by satriani04** [comment]
ahh... it's worked now.
I switch my dev server from supervisor to nodemon. it work perfectly. now it can upload without breaking my user session.

sorry to trouble you.
thank you

**Comment by LinusU** [comment]
No problem, it was probably the live reload picking up on a new file in the upload directory, and thus reloaded the server.
