### ISSUE TITLE
Get text first, validate, then decide whether to upload

### ISSUE THREAD

**Issue by PyroGreg8** [expressjs/multer#378]
Hi, I want to be able to pull in text parameters first, do some validation on them, and if the validation passes, continue on with the file upload, otherwise end the response.

I'm trying to achieve something like this but without it throwing it an error because .none() doesn't allow a file to be passed. 

```javascript
var multer = require("multer");
var app = require("express")();

app.use("/route", function(req, res, next) {

	var uploadText = multer({}).none();
	
	uploadText(req, res, function(err) {

		var input = req.body.someParam;
		if (PassesSomeValidation(input)) {
			console.log("Passed validation");
		} else {
			return res.end();
		}

		var uploadFiles = multer({}).array("file", 1);
		uploadFiles(req, res, function(err) {
			console.log("files", req.files);
		});

	});
});

app.listen(8080, function() {
	console.log("Listening");
});
```

I want to be able to do this for optimization reasons, the uploaded file could be as high as 100mb, and I don't want the user to wait all that time to upload 100mb and then get an error back because something didn't pass validation.

I would make the assumption that all text fields come first before the file data.

**Comment by LinusU** [comment]
You can sort of do this with the `fileFilter` but note that the web browser is free to send the data in any order that they see fit. Therefor multer cannot make any guarantees on wether the body data will be parsed when hitting the file or not.

Getting data before files has come up a number of times before, e.g. #146 where the workaround is outlined...

Hope this helps you to fix it, feel free to keep the discussion open, I'll be happy to answer any other questions :)

**Comment by xfsinanx** [comment]
This one works for me.

![image](https://cloud.githubusercontent.com/assets/24462877/24302622/8e2501bc-10b3-11e7-86e8-fbf08122b526.png)

**Comment by itsgracian** [comment]
please LinusU can you show us simple example. thanks.
