### ISSUE TITLE
using if statement with req.file for a single file upload

### ISSUE THREAD

**Issue by Haykinz** [expressjs/multer#379]
I have a basic web app where i want the users to be able to register with a picture upload in the form, but if they do not have a picture to upload at the current time i want to automatically set a default image that is already stored locally in uploads folder as noimage.png to be called and stored as the profile image of the user. This has been my trial but not working;

```
`if(req.files.profileimage){
        console.log('uploading File...');

        // File Info
        var profileImageOriginalName = req.files.profileimage.originalname;
        var profileImageName = req.files.profileimage.name;

        var profileImageMime = req.files.profileimage.mimetype;
        var profileImagePath = req.files.profileimage.path;
        var profileImageExt = req.files.profileimage.extension;
        var profileImageSize = req.files.profileimage.size;
    } else {
        // Set a Default Image
        var profileImageName = 'noimage.png';
    }

````
How can i use multer to handle this?

**Comment by khawarali971** [comment]
is above case working for you if you upload the image ? does it store image in database in this case ? i guess in your some thing will be undefined this profileImage  or originalnaame etc

**Comment by Haykinz** [comment]
It does not upload the picture no store it in the database. only text fields are stored in the database. i do not know why. But i want it  to upload the picture and store it in the database. Any help?

**Comment by khawarali971** [comment]
okay what i did was first middleware in app.js that 
var multer = require('multer')
app.use(multer({ dest: './tmp/'}).any());

then in my post method i did this what worked for me 

if (req.files) {
            req.files.forEach(function (profileimage) {
                var filename = (new Date).valueOf() + "-" + profileimage.originalname
                fs.rename(profileimage.path, 'public/images/' + filename, function (err) {
                    if (err) throw err;
                   }
}
}

and what you need to store in your database is path+ file name that is forexample your column name in database for image in profileimage then you just have to do this 
profileimage: '/images/' + filename

**Comment by khawarali971** [comment]
i don't know how to do else case if you find a way to handle else case do tell me

**Comment by Haykinz** [comment]
Thanks for the tip. I will work on the else case soonest. Gonna get back to you.

**Comment by LinusU** [comment]
Questions like this is probably better suited on StackOverflow, judging from the code you posted here I guess that this is your question? http://stackoverflow.com/questions/39266420/using-if-statement-with-req-file-for-a-single-file-upload

It has been answered there, closing this and lets continue the discussion on StackOverflow...
