### ISSUE TITLE
I can't get req.body

### ISSUE THREAD

**Issue by avatarr** [expressjs/multer#381]
Hi, I use multer to upload file and I want to attach other parameter in request In postman like this 

![screen shot 2559-09-01 at 17 35 45](https://cloud.githubusercontent.com/assets/1640817/18164532/9069ea76-706a-11e6-9f79-f0a640473e62.png)

my code
![screen shot 2559-09-01 at 17 34 39](https://cloud.githubusercontent.com/assets/1640817/18164510/69a8bcfa-706a-11e6-936a-0ee0227b6ddc.png)

So I can't get req.body.test_body , How do I fix this??

**Comment by LinusU** [comment]
I don't see `req.body.test_body` referred to anywhere in your code? How is it not working?

also, please post the code using fenced code blocks, that way others can copy and search the code. Like so:

    ```js
    Write code here
    ```

**Comment by avatarr** [comment]
I just use 
```js
 console.log(req.body);
```
So I see is {}

**Comment by LinusU** [comment]
Your code screenshot doesn't show how it's all called so this is impossible for me to debug. Could you provide a minimum erring test case?

**Comment by iyunusov** [comment]
if your file input element is in the top of form then every data below that gets assigned to req.body after your image is uploaded, in the result of which body remains empty while you upload photo.. So take file input element to very bottom of your form so that req.body will have data from other input elements

**Comment by bliteknight** [comment]
What solved it for me was making sure the "Content-Type" header information in postman was not set; it had been set to "application/x-www-form-urlencoded" and removing allowed me to receive the file on my backend server as well as the req.body values.

**Comment by avatarr** [comment]
I have solved and I will close this issues. sorry for last reply
