### ISSUE TITLE
there is no buffer in file

### ISSUE THREAD

**Issue by wangqianliangM** [expressjs/multer#383]
using this in my code 
`app.use(multer({ dest: './uploads/' }).single('file'));`
but req.file has no key named 'buffer'
`{ fieldname: 'file',
  originalname: 'blob',
  encoding: '7bit',
  mimetype: 'text/csv',
  destination: './uploads/',
  filename: '70bda804019bbcca4b448e6987c70bee',
  path: 'uploads/70bda804019bbcca4b448e6987c70bee',
  size: 98 }`

**Comment by iiitmahesh** [comment]
@wangqianliangM  How to buffer from uploaded text file??

**Comment by LinusU** [comment]
@iiitmahesh you can use the memory storage engine for that
