### ISSUE TITLE
req.req.file to get file?

### ISSUE THREAD

**Issue by george-norris-salesforce** [expressjs/multer#384]
inside callback..
`app.post('/upload_media', uploadHandler.single('file'), (res, {req}) => { ...`

I have to do this..
`req.req.file`
to get the file..

req is...
`ServerResponse {domain: null, _events: EventHandlers, _eventsCount: 1, _maxListeners: undefined, output: Array[0]…}`

**Comment by LinusU** [comment]
I think that you have flipped the naming of your parameters, what you are naming `req` should actually be `res`, and vice versa...

Please feel free to reopen if issue persists :)
