### ISSUE TITLE
Get file size on fileFilter function

### ISSUE THREAD

**Issue by rserentill** [expressjs/multer#385]
When implementing fileFilter function, I need to access the size of the uploaded file, but the second argument of the function (file) only has 4 fields: fieldname, originalname, encoding and mimetype, it doesn't have the 'size' field.

I need to check if the user have enought free space to upload a new file, and if the file size is larger than his/her free space in the server storage, then it should throw an error.

How can I access size filed on the file?

Or how can I set the fileSize limit dynamically?

**Comment by LinusU** [comment]
This is currently not possible since we don't know how big the file is going to be at that point...

Workaround is saving it to a temporary location first, then checking file size, then either throw it away or move it to permanent storage depending on the users free space...

**Comment by rserentill** [comment]
Thank you for your reply LinusU.

I'll do what you suggest and upload the file in a temp folder.
What would be helpul too, is to be able to pass a function (which ends returning a number) as limit.fileSize option, instead of an static value. I tried that too calculating how much free space the user has and returning it, but it didn't work.

**Comment by goatandsheep** [comment]
@rserentill  Use [k-multer](https://www.npmjs.com/package/k-multer) on top of multer

**Comment by LinusU** [comment]
What is k-multer? The readme doesn't seem to be changed at all...

**Comment by goatandsheep** [comment]
@LinusU sorry! It got renamed to [multibyr](https://github.com/smipi1/multibyr)

**Comment by Prinzhorn** [comment]
> This is currently not possible since we don't know how big the file is going to be at that point...

@LinusU do I understand this correctly that `fileFilter` does currently not have access to the actual file? I wondered, because I wanted to validate the file using https://github.com/sindresorhus/file-type . I guess I'll move that to a middleware after multer.

**Comment by LinusU** [comment]
@Prinzhorn I would recommend checking out the 2.x branch in #399, it has that library built in 🙌

**Comment by Prinzhorn** [comment]
@LinusU that's awesome! For now I have to go with something stable so I just threw a middleware in there.

```js
const fileValidator = async function(req, res, next) {
  if (!req.file) {
    return next(new Error('No file uploaded'));
  }

  try {
    const buffer = await readChunk(req.file.path, 0, 4100);
    const type = fileType(buffer);
    req.file.mimetype = type.mime;

    if (!ACCEPTED_MIME_TYPES.includes(type.mime)) {
      return next(new Error(`Rejected file of type "${type.mime}"`));
    }

    next();
  } catch (ex) {
    next(ex);
  }
};
```

**Comment by LinusU** [comment]
> since middlewares are the heart of Express I don't think multer necessarily needs a fileFilter at all

👍
