### ISSUE TITLE
Multer uploads files from time to time

### ISSUE THREAD

**Issue by austyh** [expressjs/multer#393]
Ubutu 16.04
node.js 6.5.0
Multer get files only with first upload after server starts (not always). After that it doesn't upload anything. I have tried many different settings.
Config.App.post('/pipeline/addfile/:project', multer({dest: "/home/aust/uploadd/"}).any(), this.addFile);
 req.files most of the time is []

**Comment by alexcrack** [comment]
I have the same problem.
Kubuntu 16.04
node.js 6.6.0
express.js 4.14.0
multer 1.2.0

File uploads once out of ten.

My code:
``` javascript

const upload = multer({
        storage: multer.diskStorage({
            destination: "files/",
            filename: function (req, file, cb) {
                cb(null, file.originalname + '-' + Date.now())
            }
        }),
        fileFilter: function(req, file, cb) {
            if (file.originalname.endsWith('.txt')) {
                return cb(null, true)
            }

            return cb(null, false);
        }
    });

router.post('/upload', upload.single('results_file'), (req, res, next) => {
        console.log('File uploaded', req.file);

        if (req.file) {
            Parser.parse(req.file.path);
            req.flash('upload_results', 'success');
            return res.redirect('/main');
        }

        next(new Error('Error parsing file'));
    }, (error, req, res, next) => {
        console.error('ERROR', error);
        req.flash('upload_results', 'error');
        res.redirect('/main');
    });
```

**Comment by austyh** [comment]
check you app.use code.
I was using busboy from prev code. Removing it solved my problems.

**Comment by alexcrack** [comment]
I don't use busboy or any other uploading middleware. I just first added multer to my new project.

**Comment by alexcrack** [comment]
I've found the problem. 
The http logger I've written sometimes brakes the _rawBody parameter. I've replaced it with "morgan" and now everything is fine.
