### ISSUE TITLE
Can't upload image to cloudinary

### ISSUE THREAD

**Issue by enhaster** [expressjs/multer#398]
Hello, can you please tell me, what i doing wrong, when try to upload image to cloudinary?

app.js
I don't need to store images on server, so i store it in memory.
```
var cloudinary = require('cloudinary');
cloudinary.config({ 
  cloud_name: 'hidden', 
  api_key: 'hidden', 
  api_secret: 'hidden' 
});
var multer  = require('multer');
var storage = multer.memoryStorage()
var upload = multer({ storage: storage })
```

Site form (jade/pug)
```
form(action="/?_csrf="+csrfToken method="post" enctype='multipart/form-data')
	input(type="file" name="avatar")
	input(type="submit" value="upload")
```

App post
```
app.post('/', upload.single('avatar'), function(req, res, next){ 
  
  console.log('Should be undefined:', req.file.path);  //yes
  console.log('Should be the buffer:', req.file.buffer);  //yes
  cloudinary.uploader.upload(req.file.path, function(result) { console.log(result) });
//req.file.buffer is not working to, its give error - file.match is not a function
});
```

and i get error
```
{ error: { message: 'Missing required parameter - file', http_code: 400 } }
```

**Comment by enhaster** [comment]
i find out how (just use Datauri):
var dUri = new Datauri();
dUri.format(path.extname('TEST').toString(), req.file.buffer);

cloudinary.uploader.upload(dUri.content, function (err, result) {
  if (err) {
    console.log(err);
  } else {
    console.log(result);
  }
});

**Comment by ppmakeitcount** [comment]
Hey. I am having similar problem. I am trying to submit few images from html form to node server. and then i push them on cloudinary. But it not happening. can you help me out here. @enhaster

**Comment by srinath-patel** [comment]
same problem can anybody provide a complete code. it would really make my day

**Comment by adeelibr** [comment]
`let upload = multer({ 
  // storage: multer.memoryStorage() 
});`

`const file = req.files[0];

    // For documentation refer the following link
    // https://cloudinary.com/documentation/node_image_upload
    cloudinary.v2.uploader
      .upload_stream({ resource_type: 'raw' }, (error, result) => { 
        console.log(result) 
      })
      .end(file.buffer);`
