### ISSUE TITLE
Add mimetype to `req.file`

### ISSUE THREAD

**Issue by niftylettuce** [expressjs/multer#403]
`req.file.mimetype = mime.lookup(req.file.originalName);`

I added this in my use-case but I thought it might be cool to have, what do you think of this feature?

**Comment by gireeshpunathil** [comment]
@niftylettuce - is this still an issue ?

**Comment by jonchurch** [comment]
There is a mimetype property on the file object already. Closing this as resolved, unless you can clarify how this would be different from the existing property?
