### ISSUE TITLE
Stop upload for all files when validation fails

### ISSUE THREAD

**Issue by laics1984** [expressjs/multer#407]
Hi, i know we can use filefilter to validate a file. However i would want multer to stop uploading all file all together when any of the files doesnt pass validation. Is there a way to do it? like validating all the files then only atart uploading it? filefilter doesnt serve this purpose.

Thanks.

**Comment by LinusU** [comment]
If you call the callback `cb` with an error as the first parameter, that will stop all file uploading and return the error to the next middleware/route-handler. Does that work for you?

**Comment by laics1984** [comment]
can you show me how it works? Is it the callback for filterfile?

**Comment by LinusU** [comment]
```js
fileFilter: function (req, file, cb) {
  cb(new Error('I don\'t want your files!'))
}
```

**Comment by laics1984** [comment]
@LinusU , how can i pass through res.json instead of cb? i would like t return the error in res.json via express route.

**Comment by LinusU** [comment]
You can find instructions under "Error handling" https://github.com/expressjs/multer#error-handling

Please tell me if it helps :)

**Comment by laics1984** [comment]
Hi @LinusU I hv tried this by replacing return with res.json. however there saw that other files still being uploaded even though error is returned.

**Comment by laics1984** [comment]
@LinusU i have tried the method above   **cb(new Error('I don\'t want your files!'))**
but what it returns is:  **{storageErrors: []}**

**Comment by laics1984** [comment]
Hi @LinusU , i am able to get the error message to display. It is working fine now. But i have one more issue, noticed that it only works if there is a file to upload since all my validation is in filefilter. May i khow how to validate if user upload a file? as the filefilter will only work if there is a value in input[type="file"]. Thanks.

**Comment by ryhinchey** [comment]
> May i khow how to validate if user upload a file? as the filefilter will only work if there is a value in input[type="file"]. Thanks.

@laics1984  multer will add a `file` or `files` property to the http `req` object. See documentation [here](https://github.com/expressjs/multer#usage).  Checking the presence of this field should let you know if a user intended to upload a file.

I'm going to go ahead and close this issue for now.  Thanks!

**Comment by mahmoodfathy** [comment]
@LinusU  @ryhinchey  i am facing a similar problem where i want to prevent the upload if the username update failed, this seems not possible , i dont want any files uploaded to my bucket if any update failes eg. duplicate keys of username in my db , this is the code reference :https://stackoverflow.com/questions/64155106/stop-image-upload-to-s3-if-username-update-fails-in-multer-s3
, i tried everything and seems not to work , feeling kinda stuck here
