### ISSUE TITLE
Silently ignore files

### ISSUE THREAD

**Issue by qwemaze** [expressjs/multer#409]
I'm always sending data to server using FormData, but it's usually text fields, so I need one global text only parser, and an ability to explicitly define file handling on some routes.

I see there's ```.none()```, but it throws an exception, so no further processing is possible.

**Comment by LinusU** [comment]
You could use `.any()` to accept any files, but the first parser will have already consumed the stream so that your second handler, the one that you want the handle the files, will have nothing to work on...

I think this has been discussed before, with a workaround proposed...

**Comment by qwemaze** [comment]
@LinusU Yeah, I thought about this kind of workaround. It can work if I'll define ```dest``` as ```os.tmpdir()```, and will move files in discrete handlers, but it's kind of dirty. Was hoping for a cleaner solution.

Could it be made so if parser is set to consume only text fields it will consume them and if non-text received it'll be moved to another stream (will create extra readable stream from not consumed fields) for further processing? Just trying to figure out if it's even possible :)

**Comment by LinusU** [comment]
Maybe the beta of 2.x would suit you: #399. Nothing is set in stone yet, but currently it works by creating temporary files and then passes a stream that you can use later. You could then mount an `.any()` handler on the entire app, and then handle the streams in the specific endpoints.
