### ISSUE TITLE
Drop support for node < 4 

### ISSUE THREAD

**Issue by jimmywarting** [expressjs/multer#414]

**Comment by LinusU** [comment]
Node.js 0.12 is officially support until the end of the year, I would like to continue the support in multer til at least then. What are the current drawbacks of supporting 0.10 and 0.12?

**Comment by jimmywarting** [comment]
More dependencies eg like object.assign

**Comment by jimmywarting** [comment]
How about now?

**Comment by LinusU** [comment]
It's dropped in the 2.x branch, see #399

**Comment by jonchurch** [comment]
Closing as this is underway and there's not much more to add.
