### ISSUE TITLE
Missing __proto__ object in req.body

### ISSUE THREAD

**Issue by gkipnis** [expressjs/multer#415]
The 'req.body' object, that is created for the text fields in the multi-part form, does not contain __proto__ object and thus does not contain standard javascript object functions. In particular 'hasOwnProperty' of 'req.body' does not exist. A call such as 'req.body.hasOwnProperty' results in a failure. 

A workaround such us 'Object.prototype.hasOwnProperty.call(req.body, 'field_name') can be used, but since 'req.body' should be a standard javascript object, I believe it should have all properties of standard javascript objects.

Same is true for 'req.files'

**Comment by LinusU** [comment]
This is done intentionally, see expressjs/discussions#25

**Comment by gkipnis** [comment]
This implementation decision should be documented in multer Usage examples. Every new multer user will look at the Usage examples before integrating multer in the code.

**Comment by LinusU** [comment]
Yes, that would be very nice 👍 

PR welcome :)
