### ISSUE TITLE
Cant install multer 

### ISSUE THREAD

**Issue by bujardeari** [expressjs/multer#423]
When i try to install multer with npm-install --save multer i get an error saying :
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Comment by LinusU** [comment]
That is not an error, it's just a warning. It shouldn't prevent you from installing and using multer...

**Comment by LinusU** [comment]
Would be nice to know why chokidar/fsevents is being installed though...

**Comment by bujardeari** [comment]
You were right multer was installed , but i dont know why chokidar/fsevents is beeing installed, i only tried to install multer with npm install --save multer

**Comment by jonchurch** [comment]
Closing as resolved
