### ISSUE TITLE
onFileUploadComplete not called

### ISSUE THREAD

**Issue by mirwaleed** [expressjs/multer#425]
`var upload = multer({fileFilter:fileFilter,limits:limits,storage: storage,onFileUploadComplete:function (file){console.log('===)))))')}}).single('userPhoto');
`
here is where i m calling that function

**Comment by LinusU** [comment]
There is no `onFileUploadComplete` function anymore. The files will all be fully uploaded once the middleware has completed, and your route is called. Happy hacking :)
