### ISSUE TITLE
Filter file size dynamically

### ISSUE THREAD

**Issue by RobbertWolfs** [expressjs/multer#427]
Is it possible to filter the file size dynamically? Depending on the extension of the uploaded file?

**Comment by LinusU** [comment]
Not at the moment :(

**Comment by RobbertWolfs** [comment]
@LinusU Too bad.. Would be a great feature 👍

**Comment by LinusU** [comment]
Yes, pull requests welcome 🙌

**Comment by jonchurch** [comment]
Closing as resolved
