### ISSUE TITLE
Setting upload to any ignores all files

### ISSUE THREAD

**Issue by pedroabreu** [expressjs/multer#435]
I'm not sure what's going on but if I set multer in an endpoint with `.any()`, I get the req.file empty, while if I change to `.single('file')` I can write the file in my server.

This is my conf:

```
const multer = require('multer')
const upload = multer({ dest: './uploads/'})

...

app.post("/upload", upload.single('file'), function(req, res) {
    if (req.file) {
         console.dir(req.file);
         return res.end('Thank you for the file');
    }
    
    res.end('Missing file');
})
```

I'm using express 4.13.4 and multer 1.2.1. Any idea why I get undefined while using `upload.any()` ?

**Comment by LinusU** [comment]
`.any()` populates `files` (not the extra s) instead of `file` :)
