### ISSUE TITLE
Field value too long

### ISSUE THREAD

**Issue by thanhthang20** [expressjs/multer#436]
![screen shot 2016-12-28 at 10 44 36 am](https://cloud.githubusercontent.com/assets/5382700/21513411/c045baea-ccea-11e6-92f7-b46c29e2f031.png)

```
var formData = new FormData();
formData.append('text', myData);
```

'myData' content is rich text data (text + image in base64) around 15mb is encoded as multipart

**Comment by LinusU** [comment]
Increase the field data limit using the `limits` option:

```js
multer({
  limits: { fieldSize: 25 * 1024 * 1024 }
})
```

**Comment by ubershmekel** [comment]
If anyone arrives here after seeing this error and wonders how to intercept it http://expressjs.com/en/guide/error-handling.html states to use:

```
app.use(function (err, req, res, next) {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

**Comment by creightontaylor** [comment]
> Increase the field data limit using the `limits` option:
> 
> ```js
> multer({
>   limits: { fieldSize: 25 * 1024 * 1024 }
> })
> ```

where does this go?

**Comment by bytegrains** [comment]
> where does this go?

@creightontaylor 
When you initialize Multer upload function
`var upload = multer({ storage: storage,limits:{fieldSize: 25 * 1024 * 1024} });`

**Comment by squivix** [comment]
What is the difference between `fieldSize` and `fileSize`?

**Comment by jcarlosabc** [comment]
> ¿ Cuál es la diferencia entre `fieldSize`y `fileSize`?

fields seria para campo
y el file para archivos bro

**Comment by JoeBrar** [comment]
> Increase the field data limit using the `limits` option:
> 
> ```js
> multer({
>   limits: { fieldSize: 25 * 1024 * 1024 }
> })
> ```

This works. The default upload limit in multer is around 1 MB. So if you want to send more data you have to increase the limits. 25 * 1024 * 1024 (in bytes) will give you around 25 MB.
