### ISSUE TITLE
multer issue with os.tmpdir()

### ISSUE THREAD

**Issue by lkashyap4th** [expressjs/multer#437]
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by edgesoft** [comment]
@lkashyap4th Where do you see this issue? can't see anywhere in the codebase that multer uses this.

**Comment by jonchurch** [comment]
I also can't find `tmpDir` anywhere in the codebase. Possibly an older version used it? But I can't find that in any blames. Closing as resolved.
