### ISSUE TITLE
Extending a storage

### ISSUE THREAD

**Issue by SamiSammour** [expressjs/multer#441]
Why is the defined storage in multer are not exported as class, what if I want to extend one to add a tiny feature I want? Why should I rewrite the whole class again??

**Comment by LinusU** [comment]
Storage engines are probably going away in the next major version (see #399) so I don't see this as bing a long term issue. To work around it for now you could do something like:

```
function createMyStorage () {
  const diskStorage = multer.diskStorage()

  return {
    _handleFile (req, file, cb) {
      // do your own stuff

      return diskStorage._handleFile(req, file, cb)
    },
    _removeFile (req, file, cb) {
      return diskStorage._removeFile(req, file, cb)
    }
  }
}
```

**Comment by SamiSammour** [comment]
Thanks dude, this solution worked with perfectly
