### ISSUE TITLE
How to check all filenames before uploading multiple files?

### ISSUE THREAD

**Issue by ghost** [expressjs/multer#444]
Hello guys,

in my application the user has to select up to 3 files for uploading:

`app.post('/files', upload.fields([{ name: 'file1', maxCount: 1},
			{ name: 'file2', maxCount: 1},
			{ name: 'file3', maxCount: 1}]), function(req,res){`

If the user clicks the submit button and the function is called, all files get uploaded immediately. But for my application i have to check the filenames before the files are uploaded to the server. If there is something "wrong" (meaning: the filename already exists in my database) with at least ONE filename, NO files should be uploaded.

I tried the fileFilter option, but this only works for a single file. 

`	fileFilter: function(req,files,cb){
	console.log(files);
	cb(null, false);
	}`

I can check the filenames after uploading and maybe delete them, but i don't think that's the best solution (obviously).

Do you guys have an idea to make this somehow possible for multiple files? I appreciate your help, and i'm sorry if i missed something here. 

Thanks.

**Comment by HarshithaKP** [comment]
Hi, please try the below code with fileFilter condition check, it should work.

const fileFilter = (req, files, cb) => {
        //Condition to check the file names 
            //If condition       
               cb(null, true);
           //Else
               cb(null, false);

  };
  const upload = multer({ fileFilter }).array('file',3);
  app.post('/', upload, (req, res) => {
         console.log('Done!!!');
 });

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
