### ISSUE TITLE
Multer file collisions?

### ISSUE THREAD

**Issue by kevin-daniel-hunt** [expressjs/multer#448]
So I could be wrong, and though a collision is very very unlikely, isn't it possible that when using disk storage, multer can cause files to collide and perhaps overrite the only one?

`function getFilename (req, file, cb) {
  crypto.pseudoRandomBytes(16, function (err, raw) {
    cb(err, err ? undefined : raw.toString('hex'))
  })
}`

All it seems to be doing is generating a random 16 byte string to store the file under.  It doesn't appear to be checking to see if that file exists.

I understand if this is intended, and it should be up to the end-user to move a file after upload and rename, but if this is not made clear and someone is using database for file association and relying on multer to produice "Unique" filenames, this could end in tragedy.

**Comment by LinusU** [comment]
This is true, and it's fixed in #399. But...

For there to be a one in a billion chance of duplication, 103 trillion files must be uploaded

**Comment by MagnumDopus** [comment]
I totally understand the unlikely nature of collisions, I don't mean to imply they would happen often.  Also after sifting through that thread I am failing to find where the fix for that is?  I only ask because in order for my company to use a multer-only solution (and obviously there are a ton of stop-gaps to address this, its in no way blocking) I would need to be certain no collisions could occur.  I would assume this fix is not pushed to a release yet?

**Comment by davidmashe** [comment]
This issue seems old and stale. Closing.

**Comment by techwithanirudh** [comment]
This code might help
`function file2Number(filepath, number) {
	const seperator = '-';
		
	let dir = path.dirname(filepath);
	let ext = path.extname(filepath);
	let base = path.basename(filepath, ext);

	let append = seperator + number;

	const filename = path.join(dir, base + append + ext);

	return filename;
}

const storage = multer.diskStorage(
    {
        destination: './uploads/',
        filename: function ( req, file, cb ) {
            //req.body is empty...
			var filename = file.originalname
			var count = 1;
			var filepath = __dirname + '/uploads/' + filename
			while (fs.existsSync(filepath)) {
				var filename = file2Number(filename, count)
				var filepath = __dirname + '/uploads/' + filename
				count += 1;
			} 
            cb( null, filename );
			
        }
    }
);
const upload = multer({ storage: storage });
`
