### ISSUE TITLE
Can't upload if I use "npm script"

### ISSUE THREAD

**Issue by ycjcl868** [expressjs/multer#449]
![image](https://cloud.githubusercontent.com/assets/13595509/22238473/85aa6382-e24c-11e6-938b-d39585270a18.png)
![image](https://cloud.githubusercontent.com/assets/13595509/22238478/8cdc3ff4-e24c-11e6-8453-48d554a6ffb9.png)

**Comment by gireeshpunathil** [comment]
@ycjcl868  - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
