### ISSUE TITLE
File gets overwritten in case of name conflict

### ISSUE THREAD

**Issue by bugwheels94** [expressjs/multer#452]
I want to store files with original names but then when two files come of same name, the former one gets overwritten. I don't want to append all the names with some random text, so am I missing something like some error that gets thrown in conflicts so I can handle this case and do something accordingly in case of conflicts like renaming the file or showing the warning to user.

**Comment by gireeshpunathil** [comment]
@bugwheels94 - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
