### ISSUE TITLE
{"code":"LIMIT_UNEXPECTED_FILE","field":"file","storageErrors":[]} for single file

### ISSUE THREAD

**Issue by biplabmalakar** [expressjs/multer#454]
I am new in nodejs, i am trying to upload single image, but whenever i try it will throw errror: 
`{"code":"LIMIT_UNEXPECTED_FILE","field":"file","storageErrors":[]}` and my code given below

```js
var storage = multer.diskStorage({
	destination: (req,file,cb)=> {
		cb(null,'public/images/');
	},
	filename: (req,file,cb)=> {
		cb(null, Date.now() + file.originalname);
	}
});
var upload = multer({
	storage: storage,
	fileFilter: (req,file,cb)=> {
		console.log('In File Filter');
			let ext = path.extname(file.originalname);
			if(ext == '.jpg' || ext == '.png' || ext == '.gif' || ext == '.jpeg') {
				console.log('Extension Check');
				cb(null,true);
			}
			else {
				cb('Only Images Are Allow', false);
			}
	}
}).single('biplab');

router.post('/image',function(req,res){
	upload(req,res,function(err){
		if(err) res.send(err);
		else res.send('Image Successfully Uploaded');
	})
})
```

and i request from a basic html page.

**Comment by mariohmol** [comment]
Same issue here, could u figure it out?

**Comment by LinusU** [comment]
Yeah it's probably the same problem, @biplabmalakar could you look into #159 and see if that solves it for you, otherwise post your html page and I will help you out further...

**Comment by kunalp-scalex** [comment]
Still getting error : {
"code": "LIMIT_UNEXPECTED_FILE",
"field": "file",
"storageErrors": []
}.

Below is my code-

knowledgeHubRoute.post('/upload_image', upload.single('upload'), (req, res) => {
try {
res.status(200).send('Image Uploaded Successfully');
} catch (error) {
res.status(400).send({
message: error.message,
});
}
});

import { CONFIG } from '../config';
import { s3 } from '../aws-sdk/s3/index';
import multer from 'multer';
import multerS3 from 'multer-s3';
const bucket = CONFIG.AWS.AWS_BUCKET_NAME;
const upload = multer({
storage: multerS3({
s3: s3,
bucket,
acl: 'public-read',
metadata: function (req, file, cb) {
cb(null, { fieldName: file.fieldname });
},
contentType: multerS3.AUTO_CONTENT_TYPE,
key: function (req, file, cb) {
var newFileName = Date.now() + '-' + file.originalname;
var fullPath = 'knowledge_hub/media/' + newFileName;
cb(null, fullPath); // Use a unique filename or any other logic you prefer
},
}),
});

module.exports = upload;

3) From postman I am sending request:
![image](https://github.com/expressjs/multer/assets/114995211/673cf432-dda2-4591-adda-62493cd97479)

**Comment by tim5chneider** [comment]
In Postman the Key should be "file" not "upload"!
