### ISSUE TITLE
do I have to specify field name in upload.fields?

### ISSUE THREAD

**Issue by kiwenlau** [expressjs/multer#458]
I want to upload multiple files with random field name

```
curl http://localhost:5050/upload \
     -X POST \
     a=@china.txt \
     b=@america.txt \
     c=@england.txt
```

When I don't specify "a", "b" and "c" in upload.fields, I will get "Error: Unexpected field".

Note that the field name is random and the number of fields can not be determined. So it is impossible to define field name in upload.fields.

Do I have to specify field name? How can I solve this problem?

**Comment by LinusU** [comment]
You can use `.any()`, be sure to handle all the files though :)

https://github.com/expressjs/multer#any

**Comment by kiwenlau** [comment]
Works like a charm! Thank you!

**Comment by mjdude** [comment]
I had the exact same problem using multer to parse incoming emails with attachments. using .any solved the problem. Thank you.

**Comment by krzkaczor** [comment]
In case you just copied that curl command and wonder why it doesn't work — it's missing -F switch.
