### ISSUE TITLE
connection timeout with FTPstorage 

### ISSUE THREAD

**Issue by nitrothejello** [expressjs/multer#460]
I use the FTPstorage module https://github.com/hnrch02/multer-ftp,  but I wont get response until connection timeout.
`var ftpStorage = new FTPstorage({
host: host,
secure: false,
.......
});`
`var upload= multer({storage:ftpStorage});`

and when I use :
`upload(req, res, function(err){
// do something with req.files
})`
the callback function never executes

**Comment by gireeshpunathil** [comment]
@nitrothejello  - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
