### ISSUE TITLE
req.body appears empty half the time

### ISSUE THREAD

**Issue by Zyphxion** [expressjs/multer#461]
I'm having an issue with multer that has stumped me for a few days.  Half the time, everything works as expected and flawlessly, and the other half of the time req.body is an empty object and req.file is undefined.

Here's what my setup looks like:

Frontend:

      const source = {uri: image.path, isStatic: true, type: image.mime, name: image.path.split("/").pop()};
      const xhr = new XMLHttpRequest();
      let formData = new FormData();
      formData.append('userId', userId);
      formData.append('file', source);
  
      xhr.onreadystatechange = () => {
        if (xhr.readyState === xhr.DONE) {
          if (xhr.status >= 400) {
            alert(xhr.responseText);
          } else {
            const response = JSON.parse(xhr.response);
            if (response.success) {
              //success handler
            } else {
              //failure handler
            }
          }
        }
      };
      xhr.open('POST', `${ROOT_URL}/api/user/profile_photo`);
      xhr.send(formData);

The image object used in source is being supplied by a React Native module that selects and crops images.

My route:

        const multer = require('multer');
        const upload = multer().single('file');

        module.exports = function(app) {
          app.post('/api/user/profile_photo', upload, User.updateProfilePhoto);
        }

And Express endpoint:

        exports.updateProfilePhoto = function(req, res, next) {
          const _id = req.body.userId;
          const file = req.file;

          console.log("file", req.file);
          console.log("body", req.body);

          //S3 upload and other things
        }

I can't for the life of me figure out what's going wrong?  It's a pretty simple setup.  I thought maybe it was a conflict with bodyParser but having tested it without bodyParser it still only works half of the time.

Any insight?  I'm using v1.3.0 of multer

**Comment by markusekblad** [comment]
@Zyphxion Have you figured anything out? It sounds a lot like my issue. https://github.com/expressjs/multer/issues/462 Can you check if it is the same?

**Comment by robcalcroft** [comment]
I've found adding `enctype="multipart/form-data"` to the form seems to stop multer returning an empty `req.body`

**Comment by joaocrq** [comment]
I had a similar issue and it worked following [this solution](http://stackoverflow.com/questions/39589022/node-js-multer-and-req-body-empty).

It appears that `req.body` is only fulfilled after file uploaded, like so:

```javascript
async createSlide(req, res, next) {
  try {
    // req.body is empty here
    await this.uploadSingle('image')(req, res); // this is: pify(multer({dest: 'uploads/').single(fieldname));

    // req.body is ok
    let slide = new Slide(req.body);

    slide.image = {
      mimetype: req.file.mimetype,
      path: req.file.path
    };

    await slide.save();

    return res.json(slide);
  }
  catch (err) {
    next(err);
  }
}
```

Not sure why this works but anyway it's a workaround for now... Hope it helps you!

**Comment by dman777** [comment]
Are you sure it's not this? 

> Note that req.body might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

I resolved my issue by reversing the order of my form object properties in the front end:

```javascript
        var newFormObj  = new FormData();
        newFormObj.append('internalUserID', internalUserID);
        newFormObj.append('listingImage', this.binaryImages[image]);
```

**Comment by joaocrq** [comment]
Thanks for explaining why!

**Comment by microacup** [comment]
Unfortunately，it is a bug. Because multer listener expect order is `field -> file`. But in fact, parallel cause it is random.

**Comment by axelpale** [comment]
I experienced a bit similar behaviour due to heavy write frequency. The setup: a client tried to upload a file with `request` module and the server tried to serve the upload with `multer`. On the client side, the file was under heavy rewrites so sometimes the uploaded file ended to be empty. On the server side this caused `multer` to happily accept the file. However `req.file.buffer` was empty array (not even a buffer) and blew things up.

**Comment by LinusU** [comment]
> was empty array (not even a buffer)

This should never happen, would you mind providing a minimal test case that shows this behaviour?

**Comment by axelpale** [comment]
@LinusU Hi! By looking the source of [MemoryStorage](https://github.com/expressjs/multer/blob/master/storage/memory.js) and its dependency [concat-stream](https://github.com/maxogden/concat-stream/blob/master/index.js) it surprisingly becomes somewhat clear that `concat-stream` can return a non-buffer empty array when encoding is not explicitly set to `buffer` and the stream is empty. Furthermore, it seems to happen that Multer does **not** explicitly set that, forcing `concat-stream` to try infer the encoding.

I suppose that Multer's `memory.js` should replace the following line:

    file.stream.pipe(concat(function (data) {

with this:

    file.stream.pipe(concat({ encoding: 'buffer' }, function (data) {

This is somewhat off-topic so should we open a dedicated issue? Any thoughts?

**Comment by jonchurch** [comment]
_An_ issue was resolved from this, but it's not clear if it fixes the original issue in this thread.

The original issue is pretty old by now though, I'm keeping this open for now but if no one has anything else to add I think it should be closed. (I have not tried to reproduce this issue as the provided code looks 👍 to me)

**Comment by JacobT14** [comment]
> Are you sure it's not this?
> 
> > Note that req.body might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.
> 
> I resolved my issue by reversing the order of my form object properties in the front end:
> 
> ```js
>         var newFormObj  = new FormData();
>         newFormObj.append('internalUserID', internalUserID);
>         newFormObj.append('listingImage', this.binaryImages[image]);
> ```

Order definitely mattered for me! Thanks!

**Comment by UlisesGascon** [comment]
@jonchurch  I believe that we can consider this issue closed, but if needed I can reopen it.
