### ISSUE TITLE
Angular 2 / Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by kamalkech** [expressjs/multer#464]
**Component**

`
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';

@Component({
  selector: 'app-upload',
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.css'],
})
export class UploadComponent implements OnInit {
  filesToUpload: Array<File> = [];

  constructor(private http: Http) {}

  ngOnInit() {}
  
  upload() {
    const formData: any = new FormData();
    const files: Array<File> = this.filesToUpload;

    formData.append("uploads[]", files[0], files[0]['name']);
    
    this.http.post('http://localhost:4200/upload-file', formData)
      .map(files => files.json())
      .subscribe(files => console.log('files', files))
  }

  fileChangeEvent(fileInput: any) {
    this.filesToUpload = <Array<File>>fileInput.target.files;
    //this.product.photo = fileInput.target.files[0]['name'];
  }

}

`

**Server.ts**

`
var multer  = require('multer')
var upload = multer({ dest: 'uploads/' })

app.get('*', function (req: any, res: any) {
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, PATCH, DELETE, OPTIONS');
  
  const pojo = {status: 404, message: 'No Content'};
  const json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});

// Upload file
app.post('/upload-file', upload.array(), function (req, res, next) {
  console.log(req.body)
})

`

**I get this error :** 
TypeError: Cannot read property 'on' of undefined
    at new Multipart (C:\Projets\Angular\ung-universal\node_modules\busboy\lib\types\multipart.js:106:5)
    at Multipart (C:\Projets\Angular\ung-universal\node_modules\busboy\lib\types\multipart.js:26:12)
    at Busboy.parseHeaders (C:\Projets\Angular\ung-universal\node_modules\busboy\lib\main.js:71:22)
    at new Busboy (C:\Projets\Angular\ung-universal\node_modules\busboy\lib\main.js:22:10)
    at multerMiddleware (C:\Projets\Angular\ung-universal\node_modules\multer\lib\make-middleware.js:33:16)

Any dea ?

**Comment by kevinlllR** [comment]
Friend can solve it, but it seems a bit tedious to do it by hand, you just have to modify the lines uqe marks you with part.on or this.parser.on, I hope another solution because doing it every time it is installed is tedious.

**Comment by kevinlllR** [comment]
Friend can solve it, but it seems a little tedious to do it by hand, you just have to modify the lines that you mark with part.on or this.parser.on, I hope another solution because doing it every time it is installed is tedious.

**Comment by LinusU** [comment]
I don't think it's related to usage of Angular, but rather a bug in busboy, see #468
