### ISSUE TITLE
Checking some form data constraints before uploading. 

### ISSUE THREAD

**Issue by radwasherif** [expressjs/multer#465]
I basically want to validate some form data (e.g. certain fields are not empty, some input is in certain format.. etc.) before actually uploading the files. 

What happens is that if I place a callback before the upload, `req.body` is empty. 

Anyone solutions/workarounds for this?

**Comment by LinusU** [comment]
From the documentation:

> Note that `req.body` might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

As you can see in your request payload, the file is sent before the `classId` field, and thus there is no way for multer to know about `classId` when it's handling the file.

I wish I had an easy solution for you but the only thing I can recommend is to manually reorder the fields with javascript to make sure that fields are sent before files.

This has come up a number of times before, e.g. #322 and #146 where the workaround is outlined...
