### ISSUE TITLE
diskStorage/memoryStorage based on ContentType

### ISSUE THREAD

**Issue by xgvargas** [expressjs/multer#466]
Hello,

Based on current documentation I couldn't find a way to select storage based on file content.

My current project needs to use a single endpoint to receive files, if `image/jpg` then I want them saved to specific directory, if `appication/json` I just want its content for processing.

Yes, I know I can use diskStorage only, let multer save both files and then delete the json file after processing it. But I was wondering if I could simple use a different Storage system for each file.

I tried this:

```coffee
# coffee-script, sorry... :)

image = multer
    storage: multer.diskStorage
        filename: (req, file, cb) -> cb null, file.originalname
        destination: (req, file, cb) -> cb null, '/var/www/azm-media/'

fjson = multer {storage: multer.memoryStorage()}

route.post '/', image.single('image'), fjson.single('data'), (req, res) ->
    if req.is 'multipart'
        if req.image?.mimetype is 'image/jpg'
            return res.status(200).json {_err: null, message: 'image received'}

        if req.data?.mimetype is 'application/json'
            doProcess req.data.buffer.toString(), ->
                return res.status(200).json {_err: null, message: 'data processed.'}
            return

        return res.status(422).json {_err: 'Invalid format'}
    return res.status(422).json {_err: 'Invalid'}
```

This fails due to the use of `single`. And I could not figure out what combination of multer functions could work here.

Any tip will be welcome!

**Comment by gireeshpunathil** [comment]
@xgvargas - is this still an issue for you?

**Comment by xgvargas** [comment]
No, this was a long time ago, I guess we could close it. I mean, I was not able to accomplish what I intended, since I remember I ended using `diskStorage` for both file types. Not ideal but worked! Thanks!
