### ISSUE TITLE
 You can not find the property 'on' multer, in busboy

### ISSUE THREAD

**Issue by kevinlllR** [expressjs/multer#468]
Hello, this may not have much to do with multer itself, but install multer npm install -S multer, I followed the example steps and I left that error, I went to the source code and saw several

Nested part.on
```
//busboy/lib/types/multipart.js  line 279 ,286,etc,etc
part.on ('errror', function () {...}).on....
```
change to:
```
part.on('error',function(){});
part.on('finish',function(){});
```
`this.parser.on('error',function(){}).on...`

And so on, change the .on by part.on, and I solve the problem, does anyone know why this type of error is due? , Because it is tedious to do the same changes every time I have to install the module, use node 6.9.5, npm 3.10.8, and using universal angular for the job.

**Comment by LinusU** [comment]
Could you report this to busboy and link to this bug report? :)

**Comment by kevinlllR** [comment]
Hi, if I do, I'm a little new at this, how should I report it?

**Comment by LinusU** [comment]
Just as reported to this repo, but here: https://github.com/mscdex/busboy

**Comment by jonchurch** [comment]
Not sure if this is still an issue? This doesn't seem to have been reported to busboy, but I don't really understand the issue myself. If anyone else ends up here with the same problem, please do report it to busboy.

Will keep open for a little longer, pending more info.

**Comment by ryhinchey** [comment]
going to close this as it's been a few months and no more info has been provided
