### ISSUE TITLE
Multer not parsing the form data. Always shows undefined

### ISSUE THREAD

**Issue by kirtanshetty** [expressjs/multer#472]
I am getting all three fields body, file and files as undefined no matter what I do .. Please can anyone tell me what am I doing wrong.

```
var express = require("express");
var app = express();
var multer = require('multer');

var upload = multer({
  dest: 'images/',
});

app.post('/uploadchq', upload.single('file'), function(req, res, next) {
  console.log("file", req.file);
  console.log("files", req.files);
  console.log("body", req.body);
  next();
  res.sendStatus(200);
});

app.listen(9999);
console.log("listening to port", 9999);
```

This is another way in which I tried but it is still undefined.

```
var express = require("express");
var app = express();
var multer = require('multer');

var storage = multer.diskStorage({
  destination: function(req, file, cb){
    console.log("destination");
    var dest = 'images/';
    cb(null, dest);
  }
});

app.post('/uploadchq', upload.fields([{ name: 'file' }]), function(req, res, next) {
  console.dir("file", req.file);
  console.log("files", req.files);
  console.log("body", req.body);
  res.sendStatus(200);
});

app.listen(9999);
console.log("listening to port", 9999);
```

**Comment by LinusU** [comment]
How are you posting to the server? Are you using `enctype="multipart/form-data"` on your form?

**Comment by kirtanshetty** [comment]
@LinusU ... hey, it got resolved when i remove the content type ... thanks 👍

**Comment by LinusU** [comment]
No problem 👍

**Comment by jyjin** [comment]
@LinusU @kirtanshetty   Why I have set the contentType to "multipart/form-data", but I still got file undefined in my server code;

I use the FormData Object posting my data like this:

`      var formData = new FormData();
        formData.append('remark','this is the text file')
        formData.append('license',this.state.file);`

**Comment by LinusU** [comment]
`formData.append('key', 'value')` adds a text field, not a file. It will be available on `req.body` (e.g. `req.body.key === 'value'`

**Comment by jyjin** [comment]
But I need to upload a file by FormData, that file is a file data of one file-input .So how can I upload a file ？

**Comment by leviwheatcroft** [comment]
@LinusU formData.append can add files / blobs to the formData. It's working for me. https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

**Comment by musmanalibaloch** [comment]
https://github.com/musmanalibaloch/express-form-data, Use this example, it uses firebase cloud function and firebase storage to upload file but you can use it for anything , it uses `express-multipart-file-parser` and works like charm the above link just works perfectly,I tested this code and pushed it to repo for you guys.Just add your configuration and there you go.Cheers.

**Comment by a-box31** [comment]
Make sure you are targeting the right value in the HTML/react code. If you are using React, the `onChange` property should set the state variable to `setVariableFunction(e.target.files[0])`

**Comment by jyjin** [comment]
邮件我已收到，谢谢！
