### ISSUE TITLE
upload one file but get two and one is good, another is broken 

### ISSUE THREAD

**Issue by TomasPangzi** [expressjs/multer#477]
I upload one file,
I got two file in the server,
one of them is ok to be open,
another is broken,
I console the `req.files`
the info show that the filename is the broken one

**Comment by LinusU** [comment]
I need some more information to be able to reproduce this, can you supply a minimal test case that shows this behaviour?

**Comment by TomasPangzi** [comment]
this is my code
`var multer = require('multer')
var config = require('../config')
var fs     = require('fs')
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        var destPath = config.uploadFile
        fs.stat(destPath, (error) => {
            if (error) {
                fs.mkdir(destPath, (error) => {
                    if (error) {
                        cb(error)
                    } else {
                        cb(null, destPath)
                    }
                })
            } else {
                cb(null, destPath)
            }
        })
        cb(null, config.uploadFile)
    },
    filename: function(req, file, cb) {
        var fileFormat = (file.originalname).split('.')
        cb(null, file.fieldname + Date.now() + '.' + fileFormat[fileFormat.length - 1])
    }
})

var upload = multer({
    storage: storage
})

module.exports = upload`
`

var uploads = require('../common/fileuploads')

var PointController = require('../controller/point.controller')

var fields = [{name: 'photo', maxCount: 1},{name: 'video', maxCount: 1}]
router.post('/add',uploads.fields(fields) ,PointController.add)`
I used Postman to send a request, then my folder got two file, `req.files` record the broken file's information.

**Comment by TomasPangzi** [comment]
Sorry! this is my fault. I callback twice in the` multer.diskStorage`

**Comment by LinusU** [comment]
Ah, interesting, we should probably guard against that somehow, maybe using [`once.strict`](https://github.com/isaacs/once#oncestrictfunc)

**Comment by TomasPangzi** [comment]
@LinusU Thanks. I will try
