### ISSUE TITLE
Error when use file properties in multer

### ISSUE THREAD

**Issue by crisiiii** [expressjs/multer#485]
I have a route created which uses multer. When I try to get the file extension using the file properties it returns an error, but if I write the name manually it works fine and upload the image. Here my code:

    var storage = multer.diskStorage({
    destination: function (req, file, callback) {
        callback(null, 'path/images/');
    },
    filename: function (req, file, callback) {
        callback(null, 'file.jpg') //option 1: works fine and the image is uploaded
        callback(null, req.file.filename) //option 2: doesn't work, return net::ERR_EMPTY_RESPONSE
        callback(null, file.filename) //option 3: doesn't work, return net::ERR_EMPTY_RESPONSE
    }
    });

    var upload = multer({ storage: storage }).single('file');

    router.route('/representatives/:id/logoImage')
    .post((req, res, next) => {
        upload(req, res, function (err) {
            if (err) {
                console.log('Error Occured');
                return;
            }
            res.end('Your File Uploaded');
        })
    });

Someone knows why do that? Thanks!

**Comment by jonchurch** [comment]
Closing as inactive 📁
