### ISSUE TITLE
Upload file without fieldname

### ISSUE THREAD

**Issue by shahzadthathal** [expressjs/multer#490]
Hi,

Is it possible to upload a file without `fieldname`? 

I'm using Postman and there is no option for uploading the file with the field name.

Thanks

**Comment by iBicha** [comment]
You do need the field names in `multipart/form-data` POST request.
In postman, select the POST type, select Body tab, and the form-data option.

**Comment by LinusU** [comment]
Thanks @iBicha 🙌
