### ISSUE TITLE
Can´t resend file with memoryStorage option

### ISSUE THREAD

**Issue by davidanaya** [expressjs/multer#493]
Hi!

I've an Express server which expects a file uploaded via form and then sends that file over to another API. 

I tested it saving the file to disk and it works perfectly.

```
const multer = require('multer');
const fs = require('fs');
const request = require('request');

exports.upload = multer({ dest: 'uploads/' }).single('file');

exports.uploadFile = (req, res) => {
      const formData = {
        name: req.body.name,
        file: fs.createReadStream('uploads/' + req.file.filename)
      }

      const options = {
        url: `${path}/nodes`,
        formData
      }

      request.post(options, (err, response, body) => {
        if (err) return res.status(400).send({ msg: 'error', err });
        return res.status(201).send(response.body);
      });
    })
    .catch(err => res.status(400).send({ msg: 'error', err }));
}
```
Now, as this is just an intermediate step (for authentication purposes), I don´t really need to save the file to disk, I want to keep it in memory and send it to the other API. So I changed my code:

```
exports.upload = multer({ storage: multer.memoryStorage() }).single('file');

exports.uploadFile = (req, res) => {
      const formData = {
        name: req.body.name,
        file: req.file.buffer
      }

      const options = {
        url: `${path}/nodes`,
        formData
      }

      request.post(options, (err, response, body) => {
        if (err) return res.status(400).send({ msg: 'error', err });
        return res.status(201).send(response.body);
      });
    })
    .catch(err => res.status(400).send({ msg: 'error', err }));
}
```

But this is not working. I tried many things, encode it to base64 before sending it, create a bufferStream with ```new stream.PassThrough()``` but nothing seems to work. Am I doing anything wrong here?

Thanks

**Comment by LinusU** [comment]
I think that this is probably an issue better opened on the `requests` repo...

If you `console.log(req.file.buffer)`, do you get a proper buffer?

**Comment by davidanaya** [comment]
Yes, I do. You're right, it might be better in ```requests```, sorry.

**Comment by stringbeans** [comment]
@davidanaya did you ever find solution for this? im doing a very similar thing except using `FormData` to "forward" the upload to a different api. It works perfectly fine if I use LocalStorage but when using MemoryStorage and using the `file.buffer` it doesnt seem to work

**Comment by axelpale** [comment]
@davidanaya did you find a solution? The issues at request discuss this but provide no good answers.

**Comment by jonathangaldino** [comment]
I'm having the same issue. Did you find a solution?
