### ISSUE TITLE
¿Is new-api ready for production?

### ISSUE THREAD

**Issue by sant123** [expressjs/multer#494]
Hi, I really liked the new API and it solves some bugs in the current version. But, is it ready for production? I haven't seen more contributions since February and I haven't found bugs there. Or, is it beta coming?

Thank you!

**Comment by LinusU** [comment]
`multer@2.0.0-alpha.6` is released on npm and I feel that we are quite ready to push out a final 2.0... I haven't had too much time to work on this, but hopefully that will change shortly :)

**Comment by sant123** [comment]
I like to read that, I appreciate it @LinusU.

**Comment by sant123** [comment]
Any advance on this?

**Comment by jonchurch** [comment]
Things are still being worked on. I believe #399 is the PR to track for updates.
