### ISSUE TITLE
Unable to wrap multer middleware

### ISSUE THREAD

**Issue by ekaratzaferis** [expressjs/multer#497]
Hello! I'm trying to wrap this middleware inside a custom middleware in order to do some extra vadilation to the request. Specifically I'm invoking multer like this:

```
var upload = (req, res, next) => {
        multer({storage: storage}).fields(fields)(req, res, () => {
            if (!req.body.data) {
                res.status(400).send('Some error')
            } else {
                next()
            }
        })
    }
return upload
```

I'm expecting multer to finish its job and the I'm checking for the req.body.data, and then call next. I'm also expecting that next will trigger the next middleware which is:

```
const router = require('express').Router()
router.post('/admin/', upload, myController)
```

Also, I'm connecting the router and some final error handling middleware, like this:
```
app.use('/', adminRouter)
app.use(errorMiddleware)
```

My problem is, that every time I throw any error inside myController, it never reaches the errorMiddleware. It's like the chain is broken and the errorMiddleware is completely ignored. I should mention that if I route the endpoint like this:

```
const router = require('express').Router()
router.post('/admin/', myController)
```

errors reach the errorMiddleware perfectly fine. If I intercept my middleware, whenever an error is thrown inside myController, the request hangs.

Do you have any idea how to wrap the multer middleware correctly?

Edit: I forgot to mention that I get no errors back when initializing multer storage or fields. Also, I get a 404 every time I'm hitting this endpoint even though the middlewares are being triggered.

**Comment by ekaratzaferis** [comment]
OK I have an update on this:

If I attach this middleware before the errorMiddleware:
``` app.use((req, res, next) => {}) ```

then I'm able to catch the error in errorMiddleware, which is really weird!

I'm not even calling the next function. It's like it "consumes" a middleware chain that was split some time during my handles, and the errorMiddleware is able to carry on with the error.

Is it possible that the execution is split into different chain in my "upload" middleware which uses multer?

**Comment by ekaratzaferis** [comment]
Nevermind, I've been listening for a wrong event in another middleware, which triggered and extra next invocation :/ 

It would be really nice if I could easily trace the middleware chain through Express

I'm closing the issue :(

**Comment by george-norris-salesforce** [comment]
same question
