### ISSUE TITLE
Upload bigger Videos

### ISSUE THREAD

**Issue by oliverjessner** [expressjs/multer#502]
Hello everyone, 

I am able to upload a video of 9mb. But bigger files cause the heap to run out of memory. Tested with 50-200mb. Same thing happens after I changed the `memoryStorage` to `diskStorage`.  Also tried set flags to increase the old_space_size and the max_executable_size. But I am pretty sure I do not need to increase those for 200mb files.

Node version: 8.1.2
Multer version: 1.3.0

```bash
<--- Last few GCs --->

[7310:0x102801600]    39367 ms: Mark-sweep 1399.7 (1428.2) -> 1399.7 (1429.2) MB, 802.3 / 0.0 ms  allocation failure GC in old space requested
[7310:0x102801600]    40348 ms: Mark-sweep 1399.7 (1429.2) -> 1399.7 (1429.2) MB, 781.4 / 0.0 ms  allocation failure GC in old space requested
[7310:0x102801600]    41324 ms: Mark-sweep 1399.7 (1429.2) -> 1399.7 (1428.2) MB, 777.7 / 0.0 ms  last resort 
[7310:0x102801600]    42312 ms: Mark-sweep 1399.7 (1428.2) -> 1399.7 (1428.2) MB, 987.9 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x245960b29891 <JS Object>
    2: decode [/Users/oliverj/github/ganescha/Ganescha-Proxy/node_modules/busboy/deps/encoding/encoding.js:~897] [pc=0x14ac97314469](this=0x1f3446a42061 <a TextDecoder with map 0x3583de3ee5d1>,bytes=0x2907e0182311 <undefined>,options=0x2907e0182311 <undefined>)
    3: arguments adaptor frame: 1->2
    5: decodeText [/Users/oliverj/github/ganescha/Ganescha-Proxy/node_modules/busboy/lib/utils.js:...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x14ac9700437d
 7: 0x14ac9744ac53
 8: 0x14ac97314469
 9: 0x14ac9700579b
10: 0x14ac970e886b
11: 0x14ac970baffc
Abort trap: 6
```

```javascript
const multer = require('multer');
const upload = multer({ 
    storage: multer.memoryStorage(),            
    limits: {  
         fieldNameSize: 1000,
          fieldSize: 500 * 1024 * 1024, 
          fileSize: 500 * 1024 * 1024, 
          files: 1 
     }
}).single();
    
function extendTimeout (req, res, next) {
    res.setTimeout(480000, function () {
        GL.log('Timeout for /upload');
    });
      
    next();
}
    
function delegate (req, res) { 
    upload(req, res, function (err) {
         /* cut */
    });
}
    
return app.post('/upload', extendTimeout, delegate);
```

Thanks for any help

**Comment by LinusU** [comment]
Could you try it in the 2.x beta? see instructions in #399

**Comment by wzpan** [comment]
@LinusU but the 2.x version is a breaking new version that removed the concept of storage, which was taken used at many places in our projects.

**Comment by LinusU** [comment]
Would be happy to know more in detail how you are using it, and what you might be missing from 2.x? The idea with removing the concept of storage was to be able to abstract away memoryStorage vs. diskStorage, and just get a stream that you can do whatever you want with, including just saving to disk...

**Comment by klexzi** [comment]
am having the same issues, when uploading a video with multer, i dont get any errors but the video is not uploaded, all i get is a could not get any response, but when i upload an image it works fine

**Comment by oliverjessner** [comment]
Hey totally forget this is still open we swichted to socket.io for uploading videos a long time ago.

**Comment by danilogr** [comment]
So, are big files not supported by Multer ? I am having the same problem here.

**Comment by CristianSaavedraVasquez** [comment]
Hello bro, I am programming something similar but with mongoDB and it turns out that you know how I can call the video, because when I call it it gives me only the filename and nothing else

**Comment by emma-worgu** [comment]
Hey, My video got uploaded but is not showing on my text editor as pictures would normally show
