### ISSUE TITLE
Handle accept-encoding uploads

### ISSUE THREAD

**Issue by jhihn** [expressjs/multer#503]
I have a project where I accept very large > 1GB text files. Needless to say, I want to compress these over the wire and decompress them on the other side. What must I do for multer to be sent one with the browser compression as well as make sure it is decompressed on the other side (hopefully all in a streaming nature)

**Comment by LinusU** [comment]
This looks interesting, could you give me some details on how exactly this would work? What headers does the browser send?

**Comment by jhihn** [comment]
I'll get back to you on that. I'm actively working on it now (I'm porting a python flask app - which doesn't do it either) I'll post it here when I have the headers working.

**Comment by jhihn** [comment]
After looking i over, I think that this should be handled higher up the middleware stack. If I gzip the entire request, then everything should work as-is.
