### ISSUE TITLE
file and Base64 image data.

### ISSUE THREAD

**Issue by rakirox** [expressjs/multer#506]
Hi there, I'm using multer to upload an image besides other irrelevant data which works fine.
But now I got a thumbnail image in Base64, which is generated on js client.

My aprroach is just to add a new key/value to my postman. But it seems that my app gets stuck at multer. It uploads the image but somehow gets stuck (like processing something) with the base64 field and is not reaching my code -> "user.signup".

`var express     = require('express'),`
`   multer      = require('multer'),`
`    upl         = multer({dest: 'uploads/'}),`
`    app         = express(),`
`   apiRoutes   = express.Router()`
...................
`apiRoutes.post('/signup',upl.single('img'),passport.authenticate('jwt', { session: false}), user.signup)`

I have some guesses like, somehow the base64 is making a mess after multer reads the file but nothing clear.

**Comment by gireeshpunathil** [comment]
@rakirox  - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces

**Comment by kevin4dhd** [comment]
any solution?
