### ISSUE TITLE
Non Removable Directory creation on Windows

### ISSUE THREAD

**Issue by aditshinde** [expressjs/multer#508]
A non removable and persistent directory is being created if we use 
destination : __dirname+ '../public/images/' or destination : __dirname+ '..\\public\\images\\'
multer created a new "routes.." as a directory and the file was created inside this new routes.. directory. When tried to delete the newly created "routes.." directory the original "routes" directory get deleted and this newly created directory is listed as EMPTY as well as unrecognizable on windows.

The following is the screenshot of the usage of multer:
![multerusage](https://user-images.githubusercontent.com/13440621/27987590-84a620a8-642d-11e7-99d5-fb993554eee1.png)
![multerroute](https://user-images.githubusercontent.com/13440621/27987592-869c1552-642d-11e7-85ce-32b3ad9a8f4c.png)

The following are the step wise screenshot after the file has been uploaded on the server.

![uploadinfo](https://user-images.githubusercontent.com/13440621/27987582-67507422-642d-11e7-83a9-ecb4a8b8bec6.png)
![multererror](https://user-images.githubusercontent.com/13440621/27987583-71975644-642d-11e7-9cc1-c4c2e2255d80.png)
![undeletabledir](https://user-images.githubusercontent.com/13440621/27987585-7466ae6a-642d-11e7-889e-bd313a8b61e9.png)

**Comment by LinusU** [comment]
> destination : __dirname+ '../public/images/' or destination : __dirname+ '..\public\images\'

The problem is that `__dirname` doesn't have a trailing slash, I would recommend you to always use `path.join`

```js
destination: path.join(__dirname, '../public/images')
```

> When tried to delete the newly created "routes.." directory the original "routes" directory get deleted and this newly created directory is listed as EMPTY as well as unrecognizable on windows.

Hmm, this seems like an issue with Windows 🤔 I'm not sure what we should do on our part...

**Comment by aditshinde** [comment]
path.join does resolve the issue as it converts the entire path removing the ../ I think the issue lies in the mkdirp.cmd that you are using under multer. If mkdirp is able to create such directories then it seems to be a security issue. Moreover, I think you should consider adding an extra layer to convert relative paths to absolute paths. Anyways Thanks.

**Comment by LinusU** [comment]
> If mkdirp is able to create such directories then it seems to be a security issue

Maybe I'm missing something, but I don't really see how this is a _security_ issue

> Moreover, I think you should consider adding an extra layer to convert relative paths to absolute paths

The problem is that Multer got passed the string `C:\Github\inv-admin\routes..\public\images`, so the path was already absolute

**Comment by ThomasFournet** [comment]
I have exactly the same problem as you and i found a way to delete the folder
https://stackoverflow.com/questions/28175200/unable-to-delete-node-modules-folder-windows-7
The winrar/7zip method works like a charm !

**Comment by LinusU** [comment]
Seems like using rimraf should work as well:

> npm install rimraf -g

> rimraf route..
