### ISSUE TITLE
Incorrect mimetype on windows, works fine on osx

### ISSUE THREAD

**Issue by serganus** [expressjs/multer#511]
- I have tried to upload the same file using two chrome browsers one on windows and the other on osx. The windows one shows mimetype as `application/ocetet-stream` and the osx one shows as `application/zip`. This is wierd and not sure the root cause.

## Logs to give insights

- On windows

```
req.file.originalname : sample_input.zip
req.file.encoding : 7bit
req.file.size : 2020
req.file.mimetype : application/octet-stream
```
- on OSX
```
req.file.originalname : sample_input.zip
req.file.encoding : 7bit
req.file.size : 2020
req.file.mimetype : application/zip
```

## My code
```
var storage = multer.diskStorage({
    destination: function(req, file, cb) {
        cb(null, Upload_measurements_dir)
    },
    filename: function(req, file, cb) {
        crypto.pseudoRandomBytes(16, function(err, raw) {
            cb(null, raw.toString('hex') + Date.now() + '.' + mime.extension(file.mimetype));
        });
    }
});
var upload = multer({
    storage: storage,
    limits: {
        fileSize: config.maxSize
    }
});


var UploadSettings = upload.single('data');
```

**Comment by LinusU** [comment]
This is because it's the browser that sends the mimetype, and thus multer has no control over it. The 2.x beta has support for detecting mimetypes server-side, which would probably solve this for you. Would you mind trying it out? see #399

**Comment by serganus** [comment]
I did `npm install --save multer@next` but now it gives me error : 

```
TypeError: multer.diskStorage is not a function
```

Where to check for the internal functions/options?

**Comment by LinusU** [comment]
The new documentation is here: https://github.com/expressjs/multer/blob/c4b223efc4730611f7c6bfe9608bfd4048e3754d/README.md

:)

**Comment by serganus** [comment]
Thanks :-)

multer.diskStorage is not mentioned, is it not supported yet?

**Comment by LinusU** [comment]
It has been removed, now you get a stream instead. You could write it to a file as such:

```js
req.file.stream.pipe(fs.createWriteStream(...))
```

**Comment by serganus** [comment]
I used the same but I got the following error. 

```
req.file.stream.pipe(fs.createReadStream(req.file.path));
```

![screen shot 2017-07-20 at 2 13 14 am](https://user-images.githubusercontent.com/12946435/28382536-07c08d40-6cf1-11e7-95ca-229a7b0961d4.png)

**Comment by LinusU** [comment]
`createReadStream` this needs to be create *write* stream :)

**Comment by serganus** [comment]
super. Solved :-)

**Comment by serganus** [comment]
@LinusU BTW any reliable way to make sure server side system detect the correct mime type. For example i have a `.m and .prm` file which gives null on server side check, but gives octet-stream from client side check.
