### ISSUE TITLE
upload.array('file') failing for huge file

### ISSUE THREAD

**Issue by bezawada27** [expressjs/multer#512]
Hello,

One of the client machine has a problem uploading a huge file. While for others it is uploading fine
var multer = require('multer');
var storage = multer.memoryStorage();
var upload = multer({
    storage: storage
});
router.post('/upload', upload.array('file'), uploadFile);

My application not logging statements from uploadFile function when this issue happens. But it logs the methods before it comes to this(access check for route). So my strong feeling that this is failing when trying upload.array('file'). 
If the request from client has transmission problem or any problem how to find the problem and handle it? It is right now not completing request in node and client call is timing out
Anyway that we can handle error while trying to find file ?

i am ruling out memory issue as it is only happening from one client machine

**Comment by LinusU** [comment]
How large is the file? `memoryStorage` generally doesn't handle large files that well...

**Comment by jaman99** [comment]
//1,000,000 bits == 1MB


var maxSize = 1000000*90 ;

const upload = multer({
  storage: storage,
  limits: {
    fileSize: maxSize
  }
});

**Comment by jonchurch** [comment]
Closing as inactive 👻
