### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by lijicheng123** [expressjs/multer#513]
`var express = require('express');
var multer  = require('multer')
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, '/upload')
    },
    filename: function (req, file, cb) {
        var fileFormat = (file.originalname).split(".");
        cb(null, file.fieldname + '-' + Date.now() + '.' + fileFormat[fileFormat.length - 1])
    }
})

var upload = multer({ storage: storage })
var router = express.Router();
router.post('/', upload.single('avatar'), function (req, res, next) {
    // req.file 是 `avatar` 文件的信息
    // req.body 将具有文本域数据, 如果存在的话
    console.log(req.file)
    res.json({
        name:req.file.filename
    })
})

module.exports = router;
`

it tell me 

Error: ENOENT: no such file or directory, open 'F:\upload\avatar-1501142151656.png'
    at Error (native)

i don't know why , who can help me

**Comment by LinusU** [comment]
It complains that the folder `F:\upload\` doesn't exist, creating the folder should make it work 👍

**Comment by lijicheng123** [comment]
@LinusU Thanks very much

**Comment by darkotuning** [comment]
I have the same error, but i'm sure that i have created folder for uploads. Can you help me? Tnx

**Comment by khalidhmd** [comment]
I have same error even after creating the folder

**Comment by darkotuning** [comment]
> I have same error even after creating the folder

I think you just have to put them in the same folder

My code example: 

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, './uploads');
    },
    filename: function (req, file, cb) {
        cb(null, new Date().getTime() + '-' + file.originalname);
    }
});

const upload = multer({
    storage: storage,
    limits: {fileSize: 1024 * 1024 * 5}
});

**Comment by khalidhmd** [comment]
if you are using Windows machine, the issue may be due to un-valid character in the resulting filename.
for me, it worked after i replaced the colon ":" with "-" as the colon is not a valid character for file names in windows

**Comment by mandaputtra** [comment]
where colon i should replaced? @khalidhmd

**Comment by MrCEO63** [comment]
> where colon i should replaced? @khalidhmd

new Date creates something like this 2018-11-01T15:55:08 so the colon in between the numbers

**Comment by AmrAlmagic** [comment]
I solved this error with [StackOverflow](https://stackoverflow.com/a/48653921/6685807) .

**Comment by anisbhsl** [comment]
on your destination callback add:

```
 destination:(req,file,cb)=>{
        cb(null,path.join(__dirname+'/uploads'));
}

```

**Comment by lmjavascriptprogrammer** [comment]
For those use Linux:

```javascript
const storage = multer.diskStorage({
destination(req, file, cb) {
  console.log('smth file=>', file);
  cb(null, `./src/public/account/images`);
},
filename(req, file, cb) {
  // const id = uuid();
  cb(null, file.originalname);
},
});
```

If your path begins with point, package use root path of start application file. Yes, this is strange

**Comment by anisbhsl** [comment]
> If your path begins with point, package use root path of start application file. Yes, this is strange
 @lmjavascriptprogrammer
It's not strange. It is a path naming standard where "/" means root directory, "./" means current directory and "../" means parent of current directory.

**Comment by anisbhsl** [comment]
For those still having issues, use 
```
cb(null, path.join(__dirname,".","uploads",yourfilename);
```
This works independent of your OS.

**Comment by lmjavascriptprogrammer** [comment]
> > If your path begins with point, package use root path of start application file. Yes, this is strange
> 
> @lmjavascriptprogrammer
> It's not strange. It is a path naming standard where "/" means root directory, "./" means current directory and "../" means parent of current directory.

For my application, it turned out wrong. Path with a point is considered as relative. So, that's why I said it was weird.

**Comment by FuzzySid** [comment]
In case anyone still sees this error 
**For windows user**
new Date().toISOString().replace(/:/g, '-')
Replace the colons in the date of your image with hyphen using the above line of code in the callback function of your storage.

**Comment by viperguy07** [comment]
> In case anyone still sees this error
> **For windows user**
> new Date().toISOString().replace(/:/g, '-')
> Replace the colons in the date of your image with hyphen using the above line of code in the callback function of your storage.

This was my issue in windows and it solve it Thanks.

**Comment by mimya01** [comment]
change destination 
```
 destination: function (req, file, cb) {
    cb(null, path.join(__dirname, '../storage/'))
  },
```

**Comment by Abdelkader-Garaali** [comment]
I am in windows, it works with   **new Date().getTime()**   but not with   **new Date().toISOString()**

**Comment by jonchurch** [comment]
@Abdelkader-Garaali Did you try the suggestion https://github.com/expressjs/multer/issues/513#issuecomment-532772540 ?

**Comment by ibadeeCodes** [comment]
const fileStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    // let dest = path.join(__dirname, '/images')
    cb(null, path.join(__dirname, '/images/'))
  },
  filename: (req, file, cb) => {
    cb(null, Date.now() + file.originalname)
  },
})

This worked for me...

**Comment by MOIN-AKHTAR** [comment]
On  windows, it works with new Date().getTime() but not with new Date().toISOString() i think toISOString() will perfectly work on mac but not on windows other wise it will give you Error: ENOENT: no such file or directory, open type of error

**Comment by Jayashree-panda** [comment]
> on your destination callback add:
> 
> ```
>  destination:(req,file,cb)=>{
>         cb(null,path.join(__dirname+'/uploads'));
> }
> ```

It worked! Thank you

**Comment by thilina15** [comment]
> In case anyone still sees this error
> **For windows user**
> new Date().toISOString().replace(/:/g, '-')
> Replace the colons in the date of your image with hyphen using the above line of code in the callback function of your storage.

thank you.. u saved me

**Comment by geraldombuthia** [comment]
I just realised that you need to manually create the upload folder, i tried everything everyone suggested in the comments only to add the folder and having things work

**Comment by ajaysbugatti** [comment]
made a public folder in the root directory of server.js ...or create the public folder at different location

i created in ther server folder

**Comment by abdessamadelhamdany** [comment]
If you prefer date organized directories, I just came up with this solution:

```TypeScript
const storage = multer.diskStorage({
  destination: (req: Request, file: Express.Multer.File, cb: MulterCallback) => {
    const date = dateFormat(new Date(), 'yyyy/mm/dd');
    const dir = `uploads/${date}`;
    const absPath = path.resolve(__dirname, '../..', 'uploads', date);
    const exists = fs.existsSync(absPath);

    if (!exists) {
      fs.mkdirSync(absPath, { recursive: true });
    }

    cb(null, dir);
  },
  filename: (req: Request, file: Express.Multer.File, cb: MulterCallback) => {
    crypto.pseudoRandomBytes(16, function (err: Error, buf: Buffer) {
      if (err) {
        return cb(err);
      }
      const filename = buf.toString('hex') + path.extname(file.originalname);
      cb(null, filename);
    });
  },
});
```

**Comment by jwhitty1** [comment]
> just need resolve the path, try this.
> 
> ```js
> const storage = multer.diskStorage({
> 
>   destination: function (req, file, cb) {
>     cb(null, path.resolve(__dirname, './test'))
>   },
> 
>   filename: function (req, file, cb) {
>     cb(null, file.originalname)
>   }
> })
> ```
> 
> whit <3 Cesar.
https://github.com/expressjs/multer/issues/391#issuecomment-360731493

THIS WORKED!! I wasnt getting the files uploaded, then today (a week later) I stumbled upon an uploads folder created OUTSIDE my project root folder (!?) and it had...69 images...hehehe

Anyways after all this crap trying to even recreate this WRONG upload location, changing the path to all of these:
uploads/
/uploads/
./uploads/
../uploads/

Both WITH and WITHOUT the folder being previously created...nothing was working....UNTIL THIS ANSWER!
The path resolution solved everything! THANK YOU!

**Comment by bhagyashribombadi** [comment]
> In case anyone still sees this error **For windows user** new Date().toISOString().replace(/:/g, '-') Replace the colons in the date of your image with hyphen using the above line of code in the callback function of your storage.

Thanks issue solved
