### ISSUE TITLE
Is fileFilter really useful?

### ISSUE THREAD

**Issue by MolbioUnige** [expressjs/multer#515]
Sorry for asking this.

If I'm correct, the only fields present at fileFilter time are `[ 'fieldname', 'originalname', 'encoding', 'mimetype' ]` 

One cannot rely on the  `originalname` nor on the `mimetype` to check whether the file is what it pretends to be. 

What is it that I am missing?

**Comment by LinusU** [comment]
I agree, it's useless. That's why I have removed it in the 2.x alpha :) see #399 for more info 🎉

**Comment by LinusU** [comment]
Closing this since we cannot remove it in 1.x (it would be a breaking change) and it's already removed in 2.x
