### ISSUE TITLE
When not upload!

### ISSUE THREAD

**Issue by ferpalma21** [expressjs/multer#518]
Hello, I hope you can help me! I'm using multer and it works, but the user could leave this field empty if he wants, and the problem is that when he doesn't upload a file, the element isn't created. How can I use multer, and if the user doesn't attach the file the item is created.
I'm using angular 4, for the front

Thanks

**Comment by LinusU** [comment]
I think that you should both implement a check in the frontend, to stop the user from even submitting without a file, and in the backend, to make sure that no malicious user circumvents the check.

The server check would look something like this:

```js
function (req, res, next) {
  if (!req.file) {
    return next(new Error('Please attach a file'))
  }

  // continue as usual
}
```
