### ISSUE TITLE
req.file is undefined

### ISSUE THREAD

**Issue by jas75** [expressjs/multer#519]
So i followed the instructions and looked over the web to solutions but still doesn't work. I'm currently using Postman to test this route

```
var multer = require('multer');
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '/uploads');
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now());
  }
});
var upload = multer({ storage:storage}).single('userPhoto');

app.post('/editPhoto',function(req,res,next){

  upload(req,res,function(err){   
      if(err){
        res.json({success:false,message:"File was not able to be uploaded: "+err});
      }
      else{
        console.log(req.file); // undefined
        if(!req.file){
          res.json({success:false,message:'No file was selected'});
        }
        else{
          res.json({success:true,message:"Photo was updated !"});
        }
      } 
  });
});
```
req.file is undefined

**Comment by LinusU** [comment]
Seems like you have missed to attach the middleware to the route, could you try this change?

```diff
- app.post('/editPhoto',function(req,res,next){
+ app.post('/editPhoto', upload, function (req,res,next) {
```

**Comment by jas75** [comment]
It's not working, i can't understand what's the problem here ...

**Comment by LinusU** [comment]
Did you try adding the `upload` function as a middleware? Per my previous post?

**Comment by jas75** [comment]
Sure It didn't work but I've found an other way, anyway thank you very much
for your feedback.

2017-08-27 15:26 GMT+02:00 Linus Unnebäck <notifications@github.com>:

**Comment by shashvattrip** [comment]
Hey @jas75 what made it work? I'm struggling with the same problem! I'm processing the file, converting it to a different format while involves 3-4 IO methods. I use async.waterfall to keep it simple but I get req.files as undefined

**Comment by caoxiaoshuai1** [comment]
I got the same problem, this middleware is difficult to use. The upload file has been renamed to an MD5Name file, but req.files is undefined.
