### ISSUE TITLE
Is there a way to access the file path and original file name in the rename function?

### ISSUE THREAD

**Issue by codeniac** [expressjs/multer#52]
I try to rename an incoming file chunk accessing the filename parameter, but the filename is set to "blob"!! I think i misunderstand the hole concept of file uploading.... in my mind the process is something like this: the file is sent from client to server one chunk at a time that is stored in a temporary folder and after completion i must resemble this temporary chunks into the sent file and move it to a permanent folder! I was using Flow.js to allow a "smarter" upload process where the client check what chunks was already uploaded and start from there in case of some previous failure, but i'm having trouble to integrate multer with Flow.js to have this nice functionality on! Anyone could help my stupidity in this matter? :)

**Comment by jpfluger** [comment]
The onFileUpload* functions now include `req` and `res`. That doesn't give you minute control over file chunks but is a step closer. Now you can get a socket.io instance attached to your req or res session and report back to the client upload progress. Again, it's not allowing for chunked memory management on the server but will create a more responsive app for the client.
