### ISSUE TITLE
DiskStorage does not automatically create destination after startup

### ISSUE THREAD

**Issue by thegoldenmule** [expressjs/multer#521]
Very minor issue.

I'm using `multer` with this configuration:

```
var upload = multer({
	storage: multer.diskStorage({
		destination: "../RecvFiles"
	})
});
```

According to the docs:

```
Note: You are responsible for creating the directory when providing destination as a function. When passing a string, multer will make sure that the directory is created for you.
```

This is true on startup, however it does not check that the folder exists every upload. This means that if you delete the folder at runtime (common during development), `multer` will throw a filesystem exception that the directory does not exist.

It would be nice if it made sure the directory existed every time.

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
