### ISSUE TITLE
formdata params , array when length is 1, typeof it is string

### ISSUE THREAD

**Issue by johaung** [expressjs/multer#522]
#### Context

* *node version*: 6.11.1
* *multer version*: 1.3.0
* *environment* (node, browser):  windows

###  when I post a array length is 1 , the server accept it as String, but when the legnth > 1, typeof it is Object

Server
```server
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var multer = require('multer')

var app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(multer({ dest: './uploads/'}).any())

app.post('/', function(req, res, next){
  console.log("req.files.length", req.files.length)
  console.log("req.body",req.body)
  a = req.body.a; //the typeof a diffrent with it's length (but I want it as Object)
  console.log("a", typeof(a), a);
  return res.send(req.body || {})
});

// error handler
app.use(function(err, req, res, next) {
  res.status(err.status || 500).send("error" + err);
});

var server = app.listen(3000, function() {
  console.log("web server listening on port " + (server.address().port));
});
```

Test Demo
```test
var assert = require("chai").assert
var request = require('request')

var url = "http://127.0.0.1:3000/"
describe("post", function(){
  it('array length 1', function(done){
    var opts = {
      method: 'POST',
      url: url,
      formData: {
        b: "hello",
        a: [1]
      }
    };
    request(opts, function(err, res, body){
      assert.equal(null, err);
      console.log("body", body);
      done()
    });
  })

  it('array length 2', function(done){
    var opts = {
      method: 'POST',
      url: url,
      formData: {
        b: "hello",
        a: [1 ,2 , 3]
      }
    };
    request(opts, function(err, res, body){
      assert.equal(null, err);
      console.log("body", body);
      done()
    });
  })
})
```

the first demo, typeof a is string, but the second a is Object,

**Comment by johaung** [comment]
I found multer/lib/make-niddleware.js . Here busboy.on "field" , ingore the original type of fieldname
```
// handle text field data
    busboy.on('field', function (fieldname, value, fieldnameTruncated, valueTruncated) {
      if (fieldnameTruncated) return abortWithCode('LIMIT_FIELD_KEY')
      if (valueTruncated) return abortWithCode('LIMIT_FIELD_VALUE', fieldname)

      // Work around bug in Busboy (https://github.com/mscdex/busboy/issues/6)
      if (limits && limits.hasOwnProperty('fieldNameSize')) {
        if (fieldname.length > limits.fieldNameSize) return abortWithCode('LIMIT_FIELD_KEY')
      }
      appendField(req.body, fieldname, value)
    })
```

**Comment by LinusU** [comment]
Unfortunately I think that this is a limitation in the formdata format. There is no "type of fieldname" as far as I can tell and sending it as an array is simply sending the same field multiple times; thus there is no way for us to know if a single value is meant to be the value or an array with a single value...

**Comment by johaung** [comment]
I'm sorry,  I found that when use "bodyParser" to parser  the form format, even if an array with a single value，it could be recognize.  Could you can give me a little pointing to the difference between the two.

**Comment by LinusU** [comment]
`body-parser` doesn't parse `multipart/form-data`, are you thinking of the `application/x-www-form-urlencoded` format? They are quite different, I would advice you to google them to find out how they look :)

**Comment by johaung** [comment]
I am very grateful to you for your advice.

On 09/07/2017 00:49, Linus Unnebäck wrote: body-parser doesn't parse multipart/form-data, are you thinking of the application/x-www-form-urlencoded format? They are quite different, I would advice you to google them to find out how they look :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/expressjs/multer","title":"expressjs/multer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/expressjs/multer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LinusU in #522: `body-parser` doesn't parse `multipart/form-data`, are you thinking of the `application/x-www-form-urlencoded` format? They are quite different, I would advice you to google them to find out how they look :)"}],"action":{"name":"View Issue","url":"https://github.com/expressjs/multer/issues/522#issuecomment-327545495"}}}

**Comment by johaung** [comment]
I am very grateful to you for your advice.
