### ISSUE TITLE
Interference between bodyParser.Raw middleware and multer

### ISSUE THREAD

**Issue by fabricecolas** [expressjs/multer#523]
**Problem:** `req.file` is `undefined`

**Solution:**
1. Knock out `bodyParser.raw`'s middleware globally ; or 
2. Set it per route as needed. 

**Versions:** Express 4.1x, multer 1.3.x

**References:**
[1] Why req.files is always undefined https://github.com/expressjs/multer/issues/203
[2] Does multer work happily beside bodyParser in an Express 3.x app?https://github.com/expressjs/multer/issues/251

**Comment by zomars** [comment]
Thanks for reporting this, I'm having this exact issue.

**Comment by LinusU** [comment]
I don't think that there is anything that we can do here. You can only consume a stream once, and if it's passed to the raw body parser that will consume it.

We could potentially add some kind of warning if the stream have been consumed, but I'm not sure exactly how that would look 🤔

**Comment by cipher-code** [comment]
You can use them for different routes
```
const rawBodyParser =bodyParser.raw({
  inflate: false,
  type: '*/*'
});

const upload = multer({dest: 'uploads/'});

app.get('/raw', rawBodyParser, (req, res) => {
   // using raw body parser
});

app.get('/upload', upload.single('photo'), (req, res) => {

});
```
