### ISSUE TITLE
Can't upload multipart file in integration test

### ISSUE THREAD

**Issue by jasperblues** [expressjs/multer#528]
I'm assuming this is a user error, rather than a bug, and thus have posted on StackOverflow. In case it is the latter, repeating here: 

--
I'm adding integration tests to a legacy code-base prior to refactoring. For this case, uploading a file. 

**The Test:**

    it('uploads a photo at the specified index', done => {

        chai.request(server.instance)
            .post('/profile/photo/0')
            .set('Access-Token', `${token}`)
            .set('API-Key', testConfig.apiKey)
            .field({contentId: 'foobar'})
            .attach('file', fs.readFileSync(__dirname + '/logo.png'), 'file')
            .end((err, res) => {
                console.log(JSON.stringify(res.body))
                res.should.have.status(200)

                done()
            })
    }) 

The endpoint being tested works ok in production. But to get the test to pass, I have to comment out the following lines in `make-middleware.js` of the `multer` module: 

    if (!includeFile) {
      // appender.removePlaceholder(placeholder)
      // return fileStream.resume()
    }

How can I make the test pass without the modification above?

**Comment by LinusU** [comment]
It _feels_ like this has something do to with `chai.request` since, as you say, it works in production. It could be because it's trying to fake the network request, and are simply missing to mock some specific property; just guessing here since I haven't looked at any code...

I would open an issue with chai.request and see what they have to say...

**Comment by jasperblues** [comment]
Good thinking. Sounds plausible. I will change the test to use super-agent directly, and let know you what happens. (Likely solved).

**Comment by jasperblues** [comment]
Still happens with superagent, and passes if I uncomment the same lines. chai-http uses superagent under the hood. I'll find another file upload library and test that. New to nodejs, know some other options?

**Comment by jasperblues** [comment]
It was just a fileFilter (by mime-type) that I wasn't aware was there. Sorry for the confusion, but thanks for the great support.
