### ISSUE TITLE
Typescript properties not matching up correctly

### ISSUE THREAD

**Issue by shogan94** [expressjs/multer#529]
I believe this is an issue, but it might just be user error. 

My post looks like this...
```
 private uploadFiles(req: Request, res: Response, next: NextFunction) {
        upload.any()(req, res, (err) => {
            if (err) {
                res.status(500)
                    .send({
                        error: err.message
                    });
            } else {
                let filePaths = [];
                console.log(req.files);
                req.files.forEach(file =>
                    filePaths.push(file.path)
                );
                console.log(filePaths);
                res.status(200)
                    .send({
                        uploaded: true
                    })
            }
        });
    }
```

Before I was using `upload.array('Files[]')` but switched to any to see if it worked differently. 

The above code works, but I get a warning from TypeScript saying

`src\routes\FileRouter.ts(41,27): error TS2339: Property 'forEach' does not exist on type '{ [fieldname: string]: File[]; } | File[]'.
  Property 'forEach' does not exist on type '{ [fieldname: string]: File[]; }'.
[08:15:21] TypeScript: 1 semantic error
`

So I tried doing `req.files['Files[]'].forEach(...) ` but that always crashes and says `TypeError: Cannot read property 'forEach' of undefined`. 

Am I doing something wrong here? Since `req.files.forEach` is working, I'd assume it's just a documentation issue? Please correct me if I'm wrong

**Comment by LinusU** [comment]
Unfortunately TypeScript and middleware isn't working super perfect at the moment. The multer typings will (I think) just add `req.file` and `req.files` to the `express.Request` type; which means that they will be there wether you have used a middleware or not for that particular route.

In this case it also means that TypeScript doesn't know if you have used `.array`, `.fields` or `.any`, which means that the type of `req.files` is a union type and it's up to you to cast it to the correct one.

```typescript
// .array(...)
const files = req.files as File[]

// .fields(...), .any()
const files = req.files as { [fieldname: string]: File[] }
```

I understand that this is not ideal and would love any ideas for how we could make this better!

**Comment by shogan94** [comment]
Ah that Makes sense! Thank you for the quick reply

**Comment by LinusU** [comment]
No problem!

...as I don't think that there is anything that we can do from our side right now, I'll close this for now. If anyone have any ideas for improvements to the typings, I would love to hear them!
