### ISSUE TITLE
Content-type = 'multipart/form-data',  req.body, req.file still undefined

### ISSUE THREAD

**Issue by jyjin** [expressjs/multer#532]
I waste a lot of time to resolve this problem, I have tried to use html form element post data, and use FormData object post data. But it stile undefined in my req.body

shotcut for my http request:
![http](https://user-images.githubusercontent.com/8912548/31535308-40b3f798-b02d-11e7-81b3-a50670201d44.png)

my server code:
<img width="810" alt="server" src="https://user-images.githubusercontent.com/8912548/31535338-596d066c-b02d-11e7-8bc6-dc6f5407dc2c.png">

and server log:
<img width="734" alt="log" src="https://user-images.githubusercontent.com/8912548/31535342-5e09d966-b02d-11e7-8ebd-afc65b1d8f72.png">

Besides, .single(fieldname),   Are this 'fieldname' is the formdata file key?

**Comment by LinusU** [comment]
Hmm, the only thing I can think of is that something else is consuming the body before multer. Do you have any other middlewares that runs before this route?

**Comment by juanmav** [comment]
@LinusU I have the same issue and I have removed all middlewares to test it and still fails.

**Comment by LinusU** [comment]
Interesting, would you mind posting similar data as @jyjin did? I think it could help me debug the issue 😃

**Comment by jyjin** [comment]
I ve got the point，my problem made by I have a redirect server which didnt handle the request. so when a post a request , it lose the data on the middle redirect server. Now I  pipe the request or temp save and resend formdata to final server，it worked！

**Comment by LinusU** [comment]
Glad to hear that you solved it!

@juanmav if you still have a problem and can share some more data I'll reopen this 👌
