### ISSUE TITLE
Is there a way to get the upload duration for each file in a multi upload ?

### ISSUE THREAD

**Issue by sfeher-paymentus** [expressjs/multer#536]
Hi,

I'm using multer to upload multiple files and then copy them to SFTP and I need to write some performance stats to InfluxDB. Is there a way to get the upload duration for each file ?

Thanks.
Sebastian

**Comment by gireeshpunathil** [comment]
@sfeher-paymentus - is this still outstanding?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
