### ISSUE TITLE
fileFilter is not working properly

### ISSUE THREAD

**Issue by ferasallaou** [expressjs/multer#537]
I'm accepting a multiple files from the user, thus I'm using upload.array().
My issue is in fileFilter, so I only want to upload images and I want to ignore the rest.
`let upload = multer({ storage: storage, 
  fileFilter: function(req, file,cb){ if (file.mimetype != "image/jpeg" && file.mimetype != "image/png") { return cb(null, false) } cb(null, true) } })`
what actually happens here is that this works fine when all the files are images, but if let's say they thrid file is not an image, i only uploads the forth and the fifth, which means it ignores the first and the second.
example: filesArr['image1','image2','txt1','image3','image4'] // image 4 & 3 will be uploaded, 2 & 1 are ignored.
 filesArr['image1','image2','txt1','image3','image4','txt2'] //everything will be ignored as if return false is forcing fileFilter to stop.

any help?

**Comment by HarshithaKP** [comment]
@ferasallaou  It is working fine for me as I made a small change (`file` -> `files`  in fileFilter function), please find the working code below.

```
var upload = multer({ dest : './uploads',
        fileFilter: function(req, files, cb){
                if (files.mimetype != "image/jpeg" && files.mimetype != "image/png") {
                        return cb(null, false)
                 }
        cb(null, true) } });

app.post( '/', upload.array('file',4), (req, res) =>{
        console.log(req.files);
});
```

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
