### ISSUE TITLE
Problem uploading larger files

### ISSUE THREAD

**Issue by lcheewei** [expressjs/multer#539]
Hi, I am using Multer to upload video clips from client to server. My server is hosted on aws ubuntu. For small files < 10mb, uploads are successful and code is able to execute, but for larger files (about 30-40mb), the file is stored in the (/Uploads) directory but codes inside the http post do not execute at all (see code snippet below). i.e. no error msg, first console log not showing. In the status bar I see "Uploading xx%", and after hitting 100% the uploading repeats. I did not have this problem when testing in localhost environment. 
```

`app.post('/api/Upload', upload.array('file[]', 3), function (req, res, next) {
    upload(req, res, function (err) {
        if (err) {
          // An error occurred when uploading 
          return
      }
    console.log('1. File received in server'); 
    console.log(req.files[0]); // req.files is array of `photos` files 
    res.redirect('localhost:2000/index.html');

});`
```

**Comment by gireeshpunathil** [comment]
@lcheewei  - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces

**Comment by shailu26** [comment]
> Hi, I am using Multer to upload video clips from client to server. My server is hosted on aws ubuntu. For small files < 10mb, uploads are successful and code is able to execute, but for larger files (about 30-40mb), the file is stored in the (/Uploads) directory but codes inside the http post do not execute at all (see code snippet below). i.e. no error msg, first console log not showing. In the status bar I see "Uploading xx%", and after hitting 100% the uploading repeats. I did not have this problem when testing in localhost environment.
> 
> ```
> 
> `app.post('/api/Upload', upload.array('file[]', 3), function (req, res, next) {
>     upload(req, res, function (err) {
>         if (err) {
>           // An error occurred when uploading 
>           return
>       }
>     console.log('1. File received in server'); 
>     console.log(req.files[0]); // req.files is array of `photos` files 
>     res.redirect('localhost:2000/index.html');
> 
> });`
> ```

Same issue help please

**Comment by jonchurch** [comment]
@shailu26 We still don't have enough information to help here.

Open a new issue with a minimal example of your code and we can talk there.
