### ISSUE TITLE
Disappearing images 

### ISSUE THREAD

**Issue by Timibadass** [expressjs/multer#541]
Hi, Images I upload using multer disappear after a while, i'd like to know how to tackle this issue, heres my code
const multerOptions = {
   storage: multer.memoryStorage(),
   fileFilter(req, file, next) {
       const isPhoto = file.mimetype.startsWith('image/');
       if(isPhoto) {
           next(null, true);
       } else {
           next({message: 'That filetype isn\'t allowed!'}, false);
       }
   }
}

**Comment by istana** [comment]
Hi, you use *memoryStorage* which stores files in RAM - images will be deleted after computer is restarted. Use *diskStorage* instead.

**Comment by LinusU** [comment]
Thank you @istana!
