### ISSUE TITLE
上传大文件

### ISSUE THREAD

**Issue by zDream** [expressjs/multer#546]
在两个网之间上传大文件。前端用ajax提交formData表单提交几个G的大文件，后端用koa2，multer，程序上传到几百兆就不走了，好像是死掉了，也没有报错信息，这是为什么，

**Comment by shibazijun** [comment]
文件超过了限制的大小，可以设置fieldSize

**Comment by jonchurch** [comment]
Google translate of OP:

>Upload large files between two networks. The front end uses ajax to submit the formData form to submit a few G large files, the back end uses koa2, multer, and the program uploads to a few hundred megabytes, and it does not leave. It seems to be dead, and there is no error message.

Response from shibazijun:

> The file exceeds the limit size, you can set the fieldSize

Sounds like OP was having an upload hang and never complete when working with large files.
