### ISSUE TITLE
Using multer inside controllers/models

### ISSUE THREAD

**Issue by vasiliyb** [expressjs/multer#55]
Folks,

Host can I invoke the `onFileUploadComplete` method from my controller?

server.js
```
server.use(multer({ dest: '/tmp'}));
server.post('/users/:id/avatar', avatar.post);
```

avatar.js
```
post: function (req,res) {
    var image = req.files;
    console.log (req.files);

    onFileUploadComplete: function (file) {
        console.log(file.fieldname + ' uploaded to  ' + file.path);
       ....
         responses.Success('wroteToDB',res);
    }
},

```

Thanks!

**Comment by jpfluger** [comment]
Yep, multer is middleware, so @baryon comment applies. 

Re. S3 support check out @dustin-H's [pull request](https://github.com/expressjs/multer/pull/102). We're in the process of figuring out a way forward. It may be easiest to use his npm, [multer-pkgcloud](https://www.npmjs.com/package/multer-pkgcloud).

**Comment by vasiliyb** [comment]
@jpfluger Great! will wait for the PR to go through :)
