### ISSUE TITLE
Error handling when using both text and file input

### ISSUE THREAD

**Issue by okiti** [expressjs/multer#550]
app.post('/profile', upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file 
  // req.body will hold the text fields, if there were any 
})
When uploading via the above method how can I check if the file upload has any error. Or if it's uploaded successfully. Note: the form also has text fields

**Comment by thegauravtiwari** [comment]
I'm facing the same issue. req.file comes out to be undefined but req.body holds the text fields.

**Comment by LinusU** [comment]
Seems like this could be the same as #501, make sure that you don't have any other multer (or otherwise body consuming) middlewares mounted that also gets executed...

**Comment by osivwi** [comment]
`app.post('/profile', upload.single('avatar'), function (req, res, next) {
// req.file is the avatar file
// req.body will hold the text fields, if there were any
})` using the above format will work for both file and text but i've not seen a working way to test for the file upload errors

**Comment by rightisleft** [comment]
I found this ticket when looking at the same issue. Its odd that it appears on the body.

**Comment by HarshithaKP** [comment]
@okiti Using multer as documented in this way https://github.com/expressjs/multer#error-handling errors can be handled.

**Comment by mastermatt** [comment]
I'm going to close this as the original question seems to be answered and documented.
