### ISSUE TITLE
File uploads with PUT method doesn't send form data

### ISSUE THREAD

**Issue by jorups** [expressjs/multer#552]
I'm trying to upload file using PUT method.
Looking at the code seems that input data is processed differently for POST and PUT methods.
For POST there is input element added to form and sent over along the file content, however for PUT method only file content is sent. 

Lines that deal with PUT
```
....
xhr.open('PUT', file.putAction + queryString);
return this.uploadXhr(xhr, file, file.file);
```
POST:
```
....
form.append(this.name, file.file, file.file.filename || file.name);
var xhr = new XMLHttpRequest();
xhr.open('POST', file.postAction);
return this.uploadXhr(xhr, file, form);
```

What was intention to use different approach for both methods?

**Comment by gireeshpunathil** [comment]
@jorups - is this still outstanding?

**Comment by jonchurch** [comment]
These code snippets seem to be pulled from [another project](https://github.com/lian-yue/vue-upload-component/blob/master/src/FileUpload.vue#L848) and I'm not sure if this issue was opened here by accident or not.

Closing as inactive for now
