### ISSUE TITLE
Multer / Delete file

### ISSUE THREAD

**Issue by kamalkech** [expressjs/multer#554]
Hello,

There is any way to delete file when delete doc ??

Bests.

**Comment by adeelibr** [comment]
https://stackoverflow.com/questions/5315138/node-js-remove-file

**Comment by LinusU** [comment]
That answer provides some guiding, basically you want to do something like:

```
fs.unlink(req.file.path, (err) => /* ... */)
```

**Comment by aguileraq** [comment]
on my vps, after fs.unlink..... restart the app

**Comment by NickEmpetvee** [comment]
@LinusU @adeelibr  How can you expose `fs.unlink` in the Node / Express framework so that it can process deletes? Posts are exposed with an `app.post(...)` so is something similar needed to expose the delete request?

**Comment by NickEmpetvee** [comment]
@haxer-max yeah that was what it was. I figured it out not too long after posting it. This was my first time coding with Node.

**Comment by onlineaid** [comment]
> That answer provides some guiding, basically you want to do something like:
> 
> ```
> fs.unlink(req.file.path, (err) => /* ... */)
> ```

"msg": "Cannot read property 'path' of undefined"
