### ISSUE TITLE
Mime type is not valid

### ISSUE THREAD

**Issue by zackyjack** [expressjs/multer#555]
multer only checks mime type based on file extension.

for example if i have code like this:

``` javascript
const multerOptions = {
  storage: multer.memoryStorage(),
  fileFilter(req, file, next) {
    const isImage = file.mimetype.startsWith('image/');
    if (isImage) {
      next(null, true);
    } else {
      next({ message: 'Only image is allowed' }, false);
    }
  },
}
```

then every time I upload a pdf file with an image extension (eg: `pdffile.png`), it will pass the filter. and vice versa if i upload image file without extension or with other extension (eg:` image.pdf `or just `image`), then error will be thrown.

for now I use [file-type](https://www.npmjs.com/package/file-type) package to check buffer, is there a more effective way?

**Comment by LinusU** [comment]
> multer only checks mime type based on file extension.

Actually, Multer uses whatever value the browser sends in the header. As you have discovered this shouldn't be trusted.

> is there a more effective way?

Not really, that is the recommended way.

Multer 2.x actually does this automatically for you, by only looking at the first chunk. See #399 for more info and a chance to try it out 🙌

**Comment by zackyjack** [comment]
> Actually, Multer uses whatever value the browser sends in the header. As you have discovered this shouldn't be trusted.

I use this for restful, so I upload the file via HTTP client, will it affect anything?

> Multer 2.x actually does this automatically for you, by only looking at the first chunk. See #399 for more info and a chance to try it out :raised_hands: 

Thank you, the Multer 2.x works greatly. When will it probably be launched?

**Comment by zackyjack** [comment]
this problem has been resolved in version 2, which is currently still alpha.

for now, in version 1, I use [file-type](https://www.npmjs.com/package/file-type) to check mime type directly from the buffer.

Thanks @LinusU

**Comment by zackyjack** [comment]
this problem has been resolved in version 2, which is currently still alpha.

for now, in version 1, I use [file-type](https://www.npmjs.com/package/file-type) to check mime type directly from the buffer.

Thanks @LinusU
