### ISSUE TITLE
Upload File from memoryStorage?

### ISSUE THREAD

**Issue by es50678** [expressjs/multer#557]
Is there a way to upload a file after it's been stored as a buffer using memoryStorage?
In this particular case the user chooses a file, then the app gets some information from the file, but only uploads the file after the user has double checked the information is all correct.
So first I stored the file in memory and now I'm looking for a way to store it using diskStorage.

I apologize if this isn't the best place to ask this question, I appreciate any feedback.

**Comment by reachdevelopers** [comment]
I am trying to do the same.

How I would handle this is store info about image first with just javascript before multer is used and on submit than upload the files.

**Comment by LinusU** [comment]
You could write the file to disk using [`fs.writeFile`](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback).

I would also recommend using [StackOverflow](https://stackoverflow.com) for questions like these...

Closing for now, but please feel free to reopen if you have any more questions.
