### ISSUE TITLE
Very strange behavior, multer freezes when used in testing with mock Date

### ISSUE THREAD

**Issue by rightaway** [expressjs/multer#558]
Here's a simple standalone example demonstrating this problem. The `await upload(ctx)` function call freezes indefinitely when using in testing with a mock Date. If you run this code you'll see `before` printed to the console but not `after`.

`sinon.useFakeTimers({ shouldAdvanceTime: false })` is the trigger of the problem. If you change `false` to `true`, then it works. Both `before` and `after` will appear on the console immediately.

Why does multer depend on the time advancing, rather than having a static fixed time? It doesn't seem like the time should cause any change in the behavior of multer.

This demo shows it using `koa` and `koa-multer`, but the same problem exists when using `express` and `multer` directly.

```js
const Koa = require('koa')
const multer = require('koa-multer')
const request = require('supertest')
const sinon = require('sinon')

const pathToFile = '/tmp/file.txt'

let app = new Koa()

app.use(async (ctx) => {
	const upload = multer().single('file')
	await upload(ctx)
})

app = app.listen();

(async function run() {
	sinon.useFakeTimers({ shouldAdvanceTime: false })
	console.log('before')
	await request(app)
		.post('/')
		.attach('file', pathToFile)
	console.log('after')
})()

```

**Comment by gireeshpunathil** [comment]
@rightaway - is this still an issue ?

**Comment by rightaway** [comment]
Yes can you reproduce it?

**Comment by gireeshpunathil** [comment]
no, I did not try - as it has been some time, I thought I will check first to see if this is still outstanding. Let me see what I can do. thanks for the follow up!

**Comment by rightaway** [comment]
No problem. Maybe it's an issue in the underlying `busboy` rather than `multer` itself, but I guess you'll be able to see that. :)

**Comment by helio-frota** [comment]
hi, 
I was able to reproduce the issue.
Branch created here https://github.com/helio-frota/hold-my-file/tree/multer-558

But after search for it, this I found: https://github.com/sinonjs/sinon/issues/1925#issuecomment-429106284

So it seems to be an issue related to the sinon/lolex usage only. 
So I think this issue can be closed :+1:
