### ISSUE TITLE
Stop/Prevent file upload if user not authorized

### ISSUE THREAD

**Issue by lorenzotsi** [expressjs/multer#56]
I'm looking for a way to prevent upload in case of not authenticated user

I'm using Express which is configured to use passport as auth middelware.

I thought to use onFileUploadStart to reject the file, but I cannot find a link with "request" object, with which it would be possible to match the user.

Thanks 
Lorenzo

**Comment by jpidelatorre** [comment]
@lorenzotsi You need to use multer per route instead of globally. (https://github.com/jpfluger/multer/blob/examples/multer-upload-files-to-different-directories.md)

Then you can add an auth middleware before multer like this:

    router.post('/uploads', function (req, res, next) {
        if (!authorized) {
            res.send(403);
        } else {
            next();
        }
    },
    multer({ dest: '/uploads/' }),
    function (req, res, next) {
       // whatever you were planning to do.
    });

I know it's late, but I hope it ends up helping someone.

**Comment by hailq** [comment]
But what happen if i need to parser the form data to get the authentication value? What should i do in this case?

**Comment by tsuuuuki** [comment]
![anime-sword-art-online-hd-1280x800](https://user-images.githubusercontent.com/38116582/61190402-491a2700-a661-11e9-90c0-f60d93f95dda.jpg)
