### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by anthonycluse** [expressjs/multer#565]
I get an issue using NodeJS to upload files with Multer.

The issue is appear when the connexion of the user is very slow, with a normal connexion everything works.

**Error message :**

    Bad Gateway
    The proxy server received an invalid response from an upstream server.
    Apache/2.4.7 (Ubuntu) Server at xxxxxxxxx Port 80

**My code :**

    app.use(multer({
      dest: './public/uploads/',
      limits: {
        fileSize: 10485760 // 10485760 octets = 10mo -- 7340032 octets = 7 mo -- = 819200 octets = 800 ko --- 102400 octets = 100 ko --- 5242880 octets = 5 mo
      },
      onFileSizeLimit: function(file) {
        console.log('Failed: ', file.originalname);
        fs.unlink('./' + file.path);
      },
      onFileUploadComplete: function() {}
    }));

I don't think that the issue is due to my NodeJS code but it could be an issue with Apache...

**Comment by gireeshpunathil** [comment]
@anthonycluse - is this still an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
