### ISSUE TITLE
setting ID to each file to trace back to a optional user?

### ISSUE THREAD

**Issue by ty893777** [expressjs/multer#573]
you can upload files to a set dest but there is no documented way to set given IDs to each uploaded file.

**Comment by bartius-nigel** [comment]
Hey ty893777, I believe this can be done by including some additional text info in the form data that you send to the backend. Then, when initializing your disk storage, you have access to the request, and so you can tack it on to the filename. See below:

1) create and send the request, source: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

var formData = new FormData(); // **_create a formData object_**
var fileField = document.querySelector("input[type='file']"); // **_grab the input element containing the file_** 

formData.append('username', 'abc123'); // **_this is additional info to the file upload. This is where you'll want to include IDs_**
formData.append('avatar', fileField.files[0]); // **_this is adding the file to the formdata_**

fetch('https://example.com/profile/avatar', { // **_and then using fetch, you can send it to the backend_**
  method: 'PUT',
  body: formData
})
.then(response => response.json())
.catch(error => console.error('Error:', error))
.then(response => console.log('Success:', response));

2) set up your multer disk storage, source: multer docs

var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, './public/images')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + path.extname(file.originalname)) // **_this is where you have access to the request body. log req.body to the console to see. You can then tack on any additional data to the filename_** 
  }
});

var upload = multer({ storage: storage });

3) Add your route:

router.put('/image', upload.single('avatar'), (req, res, next) => {
   // I don't think you need to do much here
})

Hopefully that actually works, I haven't done it directly, only similar things. Give it a shot and let me know!

**Comment by jonchurch** [comment]
Yep, this is an implementation detail left up to the user on purpose. The above example of using some data on the request object in the `filename` function can work, another way would be creating a unique ID for the filename (which multer does by default if you don't provide a filename function) and then associating that in a DB with the user or file.

Closing as resolved 👍
