### ISSUE TITLE
File saving at tmp folder even after specifying path to uploads

### ISSUE THREAD

**Issue by Santoshah** [expressjs/multer#577]
I have specified path to uploads folder which is present in my project root directory.
[http://prntscr.com/j2lr2o](screenshot of directory)
      `	const storage = multer.diskStorage({
			desitnation: function(req, file, cb){
				cb(null, "uploads/")
			},
			filename: function(req, file, cb){
				cb(null, file.originalname);
			}
	})`
Even after this my images is saved at tmp folder.

[http://prntscr.com/j2lre0](tmp folder)

Please help me.

**Comment by LinusU** [comment]
are you passing `storage` to the multer constructor?

**Comment by Santoshah** [comment]
Thank you for your reply.

I have already found the issue. The spelling of  `desitnation` is spelled wrong. It should be `destination`.

**Comment by LinusU** [comment]
hehe, classic JavaScript 😆 

I can recommend using TypeScript if you want to avoid this in the future 🚀

**Comment by Santoshah** [comment]
I am using sublime. Why sublime doesn't give spelling mistake errors ? By pressing F6 (spelling error shortcut key) also doesn't help with that.

**Comment by LinusU** [comment]
I don't think that Sublime can utilize type information. Not even sure if Atom can do that, at least not out of the box, but there is probably some plugin for it.

VS Code would have caught this error for you without any extra configuration:

<img width="494" alt="screen shot 2018-04-18 at 21 11 23" src="https://user-images.githubusercontent.com/189580/38955675-44e30594-434d-11e8-9d42-92031f63f678.png">

**Comment by Santoshah** [comment]
Wow. that's great. I would probably try VS code now.
Thanks @LinusU
