### ISSUE TITLE
Set different destination path

### ISSUE THREAD

**Issue by akshaypatil1** [expressjs/multer#58]
I'm not getting how to set different destination path for say different routes?
Example : app.post('/api/upload', function (req, res) {  // here i want destination as dest: './static/uploads/'

and app.post('/api/pic', function (req, res) {  // here i want destination as dest: './static/pic/

and app.post('/api/pdf', function (req, res) {  // here i want destination as dest: './static/pdf/'

**Comment by windmaomao** [comment]
thanks guys, i think moving files is not a bad idea for security or buffer reasons. I'll give it a shot. Interesting.

**Comment by NullArgument** [comment]
@windmaomao "i think moving files is not a bad idea" Yeah, keeping the server busy for something big that you will reject at the end is really cool.

**Comment by windmaomao** [comment]
@NullArgument well, it might not work for you, but how many system will have 10GB files in daily basis ? Aiming for 1% of requirement is something i don't want to be a developer :) Or maybe i just don't want to be developer. Since sometimes we're missing a lot of fun things.

**Comment by jpfluger** [comment]
I'm catching up on outstanding issues.... Since my original post, you guys have made compelling reasons why the developer should have more control over the upload directory. (Thanks!)  I've added an option in my local tests for it. I'll push as soon as I can test it.

**Comment by windmaomao** [comment]
thanks JP, appreciate your time. We're more looking for controlling the upload folder dynamically, ex. case by case depending on the file or req info. Or maybe just a pretty entry saying here is the file that is uploaded, do whatever you want with it. Either way will work.

**Comment by jpfluger** [comment]
The `renameDestDir` has now been added. Please see Multer's [README](https://github.com/expressjs/multer) for more info about it. Let me know if this works for you and then we can close this issue.

**Comment by Torone** [comment]
well done

**Comment by windmaomao** [comment]
this is better than i expected, thanks JP, btw, can we do file instead of dest in the renameDestDir parameters ? is this possible ? if it's too much trouble, then don't worry about it. Basically after the upload, we'd like to know all information of the file before we can make decisions on the folder name or structure.

**Comment by jpfluger** [comment]
When renameDestDir runs, the file object hasn't been created yet. Maybe a separate function would be better in which the file object is passed in for evaluation and then returned. Only then would its pathing would be created and it would continue to proceed.

A work around that **might** fit your situation: if you need to know all info about the file before making decisions on dir/folder, you could use `inMemory: true` and then write out the file yourself. The only issue is that keeping the file inMemory is (a) slower and (b) could have you run out of RAM at some point.

**Comment by windmaomao** [comment]
you are right JP, thanks for explaining that to me, now I see.

ok, if i really need some basic information, i can just look at file object inside req. that should do it for now. Asking a file object might be a wrong approach here anyway, sorry about the trouble, i think whatever you said makes sense.

**Comment by jpfluger** [comment]
Ok, I reread your question.... Yes, after the upload, `req.files` contains all the file objects. No changes are needed to access this list.

**Comment by jpfluger** [comment]
FYI:  In the source, we've renamed `renameDestDir` to `changeDest`, so when 0.1.8 is published to npm, you'll want to use `changeDest`.

**Comment by eduardocasas** [comment]
Perfect. `changeDest` works great!  Thank you very much!

**Comment by tkolsen** [comment]
Getting an error when trying to use changeDest:
Error: ENOENT, open 'my path'

my code:
```javascript
var express = require('express');
var multer = require('multer');
var router = module.exports = express.Router();
router.use(multer({
    dest: './uploads',
    changeDest: function(dest, req, res){
        dest += '/haha';
        return dest;
    },
    onFileUploadStart: function(file){
        console.log('starting');
    }
}));
router.post('/upload', sendResponse);
function sendResponse(req, res){
    res.send('ok');
};
```

**Comment by jpfluger** [comment]
Cool.

**Comment by DeepzSandra** [comment]
how to pass id in multer changedest

**Comment by JaayK** [comment]
Could anyone tell me, what's wrong with following code...!!!
while am running this, it has uploads the image but it doesn't save and even doesn't show where is going to be save....!!!!!!


pls help me to solve this issue, am tired of try this for 10 days... i just want to upload and save the file in folder/directory.!!!



router.post('/photo',[ multer(
  { 
    dest:'./uploads/',
        rename: function (fieldname, filename, req, res) {
           console.log(fieldname);
        console.log("=============");
       // console.log(req.body.can);
        console.log("=============");

        console.log(filename);
            //return filename.replace(/\W+/g, '-').toLowerCase() + Date.now()
                return filename
        },
        onFileUploadComplete: function (file, req, res) {
                 console.log(file.fieldname + ' uploaded to  ' + file.path)
               // res.json({"responseCode":1});
        },
        changeDest: function(dest, req, res) {
                 dest += '/uploads'+req.body.can;
                  if (!fs.existsSync(dest)) fs.mkdirSync(dest);
                  return dest;
        }

})
]);
  router.post('/photo', function (req, res) {
    id     : req.body.can
//console.log(req.body.can)
//;return;
        var form = {
            body: req.body,
            files: req.files
        }
        res.send(form);
    });

help will appreciate greatly,
thanks in advance guys...!!!

**Comment by bote795** [comment]
Is the changeDest still a parameter, couldn't find anything about it in the readme or searching through the code base.. 
Also, If it is available wouldn't it be bad to use fs.statSync, since its synchronous? 
wouldn't it be better to use fs.stat with a promise? 
sorry new and trying to utilize best practices

**Comment by JordyCuan** [comment]
Hi! I tried the solutions shown here but nothing helped me. I am developing a little server using express and my "boss" asked an uploads folder with users sub-folders and inside this folders, its uploaded files.

I want to share my solution (I am using express 4.13 and multer 1.2):

**Imports**:
```javascript
var express = require('express');
var router = express.Router();
var fs = require('fs');
var multer  = require('multer');
```

**Storage variable** (see documentation)
```javascript
var storage = multer.diskStorage({
	destination: function (req, file, cb) {
		var newDestination = 'uploads/' + req.user._username;
		var stat = null;
		try {
			stat = fs.statSync(newDestination);
		} catch (err) {
			fs.mkdirSync(newDestination);
		}
		if (stat && !stat.isDirectory()) {
			throw new Error('Directory cannot be created because an inode of a different type exists at "' + dest + '"');
		}		
		cb(null, newDestination);
	}
});
```


**Initializing Multer:**
```javascript
var upload = multer(
	{ 
		dest: 'uploads/',
		limits: {
			fieldNameSize: 100,
			fileSize: 60000000
		},
		storage: storage
	}
);
```

**Using it!**
```javascript
router.use("/upload", isAuthenticated);
router.use("/upload", upload.single("obj"));
router.post('/upload', controllers.upload_file);
```

**Comment by bote795** [comment]
@JordyCuan do you happen to know why i cant access the req.body params inside the destination function? Or how i should go about actually accessing it?

**Comment by atulmy** [comment]
@bote795 did you manage to access `req.body` params? I am not able to figure it out, even I tried changing the order that the client transmits fields.

Client:
```
let data = new FormData()
data.append('folder', 'product')
data.append('file', event.target.files[0])
```

**Comment by Mutharaju** [comment]
dest: 'uploads/', insteed can i possible to specify https://www.abcabc.in/assets/doc/journal/

**Comment by Roberto-LRivas** [comment]
Hola,  lo que funciono para mi fue:

Desde el frontEnd envía tu archivo binario al final del formData asi multer lo ultimo que procesara sera el binario.

Mi FrontEnd:
![image](https://github.com/expressjs/multer/assets/87246000/1d01ca6c-754e-4ae0-b490-07cc133081e9)

Mi backeEnd:
![image](https://github.com/expressjs/multer/assets/87246000/c54f1b91-a7af-48d9-b7b6-314310b65ad6)
