### ISSUE TITLE
Uploading blobs

### ISSUE THREAD

**Issue by o-t-w** [expressjs/multer#581]
I want to POST a blob to my node/express server with fetch. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) implies that a blob can be posted directly (I could only find documentation about XMLHttpRequest) 

"The send method of the XMLHttpRequest has been extended to enable easy transmission of binary data by accepting an ArrayBuffer, Blob, or File object."

```
var oReq = new XMLHttpRequest();
oReq.open("POST", url, true);
oReq.onload = function (oEvent) {
  // Uploaded.
};

var blob = new Blob(['abc123'], {type: 'text/plain'});

oReq.send(blob);
```

Can i do `fetch('/canvas', { method: 'POST', body: blob })`

or do I need to send as formData and use Multer? e.g.

`formData.append("blob", blob, "art.jpg");`

**Comment by LinusU** [comment]
Multer needs it to be a `FormData`, e.g. `formData.append('blob', blob, 'art.jpg')`.

Use the raw body parser if you just want the blob: https://github.com/expressjs/body-parser#bodyparserrawoptions
