### ISSUE TITLE
Which is the best way to store uploaded files to Mongodb using mongoose?

### ISSUE THREAD

**Issue by harishankards** [expressjs/multer#588]
Hi, I'm using multer and it works great. I'm now having the files being then to /uploads folder. Pretty great!

Now, I want to store the files in MongoDB, later I may switch to S3. I searched online, found a lot of ways, one of which is multer-grid-fs. But could not, decide which would be good for me. So, if you can suggest something, would be better.

**Comment by LinusU** [comment]
(multer-gridfs-storage)[https://github.com/devconcept/multer-gridfs-storage] looks very nice, I would recommend trying that one out.

GridFS is definitively the preferred way of storing binary files in MongoDB.

**Comment by harishankards** [comment]
Thanks, @LinusU! Will try that out.
