### ISSUE TITLE
How to delete/retrieve the uploaded files in /upload?

### ISSUE THREAD

**Issue by harishankards** [expressjs/multer#589]
Hi,

I have successfully configured and uploaded the file to `/upload` folder. Now, I want to retrieve those uploaded files and also want to know how to delete them. 

Thanks in advance.

**Comment by LinusU** [comment]
I would recommend looking at [`del`](https://github.com/sindresorhus/del).

If you need more help than that, I would recommend posting a question on StackOverflow, as that forum is more appropriate for broad questions like this that don't necessarily relate to the multer package.

**Comment by harishankards** [comment]
Yep, thanks @LinusU

**Comment by harishankards** [comment]
`fs.unlink(filepath)` worked great for me
