### ISSUE TITLE
ENOENT error when deploy to heroku

### ISSUE THREAD

**Issue by SamnnyWong** [expressjs/multer#591]
the error:
```
2018-05-12T05:47:21.500393+00:00 app[web.1]: HTTP request POST /api/postImage/ {}
2018-05-12T05:47:21.501779+00:00 app[web.1]: HTTP request undefined POST /api/postImage/ {}
2018-05-12T05:47:21.591203+00:00 app[web.1]: { Error: ENOENT: no such file or directory, open '/app/static/uploads/76cc729da26dc8da18cda7924fc5eaf31526104041562.png'
2018-05-12T05:47:21.591209+00:00 app[web.1]: code: 'ENOENT',
2018-05-12T05:47:21.591213+00:00 app[web.1]: syscall: 'open',
2018-05-12T05:47:21.591216+00:00 app[web.1]: path: '/app/static/uploads/76cc729da26dc8da18cda7924fc5eaf31526104041562.png',
2018-05-12T05:47:21.591217+00:00 app[web.1]: storageErrors: [] }
2018-05-12T05:47:21.591207+00:00 app[web.1]: errno: -2,
```
multer setup:
```
var multer = require('multer');
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, path.join(__dirname, '/static/uploads/'))
        // cb(null, "localhost:" + process.env.PORT + '/static/uploads/')
    },
    filename: function (req, file, cb) {
        crypto.pseudoRandomBytes(16, function (err, raw) {
            cb(null, raw.toString('hex') + Date.now() + '.' + mime.extension(file.mimetype));
        });
    }
});
var upload = multer({storage: storage});
```
and port is set to:
`var PORT = process.env.PORT || 3000;`
project structure:
<img width="172" alt="screen shot 2018-05-12 at 01 48 29" src="https://user-images.githubusercontent.com/2942477/39954082-fbe20966-5586-11e8-8092-6020e9481101.png">

what did i mess up?

Thanks in advance!

**Comment by LinusU** [comment]
It seems like the `/app/static/uploads/` directory doesn't exist. Might it be that the Heroku client doesn't upload empty folders? Or that it's ignored in some `.*ignore` file?

I would suggest creating the directory when the process starts for the first time:

```js
try {
  fs.mkdirSync(path.join(__dirname, '/static/uploads/'))
} catch (err) {
  if (err.code !== 'EEXIST') throw err
}
```

**Comment by kukode** [comment]
@LinusU  
my code 
const storage  = multer.diskStorage({
  destination : function(req,file,cb){
    cb(null,'./public/gambar/')
    
  },
  filename : function(req,file,cb){
    cb(null,file.fieldname + '-' + Date.now() + '.jpg')
  }
})
after im upload via application 
this path
http://batikmart.herokuapp.com/dashboard/product/uploads/flPhoto-1540382362434.jpg
not same with destination

**Comment by kukode** [comment]
so image crash and doesnt upload to path destination

**Comment by LinusU** [comment]
@kukode does the folder `gambar` exist?

**Comment by kukode** [comment]
Yes

**Comment by LinusU** [comment]
Could you change `'./public/gambar/'` to something like this?

```js
path.join(__dirname, 'public/gambar')
```

**Comment by kukode** [comment]
Yes i change to

**Comment by jawad-aziz-farhad** [comment]
I was having the same issue after deploying my **Mean Stack** app to heroku.
I was pushing the code with **empty uploads folder**. After adding a temporary file in uploads folder , Issue is gone.

**Comment by Harrys76** [comment]
> I was having the same issue after deploying my **Mean Stack** app to heroku.
> I was pushing the code with **empty uploads folder**. After adding a temporary file in uploads folder , Issue is gone.

saved my day, thank u very much... but why it happen tho?

**Comment by LinusU** [comment]
Seems like the problem is that Heroku strips empty folders. As mentioned, placing an empty file in the upload folder works around that 👍

**Comment by BrahimAkar** [comment]
> I was having the same issue after deploying my **Mean Stack** app to heroku.
> I was pushing the code with **empty uploads folder**. After adding a temporary file in uploads folder , Issue is gone.

You saved my life! thank you!

**Comment by abhijit-hota** [comment]
Thank you so much, everyone. Empty folders were indeed the case. 

I did some googling and found out that **Heroku doesn't exclude empty folders, Git does**. 
If you're using GitHub along with Heroku, you can clearly see that there are no empty folders. In Heroku CLI, if you do a `heroku run dir` , you can see the that the empty folders are missing. The usual workaround for this is to keep a file called `.gitkeep` in the empty folders.

Source: https://stackoverflow.com/a/44020216/12172493

**Comment by jorgerosal** [comment]
> It seems like the `/app/static/uploads/` directory doesn't exist. Might it be that the Heroku client doesn't upload empty folders? Or that it's ignored in some `.*ignore` file?
> 
> I would suggest creating the directory when the process starts for the first time:
> 
> ```js
> try {
>   fs.mkdirSync(path.join(__dirname, '/static/uploads/'))
> } catch (err) {
>   if (err.code !== 'EEXIST') throw err
> }
> ```

This saves my day. Thank you @LinusU

**Comment by dexeloper** [comment]
> I was having the same issue after deploying my **Mean Stack** app to heroku.
> I was pushing the code with **empty uploads folder**. After adding a temporary file in uploads folder , Issue is gone.

Thank you a million times!! It worked!!!!!!!!!!!!!!!!!

**Comment by hamudeshahin** [comment]
What about if i want to upload my images to heroku server ? without cloudinary or etc ... ? can we do that just with heroku server ?

**Comment by pupixipup** [comment]
> It seems like the `/app/static/uploads/` directory doesn't exist. Might it be that the Heroku client doesn't upload empty folders? Or that it's ignored in some `.*ignore` file?
> 
> I would suggest creating the directory when the process starts for the first time:
> 
> ```js
> try {
>   fs.mkdirSync(path.join(__dirname, '/static/uploads/'))
> } catch (err) {
>   if (err.code !== 'EEXIST') throw err
> }
> ```

You are amazing, thanks

**Comment by thiagoacmonteiro** [comment]
@jawad-aziz-farhad I love youuuuuu!
