### ISSUE TITLE
UTF-8 maybe a good choice for doc file?

### ISSUE THREAD

**Issue by nfer** [expressjs/multer#600]
```
file doc/*
doc/README-ko.md:    UTF-8 Unicode text, with very long lines
doc/README-zh-cn.md: Non-ISO extended-ASCII text, with very long lines
```
 
The README-zh-cn.md display badly in mac terminal and finder preview.
Maybe use UTF-8 could more friendly?

**Comment by LinusU** [comment]
Hmm, yeah UTF-8 would be preferred, pull request welcome 👍
