### ISSUE TITLE
how to save input data and image to Expressjs from an android application

### ISSUE THREAD

**Issue by uistacks** [expressjs/multer#601]
I have created web-service to add user data and image to mongodb using expressjs from an Android application, but not able to save it.
Either i'm able to save input data using (x-www-form-urlencoded).
or i'm able to upload image using (form-data).

Please provide me such solution, so i can upload image and save input data at a time.

I'm using meanjs for the same.

**Comment by LinusU** [comment]
`multipart/form-data` support uploading fields as well, which will be populated to `req.body`. I would recommend turning to StackOverflow on how to send that from Android...

**Comment by uistacks** [comment]
Hi,
I have already posted this question on stackoverflow, please check below URL.
https://stackoverflow.com/questions/50849603/how-to-save-input-data-and-image-to-mongodb-using-expressjs-from-an-android-appl
