### ISSUE TITLE
ENOENT: no such file or directory, while folder exist

### ISSUE THREAD

**Issue by sudarsan15** [expressjs/multer#605]
`
const storage = multer.diskStorage({
    destination: function (req, file, callBack) {
        callBack(null,'/Users/username/Desktop/projects/sampleproject1/testuploads');
    },
    filename: function(req, file, callBack) {
        console.log("req.file:"+ JSON.stringify (req.files));
        console.log("file:"+ JSON.stringify( file));
       
        var ext = file.originalname.split('.').pop();
        callBack(null, file.fieldname + '-' + curDateTime + '.' + ext);
    }
});

const uploadTagImage = multer({
	storage: storage, 
	limits: { fileSize: 3 * 1000 * 1000 } ,
	fileFilter: function(req, file, callBack) {
       var type = file.mimetype;
       if (type !== 'image/png' && type !== 'image/jpg' && type !== 'image/jpeg') {
        callBack(new Error('imageExtensionError'));
       } else {
        callBack(null, true);
       }
   	}
}).array('tagImage', 1)
`
I am getting following error : 

> `Error: ENOENT: no such file or directory, open '/Users/username/Desktop/projects/sampleproject1/testuploads/tagImage-1529589557350.png'`

Its validates the files as per the code but when coming to saving to folder i am facing this issue.

Form 
====

 <form  id="tag_create_form" name="tag_create_form" enctype="multipart/form-data">
     
 
            <div class="form-group">
                <label>Tag Image</label>
                <input type="file" name="tagImage" id="tagImage" class="form-control" placeholder="please enter tag Image">
            </div>
        
            <div class="form-group">
               <input type="button" name="submit" id="submit" value="create" class="btn btn-primary create-tag">

                <input type="reset" name="reset" id="reset" value="reset" class="btn btn-warning">
            <div>
        </form>
      </div>

**Comment by mfaheemakhtar** [comment]
Are you sure that this path exist?

"/Users/username/Desktop/projects/sampleproject1/testuploads/"

^ is your username is "username"?

**Comment by sudarsan15** [comment]
Well, it's actually not that .. but I have just renamed it before posting it. Anyways I have resolved it by giving different path

**Comment by BhojrajPathak001** [comment]
> Well, it's actually not that .. but I have just renamed it before posting it. Anyways I have resolved it by giving different path

how did you did that i got the same error using  multer
const fileStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    const destinationPath = "images/";
    console.log("Resolved destination path:", destinationPath);

    cb(null, destinationPath);
  },
  filename: (req, file, cb) => {
    cb(null, new Date().toISOString() + "-" + file.originalname);
  },
});
and it's giving  me  this errror
[Error: ENOENT: no such file or directory, open 'C:\Users\bhojraj pathak\Desktop\Node js\images\2024-05-13T10:05:18.854Z-me.jpg'] {
 errno: -4058,
 code: 'ENOENT',
 syscall: 'open',
 path: 'C:\\Users\\bhojraj pathak\\Desktop\\Node js\\images\\2024-05-13T10:05:18.854Z-me.jpg',
 storageErrors: []
}
i am getting this error even  through  i  have images folder in my Node js folder

**Comment by eliuakgg** [comment]
> > 嗯，其实不是那样的……但我在发布之前刚刚重命名了它。无论如何，我已经通过提供不同的路径解决了这个问题
> 
> 你是怎么做到的，我在使用 multer 时遇到了同样的错误 const fileStorage = multer.diskStorage({ destination: (req, file, cb) => { const destinationPath = "images/"; console.log("Resolved destination path:", destinationPath);
> 
> ```
> cb(null, destinationPath);
> ```
> 
> }, filename: (req, file, cb) => { cb(null, new Date().toISOString() + "-" + file.originalname); }, }); 它给了我这个错误 [错误：ENOENT：没有这样的文件或目录，打开'C:\Users\bhojraj pathak\Desktop\Node js\images\2024-05-13T10:05:18.854Z-me.jpg'] {  errno: -4058,  code: 'ENOENT',  syscall: 'open',  path: 'C:\Users\bhojraj pathak\Desktop\Node js\images\2024-05-13T10:05:18.854Z-me.jpg',  storageErrors: [] } 即使我的 Node js 文件夹中有图像文件夹，我也会收到此错误

我遇到和你一样的错误，可以仔细检查一下destination存放的路径位置。
