### ISSUE TITLE
Could not install multer via NPM.

### ISSUE THREAD

**Issue by manprajapat** [expressjs/multer#618]
![untitled](https://user-images.githubusercontent.com/20878896/42520791-d1b9bff8-8484-11e8-9623-f45a49278f7f.png)

This is my error log file.
saying some error in parsing json.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'multer' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose npm-session 042121868ae951be
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/multer 4035ms (from cache)
8 silly pacote tag manifest for multer@latest fetched in 4104ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule multer@1.3.1 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/append-field 1189ms (from cache)
15 silly pacote range manifest for append-field@^0.1.0 fetched in 1197ms
16 silly resolveWithNewModule append-field@0.1.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/busboy 3751ms (from cache)
18 silly pacote range manifest for busboy@^0.2.11 fetched in 3756ms
19 silly resolveWithNewModule busboy@0.2.14 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/concat-stream 3759ms (from cache)
21 silly pacote range manifest for concat-stream@^1.5.2 fetched in 3762ms
22 silly resolveWithNewModule concat-stream@1.6.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/xtend 3862ms (from cache)
24 silly pacote range manifest for xtend@^4.0.0 fetched in 3870ms
25 silly resolveWithNewModule xtend@4.0.1 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/mkdirp 3895ms (from cache)
27 silly pacote range manifest for mkdirp@^0.5.1 fetched in 3903ms
28 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/object-assign 3927ms (from cache)
30 silly pacote range manifest for object-assign@^3.0.0 fetched in 3933ms
31 silly resolveWithNewModule object-assign@3.0.0 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/dicer 1402ms (from cache)
33 silly pacote version manifest for dicer@0.2.5 fetched in 1408ms
34 silly resolveWithNewModule dicer@0.2.5 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/readable-stream 1461ms (from cache)
36 silly fetchPackageMetaData error for readable-stream@1.1.x Unexpected end of JSON input while parsing near '...":"readable-stream","'
37 silly saveTree mongo@0.0.0
37 silly saveTree +-- cookie-parser@1.4.3
37 silly saveTree | +-- cookie-signature@1.0.6
37 silly saveTree | `-- cookie@0.3.1
37 silly saveTree +-- debug@2.6.9
37 silly saveTree | `-- ms@2.0.0
37 silly saveTree +-- ejs@2.5.9
37 silly saveTree +-- express@4.16.3
37 silly saveTree | +-- accepts@1.3.5
37 silly saveTree | | +-- mime-types@2.1.18
37 silly saveTree | | | `-- mime-db@1.33.0
37 silly saveTree | | `-- negotiator@0.6.1
37 silly saveTree | +-- array-flatten@1.1.1
37 silly saveTree | +-- body-parser@1.18.2
37 silly saveTree | | +-- bytes@3.0.0
37 silly saveTree | | +-- content-type@1.0.4
37 silly saveTree | | +-- depd@1.1.2
37 silly saveTree | | +-- http-errors@1.6.3
37 silly saveTree | | | +-- inherits@2.0.3
37 silly saveTree | | | +-- setprototypeof@1.1.0
37 silly saveTree | | | `-- statuses@1.4.0
37 silly saveTree | | +-- iconv-lite@0.4.19
37 silly saveTree | | +-- on-finished@2.3.0
37 silly saveTree | | | `-- ee-first@1.1.1
37 silly saveTree | | +-- qs@6.5.1
37 silly saveTree | | +-- raw-body@2.3.2
37 silly saveTree | | | +-- http-errors@1.6.2
37 silly saveTree | | | | +-- depd@1.1.1
37 silly saveTree | | | | `-- setprototypeof@1.0.3
37 silly saveTree | | | `-- unpipe@1.0.0
37 silly saveTree | | `-- type-is@1.6.16
37 silly saveTree | |   `-- media-typer@0.3.0
37 silly saveTree | +-- content-disposition@0.5.2
37 silly saveTree | +-- content-type@1.0.4
37 silly saveTree | +-- depd@1.1.2
37 silly saveTree | +-- encodeurl@1.0.2
37 silly saveTree | +-- escape-html@1.0.3
37 silly saveTree | +-- etag@1.8.1
37 silly saveTree | +-- finalhandler@1.1.1
37 silly saveTree | | `-- parseurl@1.3.2
37 silly saveTree | +-- fresh@0.5.2
37 silly saveTree | +-- merge-descriptors@1.0.1
37 silly saveTree | +-- methods@1.1.2
37 silly saveTree | +-- on-finished@2.3.0
37 silly saveTree | +-- parseurl@1.3.2
37 silly saveTree | +-- path-to-regexp@0.1.7
37 silly saveTree | +-- proxy-addr@2.0.3
37 silly saveTree | | +-- forwarded@0.1.2
37 silly saveTree | | `-- ipaddr.js@1.6.0
37 silly saveTree | +-- qs@6.5.1
37 silly saveTree | +-- range-parser@1.2.0
37 silly saveTree | +-- safe-buffer@5.1.1
37 silly saveTree | +-- send@0.16.2
37 silly saveTree | | +-- destroy@1.0.4
37 silly saveTree | | `-- mime@1.4.1
37 silly saveTree | +-- serve-static@1.13.2
37 silly saveTree | +-- setprototypeof@1.1.0
37 silly saveTree | +-- statuses@1.4.0
37 silly saveTree | +-- type-is@1.6.16
37 silly saveTree | +-- utils-merge@1.0.1
37 silly saveTree | `-- vary@1.1.2
37 silly saveTree +-- http-errors@1.6.3
37 silly saveTree +-- mongoose@5.1.6
37 silly saveTree | +-- async@2.6.1
37 silly saveTree | | `-- lodash@4.17.10
37 silly saveTree | +-- bson@1.0.9
37 silly saveTree | +-- kareem@2.2.1
37 silly saveTree | +-- lodash.get@4.4.2
37 silly saveTree | +-- mongodb@3.0.10
37 silly saveTree | | `-- mongodb-core@3.0.9
37 silly saveTree | |   `-- require_optional@1.0.1
37 silly saveTree | |     +-- resolve-from@2.0.0
37 silly saveTree | |     `-- semver@5.5.0
37 silly saveTree | +-- mongoose-legacy-pluralize@1.0.2
37 silly saveTree | +-- mpath@0.4.1
37 silly saveTree | +-- mquery@3.0.0
37 silly saveTree | | +-- bluebird@3.5.0
37 silly saveTree | | +-- regexp-clone@0.0.1
37 silly saveTree | | `-- sliced@0.0.5
37 silly saveTree | +-- regexp-clone@0.0.1
37 silly saveTree | `-- sliced@1.0.1
37 silly saveTree +-- morgan@1.9.0
37 silly saveTree | +-- basic-auth@2.0.0
37 silly saveTree | `-- on-headers@1.0.1
37 silly saveTree +-- multer@1.3.1
37 silly saveTree | +-- append-field@0.1.0
37 silly saveTree | +-- busboy@0.2.14
37 silly saveTree | | `-- dicer@0.2.5
37 silly saveTree | +-- concat-stream@1.6.2
37 silly saveTree | +-- mkdirp@0.5.1
37 silly saveTree | +-- object-assign@3.0.0
37 silly saveTree | `-- xtend@4.0.1
37 silly saveTree `-- node-cron@1.2.1
38 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...":"readable-stream","'
38 verbose stack     at JSON.parse (<anonymous>)
38 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
38 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
38 verbose stack     at process._tickCallback (internal/process/next_tick.js:178:7)
39 verbose cwd E:\mongo
40 verbose Windows_NT 10.0.16299
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "multer"
42 verbose node v10.0.0
43 verbose npm  v5.6.0
44 error Unexpected end of JSON input while parsing near '...":"readable-stream","'
45 verbose exit [ 1, true ]

**Comment by LinusU** [comment]
Could it be that your `package.json` is malformed?

**Comment by manprajapat** [comment]
Issue is solved. Clearing npm cache fixed my problem.

**Comment by prasadInnovate369** [comment]
> npm cache clean --force

not worked
