### ISSUE TITLE
Upgrading from 0.1.7 to 1.0.0 middleware initilization changed?

### ISSUE THREAD

**Issue by ceastman-ibm** [expressjs/multer#619]
I need to upgrade from multer 0.1.7 to 1.0.0 to resolve a vulnerability. 

My current code is:
const multer = require('multer');
const app = express();
app.use(multer());

when my test cases run I get the following error:
TypeError: app.use() requires a middleware function

**Comment by LinusU** [comment]
The API of the library has changed, please see the readme on how to use this version ☺️
