### ISSUE TITLE
Res to rename file

### ISSUE THREAD

**Issue by Enishowk** [expressjs/multer#620]
Hello,

I have a question about Multer. Is it possible to retrieve the Response object from Express in the file rename function?

I use this route here: ` app.post("/companies/upload", ensureAuthenticated, upload, CompanyController.upload);`

I have a first Middleware (ensureAuthenticated) that decrypts the token, and returns the user ID in the object `res.locals.token`.
So, i want to rename the file with the id of the user or his company and so, to make a request before renaming it.

Like this for example:

```
var storage = multer.diskStorage({
  filename: function (req, file, cb) {
    // Get id but RES is not available.
   const {id} = res.locals.token
    // Do the request, for example : 
    const user = await userRepository.findOne({where: { id: sub }, relations: ["company"]});
    cb(null, user.company.id) 
  }
})
```

Can i do that (pass the res object) ? Or is it possible to rename the file AFTER in the next middleware ?
Or the only way is to pass company.id from front in file object ?

Thanks. :smile:

**Comment by LinusU** [comment]
I think you can access the Response on `req.res`

**Comment by Enishowk** [comment]
Yes, it's good ! Thank you very much !

So, I have another question. If upload is sucess but after i have a problem with insert name in database, its possible to delete the file upload with multer ? Of i must do that with FS in node ? :)

**Comment by LinusU** [comment]
You need to do that manually with FS :)

**Comment by Enishowk** [comment]
Thanks :) I close it.
