### ISSUE TITLE
Multer uploads the file uploaded from angular (stores in the drive) but doesnot execute next funtion 

### ISSUE THREAD

**Issue by snj-adhikari** [expressjs/multer#623]
File was uploaded from the angular and accepted by multer i can see the file on disk where i have set the destination but it doesn't give any response or execute another function in the sequence of the route.

**Comment by snj-adhikari** [comment]
`//My angular side code is following 


  foodAdd(value) {
    this.httpHeaders = new HttpHeaders;
    this.setHeaders('cat_id', value.cat_id);
    console.log("the httpoptions is", this.httpOptions);

    // Object.keys(value).forEach(key => formdata.append(key, value[key]));
    var formdata = this.convertFormDataForFood(value);
   

    return this.http.post(CloudConfig.serverUrl.concat(CloudConfig.branchRoute).concat('menu/add'), formdata, this.httpOptions);

  }
  convertFormDataForFood(object) {
    console.log("the form value is" , object);
    let  newFormData = new FormData();
    console.log("the food is " , object.food);
    newFormData.set('food', object.food , object.food.name);
    newFormData.append('name', object.name);
    newFormData.append('price', object.price);
    newFormData.append('description', object.description);
    newFormData.append('url', object.url);
    newFormData.append('photo', object.photo);
    newFormData.append('cat_id', object.cat_id);
    // console.log("the form we created is " , newFormData);
    return newFormData;
  }


// backend side is code is following 


var storage = multer.diskStorage({
  destination: function(req, file, cb) {
      var dest ='public/uploads/';
      mkdirp.sync(dest); 
      cb(null, dest);
  },
  filename: function(req, file, cb) {
      crypto.pseudoRandomBytes(16, function(err, raw) {
          cb(null, raw.toString('hex') + Date.now() + '.' + mime.getExtension(file.mimetype));
      });
    }
});

var upload = multer({
  storage: storage,
  limits: {
    fieldNameSize: 999999999,
    fieldSize: 999999999
  },
});

app.use('/branch/v1' ,
//   middleWareController.requireLogin , middleWareController.checkBranchAdmin ,
 function(req,res,next){
	upload.single('food')(req , res , function(err){
		console.log("inside multer fnction");
		if(err){
			return res.json({success:false , msg:"Error " , err:err });
		}
		else {

			return res.json({success:true , msg:"Successfully on next step"});  
 /* some image doesnot reach upto this step when uploaded with angular but same image tried with postman works just fine */
			next();
		}
	 });

 }  , branchRoute) ;


`

**Comment by LinusU** [comment]
> some image doesnot reach upto this step when uploaded with angular but same image tried with postman works just fine

Unfortunately, this doesn't really seem to be a problem with Multer, but rather with Angular. The backend code looks correct, and I'm not familiar with Angular so I cannot really help you there...
