### ISSUE TITLE
req.body in destination function  get empty when using multer.diskStorage

### ISSUE THREAD

**Issue by AlanKnightly** [expressjs/multer#626]
> I'm trying to dynamically mkdir to save some file when a request come in,but I find that  I cant get the formdata from req.body object. For example,code below get two '{}' empty object.
```
var storageAvatar = multer.diskStorage({
  destination: function (req, file, cb) {
    console.log('this is req.body')    
    console.log(req.body)
    let avatarPath = path.join(__dirname,`/asserts/${req.body.uid}/avatar`);
    if (!fs.existsSync(avatarPath)) {
            fs.mkdirSync(avatarPath);
    }
    cb(null, avatarPath)
  },
  filename: function (req, file, cb) {
    console.log('this is req.body')    
    console.log(req.body)
    cb(null, file.originalname)
  }
})
var uploadAvatar = multer({ storage: storageAvatar });
exports.avatarMiddleWare= uploadAvatar.single('avatar');
...
```

**Comment by LinusU** [comment]
From the documentation:

> Note that `req.body` might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

I wish I had an easy solution for you but the only thing I can recommend is to manually reorder the fields with javascript to make sure that fields are sent before files.

This has come up a number of times before, e.g. #146 where the workaround is outlined...

**Comment by BayoKwendo** [comment]
No tangible solution on this?
