### ISSUE TITLE
Req.body contains invalid data when uploading text file

### ISSUE THREAD

**Issue by AdamT213** [expressjs/multer#629]
When i try to upload a csv file, then console.log(req.body) to get its contents, I see an object like this: {"foobar"}. Since there are no keys or values, I cannot parse the csv string contained inside.

**Comment by LinusU** [comment]
How are you uploading the file? What does your multer code look like?

You should have the file on `req.file` (or `req.files` if accepting multiple files)...

**Comment by AdamT213** [comment]
Here is the code: 

const csv = require('csvtojson');
const multer  = require('multer');
const upload = multer();

router.post('/distributor/:id/upload', upload.single('newFile'), function (req, res, next) {
  req.setTimeout(600000);
  console.log(req.body)
  console.log(req.file) 
  next()
}, function (req, res, next) { 
  csv()
    .fromFile(req.file.path)
    .subscribe((csvLine) => {
      console.log(csvLine); 
    })
    // // //   // item.distributor_id = req.params.id 
    // // //   // Product
    // // //   // .forge(item.body)
    // // //   // .save()
    // // //   // .then((product) => {
    // // //   //   res.json({id: product.id});
    // // //   // })
    // // //   // .catch((error) => {
    // // //   //   console.error(error);
    // // //   //   return res.sendStatus(500);
  res.end() 
})  

If I console.log req.body, I get all the text from the file, but in an object with no keys or values, so I can't use it. If I console.log(req.file), I get undefined, and if I try to set csv.fromFile(req.file.path), I get an error saying "Cannot read property 'path' of undefined"

**Comment by AdamT213** [comment]
Before I was using bodyParser. I saw in another issue that using bodyParser with multer will not work, so I commented it out. Now, I don't get a body object, or  a file object, or a files object. I tried using upload.none() and sending the same file in the request, to see if I could get it to error out with the message "LIMIT_UNEXPECTED_FILE", but it did not, so it seems multer does not even recognize that a file is being sent. I am testing this in Postman, with the content-type set to false and the body as binary with a file attached. Is there something wrong with trying to test the request that way?

**Comment by AdamT213** [comment]
I see now that the body object I was getting was being populated by bodyParser before, so it makes sense that it was invalid, because bodyParser is not supposed to handle multipart/form-data. But multer doesn't seem to be processing the request at all! Could this be due to a conflict with another package? Here are the package configurations: 

const _ = require('lodash');
const path = require('path');
const bodyParser = require('body-parser');
const express = require('express');
const cookieParser = require('cookie-parser');
const session = require('cookie-session');
const knex = require('knex');
const passport = require('passport');
const LocalStrategy = require('passport-local').Strategy;
const flash = require('connect-flash');
const csv = require('csvtojson');
const multer  = require('multer');
const upload = multer();
const ENV = process.env.NODE_ENV || 'development';
const config = require('../knexfile');
const db = knex(config[ENV]);
require('dotenv').config()

// Initialize Express.
const app = express();
const router = express.Router();
// create application/json parser
const jsonParser = bodyParser.json()

// create application/x-www-form-urlencoded parser
const urlencodedParser = bodyParser.urlencoded({ extended: false })
app.use(session({ secret: 'some secret' }));
app.use(flash());
app.use(cookieParser());
app.use(passport.initialize());
app.use(passport.session());
app.use('/api', router);
