### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by BlueOctober** [expressjs/multer#631]
1. Is there a file size limitation in multer specification besides limits in upload?
(I use diskStation instead of memory.)
2. When using diskStation, does multer manage its memory by reading and writing its own stream?

**Comment by LinusU** [comment]
1. No
2. Could you clarify what you mean here? `diskStorage` will write files using a `fs.WriteStream` so the file will not be kept in memory.

**Comment by BlueOctober** [comment]
Is it true that there is no upload failure due to memory?

**Comment by LinusU** [comment]
If you are using `diskStorage` there should be no failure due to memory.

It will only keep small chunks of the file in memory at a time, so even when uploading huge files it shouldn't use that much memory at all.
