### ISSUE TITLE
Originalpath of the uploaded file

### ISSUE THREAD

**Issue by louloup22** [expressjs/multer#633]
Is it possible to have the originalpath (instead of only originalname) of the uploaded file (ie where the root where the file is stored in our local computer when we upload the file). I thought that setting preservePath: true would hep but it did not change anything ?

**Comment by LinusU** [comment]
Hmm, I'm not 100% sure of this, but I don't think that the browser sends that information to us.

**Comment by louloup22** [comment]
OK thanks
