### ISSUE TITLE
how to validate input field before uploading process using multer.

### ISSUE THREAD

**Issue by itsgracian** [expressjs/multer#640]
here is my code
//
const mongoose = require('mongoose');
const multer = require('multer');
const FroalaEditor = require('wysiwyg-editor-node-sdk/lib/froalaEditor.js');
const sizeOf = require('image-size');
const path = require('path');
const fs = require('fs');
const hashids = require('hashids');
const hash=new hashids();
//require models
const Product=require('../models/productModel');
const Image=require('../models/productImageModel');
const Status=require('../models/statusModel');
const Category=require('../models/categoryModel');
const Tag=require('../models/tagModel');

//@multer setup
const errors='Image files must be jpg,png or jpeg';
const Storage=multer.diskStorage({
  destination:function(req,file,cb){
    cb(null,'./public/uploads/');
  },
  filename:(req,file,cb)=>{
    cb(null,file.fieldname+'-'+Date.now()+'-'+file.originalname);
  }
});
//check file extension
const fileFilter=(req,file,cb)=>{
  if (file.mimetype==='image/jpeg'||file.mimetype==='image/jpg'|| file.mimetype==='image/png') {
    cb(null,true);
  }else {
    cb(errors,false);
  }
};
//@set multer storage and fields
const upload=multer({
  storage:Storage,
  fileFilter:fileFilter
}).fields([{name:'img1',maxCount:1},{name:'img2',maxCount:1},
          {name:'img3',maxCount:1},{name:'img4',maxCount:1}]);
exports.saveProduct=(req,res,next)=>{
  upload(req,res,function(err){
    if(err){
        console.log(err);
    }
  req.checkBody('productName','product name is required').notEmpty();
  req.checkBody('category','category is required').notEmpty();
var errors=req.validationErrors();
    if (errors) {
      productError(req,res);
      for(var i in errors){
      req.flash('errors',errors[i].msg);
      }
      res.redirect('/dashboard/product/setup');
    }
       console.log(req.body);
    console.log(req.files);
 
})

**Comment by LinusU** [comment]
I think that you are better of posting these kinds of questions to StackOverflow, good luck ☺️
