### ISSUE TITLE
Android client uploads file in a different way than a browser does.

### ISSUE THREAD

**Issue by asedsami** [expressjs/multer#645]
When I upload a file with the browser, it works perfectly. the file get's uploaded, renamed and saved.    
But when android uploads the file, the `destination` and `filename` functions in diskStorage does not even execute. and multer throws no error.    
I used `formidable` and `connect-busboy` and I came to the understanding that these two packages give me two variables. `files` and `fields`(alongside `file` event and `field` event). android was uploading the 'file' in a 'field' which triggered the `field` event and so it seems that's why multer doesn't save the uploaded file.
I think it's like he's sending
`<input name="somefile" />`
instead of
`<input name="somefile" type="file" />  `
and so he's sending the file in a text field.

my question is, what should the android client change in his request? is it a Header he should set?

**Comment by turakvlad** [comment]
Are you sure that your Android application sends the `content-type` header equals to `multipart/form-data`?

**Comment by jonchurch** [comment]
Was this ever resolved? I'm going to close for now as it's not strictly related to multer.

If you have more questions feel free to comment here

**Comment by asedsami** [comment]
I don't know how but the Android developer solved it somehow.
