### ISSUE TITLE
Multer HELP | Can't get sperarte filename based on fieldname 

### ISSUE THREAD

**Issue by TheNexusDesigns** [expressjs/multer#649]
What I try to do is select let's say:

 - Upload 1 - that has a fieldname of upfile1
 - Upload 2 - that has a fieldname of upfile2
 - Upload 3 - that has a fieldname of upfile3

basically, I need to select every uploaded filename item of the multi upload app separately using my app code because every upload needs to be handled differently in my app for different tasks. Let's use console.log as an example I need to have an option to use something like:

 - console.log(file.upfile1.filename);
 - console.log(file.upfile2.filename);
 - console.log(file.upfile3.filename);

to select the different items that get handle in my app using different fieldname that are defined in my views using the name attribute.

**below is my code** 

### Views [index.html]
> <form class="fileupload" action="upload" method="post" enctype="multipart/form-data">
    <h1>Multi File Uploads</h1>
    <input type="file" name="upfile" value="">
    <input type="file" name="upfile2" value="">
    <input type="file" name="upfile3" value="">
    <input type="submit" />
  </form>

### NodeJS [app.js]
> app.get("/", function(req, res) {
      res.sendFile(__dirname + "/index.html");
}); 
app.post("/app", upload.any(), function(req, res) {
    let files = req.files;
       files.forEach(file => {
       console.log(file.filename);
    });
   res.send(req.files);
   res.end();
   });

help would be very appreciated!

**Comment by LinusU** [comment]
You can use the [`find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) method to find the specific file:

```js
const file3 = req.files.find(file => file.fieldname === 'upfile3')
```
