### ISSUE TITLE
Large File Handling (eg 2.5 MB file) Slower When InMemory is True

### ISSUE THREAD

**Issue by jpfluger** [expressjs/multer#65]
When inMemory is true and file.buffer is larger than 64 Kb, there is an "issue" that I don't think is fixable right now b/c it's the way Node.js currently allocates memory for large buffers. (see [StackOverflow](http://stackoverflow.com/questions/12523125/how-fast-can-the-method-write-of-writable-stream-in-node-js-be-called) and [this blog](http://blog.andrewvc.com/node-js-and-binary-data)) 

In multer/master, I have mocha tests (see test/inmemory.js) that can be used to test this issue. When running, the multi-file upload test take an average of 1 second. Compare this to the write-to-disk multi-file upload taking 100 ms. In local tests, I changed-up my inMemory Buffer code to a writable stream and piped the filestream directly to it but still would get 1 second performance. I don't think my test hardware is to blame (i7-4810MQ w/ 32 Gig RAM on SSDs).

I also ran the tests against the latest node in development 0.11.14 but there's a bug preventing mocha from completing. Need to keep an eye on this b/c TJ wrote "[there's been] significant performance work done in core features (Buffers, TLS, streams)." [reference](https://www.joyent.com/blog/node-js-and-the-road-ahead) 

Hopefully I'm wrong with this issue and someone knowing more about how core streams/Buffers work can suggest ways to improve inMemory performance for large buffers.

**Comment by IsaiahJTurner** [comment]
Buffer is null for me. Is that normal?

**Comment by jpfluger** [comment]
If `inMemory` is true and the buffer is null, this is not normal.  If the default setting is used (where `inMemory` is false), then yes it is normal.  Maybe it's the latter?

**Comment by LinusU** [comment]
I'm not sure that this is an issue anymore with never node. From the blog:

> UPDATE: None of this should be necessary, as FileReadStream in the latest node uses buffers by default. However, it appears that either I'm doing something wrong or the docs are out of date, as it doesn't work that way on node HEAD.

We are using buffers internally in `1.0.0`.

Please reopen if you feel that this is still an issue.
