### ISSUE TITLE
err.response.data doesn't contain err.message, only err.code

### ISSUE THREAD

**Issue by sarpik** [expressjs/multer#654]
My fileFilter function is set up to only allow files up to 2 MB of size, else, the following is executed:

express backend:

router.post("/", passport.authenticate("jwt", { session: false }), (req, res, next) => {
//...
upload(req, res, (err) => {
  if (err) {
    // assume that I got a 'LIMIT_FILE_SIZE' error. 
    console.log(err.message); // => 'File too large'
    return res.status(400).json(err);
}
})

//...

});

in my front end

**Comment by LinusU** [comment]
That's how `Error` instances works with `JSON.stringify`, use this package to work around it: https://www.npmjs.com/package/serialize-error

**Comment by sarpik** [comment]
Hey, sorry, I posted the issue too soon, here's the full issue's description /\
