### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by muturgan** [expressjs/multer#657]
I working with file uploading on my project now.

I tried lot of multipart parsers, and I understood that multer is the best.

But multiparty has one feature that very usefull and multer has not it.
Parsed file in multiparty has some fields and file's own headers among them (in addition to the request headers), that includes content-type. Of cause, I can checking file extantion for filtering, but file's own headers are very usefull too.

it would be great if you add this feature in multer.

**Comment by LinusU** [comment]
You can look at e.g. `req.file.mimetype` to see which `Content-Type` the client sent for that file ☺️

**Comment by LinusU** [comment]
In `2.0.0-alpha.6` you can look at `detectedMimeType` and `clientReportedMimeType`

**Comment by muturgan** [comment]
Well, thank you for the usefull info!

I will try it tomorrow in the workplace.
