### ISSUE TITLE
Decipher / Cipher Stream with request() to API with multer produces an error

### ISSUE THREAD

**Issue by Ncifra** [expressjs/multer#660]
Hello,

We have two API's in Node.js. The first one acts as the main hub, while the other one is used to send emails.

Currently I have some files that are encrypted and stored in the file system of the first API. The files get decrypted with the following function:

```
decryptFile: function (filePath, callback) {
                var fileName = path.basename(filePath);
                var encryptedFilePath = path.dirname(filePath) + '/' + this.encryptText(fileName);
                // input file
                var fileDecipher = encryptionKeys.crypto.createDecipher(encryptionKeys.algorithm, encryptionKeys.password);
                var r = fs.createReadStream(encryptedFilePath);
                r.on("error", function (err) {
                    if (err) {
                        callback(err);
                    }
                });
                // return decrypted content
                return callback(null, r.pipe(fileDecipher));

        }
```

To send the files we use:

```
utils.files.decryptFile(fullPath, function (err, decryptedFile) {

requestOptions = {
            url: pushAPIURL + 'email/send',
            method: "POST",
            formData: {
               attachments: [decryptedFile]
            },
            headers: {
                authorization: global.PUSHToken
            }
        };
        return request(requestOptions);
});
```

Due to this we receive:

>     Error: Part terminated early due to unexpected end of multipart data

on the mail API

Any idea as to what may be wrong?

Thanks

**Comment by LinusU** [comment]
Are you sure that the `request` function accepts `formData.attachments` as an array of streams?

**Comment by LinusU** [comment]
Aha, I think it's because it can only take streams that have a known length. You can see the logic here:

https://github.com/form-data/form-data/blob/017017813917aaeee928a50e6c7e5f3af5ab7c2f/lib/form_data.js#L116-L151

If you know the length of the deciphered data, you can probably fake it by doing something like:

```
fileDecipher.fd = -1
fileDecipher.start = 0
fileDecipher.end = THE_LENGTH
```

Closing since this isn't related to anything inside of Multer ☺️

**Comment by Ncifra** [comment]
I don't know why I didn't receive an email about this. 

Is there a way to know beforehand the size of the file, or calculate it? Considering the fact the default fs.readStream works for the unencrypted file, is there any behind the scenes that I can use to calulcate the size of the file?

Thank you

**Comment by LinusU** [comment]
I would recommend posting to StackOverflow with that question. It probably depends on which type of encryption you are using...

**Comment by Ncifra** [comment]
Just in case somebody comes to this, I opened the same issue for this on form-data, where I also posted the solution:
https://github.com/form-data/form-data/issues/409
