### ISSUE TITLE
upload with curl

### ISSUE THREAD

**Issue by Wildflyy** [expressjs/multer#666]
I have a minimal example done with express.js but I cant get it to work. here is my routes/index.js:
```
var express = require('express');
var router = express.Router();

var multer              = require("multer");
var upload              = multer({ destination: './'})

router.post('/restapi', upload.single('weg'), function(req, res, next){
  console.log("here");
  console.log(req.file);
  console.log(req.body);

  if(!req.file){
    res.json({"error": "not working"});
    return;
  }

    res.json({"error": "test"});
    return;
});

router.get('/', function(req, res, next) {
  res.json({ "title": "Express" });
  return;
});
module.exports = router;
```
I want to upload a file to the server with the command:

> curl -F weg=@weg.txt localhost:port/restapi; echo
>{"error":"not working"}

and my output on the server side is:

> > node ./bin/www
> 
> here
> undefined
> {}
> POST /restapi 200 17.450 ms - 23
> here
> { fieldname: 'weg',
>   originalname: 'weg.txt',
>   encoding: '7bit',
>   mimetype: 'text/plain',
>   buffer:

So the file does get uploaded eventually but before the server returns to the client with the error message "not working" because req.file is undefined.
Can anyone help?

**Comment by LinusU** [comment]
Seems like the route is triggered twice for some reason, have you removed all other code and just run this file? What happens if you minimize it to just:

```js
var express = require('express');
var router = express();

var multer              = require("multer");
var upload              = multer({ destination: './'})

router.post('/restapi', upload.single('weg'), function(req, res, next){
  console.log("here");
  console.log(req.file);
  console.log(req.body);

  if(!req.file){
    res.json({"error": "not working"});
    return;
  }

    res.json({"error": "test"});
    return;
});

router.get('/', function(req, res, next) {
  res.json({ "title": "Express" });
  return;
});

router.listen(() => console.log('http://localhost:3000/'), 3000)
```

and then run just that file?

**Comment by Wildflyy** [comment]
Thank you for your reply. I set up the file you suggested, though with a minor change at the end to get it to run:
`router.listen(3000, function () {
  console.log('Example app listening on port 3000!');
})`
However, I get the same result:

> here
> undefined
> {}
> here
> { fieldname: 'weg',
>   originalname: 'weg.txt',
>   encoding: '7bit',
>   mimetype: 'text/plain',
>   buffer:
>...

**Comment by LinusU** [comment]
I tried creating that file, installing express and multer, and running the same curl command as you. For me it seems to work as it should 🤔 

<img width="644" alt="screenshot 2018-10-12 at 13 09 09" src="https://user-images.githubusercontent.com/189580/46866036-0a301a00-ce20-11e8-9c3f-dbe6a2d067f4.png">

<img width="408" alt="screenshot 2018-10-12 at 13 08 55" src="https://user-images.githubusercontent.com/189580/46866042-0d2b0a80-ce20-11e8-8f8b-4943dc8f0a43.png">

<img width="304" alt="screenshot 2018-10-12 at 13 09 15" src="https://user-images.githubusercontent.com/189580/46866047-1025fb00-ce20-11e8-902f-b26af3122294.png">

Which version of Node.js are you using?

**Comment by Wildflyy** [comment]
Hey,
I am using:
 node v10.11.0
 express v4.16.0
multer v1.4.0

**Comment by LinusU** [comment]
Can you add a middleware just before multer that simply logs something, that way we can see if that line is being called more than once...

```diff
 var upload              = multer({ destination: './'})

+const logRequest = (_, __, ___, next) => { console.log('request received'); next() }
+
-router.post('/restapi', upload.single('weg'), function(req, res, next){
+router.post('/restapi', logRequest, upload.single('weg'), function(req, res, next){
   console.log("here");
```

**Comment by Wildflyy** [comment]
I added your suggestion but with minor adapdation to create a log:
`//const logRequest = (_, __, ___, next) => { console.log('request received'); next() }
const logRequest = (_, __, ___, next) => { console.log('request received'); }

router.post('/restapi', logRequest, upload.single('weg'), function(req, res, next){

  logRequest();
  console.log("here");
`
My result is:

> Example app listening on port 8080!
> request received
> here
> undefined
> {}
> request received
> here
> { fieldname: 'weg',
>   originalname: 'weg.txt',
>   encoding: '7bit',
>   mimetype: 'text/plain',
>   buffer:
> ....

But I am not sure that is what you wanted to see. When I don't add the "logRequest();" it doesn't log. If I add "loqRequest();" with your orignial suggestion I get a TypeError "next is not a function".

**Comment by Wildflyy** [comment]
I ran another test using Postman and there the example we set up works just fine. So I suppose it has something to do with my cURL. I am sorry for the inconvenience but I wouldn't have guessed that something is wrong on that side.
