### ISSUE TITLE
req.file.buffer is sometimes not a Buffer

### ISSUE THREAD

**Issue by axelpale** [expressjs/multer#667]
As [discussed in another issue](https://github.com/expressjs/multer/issues/461#issuecomment-428011146) with @LinusU, we found that sometimes `req.file.buffer` is not a Buffer but an empty array `[]`. This happens because Multer does not explicitly set stream concatenation encoding. I faced the issue when a buggy client program uploaded an empty stream and the server applied Multer to handle it. The server expected `req.file.buffer` to be a buffer but it was not and thus errors began flooding in.

By looking the source of [MemoryStorage](https://github.com/expressjs/multer/blob/master/storage/memory.js) and its dependency [concat-stream](https://github.com/maxogden/concat-stream/blob/master/index.js) it becomes somewhat clear that `concat-stream` can return a non-buffer empty array when encoding is not explicitly set to `buffer` and the stream is empty. It seems that this is the case i.e. that Multer does **not** explicitly set that, forcing `concat-stream` to try infer the encoding.

I suppose that in Multer's `memory.js` we should replace the following line:

    file.stream.pipe(concat(function (data) {

with this:

    file.stream.pipe(concat({ encoding: 'buffer' }, function (data) {

to force the `req.file.buffer` to always be a Buffer.

**Comment by LinusU** [comment]
Fixed in `1.4.1`, thanks!
