### ISSUE TITLE
can i use Multer without Express?

### ISSUE THREAD

**Issue by sadeghrz** [expressjs/multer#674]
hi can use multer with simple node js http server without express?

**Comment by LinusU** [comment]
That should be possible, just call the middleware directly with `req`, `res`, and a callback 👍

**Comment by sadeghrz** [comment]
great! it's worked
thank you

**Comment by tjabdoullah** [comment]
Could you please share how you made it work?

**Comment by sadeghrz** [comment]
> Could you please share how you made it work?

you can do it like with something like this:

const multer = require('multer');
multer({ 
        multer.diskStorage({ options }),
        limits: { fileSize: 1000000 },
        fileFilterCB
    }).single('file');

but if you want to upload file without express, i preferred you to use this:
https://github.com/felixge/node-formidable

**Comment by tjabdoullah** [comment]
Thank you!!

**Comment by AGSTRANGER** [comment]
> > Could you please share how you made it work?
> 
> you can do it with something like this:
> 
> const multer = require('multer');
> multer({
> multer.diskStorage({ options }),
> limits: { fileSize: 1000000 },
> fileFilterCB
> }).single('file');
> 
> but if you want to upload file without express, i preferred you to use this:
> https://github.com/felixge/node-formidable

But, how can I acced the information like I would usually do with express request:  
`app.post('/uploadfile', upload.single('myFile'), (req, res, next) => {
   // Can I access the file information without req.file??
   const file = req.file
   if (!file) {
     const error = new Error('Please upload a file')
     error.httpStatusCode = 400
     return next(error)
   }
     res.send(file)
   
 })`

**Comment by farrukh-develo** [comment]
Do this
` upload.single('myFile')(req,res,(err)=>{
  if(err) console.log('error uploading file',err)
  console.log('file uploaded',req.file)
})`
