### ISSUE TITLE
How to check if image file is submitted by user or not

### ISSUE THREAD

**Issue by sundarkrish** [expressjs/multer#676]
When I don't submit image file ,the req.file is undefined under upload(req,res,function(err){ });
But no error is thrown.When I try to access req.file.path it shows cannot access path of undefined.
Is there a way to validate the text fields along with file field ?

**Comment by LinusU** [comment]
You can check whether or not `file` is defined, and throw an error appropriately:

```js
if (!req.file) {
  return next(new Error('Missing mandatory file'))
}

// rest of the code...
```

**Comment by sundarkrish** [comment]
Okay thanks.What is a good approach in case of REST apis for large size (> 50mb) uploads in node js?

**Comment by LinusU** [comment]
Multer shouldn't have a problem with any size on the file. I would recommend creating a post on StackOverflow if you want to get some recommendations on API design...

**Comment by sundarkrish** [comment]
Okay I will do that.So multer does streaming of contents  from the client side ,as soon as it arrives at the server?

**Comment by LinusU** [comment]
> So multer does streaming of contents from the client side [...]

Yes ☺️
