### ISSUE TITLE
using busboy body parser with multer

### ISSUE THREAD

**Issue by vipinrana** [expressjs/multer#683]
Iam using busboy body parser to parse the multipart form data. So Iam getting the fields like name, username key values in req.body and files in req.files. But Iam unable to upload files to the directory using multer.
`app.use(busboyBodyParser());`
`app.post('/createUser', (req, res) => {`

  `console.log(req.body);`
  `console.log(req.files);`
   `const storage = multer.diskStorage({`
     `destination: './public/uploads/',`
     `filename: function (req, file, cb) {`
       `cb(null, file.fieldname + '-' + Date.now() + path.extname(file.originalname));`
     `}`
   `});`
   `const upload = multer({`
      `storage: storage`
   `}).single(req.files['uploadpic']);`
   `upload(req, res, (err) => {`
   `});`
`});`

**Comment by LinusU** [comment]
You cannot use both Busboy and Multer as they both consume the request stream. You'll have to pick one of them ☺️

**Comment by vipinrana** [comment]
@LinusU thanks it worked now.
