### ISSUE TITLE
High Response Time: Heroku/Syslog drain

### ISSUE THREAD

**Issue by MihaiZhaoDev** [expressjs/multer#685]
NodeJS, ExpressJS, Multer on Heroku

Hi guys! I have a post form which uploads an image aprox. 9MB, it takes about 20-30 seconds to upload and Heroku continuously gives me alerts about High Response Time: Heroku/Syslog drain.

Is this a normal behaviour from multer and Heroku is not aware?

Everything works on the server there are not any issues, I get the image on server. The only thing is the Heroku alert which triggered me a sign of concern.

2018-11-01 10:25:54.548
336 <158>1 2018-11-01T10:25:54.209784+00:00 heroku router - - at=info method=POST path="/portal/profile/change-cover" host=www.example.co.uk request_id=ece4cd7e-3d42-4cde-838d-f9d633f64d81 fwd="XX.102.245.XXX" dyno=web.1 connect=0ms service=12468ms status=302 bytes=429 protocol=https

**Comment by Guziq** [comment]
Additional info from the Heroku's support team member (we also had a lot of **H18**):

> H18's mean that the client closed the connection before the server responded. There are multiple reasons for this to occur (including the browser closing the window or a cell phone losing signal). Unless there are other issues here that are being reported, I wouldn't worry too much about the H18 for now.

**Comment by jonchurch** [comment]
Closing as inactive. Let us know if you are still experiencing this or found a solution ❤️
