### ISSUE TITLE
Associative array of uploads

### ISSUE THREAD

**Issue by Ncifra** [expressjs/multer#688]
Is it possible to have an array of images, that instead of them being numerically indexed, req.files[0], req.files[1]..., to have them in an associative array like req.files['lang1'], req.files['lang2'], etc. This could be done with the filenames in the request being in typical array structure: document['lang1'], document['lang2'], and so on. 

This structure would help to have a dynamic way of getting the files, without hard coding name variations and checking manually.

Can this be done currently, or, if not, I think it would be a nice addition.

**Comment by LinusU** [comment]
You can always use the `.any()` function to accept any field names at all

**Comment by Ncifra** [comment]
Yes, I tested it, and this allows to bypass the name filter. And to do what I said above, you need to "play" with the `fieldname` and the square brackets, or any other naming convention for that matter. That fulfills the needs indeed.

Still I think having the type of naming convention used by express in the `req`, where the square brackets in the name are used to create Array/Object like variables, would be helpful.

**Comment by philBrown** [comment]
It's unfortunate that the same field name handling used for non-file fields cannot be applied to the files as well.

For example, sending something like
```html
<input name="foo[bar][baz]" value="test" />
```
results in `req.body` having a structure like
```js
{
  "foo": {
    "bar": {
      "baz": "test"
    }
  }
}
```

but using a file field and `.any()`
```html
<input type="file" name="foo[bar][baz]" />
```
results in `req.files` looking like
```js
[
  {
    "fieldname": "foo[bar][baz]",
    //...
  }
]
```

What are you using to handle the structured field names for non-files?

**Comment by philBrown** [comment]
FYI, I wrote a tiny piece middleware to make this nicer using Lodash's `.set()`

```ts
const mapFiles: RequestHandler = (req, _res, next) => {
  if (Array.isArray(req.files)) {
    req.files = req.files.reduce(
      (map, { fieldname, ...file }) => set(map, fieldname, file),
      {}
    );
  }

  next();
};
```
