### ISSUE TITLE
MulterError: Unexpected field

### ISSUE THREAD

**Issue by zoukie33** [expressjs/multer#690]
Hello, 
i've tried to upload a file with postman, but i get an "MulterError: Unexpected field", i search in all issues and i see all the time this is the field name. But for me i put the good filedname in postman and in my code.

here my code (sorry for screens, my first time posting code in issues):

![image](https://user-images.githubusercontent.com/5038862/49307669-2d994c00-f4d6-11e8-8a12-c4c691da3566.png)

here my postman request:
![shitappend](https://user-images.githubusercontent.com/5038862/49307299-05f5b400-f4d5-11e8-8c3b-f588192d9b74.jpg)

Thank your for the help.

**Comment by zoukie33** [comment]
hello again,
i've done what you told me, and i get: "This is the invalid field -> pic".
but the file field in postman is goo and in the code too.

![field_error](https://user-images.githubusercontent.com/5038862/49387863-25821c00-f723-11e8-8e83-97a9eb502008.jpg)

**Comment by LinusU** [comment]
Hmm, interesting 🤔 

Could it be that there is more than one muter attached as a middleware somehow? It's hard for me to tell since I can't see the entire code...

That's the only thing I can think of, otherwise, could you try and reduce this to the absolute minimal code that's required to show this behaviour and upload somewhere, and then I could take a look at it 👀

**Comment by zoukie33** [comment]
> Could it be that there is more than one muter attached as a middleware somehow? It's hard for me to tell since I can't see the entire code...

hum i dont really know, but i have jwt protection for this routes, and i have an invalid Access if i dont put this in my app.js :
`app.use(upload.array());
app.use(express.static('public'));
app.use('/files', express.static('files'));`

I've tried without upload.array(), not working and with .none() the same.
this in my app.js can be the problem, but without that i can't access to the route.

for now i just uploaded the 3 files concerned about this problem, if you want i can make you a working version without all my routes (because if you run my api without everything behind this won't work ^^).

here the files
https://ufile.io/c3yp2

my app is working on ubuntu server:  Ubuntu 18.04.1 LTS

**Comment by LinusU** [comment]
```js
app.use(upload.array());
```

This line is probably the problem, it shouldn't be there as it will catch all files uploaded to any route and then complain that that they have the wrong field (since none was supplied to that function).

**Comment by zoukie33** [comment]
ok, so what can i do to fix that ? cause if i dont put it in my add.js, et post route who need an upload cant be reach if this is not here ... 
the solution can be do an app.use on multer + the configurations needed (storage etc), but how can i use it next in multiples routes ?

**Comment by LinusU** [comment]
You should be able to remove the `app.use(upload.array())` but keep the `, upload.single('pic'), ` part. Is there anything that doesn't work when you do that?

**Comment by zoukie33** [comment]
I've already try it, it i remove the app.use(upload.array()), there is a conflic with my jwt securrity, i have an error 401 (Invalid Access). All the routes who need an auth pass through this function:

```javascript
var verifyToken=function (req, res,next) {
	var token = req.body.token || req.query.token || req.headers['token'];
	 if (token) {
		jwt.verify(token, config.secret, function (err, currUser) {
			if (err) {
				res.send(err);
			} else {
				req.currUser = currUser;
				next();
			}
		});
	}
	 else {
		res.status(401).send("Invalid Access");
		console.log("User rejeté");
	}
};
```

but as you can see, in postman there is the token. did i need to put multer bnefore jwt auth ? It's not very safe in my case ... :/

**Comment by zoukie33** [comment]
I will try, I will come back to you as soon as possible

**Comment by wachukxs** [comment]
> ```js
> app.use(upload.array());
> ```
> 
> This line is probably the problem, it shouldn't be there as it will catch all files uploaded to any route and then complain that that they have the wrong field (since none was supplied to that function).

fixed the problem. Thanks a whole lot

**Comment by bogadrian** [comment]
Let me help here if I can. I had same problem. 2 hours to understand the error. When I was sending the Postamn field as photo, I had there some space after inserting photo in form-data ame field. so multer was returning the erro every time as it wasn't able to much photo (some white space) with upload.single('photo') in my code. I solved this by changing the name from photo in only p, in Postamn and in my app upload.single('p')  Too stupid error but so hard to detect.

**Comment by wilson-faustino** [comment]
I was having the same error message.

In my case the problem was that I was using "upload.single('productImage')" in Node JS and in Postman I was using 'prodImg' inside the file field.

I changed the file field name to 'productImage' so that would match "upload.single('productImage')".

Now I get no more error messages.

**Comment by jonchurch** [comment]
Closing as original thread went inactive. This is a common error, if you experience it yourself try some of these solutions and if you you're still stuck you'll get more visibility opening a new issue ❤️

**Comment by cvallejoec** [comment]
This worked for me. I also add the field name in my `component.ts`
`public uploader:FileUploader = new FileUploader({
    url: 'http://localhost:3000/api/upload',
    itemAlias: 'yourFieldName',
  });`

**Comment by jrschumacher** [comment]
I had to change my usage of `upload.array('files')` to `upload.array('files[]')`

**Comment by webafra** [comment]
i same problem.
if create two file input for upload ( thumbnail and gallery  input ) but send three file ( avatar or any other input name )  , give this error !

this method is not resolve if send correct input name ( thumbnail or gallery )
(err, req, res, next)


this method give error after send not send correct input name :
(req, res, next)

!!!!!

please help me.

**Comment by jrschumacher** [comment]
@webafra have you tried the approaches listed above? For instance my comment on Apr 12.

**Comment by webafra** [comment]
> @webafra have you tried the approaches listed above? For instance my comment on Apr 12.

No, my inputs are different.
For example, I send a picture to Avatar and a PDF file.
In this case, Malter makes a mistake and does not allow the process to continue.

**Comment by jrschumacher** [comment]
@webafra Please create a codesandbox.io example showing your issue. There is no way to assist you based on your description.

**Comment by osadasami** [comment]
I got the same issue and solve it. Your input name should me the same as `upload.single('inputName')`

```html
<input id="inputfield" type="file" name="upfile">
```

```js
app.post('/api/fileanalyse', upload.single("upfile"), (req, res) => { 
  res.json({
    "name": req.file.originalname,
    "type": req.file.mimetype,
    "size": req.file.size
  })
})
```

**Comment by kuldeepchopradotnet** [comment]
i getting this problem then i did this step 

just removed this 
app.use(upload.array());
or put this line after registering all routes 

![image](https://user-images.githubusercontent.com/47147176/87847536-bb69bb00-c8f6-11ea-99a0-bf23032dd397.png)

**Comment by mdaijaj** [comment]
i have same issue how can be solve please tell me if you know i am stucking whole day.

app.post('/upload', (req,res)=>{
    upload(req, res, err =>{
        if(err){
            console.log(err)
        }else{
            console.log(req.file)
        }
})

**Comment by julix-unity** [comment]
@mdaijaj  Stuck the whole day and can't be bothered to format the question? 

Check out some of the answers above, such as https://github.com/expressjs/multer/issues/690#issuecomment-645977419

**Comment by Julix91** [comment]
@mdaijaj  Stuck the whole day and can't be bothered to format the question? 

Check out some of the answers above, such as https://github.com/expressjs/multer/issues/690#issuecomment-645977419

**Comment by matheus1987** [comment]
> Let me help here if I can. I had same problem. 2 hours to understand the error. When I was sending the Postamn field as photo, I had there some space after inserting photo in form-data name field. so multer was returning the error every time as it wasn't able to match photo (some white space) with upload.single('photo') in my code. I solved this by changing the name from photo in only p, in Postamn and in my app upload.single('p') Too stupid error but so hard to detect.

Thank you! It was the same error for me!

**Comment by isais1** [comment]
> ```js
> app.use(upload.array());
> ```
> 
> This line is probably the problem, it shouldn't be there as it will catch all files uploaded to any route and then complain that that they have the wrong field (since none was supplied to that function).

Thanks!

**Comment by nikhils4** [comment]
If anyone wants to upload multiple files using multer and getting unexpected field error, try replacing `upload.array('image')` to `upload.any('image')`.

**Comment by tatianajiselle** [comment]
Thanks @osadasami -> knowing the field name is the same as the `upload.single('inputName')` saved me!

**Comment by Chanondler** [comment]
> I had to change my usage of `upload.array('files')` to `upload.array('files[]')`
@jrschumacher 
Doesn't work in my case.
`uploadImage.array('photos', 10),`
or
`uploadImage.array('photos[]', 10),`
<img width="1043" alt="Screenshot 2020-10-30 at 4 00 48 PM" src="https://user-images.githubusercontent.com/57944922/97694774-151e7b80-1ac9-11eb-819c-14412f75b256.png">

**Comment by lazycipher** [comment]
> ```js
> app.use(upload.array());
> ```
> 
> This line is probably the problem, it shouldn't be there as it will catch all files uploaded to any route and then complain that that they have the wrong field (since none was supplied to that function).

It saved my day! didn't help directly but I knew what to look for after that i.e overridden config!!
Thanks a ton!

**Comment by guidorearte** [comment]
`router.post("/", upload.single("avatar"), async (req, res) => {
  try {
    // Upload image to cloudinary
    const result = await cloudinary.uploader.upload(req.file.path);

    // Create new user
    let user = new User({
      name: req.body.name,
      avatar: result.secure_url,`

Look for the parameter avatar of the first line with the object user is avatar too!

**Comment by Maximization** [comment]
If you're getting the error `MulterError: Unexpected field` and are stuck, read what others have suggested in this thread. In particular:

- Triple-check(!) the file input name [matches *exactly* the argument passed to the multer middleware function](https://github.com/expressjs/multer/issues/690#issuecomment-645977419). Pay special attention to whitespace.
- [Some clients might append `[]` to the input name if it there are multiple files](https://github.com/expressjs/multer/issues/690#issuecomment-612745883) (thanks to @jrschumacher)
- [Make sure there are no conflicting multer instances](https://github.com/expressjs/multer/issues/690#issuecomment-444177975) (thanks to @LinusU)
- If the client is sending multiple file inputs, you need to tell multer about *all* of them for the request to be valid. You can configure multer to accept multiple fields with `fields(fields)` method, where `fields` is an array of objects with a `name`, and optionally `maxCount`, key.
- Multer throws the same error if the number of files uploaded exceeds `maxCount`. If you're using a middleware function that allows multiple files to be uploaded (`array()` or `fields()`), make sure the number of files uploaded doesn't exceed `maxCount`.
- You can [extract more details from the Multer error and find the invalid field](https://github.com/expressjs/multer/issues/690#issuecomment-443749868) to pinpoint the issue. (thanks to @LinusU)

I've compiled a list of common reasons for this error (including solutions) and turned it into an article:
**📚 [Fix "Unexpected field" Error From Multer](https://maximorlov.com/fix-unexpected-field-error-multer/)**

Hopefully you fix the error and finally have working file uploads in Node.js using multer. 🌟

**Comment by julesntare** [comment]
> ```js
> app.use(upload.array());
> ```
> 
> This line is probably the problem, it shouldn't be there as it will catch all files uploaded to any route and then complain that that they have the wrong field (since none was supplied to that function).

Ewana aha urandokoye musaza

**Comment by Dmaina5054** [comment]
I am having a similar problem but my api service does not have a html form since i intend to use it using flutter.
![issue](https://user-images.githubusercontent.com/43588385/168631240-748cceba-8803-408e-ba73-15540ee641da.png)
![twoo](https://user-images.githubusercontent.com/43588385/168631381-b22d6642-3d7e-4217-b058-005d9ebd594d.png)
![errorpost](https://user-images.githubusercontent.com/43588385/168631479-d7940234-dc5c-499b-af01-6a7f9e4e750f.png)

**Comment by Davidon4** [comment]
I encountered this error after 24hours of headache and fixing and scattering my code and was finally able to solve this, I discovered that multer stopped working with newer versions of some packaging, Mine was with express-jwt (with the newer version not taking function as the middleware) so what i did was install the older version and voila it worked for me.

**Comment by dyary98** [comment]
> If anyone wants to upload multiple files using multer and getting unexpected field error, try replacing `upload.array('image')` to `upload.any('image')`.

This worked for me, Thank you so much
