### ISSUE TITLE
The bug for  picture width and height exchange

### ISSUE THREAD

**Issue by loveJSON** [expressjs/multer#692]
The picture in pc，width=2250px, height=4000px
but use formData upload ，multer  get  the picture，width=4000px,   height=2250px

**Comment by LinusU** [comment]
Multer doesn't know anything about the files except that it's a collection of bytes, if the image is being rotated that must be happening somewhere else I'm afraid.

**Comment by albinekb** [comment]
If you are uploading images via iOS/Android you could be hitting this issue: https://stackoverflow.com/questions/10600613/ios-image-orientation-has-strange-behavior 

Check the exif data of the image you upload and try with another image from another source to rule out that this is the issue.

**Comment by LinusU** [comment]
@loveJSON it could have something to do with the EXIF data, maybe the viewer you are using on the PC reads the exif data and rotates the image for you? Whereas your viewer on the server doesn't?

In any case, it shouldn't be Multer that changes the file ☺️

**Comment by loveJSON** [comment]
I did the test, and only when the pictures were too big did the width swap occur

**Comment by loveJSON** [comment]
HI：
I don't know why, only when the big picture is big will the problem recur.
You can try it


thanks





------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2018年12月4日(星期二) 晚上9:00
收件人: "expressjs/multer"<multer@noreply.github.com>;
抄送: "微风@浪子"<741452843@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [expressjs/multer] The bug for  picture width and height exchange(#692)




@loveJSON it could have something to do with the EXIF data, maybe the viewer you are using on the PC reads the exif data and rotates the image for you? Whereas your viewer on the server doesn't?
 
In any case, it shouldn't be Multer that changes the file ️

**Comment by albinekb** [comment]
I think this library can help you: https://www.npmjs.com/package/jpeg-autorotate

**Comment by loveJSON** [comment]
Thank you very much.
I used ImageMagick，Get the picture information Orientation:'RightTop', size: { width: 4000, height: 2250 },
But I don't know where the problem is.
