### ISSUE TITLE
Keeping the folder structure from the request

### ISSUE THREAD

**Issue by craigcartmell** [expressjs/multer#706]
I'm using react-dropzone to upload a folder as per the documentation [here](https://react-dropzone.netlify.com/#dropzone-for-folders).

Example structure of the folder:
```
- packages.json
- src
    - index.js
```

The client receives the full file and directory structure with each file prefixed with the source folder, e.g. `package.json` and `src/index.js`. However when posting the data as FormData to the server, mutler only shows the filename, not including the folder, so I can only access `package.json` and `index.js` but I'd like to be able to access `src/index.js`.

Is there any way around this?

**Comment by LinusU** [comment]
Do you know what name is being sent over the wire? If the full name is being sent to the server we should be able to read that 🤔 

You can check using e.g. the Chrome network inspector

**Comment by craigcartmell** [comment]
Yep according to the network panel, it's sending the full file path including folders. I'll upload an image when I get chance.

I actually got around this by sending another array field as form data with the full file paths. I could then match these up on the server.

```
 storage: multerS3({
    s3: s3,
    bucket: process.env.S3_BUCKET,
    contentType: multerS3.AUTO_CONTENT_TYPE,
 
    key: function(req, file, cb) {
      const {
        body: { meta },
      } = req

      const filename = meta[key]

      cb(null, `${keyPrefix}${filename}`)
    },
  }),
```

**Comment by edgarogh** [comment]
I'm having the same problem. The form data that is sent looks like this: 
![image](https://user-images.githubusercontent.com/46636609/52878697-8c797380-315d-11e9-920b-edee02c1a0fe.png)
But the `req.files` array contains the "flattened" names. The directory structure is missing and that's very annoying...

**Comment by edgarogh** [comment]
To keep the path in the response, add `preservePath: true` to the _multer_ setup:
```javascript
const upload = multer({ preservePath: true });
```
Hope this helps !

**Comment by LinusU** [comment]
@edgarogh that's awesome, had forgotten we had that 😄 

it's in the docs as well: https://github.com/expressjs/multer#multeropts

**Comment by craigcartmell** [comment]
Ah, how did I miss that. Cheers!
