### ISSUE TITLE
Progress tracking, stream piping

### ISSUE THREAD

**Issue by cyrilchapon** [expressjs/multer#707]
Hey,

I just came to an hard topic...

I rolled my own google-drive-piper engine this way :

```
class GoogleDriveMulterStorage {
  constructor (jwtClient) {
    this._jwtClient = jwtClient
    this._drive = gapi.google.drive({
      version: 'v3',
      auth: this._jwtClient
    })
  }

  async __handleFile (req, file) {
    return this._drive.files.create({
      requestBody: {
        name: file.originalname,
        mimeType: file.mimetype
      },
      media: {
        body: file.stream,
        mimeType: file.mimetype
      }
    })
  }

  _handleFile (req, file, cb) {
    this.__handleFile(req, file)
      .then(res => cb(null, {
        id: res.data.id,
        kind: res.data.kind
      }))
      .catch(err => cb(err))
  }

  _removeFile (req, file, cb) {}
}

module.exports = GoogleDriveMulterStorage
```

And I'm using it with axios on the frontend like this :

```
  const data = new window.FormData()
  data.append('file', fileDescriptor, fileDescriptor.name)

  return axios.post(`/api/v1/file`, data, {
    onUploadProgress: (evt) => {
      if (evt.loaded && evt.total) {
        const progress = (evt.loaded / evt.total) * 100

        // Here
        console.log(progress)
      }
    },
    headers: {
      'Content-Type': `multipart/form-data; boundary=${data._boundary}`
    }
  })
     // And here
    .then(res => console.log('Done'))
```

The trouble is, the progress is acting very very fast (but seems working), but the "done" event occurs largely after the 100% is reached... Like so :

```
> 10%
> 20%
> 30%
> 50%
> 80%
> 100%
>
> // (1 second elapsed)
> 
> Done !
> // (15 seconds elapsed)
```

This is kinda strange, I'm suspecting this is because the read stream is somehow "not paused" (caching it somehow...) and the writeable stream on gdrive is longer to process (this would be consistent, as I'm running the server locally, and gdrive is remote).

2 questions :
- How can I make the progress reflect the actual handling progress ?
- Is that wanted ? What happens if the file would be 1TB of data, the multer read-stream blazing-fast and the Gdrive write stream deadly-slow ?

**Comment by gireeshpunathil** [comment]
@cyrilchapon - is this still outstanding?

**Comment by cyrilchapon** [comment]
@gireeshpunathil

No sorry, forgot to close. This was a known issue with google drive package and its underlying gaxios dependency. You can find out the issue typing "node Google drive backpressure" in google

Closing
