### ISSUE TITLE
Multer uploads file to destination folder but gives "CANNOT GET" error while reading.

### ISSUE THREAD

**Issue by maddy2894** [expressjs/multer#708]
I am trying to upload image into disk storage and read from it, multer successfully uploads image into destination folder but when reading it gives "Cannot GET /Users/maddy/Documents/GitHub/test-upload/imagetest1547435367640" error. 

Anyone faced with same issue? 

Multer code:
`const multer  = require('multer');`
  `const storage = multer.diskStorage({`
 ` destination: function (req, file, cb) {`
   ` cb(null, '/Users/maddy/Documents/GitHub/test-upload');`
 ` },`
 ` filename: function (req, file, cb) {`
    `cb(null, file.fieldname + 'test' + Date.now().toString());`
 ` }`
`});`
`const upload = multer({ storage: storage });`
`module.exports = upload;`

service code:
`const imageUpload = require('../services/image-upload');`
`const singleUpload = imageUpload.single('image');`
`module.exports = function(app) {`
  `app.post('/api/user/save-details', auth.jwtRefreshToken, saveDetails);`
  `app.post('/api/image-upload', auth.jwtRefreshToken, imageUploadRoute);`
`};`
  `function imageUploadRoute(req, res) {`
 ` const userId = req.userId;`
 ` if (typeof userId !== 'string') {`
    `return res.status(422).json({message: 'Error in UserId'});`
 ` }`
  `singleUpload(req, res, function(err) {`
  `  if (err) {`
      `return res.status(422).send({errors: [{title: 'Image Upload error', detail: err.message}]});`
   ` }`
    `User.findOne({_id: userId})`
       `.then((user) => {`
         `console.log(req.file);`
         ` user.profileImage = req.file.path;`
          `return user.save()`
             ` .then(() => {
                return res.status(200).send({message: 'Image Uploaded Successfully'});
              })
              .catch(() => {
                return res.status(500).send({message: 'Error in uploading image'});
              });
        })
        .catch(() => {
          return res.status(500).send({message: 'UserId not found'});
        });
  });
}`

I am not implementing GET API, instead I assign the file path to user and call user details in another component.

**Comment by gireeshpunathil** [comment]
@maddy2894 - is this still an issue ?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
