### ISSUE TITLE
TypeError: next is not a function

### ISSUE THREAD

**Issue by bogere** [expressjs/multer#710]
I happen to be getting this kind of error when i upload the files.
i have been using multer package  for long time without any issues.
`NodeJS version- v6.11.4
multer -1.4.1`

`TypeError: next is not a function
    at multerMiddleware (/user_code/node_modules/multer/lib/make-middleware.js:18:41)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:726:7
    at /var/tmp/worker/worker.js:709:11`

**Comment by bogere** [comment]
No iam not using express.
It seems that currently firebase storage does not support multer and express formidable basing on they way they handle the req.files object which firebase functions does not consider.
One can read nore [here](https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase).

**Comment by LinusU** [comment]
> No iam not using express

Unfortunately for you, this module is made to work with Express.

If it's quite straight forward, we could potentially accept a pull request to add support for Google Cloud Functions, but we would need a way to test that on the CI then...

So basically, I would accept a PR to add support, but currently we don't support non-express based setups ☺️
