### ISSUE TITLE
Trying to upload muliple files using the .fields(fields) method

### ISSUE THREAD

**Issue by Jimmyelvis** [expressjs/multer#712]
What I'm trying to do is upload multiple files, (pictures of sneakers) to a specified folder and a Mongodb database using mongoose, and PostMan. I have a field for the main image and another field for the gallery where I can upload up to four pics. I looked through the documentation and I figured the .fields(fields) method would work. Here's my relevant code trying to implement this method.

```
// Set The Storage Engine
const storage = multer.diskStorage({
  destination: './public/uploads/sneakers',
  filename: function(req, file, cb){
    cb(null,file.fieldname + '-' + Date.now() + path.extname(file.originalname));
  }
});

// Init Upload
const upload = multer({
  storage: storage,
  limits:{
    fileSize: 100000000
  },
  fileFilter: function(req, file, cb){
    checkFileType(file, cb);
  }
});

// Check File Type
function checkFileType(file, cb){

  // Allowed ext
  const filetypes = /jpeg|jpg|png|gif/;

   // Check ext
   const extname = filetypes.test(path.extname(file.originalname).toLowerCase());

   // Check mime
  const mimetype = filetypes.test(file.mimetype);

  if(mimetype && extname){
    return cb(null,true);
  } else {
    cb('Error: Images Only!');
  }

}
```

```
router.post(
  "/",
  passport.authenticate("jwt", { session: false }),
  upload.fields(
      [
         { name: 'mainimage', maxCount: 1 },
         { name: 'gallery', maxCount: 8 }
      ]
  ),
  (req, res) => {
   
    const newSneaker = new Sneaker({
      model: req.body.model,
      colorway: req.body.colorway,
      year: req.body.year,
      text: req.body.text,
      mainimage: req.file.filename,
      gallery: req.file.filename,
    });

    newSneaker.save().then(sneaker => res.json(sneaker));
  }
);

module.exports = router;

```
The problem is that right when it hits "_mainimage: req.file.filename_" , I get an error "_TypeError: Cannot read property &#39;files&#39; of undefined_". Although oddly enough it stills uploads the files to the specified folder, however, it won't save any data to the database.

If I just upload a single file using the .single(fieldname) method it works just fine, as far as uploading the file and saving the data to the database.

**Comment by realrgt** [comment]
Instead `req.file` try `req.files['fieldname']`

**Comment by Craig-Burch** [comment]
this works for me
only a snippet but hopefully this gives anyone looking at this a good idea

const multiUpload = upload.fields([{ 
                      name: 'employeePic', maxCount: 1
                    }, { 
                      name: 'uploadId', maxCount: 1
                    }])

           const s3link1 = req.files.employeePic[0].location;
           const s3link2 = req.files.uploadId[0].location;

             return res.json({'imageUrl1': req.files.employeePic[0].location,
                                      'imageUrl2': req.files.uploadId[0].location
                                     });
