### ISSUE TITLE
multer 2.0.0 buffer is undefined

### ISSUE THREAD

**Issue by kmcnerney-salesforce** [expressjs/multer#713]
Due to a security vulnerability, I have to upgrade to 2.0.0+ but now `req.file.buffer` is undefined. `memoryStorage()` is no longer a function, so can you help me figure out how to get the buffer object for my file?

```
const multer = require('multer');
const storage = multer.memoryStorage() // memoryStorage() is not a function
const upload = multer({ storage: storage })

router.post('/', upload.single('file'), function (req, res, next) {
    console.log('file:', req.file) // ok
    console.log('path:', req.file.path) // ok
    console.log('buffer:', req.file.buffer) // undefined when I don't use memoryStorage
}
```

**Comment by kmcnerney-salesforce** [comment]
Thanks for the quick response! `getStream` works for me.

A team member found that 1.x is vulnerable by not limiting file sizes and apparently that is fixed in 2.x, even though I'm sure that can be handled outside of multer.

**Comment by kmcnerney-salesforce** [comment]
@LinusU I'm having trouble finding any updated documentation for 2.x. Is there such thing available?
The last thing I need is to only allow certain mimetypes. Before I was using `fileFilter`, but I don't know what the new alternative is. 
Thank you in advance

**Comment by HarshithaKP** [comment]
@kmcnerney-salesforce  `fileFilter` can still be used to filter files based on mimetypes. Are you still facing the issue ??

**Comment by RegularDan** [comment]
Guys, how to use this getStream thing? First time Multer user here. I successfully send formData from Postman to my server, I can see the 'req.file', I did `const buffer = await getStream(req.file.stream)`, but, mmm... what next? I'm using imgur API (it works with uploading to imgur directly from Postman, but I'm trying to send the image to my server first, and only then upload to imgur).

**Comment by LinusU** [comment]
@RegularDan can't you send the stream directly to imgur, instead of using `getStream` to turn it into a buffer? Something like `got.post('https://imgur.com/api/upload', { body: req.file.stream })`?

Anyhow, since the original question have been answered I will close this...
