### ISSUE TITLE
req.file undefined for single

### ISSUE THREAD

**Issue by dsres** [expressjs/multer#714]
Hi

I'm trying to upload a single file and then send it to another server, I need the buffer but no matter what I do `req.file` is always empty, `req.files.file` is not however, but `req.files.file.buffer` is not there either, my code is

// The Client:

const uploader = document.createElement('input')
    uploader.type = 'file'
    uploader.accept = '.csv'
    uploader.name = 'my_file'
    uploader.addEventListener('change', event => {
      const formData = new FormData()
      formData.set('enctype','multipart/form-data') // I also tried formData.enctype = 'multipart/form-data'
      formData.append('file', uploader.files[0])
      
window.fetch(url, {
    headers: {
      'Accept': 'application/json'
    },
    body: formData,
    method: 'POST',
    mode: 'no-cors',
    credentials: 'same-origin'
  })
    .then(response => handleResponseErrors(response, url))
    })

// The server:

const storage = multer.memoryStorage()
  console.log({ storage: storage })
  const upload = multer({ storage: storage, inMemory: true }).single('my_file')
  upload(req, res, (err) => {
    if (err) throw err

// I need a buffer here
   console.log({ content: req.file )} /// this is undefined
   console.log({ content: req.files.file )} /// this is defined
   console.log({ content: req.files.file.buffer )} /// this is undefined
  })

Like I said, req.file is empty even though I'm using .single('my_file') , I also don't understand what the difference between req.file and req.files.file (which I do end up having but still without buffer)

I also want to add that uploading the file from the client directly to the end server without passing through node.js and multer works but as a requirement I need to pass through nodejs and I just cannot make it work

**Comment by Edgame2** [comment]
Hello i have the same issue

**Comment by nolafs** [comment]
It did work for me, then it just stopped. Very frustrating. I cannot figure out what changed from my work local install and my live install.

**Comment by Edgame2** [comment]
I did find the solution on my side, I had express-upload making req.file inaccessible.

**Comment by bilalyaqoob** [comment]
i also have the same issue and after too many code tests still didnt find the answer i get req.files because it is coming directly from but could not get req.file which is coming from multer we have some issue using multer config

**Comment by draugnim** [comment]
Same issue. Anyone find a solution?

**Comment by bilalyaqoob** [comment]
yes i know why that was happening because i was not setting the folder where i want to uplaod the image.make sure give the right path

**Comment by draugnim** [comment]
Thanks for the reply. I figured it out too. I'm using memory storage. When I use Postman and set body to form-data its working fine. But I'm building a NativeScript app and I'm using nativescript-background-http plugin. Just have to figure out how to set body to form-data in the plugin.

**Comment by sohaibiii** [comment]
ggg

**Comment by bill-thedbaguy** [comment]
Same issue. I found that single('my_file') does not create the req.file property. It does create req.files.my_file.
buffer property does not exist, use the data property.

**Comment by tomislav13** [comment]
In my case, I was using both multer AND express-fileupload packages.
Just remove express-fileupload or similar file upload library and it should work.

**Comment by HarshithaKP** [comment]
@dsres is this issues still exists for you ??

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces

**Comment by mdehoogh** [comment]
The multer documentation explicitly states to include enctype="multipart/form-data" in the form declaration. That did the trick for me.

**Comment by githuboftigran** [comment]
@mdehoogh , enctype header saved the day, thanks!

**Comment by rolandeke** [comment]
Thanks very much this really helped me solve the issue.

**Comment by hamudeshahin** [comment]
i have this issue until now ! -_-

**Comment by rolandeke** [comment]
@hamudeshahin firstly make sure the form that is submitting the file has an enctype="multipart/form-data".

**Comment by Dtech-Dbug** [comment]
i have followed the multer docs properly.
set the enctype, configured it according to the docs, specified storage.
but while uploading a single file, I am getting req.file as undefined.

any suggestion would be appreciated.

code for the backend below :

```
const multer = require("multer");
const path = require("path");

// TODO : init a storage engine for multer
const storage = multer.diskStorage({
  destination: "./Uploads/",
  filename: function (req, file, callBack) {
    callBack(
      null,
      file.fieldname + "-" + Date.now() + path.extname(file.originalname)
    );
  },
});

// TODO : upload function
const upload = multer({
  storage: storage,
  limits: { fieldSize: 10 * 1024 * 1024 },
});

const uploadMulter = upload.single("image");
```
i am using the upload.single() middleware in the request path where I would do something with the form data coming from the client interface

in the controller function after the request passes thru the middleware : just doing console.log(req.file | req.files) return undefined

**Comment by fcamgz** [comment]
@Dtech-Dbug I got the same issue did you find the answer? 

Mine looks like this 

const storage = multer.diskStorage({
  destination: (req, file, callback) => {
    callback(null, "./public/uploads/images/");
  },
  filename: (req, file, cb) => {
    cb(null, file.originalname);
  },
});

const upload = multer({
  storage: storage,
});

router.post("/add", upload.single("cardImage"), async (req, res) => {
  console.log(req.file);  // is undefined

My frontend
                  <input
                    type="file"
                    name="cardImage"
                    onChange={(e) =>
                      setFormInformation({
                        ...formInformation,
                        image: e.target.files[0],
                      })
                    }
                 />

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(formInformation); // I see the image object in the console 
// I send it to backend like this
    axios
      .post("/api/cards/add", {
        image: formInformation.image,

**Comment by sanjeev-pandey23** [comment]
If it helps anyone:
``` 
const MulterOptions: multer.Options = {
    storage: multer.diskStorage({
        destination(req, file, callback) {
            callback(null, `./${UploadDirectory}`);
        },
        filename(req, file, callback) {
            callback(null, `${file.originalname}`);
        },
    }),
    // if you were to filter for any file extn
    fileFilter: function (req, file, callback) {
        var ext = path.extname(file.originalname);
        var ext = ext.toLowerCase();
        if (ext !== '.mp4') {
            console.log("MediaTypeMismatch")
            return {
                message: "MediaTypeMismatch",
            };
        }
        callback(null, true);
    },
    limits: {
        fileSize: 10 * 1024 * 1024, // add your limits
    },
};

 private upload = multer(MulterOptions).single('my_filename');

// your controller
    async Upload(req: Request, res: Response, next: NextFunction) {
        try {
            let data: any = this.upload(req, res, (err) => {
                if (err instanceof multer.MulterError) {
                    // A Multer error occurred when uploading.
                    let e = `Multer error ${err} occured ${ErrorMessages.MulterError}`;
                    console.log(e);
                    return e;
                } else if (err) {
                    // An unknown error occurred when uploading.
                    let e = `Other error ${err} occured`;
                    console.log(e);
                    return e;
                }
            });
            data = (data != undefined) ? data : `File uploaded successfully`;
            res.status(StatusCodes.HttpOk).json(data);
        } catch (error) {
            next(error)
        }
    }
    ```
