### ISSUE TITLE
No simple way to tell the client if an error occured

### ISSUE THREAD

**Issue by james147** [expressjs/multer#72]
All of the error handling functions, `onFileSizeLimit`, `onError` etc... have no way of either telling the client that an error has happened or passing the fact an error happened to the next middle ware:

```
  router.use('/uploads', multer({
    dest: './uploads',
    limits: { files: 2 },
    onFilesLimit: function () {
      // No way to add to the request that an error occurred, or respond to the client
   }
  });

  router.post('/uploads', function(req, res) {
    // Cannot tell that any of the limits has been reached so cannot inform the client
  });
```

You probably don't want to respond to the client directly when a limit has been hit, but you should at least be able to tell that an error occurred later on.

Something along the lines of:
```
  router.use('/uploads', multer({
    dest: './uploads',
    limits: { files: 2 },
    onFilesLimit: function (file_data) {
      file_data.files_limit_reached = true;
   }
  });

  router.post('/uploads', function(req, res) {
    if (file_data.files_limit_reached) {
        res.json({ error: "file limit reached" });
    }
  });
```
So that rather then removing the files that have hit an error or exceeded a limit they are flagged with an error message.

**Comment by qqilihq** [comment]
I'm having the same issue; after the files limit has been reached, I cannot find any way to send back an error response, instead the request just times out.

Did you solve that problem? If there is anything I might have overlooked, please let me know.

**Comment by jasson15** [comment]
hi @qqilihq, I'd like to share my solution. please take a look:

``` javascript
app.use('/route', multer({
  dest: './upload/',
  limits: {
    fileSize: 1024*1024, // at most 1MB
  },
  // setting attributes of `file` is useful for passing info to the
  // next middleware
  onFileSizeLimit: function (file) {
    fs.unlink('./' + file.path); // delete the partially written file
    file.failed = true;
  }
}));
```

After the middleware above, we can do the trick as below:

``` javascript
app.use('/route', function(req, res, next){
  // take the 1st file for example, of course you can do a for-loop instead
  var files = req.files.yourfilename; // yourfilename is the field name defined in front-end
  var file = files[0];
  if (!file.failed) {
    // gotcha!
  }
}
```

I think this might help you. One more thing might be helpful: `onFileUploadComplete` does not mean `success`, any single file will fire this event one time, even if it runs over filesize limit.

**Comment by jpfluger** [comment]
@jasson15: that was clever.

**Comment by jpfluger** [comment]
Ok, I've had a chance to look at this issue a little.... What if we add an error parameter to onFinish and then go through the code and add places where processing seems to hang b/c there's no callback? A rewrite of some of those places would look like....

```
      busboy.on('partsLimit', function() {
        if (options.onPartsLimit) { options.onPartsLimit(); }
        onFinish(new Error('partsLimit reached: cannot upload more parts than specified in options.limits.parts'));
      });

      busboy.on('filesLimit', function() {
        if (options.onFilesLimit) { options.onFilesLimit(); } 
        onFinish(new Error('filesLimit reached: cannot upload more files than specified in options.limits.files'));
      });

      busboy.on('fieldsLimit', function() {
        if (options.onFieldsLimit) { options.onFieldsLimit(); }
        onFinish(new Error('fieldsLimit reached: cannot upload more fields than specified in options.limits.fields'));
      });
```

The `onFinish` would look like this:

```
      var onFinish = function (err) {
        if ( err ) {
          req.files = {}
          req.body = {}
          // onParseEnd is never reached b/c there's an error, so let's next the err
          return next(err);
        } else {
```

There's some other places in the code we might want to add `next` as a param, such as changeDest or rename. It would need to be tested that when `next` is called the underlying process from `busboy` doesn't continue to receive and read data.

**Comment by qqilihq** [comment]
@jasson15 Thanks for the suggestion, I actually went for a similar solution finally. Btw., there is a pre-existing property `truncated` which you can use to check whether the transfer for a specific file was cancelled.

@jpfluger That looks like a good idea. Having that changes in a future release would be great. Thank you so far for your great work!

**Comment by jasson15** [comment]
@qqilihq wow, I'll give `truncated` a try, thanks!
@jpfluger It looks great! But here comes another issue: maybe there are several `err` passed to `onFinish` when more than 1 file reach the limits. Once `onFinish` gets an `err`, if we just let it pass the control to the next middleware, we might lose other `err` or other succesfully uploaded files.

This reminds me of how package q is designed in [combination](https://www.npmjs.com/package/q#combination): it gives developers 2 choices: a) return the results only when everything is done well (`Q.all`), or b) return all of the good and bad results (`Q.allSettled`).

So, the `onFinish` might become:

``` javascript
var onFinish = function (err) {
    if (!options.allSettled) { // the developer only cares when everything done right
        if ( err ) {
          req.files = {}
          req.body = {}
          // onParseEnd is never reached b/c there's an error, so let's next the err
          return next(err);
        } else {
            ...
        }
    } else { // no matter what the results are, the developer wants all the results
        ...
    }
}
```

**Comment by danielabar** [comment]
@jasson15 I was having the same issue unable to send client error, and your solution worked for me, thanks!

**Comment by LinusU** [comment]
Error handling is rewritten to be much more straight forward in the newly released version `1.0.0`. Please reopen if you feel that there is still room for improvements.

**Comment by georgschlenkhoff** [comment]
@LinusU: I still don't get it to work. That's my implementation:

```
var upload = multer({
  dest: './uploads/',
  limits: {
    fileSize: 1024 * 1024 * 1
  },
  onFileSizeLimit: function(file) {
    console.log('does not get reported');
  }
});

app.post('/file', upload.single('file'), function(req, res, next) {
  // never touched when sending file larger than 1 MB
  res.status(200).send('OK');
});

app.use(function(err, req, res, next) {
  // throws sometimes once, but with 2nd request app hangs somewhere and does not respond anymore
  console.error(err.stack);
  res.status(500).json({error: err.message});
});
```

Any idea?

**Comment by LinusU** [comment]
There isn't any `onFileSizeLimit` option any more so that will never log. You other code should work thought, however; I think that you are hitting bug #168.

**Comment by jwhitmarsh** [comment]
Why has `onFileSizeLimit` been removed? Is there an alternative to it that we could use?

**Comment by LinusU** [comment]
Yes, standard express error handling. See [Error handling](https://github.com/expressjs/multer#error-handling) in the readme...

**Comment by jwhitmarsh** [comment]
I read the readme, and the standard error handling is fine but has to be implemented in every route individually - the events allowed for a shared instance of multer to be used in multiple routes.

**Comment by jwhitmarsh** [comment]
Would you be open to a PR that re-implemented the events?

**Comment by LinusU** [comment]
It doesn't have to be implemented for each route:

```javascript
app.use(function (err, req, res, next) {
  // all errors, from all routes, will be sent here \o/
})
```
