### ISSUE TITLE
Reading File-Dimensions

### ISSUE THREAD

**Issue by tobiasgruber-at** [expressjs/multer#720]
Hello!

Is it possible to read the File-Dimensions, either before or after uploading it?
I've tried to perform it with other libraries, but therefore I'ld need the File as an Stream and I haven't found a way to get it.

Side-Note: I'm using the [S3 extension](https://www.npmjs.com/package/multer-s3), so I don't think, that I have access to the File-Path afterwards

**Comment by gireeshpunathil** [comment]
@tobiasgruber-at  - is this still an issue ?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
