### ISSUE TITLE
Invalid Path upon File Upload from 'Postman'

### ISSUE THREAD

**Issue by CyberpunkDanny** [expressjs/multer#722]
Hi All! I'm trying to upload an image using multer through my Express Server whenever a 'POST' request hits my 'imageUpload' REST API End Point. 
    File is uploaded successfully but inside 'path' property of 'req.file', incorrect path is being shown with backslashes. 

"path": "public\\\images\\\Jellyfish.jpg" (Please refer to image)

Please let me know where I'm going wrong. 

_I am using multer@1.4.1_

```
const express = require('express');
const bodyParser = require('body-parser');
const authenticate = require('../authenticate');

const multer = require('multer');

const storage = multer.diskStorage({
    destination: (req, file, callback)=>{
        callback(null, 'public/images');
    },
    
    filename: (req, file, callback)=>{
        callback(null, file.originalname)
    }
});

const imageFileFilter = (req, file, callback)=>{
    if(!file.originalname.match(/\.(jpg|jpeg|png|gif)$/)){
        return callback(new Error('You can upload only image files!'), false);
    }
    callback(null, true);
};

const upload = multer({storage: storage, fileFilter: imageFileFilter});

const uploadRouter = express.Router();

uploadRouter.use(bodyParser.json());

uploadRouter.route('/')
    .get(authenticate.verifyUser, authenticate.verifyAdmin, (req, res, next)=>{
        res.statusCode = 403; //Forbidden
        res.end('PUT operation not supported on /imageUpload');
    })
    
    .post(authenticate.verifyUser, authenticate.verifyAdmin, upload.single('imageFile'), (req, res)=>{
        res.statusCode = 200;
        res.setHeader('Content-Type', 'application/json');
        res.json(req.file); /* req.file object contains the path to the file which can be used by client */
    })
    
    .put(authenticate.verifyUser, authenticate.verifyAdmin, (req, res, next)=>{
        res.statusCode = 403; //Forbidden
        res.end('PUT operation not supported on /imageUpload');
    })

    .delete(authenticate.verifyUser, authenticate.verifyAdmin, (req, res, next)=>{
        res.statusCode = 403; //Forbidden
        res.end('PUT operation not supported on /imageUpload');
    })


module.exports = uploadRouter;
```
![Capture](https://user-images.githubusercontent.com/9845321/54255488-51146e00-457e-11e9-9210-d8dcb4a1b0fa.PNG)

**Comment by LinusU** [comment]
Are you running on Windows? On Windows the correct path separator is a backwards slash...

**Comment by CyberpunkDanny** [comment]
> Are you running on Windows? On Windows the correct path separator is a backwards slash...

Hi Linus! 
I am running it on Windows. The path I've written is what is generated when an image is uploaded. Extra backwards slash is observed in the path

**Comment by LinusU** [comment]
The extra backward slash is just because it's being escaped in the JSON output, the string still holds the correct value with just one backslash. You can see it by running the following in a Node.js shell:

```sh
$ node
> let a = JSON.stringify({ path: 'public\\images\\Tulips.jpg' })
> console.log(a)
{"path":"public\\images\\Tulips.jpg"}
> let b = JSON.parse(a)
> console.log(b.path)
public\images\Tulips.jpg
```

**Comment by CyberpunkDanny** [comment]
Hey Linus! 

Thank you for clarifying this. I've been banging my head on this. Thanks again! :)

**Comment by LinusU** [comment]
No problem 🍻

**Comment by rades12340** [comment]
I have the same problem, have the right path, it works fine when I use a static file, but when I upload an image with Multer it generates a path with backslashes which don't work(also in Windows). How I can change this backslashes into forwarding slashes, so it can work?
