### ISSUE TITLE
Can fileFilter get a files content?

### ISSUE THREAD

**Issue by george-norris-salesforce** [expressjs/multer#723]
I'm trying to use [file-type](https://www.npmjs.com/package/file-type) to detect the files type in `fileFilter`. I'd need to the file from disk and pass it to file-type. Is it possible to get a hangle on where the file is while in `fileFilter`? The `destination` property is not available in the `fileFilter` so I can't find it within this function.

**Comment by LinusU** [comment]
Unfortunately, the file hasn't yet been received when `fileFilter` is called since the idea with `fileFilter` is to be able to stop a file from being uploaded.

I would recommend looking at the 2.x beta which I think solves your problem: #399

**Comment by george-norris-salesforce** [comment]
thanks
