### ISSUE TITLE
fileFilter's callback can not get req.body

### ISSUE THREAD

**Issue by flameddd** [expressjs/multer#724]
Hi 
There is a situation I wonder what's going on.  

Why can not get `req.body` in `fileFilter function` because The `Order` of the fields 

### version
- "express": "^4.16.4"
- `"multer": "^1.4.1"`

```js
// index.js
const upload = multer({
  dest: './uploads',
  fileFilter: (req, file, cb) => {
    console.log("req.body")
    console.log(req.body) // <-----
    cb(null, true)
  }
}).any();
```

## test repo
https://github.com/flameddd/multer_test  

### test
use `postman` send an POST request `127.0.0.1:3000`

#### test1
![image](https://user-images.githubusercontent.com/22259196/55141815-32b19380-5176-11e9-9e63-3db96ece8cc0.png)  
##### result:  console.log(req.body)
> { gid: 'aaaa', uid: 'bbbb' }

#### test2
![image](https://user-images.githubusercontent.com/22259196/55141856-4957ea80-5176-11e9-978f-6328c96f4300.png)  
##### result:   console.log(req.body)
> { gid: 'aaaa' }  //  <--- only get 'gid'

#### test3
![image](https://user-images.githubusercontent.com/22259196/55141869-54ab1600-5176-11e9-9fdf-f103efac0232.png)  
##### result:  console.log(req.body)
> {}  // <--- get nothing

Do I use wrong to test? or?  
Thanks for your time, and thanks this awesome lib :)

**Comment by LinusU** [comment]
This is a limitation of how the form-data format works, and unfortunately, there is no way to work around it.

What you could do is accept all files and then later filter thru and remove the ones you don't want...
