### ISSUE TITLE
multer.memoryStorage() is not a function

### ISSUE THREAD

**Issue by laurentsmohr** [expressjs/multer#733]
version: 2.0.0-alpha.6

I am using routing-controllers (version: 0.7.7). I am have an endpoint that receives a file:

```
 @Routing.UploadedFile('doc', {
      options: FILE_UPLOAD_OPTIONS,
    })
```
with FILE_UPLOAD_OPTIONS being:
```
import multer from 'multer'

export const FILE_UPLOAD_OPTIONS = {
  storage: multer.memoryStorage(),
}
```

when starting the server, I am getting the following error:

**"TypeError: multer_1.default.memoryStorage is not a function"**

This is not an issue, when using version 1.4.1

**Comment by LinusU** [comment]
It seems like it has something to do with your compatibility layer for using the `import` syntax. Could you try doing `import { memoryStorage } from 'multer'`?

**Comment by dnutels** [comment]
Same here on ^2.0.0-alpha.7,

Translating the above suggestion by @LinusU to CommonJS:

```
const {memoryStorage} = require('multer');
...
 
doesn't work, especially since there is a need for `multer` instace:

```
const storage = memoryStorage();
const upload = multer({storage});
const single = upload.single('some-name');
```

I am a little perplexed as to why it is, in addition to the docs (for 2.0.0 having __removed__ all mentions of `memoryStorage`.

Any suggestions?

**Comment by LinusU** [comment]
I, missed that you were talking about the 2.x alpha and not the 1.x stable release.

`memoryStorage` (and the entire concept of storage engines) is removed from the 2.x release line, which uses streams instead.

Read more about the new api in #399 and https://github.com/expressjs/multer/tree/explore-new-api
