### ISSUE TITLE
req.files.fieldname is not an array

### ISSUE THREAD

**Issue by chronotc** [expressjs/multer#74]
Hi,
I'm really new to all this so I apologize if this is a really stupid question
Is there any particular reason why
          if (req.files[field].length === 1) {
            req.files[field] = req.files[field][0];
          }
is included in the onFinish function?

This is causing the length attribute to become undefined.
This is a small issue as I use the length to traverse through the entire array in case multiple files are sent.

**Comment by jpfluger** [comment]
@chronotc ... Finally got the `putSingleFilesInArray` functionality in Multer. Github master is updated. Waiting for Multer version 0.1.8 to be put on npm. The README docs will describe its use.
