### ISSUE TITLE
disk.js - that.getDestination is not function error occured.

### ISSUE THREAD

**Issue by chiuoo** [expressjs/multer#743]
that.getDestination(req, file, function (err, destination) {
       ^

TypeError: this.getDestination is not a function
    at DiskStorage._handleFile (/sledger/SLedgerHub/node_modules/multer/storage/disk.js:31:8)

--- changed ---

  getDestination(req, file, function (err, destination) {

if "that." erase, not error.

**Comment by chiuoo** [comment]
disk.js is not class. 

how to local function call .. 

function aa() {

}

function bb() {
  aa();
}

if, disk.js is class,

aa() {

}

bb() {
  this.aa();
}

**Comment by gireeshpunathil** [comment]
@chiuoo - can you pls describe the issue with the help of a small, but complete program, so that I can create and visualize the same, in expectation of debugging it? thanks!

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces

**Comment by madrackwp** [comment]
I am also currently experiencing this issue and is unsure about why this error is occurring.

I am trying to create a web application that takes in files front the UI and uploads it to the backend, an express server. 

On the backend, I have created an endpoint to accept the file to be uploaded to the server.

Here is the code I am using:
==========================================================
const storage = multer.diskStorage({
  destination: (req, file, callBack) => {
    callBack(null, 'uploads')
  },
  filename: (req, file, callBack) => {
    callBack(null, `${file.originalname}`)
  }
})

let upload = multer({ dest: storage })

app.post('/file', upload.single('file'), (req, res, next) => {
  const file = req.file
  console.log(file)
  console.log(file.filename)
  if (!file) {
    const error = new Error('No file')
    error.httpStatusCode = 400
    return next(error)
  }
  res.send(file)
})
===========================================================
I've created a simple POST request using Postman to test out the endpoint but I am getting the error in this thread

C:\Users\madra\Documents\React\final\backend\node_modules\multer\storage\disk.js:31
  that.getDestination(req, file, function (err, destination) {

I am very new when it comes to programming in general and I apologise in advance for any stupid questions.
