### ISSUE TITLE
check if file exists

### ISSUE THREAD

**Issue by danrald** [expressjs/multer#749]
I need to check to see if a file already exists but I cannot seem to do that.  I think multer is supposed to rename a file if the file name already exists, but it does not seem to be doing that.

Thanks

    private multerStorage: Multer.StorageEngine = Multer.diskStorage({
        destination(req, file, cb) {
            cb(null, "./../media/");
        },

        filename(req, file, cb) {
            crypto.pseudoRandomBytes(16, (err, raw) => {
                
                try
                {
                   // cb(null, raw.toString("hex") + Date.now() + "." + mime.getExtension(file.mimetype));
                   cb(null, file.originalname);
                }
                catch(ex){
                    console.log(ex);
                   // cb(null, raw.toString("hex") + Date.now() + "." + mime.getExtension(file.mimetype));                    
                }
            });
        },

**Comment by flowluap** [comment]
I check it with fs: If the file exits, "(1)" will be appended to the filename:
`  var storage = multer.diskStorage({
        destination: function (req, file, cb) {
            cb(null, docfolder)
        },
        filename: function (req, file, cb) {
          console.log(file);
          if (fs.existsSync(path.join(docfolder,file.originalname))) {
            cb(null, file.originalname+"(1)")
          }else{
            cb(null, file.originalname)
          }
      }
    })
  var upload = multer({storage:storage}).any('files');`

**Comment by shivasurya** [comment]
always check for valid filename, remove other special characters and use regex [a-zA-Z0-9] and replace all other characters with _ to prevent directory traversal and overwriting internal files.

**Comment by flowluap** [comment]
> always check for valid filename, remove other special characters and use regex [a-zA-Z0-9] and replace all other characters with _ to prevent directory traversal and overwriting internal files.

```
function stripPath(pfad){
  return path.normalize(pfad).replace(/^(\.\.(\/|\\|$))+/, '');
}
```

Thats the way i do it...

**Comment by shivasurya** [comment]
What about %2f %2e encoded format ?
