### ISSUE TITLE
Dynamic folder Names would be Nice

### ISSUE THREAD

**Issue by tonyroberts85** [expressjs/multer#75]
Hope all is well and understand you're quite busy.  But it would be great if we could pass along req.params to the destination so we could save things in folders based on parameters.

**Comment by jpfluger** [comment]
The [README](https://github.com/expressjs/multer/blob/master/README.md) has been updated. Both the rename and new renameDestDir functions are passed `req` and `res`. Not certain if it applies to your situation, but please note the [req.body Warnings](https://github.com/expressjs/multer#reqbody-warnings) section.
