### ISSUE TITLE
File/Buffer Size different in memory/file unreadable

### ISSUE THREAD

**Issue by adamwilbert** [expressjs/multer#750]
I am using multer in memory on a lambda (failing on both the lambda and locally currently) and uploading an image to s3.  

Once I get the buffer from req.file.buffer I send that to s3 (the aws sdk takes in a buffer as one of its payload options) but the file cannot be opened and the file size is quite different than that of the image in the file attached to the request.

Am I missing something?  

Is there anything added to the buffer when multer reads the file from the request?

The buffer opening the file locally and the buffer from multer are completely different.

**Comment by BryanJAraujo** [comment]
How did you resolve this?

**Comment by Doc999tor** [comment]
Can be related to #1242?

**Comment by BryanJAraujo** [comment]
> Can be related to #1242?

The problem I'm having is that when trying to upload, the file that sends is different from the original. Not necessarily the file size

**Comment by BryanJAraujo** [comment]
I solved the problem. My application is running with aws lambda and API Gateway, I was researching and discovered that API Gateway has a configuration called Binary Support, so I left it as `*/*`, redeployed the lambda application and the file was sent correctly by multipart/form-data

template.yaml:
```yaml
FunctionName:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - '*/*'
      ...
 ```
