### ISSUE TITLE
Memory leak: when uploading a very large file ~50MB and inMemory flag set to true.

### ISSUE THREAD

**Issue by kudresov** [expressjs/multer#76]
It seems that there is a memory leak, whenever the flag inMemory is set to true and you upload a file it will cause node process to go from ~ 40MB to 1.2GB and the goes down do about 600MB.

**Comment by jpfluger** [comment]
This warning has been noted in the primary [README](https://github.com/expressjs/multer#inmemory). (Thanks!) Also, I've found using inMemory is 8x to 10x slower than piping the file to disk first.

**Comment by LinusU** [comment]
I shared some ideas in #127

**Comment by LinusU** [comment]
I believe that there is no longer any memory leaks in `1.0.0`. With that said, multer will peak at twice the size of the file being uploaded. It should then be cleared for garbage collection thought.

Please note that v8 doesn't aggressively free memory so the memory might not be freed right away.

I'm closing this in favour #127
