### ISSUE TITLE
How to show the uploaded pdf file on Browser without direct download?

### ISSUE THREAD

**Issue by cfmitrah** [expressjs/multer#760]
I've uploaded the pdf files using multer. I want to show uploaded pdf file in a separate window in the browser without download the pdf.

**Comment by gireeshpunathil** [comment]
@cfmitrah - can you evaluate https://mozilla.github.io/pdf.js/getting_started/ and see if it fits your needs? It does not fetch the uploaded file from the backend, instead from your client side itself, which I guess is not an issue for you?

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
