### ISSUE TITLE
Req.file is undefined

### ISSUE THREAD

**Issue by newdecline** [expressjs/multer#765]
I looked through all the problems similar to mine, but could not find the answer.
When I select a file in the form, then in req.file I see undefined.

SERVER.JS
`
const next = require('next');
const express = require('express');
const bodyParser = require('body-parser');
const multer  = require('multer');
const upload = multer({ dest: 'uploads/' });

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app
    .prepare()
    .then(() => {
        const server = express();

        server.use(bodyParser.json());

        server.post('/api/feedback', upload.single('file'), (req, res, next) => {
            console.log(req.body);
            console.log(req.file);
        });

        server.get('*', (req, res) => {
            return handle(req, res)
        });

        const listenCallback = err => {
            if (err) throw err;
            console.log(`> Ready on http://localhost:${port}`)
        };

        dev ?
            server.listen(port, listenCallback) :
            server.listen(port, 'localhost', listenCallback);
    })

    .catch(ex => {
        console.error(ex.stack);
        process.exit(1);
    });
`
FORM

`
<Formik
                    initialValues={{
                        name: '',
                        email: '',
                        message: '',
                        agreement: false }}
                    validationSchema={FeedbackSchema}
                    onSubmit={(values, { resetForm } ) => {
                        fetch('/api/feedback', {
                            method: 'POST',
                            body: JSON.stringify(values),
                            headers: {
                                "Content-Type": "application/json"
                            }
                        })

                    }}
                    render={props => {
                        const {
                            values,
                            errors,
                            touched,
                            handleChange,
                            handleSubmit,
                        } = props;

                        return (
                            <form
                                className="form"
                                id="form"
                                onSubmit={handleSubmit}
                                encType="multipart/form-data">
                                <h3 className="form__header">Заказать дизайн</h3>
                                <input
                                    onChange={handleChange}
                                    placeholder='Ваше имя*'
                                    type="text"
                                    className={errors.name && touched.name ?
                                        "form__input-name form__input form__input_error" :
                                        "form__input-name form__input"}
                                    name='name'
                                    value={values.name}/>

                                <input
                                    onChange={handleChange}
                                    placeholder='Ваш @mail*'
                                    type="text"
                                    className={errors.email && touched.email ?
                                        "form__input-email form__input form__input_error" :
                                        "form__input-email form__input"}
                                    name='email'
                                    value={values.email}/>

                                <textarea
                                    onChange={handleChange}
                                    cols="30"
                                    rows="3"
                                    className="form__textarea"
                                    name='message'
                                    placeholder="О проекте"
                                    value={values.message}>
                            </textarea>

                                <label className='form__label-attach-file'>
                                    Прикрепить бриф +
                                    <input
                                        type="file"
                                        name='file'
                                        className="form__input-attach-file"/>
                                </label>

                                <button type='submit' className='form__submit'>Отправить</button>

                                <label className={errors.agreement && touched.agreement ?
                                    "form__label-agreement form__label-agreement_error" :
                                    "form__label-agreement"}>
                                    <input
                                        onChange={handleChange}
                                        checked={values.agreement}
                                        type="checkbox"
                                        name='agreement'
                                        className="form__label-agreement-input"/>
                                    <span className="form__label-agreement-circle"> </span>
                                    <span
                                        className='form__label-agreement-span'>
                                    Согласие с обработкой персональных данных
                                </span>
                                </label>
                            </form>
                        )
                    }}
                />
`

**Comment by HarshithaKP** [comment]
@newdecline   Can you please replace 
` return (
                        <form
                            className="form"
                            id="form"
                            onSubmit={handleSubmit}
                            encType="multipart/form-data">`
with 
` return (
                        <form
                            className="form"
                            id="form"
                            onSubmit={handleSubmit}
                            action = "/api/feedback"
                            method = "post"
                            encType="multipart/form-data"> `

When I tried it worked, because `action` to the specified route in server and `method = post` will send data to the server.

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
