### ISSUE TITLE
TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by saharajdeep** [expressjs/multer#780]
const express=require('express');
var router=express.Router();
const mongoose=require('mongoose');
const Player = mongoose.model('Player');
const multer=require('multer');

/** Storage Engine */

var storages=multer.diskStorage({
    destination:function(req,file,next){
        next(null,'playerUploads/');
    },
    filename:function(req,file,cb){
      const ext=file.mimetype.split('/')[1];
     cb(null,file.originalname);
    
  }
  });

     var playerFile=multer({storage:storages}); 

// Form submission
router.post('/',playerFile.array('pic'),(req,res)=>{
     if(req.body._id== '')
    insertRecord(req,res);   
     else
     updateRecord(req,res); 
});

function insertRecord(req, res) {
    var player = new Player();
    player.pic = req.file.filename;
    player.teamName = req.body.teamName;
    player.year = req.body.year;
    player.phoneNo = req.body.phoneNo;
    player.firstName = req.body.firstName;
    player.lastName = req.body.lastName;
    
    player.save((err, doc) => {
        if (!err)
            res.redirect('player/list');
        // else {
        //     if (err.name == 'ValidationError') {
        //         handleValidationError(err, req.body);
        //         res.render("player/addOrEdit", {
        //             viewTitle: "Insert Employee",
        //             player: req.body
        //         });
        //     }
            else
                console.log('Error during record insertion : ' + err);
        // }
    });
}

function updateRecord(req, res) {
    Player.findOneAndUpdate({ _id: req.body._id }, req.body, { new: true }, (err, doc) => {
        if (!err) { res.redirect('player/list'); }
        // else {
        //     if (err.name == 'ValidationError') {
        //         handleValidationError(err, req.body);
        //         res.render("employee/addOrEdit", {
        //             viewTitle: 'Update Employee',
        //             player: req.body
        //         });
        //     }
            else
                console.log('Error during record update : ' + err);
        // }
    });
}

**Comment by HarshithaKP** [comment]
@saharajdeep When using multer.array('name'), req.files provides all files information.
To access individual file with information you can make use of following logic. 
```
function insertRecord(req, res) {
req.files.forEach((e) => {
console.log(e.filename);
});
```

**Comment by AvichalSrivastava** [comment]
For me, my path was wrong the file name i mentioned wasn't present
