### ISSUE TITLE
Multer undefined filename

### ISSUE THREAD

**Issue by danggadang** [expressjs/multer#781]
I try to get the filename in mongodb of multer uploaded file to delete that but it returns as 'undefined'.(multer: 1.4.2)

**Comment by HarshithaKP** [comment]
@danggadang Can you please provide the code which you are trying ??

**Comment by danggadang** [comment]
@HarshithaKP Here's the code:
router.delete('/:id',(req, res) => {
  let book = Book.findById(req.params.id);
  bookImageName=book.coverImageBasePath;
  console.log('bookImageName:' +bookImageName);
  fs.unlink(__dirname+`/../public/uploads/bookCovers/${bookImageName}`, (err) => {
    if (err) throw err;
    console.log(`successfully deleted cover image`);
  });
  Book.findByIdAndDelete(req.params.id)
    .then(()=>res.json('book deleted'))
    .catch((err)=>res.status(400).json('Error:'+err));
})
I already tried to convert bookImageName with toString and Number.

**Comment by HarshithaKP** [comment]
@danggadang Can you post the complete call stack of error ? otherwise I am thinking whether it has something to do with multer.

**Comment by sampathBlam** [comment]
@danggadang : 
Let me understand this.
- You used multer to upload a file
- You saved an entry in MongoDB with the  name of the uploaded file as the _id of the database entry. (That would be a random name without any file extension)
- When the ` DELETE /:id` endpoint is hit, you look up in the database for that `id`, get the full path of the file and delete it. 

Which part of your above code returns `undefined`? 
Did you verify in the database whether an entry with that _id exists?
Can you share the code that you wrote to create the MongoDB entry using the multer uploaded filename?

**Comment by danggadang** [comment]
Here's the updated code:
router.delete('/:id', (req, res) => {
    Book.findById(req.params.id)
        .then(rbook => {
            let bookImageName = rbook.coverImage;
            if (bookImageName != null) {
                fs.unlinkSync(__dirname + `/../client/public/Images/bookCovers/${bookImageName}`,         (err)=> {
                    if (err) throw err;
                    console.log(`successfully deleted cover image`);
                });
            }
        })
        .catch((err) => console.log(err));
    Book.findByIdAndDelete(req.params.id)
        .then(() => res.json('Book deleted!'))
        .catch((err) => res.status(400).json('Error: ' + err));
});
The previous code didn't work because result of Book.findById(req.params.id) had not returned yet. Thanks for the replies, I appreciate it.
