### ISSUE TITLE
Route.post() requires a callback function but got a [object Object]

### ISSUE THREAD

**Issue by doverradio** [expressjs/multer#794]
Hello,

I am doing everything according to the guide but seems I cannot avoid this error.  Can you please help?

Here is the relevant multer code (filename: footers.js)
```
const multer = require('multer');

// Multer Middleware
var uploading = multer({
  dest: __dirname + '../public/uploads/',
  limits: {fileSize: 1000000, files:1},
});


router.post('/',  uploading, (req, res)=> {

});
```

Here is my HTML form:
```
<div class="card card-body">
	<h3>Add Pic</h3>
	<form action="/footers" method="post" enctype="multipart/form-data">
		<div class="form-group">
			<label for="footer">Select an image to upload:</label>
			<input type="file" name="footer" class="form-control" required>
		</div>
			<button type="submit" class="btn btn-primary">Upload Image</button>
	</form>
</div>
```

I start the server and immediately get error, every time:

```
C:\Users\Uber\Desktop\NC\User\app_footerpic\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Object]
    at Route.(anonymous function) [as post] (C:\Users\Uber\Desktop\NC\User\app_footerpic\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.(anonymous function) [as post] (C:\Users\Uber\Desktop\NC\User\app_footerpic\node_modules\express\lib\router\index.js:510:19)
    at Object.<anonymous> (C:\Users\Uber\Desktop\NC\User\app_footerpic\routes\footers.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Uber\Desktop\NC\User\app_footerpic\app.js:18:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

What is the solution?

**Comment by HarshithaKP** [comment]
@doverradio  I was able to recreate the issue. Fixed  minor mistake in your `footers.js` code. Hope the following code works for you.
```
const multer = require('multer');

// Multer Middleware
var uploading = multer({
  dest: __dirname + '../public/uploads/',
  limits: {fileSize: 1000000, files:1},
});

router.post('/',  uploading.single('footer'),  (req, res)=> {
});
```

**Comment by doverradio** [comment]
Well thank you for that!  It appears now the app does not crash.  After checking again, I realize what ```uploading.single('footer')``` is doing.  

I had to pass in the absolute path (I am on Windows 10 and forward slash / was conflicting) before it saved the file in the uploads directory.

However, I noticed when it saves the file it is not putting the file extension.  Means, no .jpg, instead it is a file like this: 5ac0531397d09507ab6f02f39f9908e4

Only until I add .jpg to it will it open, like so: 5ac0531397d09507ab6f02f39f9908e4.jpg

Is there a way to preserve the file extension so if its .png it comes as .png or if .jpg it comes to that uploads directory as .jpg?

Finally, how can I get this into MongoDB?  I just want to actually not save the images like this but instead into MongoDB.  I was attempting to do this but seems nothing gets written:

```
router.post('/', uploading.single('footer'), (req, res)=> {
	console.log(req.file);

	let errors = [];

	if(!req.file){
		errors.push({text: "Please upload a photo"});
	} else {
		const newFooter = {
			footer: req.file,
			user: req.user.id
		}
		new Footer(newFooter)
		.save()
		.then(footers => {
			req.flash('success_msg', 'Footer Pic added, check your PC for document to open.');
			res.redirect('/footers', {
			footers: footers
			});
		})
	}
});
```

Got any solution for those?

Thank you so much again for the earlier solution, my output is now coming like this in console when I log the req.file object:
```
{ fieldname: 'footer',
  originalname: 'IMG_7213.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  destination:
   'C:\\Users\\Uber\\Desktop\\NC\\Sending JN Emails\\Nodejs_FooterPic\\app_footerpic\\public\\uploads\\',
  filename: '5ac0531397d09507ab6f02f39f9908e4',
  path:
   'C:\\Users\\Uber\\Desktop\\NC\\User\\app_footerpic\\public\\uploads\\5ac0531397d09507ab6f02f39f9908e4',
  size: 159566 }
```

**Comment by sampathBlam** [comment]
@doverradio : 
To preserve the original name of the uploaded file, you need to do the following. 

- Initialize multer storage.
```
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, __dirname + '../public/uploads/')
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname)
  }
});
```

- Use the multer diskStorage object while initializing multer.
```
var uploading = multer({ 
  storage: storage, 
  limits: {fileSize: 1000000, files:1} 
})
```

**destination** is a function that you can use to specify the destination directory in the server. 
**filename** is a function that you can use to specify the name in which the uploaded file is saved. If you wish to use the name of the file as it is in the source (uploading user's computer) you can use the `originalname` property of the file object. 

From the docs:
```
filename is used to determine what the file should be named inside the folder. 
If no filename is given, each file will be given a random name that doesn't include any file extension.

Note: Multer will not append any file extension for you, your function should return a filename complete with an file extension.
```

Regarding your other query with respect to storing the file in MongoDB, it seems to be a bit beyond the scope of this issue. I would appreciate creating a separate issue/question for that.

**Comment by HarshithaKP** [comment]
@doverradio Does the solution given by @sampathBlam helped you in resolving your issue ??

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
