### ISSUE TITLE
Convert binary buffer to stream

### ISSUE THREAD

**Issue by KayHS** [expressjs/multer#797]
I need to pass a file to another service, the other service will only accept a stream. Is it possible to get/convert the binary buffer to a chunked stream.

```
const documentFile = req.body.image; // Binary Buffer
```

**Comment by HarshithaKP** [comment]
@KayHS I don't think you need to use multer as middleware in this case. In plain express post request, client request will hold the data, which can be piped to the destination. After this, further data flows from client to destination seamlessly.

for example:

```js

// target_req = create the target connection
app.post('/myroute',  (req, res) => {
  req.pipe(target_req)
 // ...
})
```
Please let me know if it works.

**Comment by KayHS** [comment]
The request i receive is a multipart form data, i cannot pipe it directly to the target connection. I need to manipulate it first to send extra data. Is there some way i can store the file stream in a variable to use later?

**Comment by KayHS** [comment]
@HarshithaKP 

This is my test case for my service to receive an image.

```
  it("should submit an image, async () => {

        const stream = await fs.createReadStream(process.cwd() + "/test/resources/" + "id/front.jpg");

        const response = await request(app).post("/api/v2/document")
            .set("Authorization", AUTH_TOKEN)
            .attach("image", stream, "front.jpg")
            .field("side", "front")
            .expect(201);
    });
```

If i don't need multer where in the req object when i receive this request is the "image"

**Comment by KayHS** [comment]
In the end i used busboy to solve my problem.

https://github.com/mscdex/busboy/issues/219
