### ISSUE TITLE
empty req.file and file not saved. Node, React with Axios. 

### ISSUE THREAD

**Issue by marcosdipaolo** [expressjs/multer#800]
There's no way to get the file in the `req.file` field, i've tried with `array` method instead of `single` with `req.files` but nothing.
I think i can get the file in the req.body.img somehow, but that's not what i want.   

I actually tried many things. These are the latest.
I think I've read a lot of answers to this with no solution to me or a lot of other people.   

#### Option 1
```javascript
const multer = require('multer');
const upload = multer({dest: '../storage/images/products/'}).single('img');
```
#### Option 2
```javascript
const path = require('path');
const multer = require('multer');
const storage = multer.diskStorage({
    destination: path.join(__dirname, '../storage/images/products/'),
    filename: (req, file, cb) => {
        cb(null, file.originalname);
    }
});
const upload = multer({storage}).single('img');
```
and the route: 
```javascript
router.post('/:id/edit', upload, ProductController.update);
```
I also tried with `put`
#### In app.js
Among some code:
```javascript
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true,
}));
```
#### In the Frontend
```javascript
let url =  `http://localhost:3000/products/${product_id}/edit`;
const data = new FormData();
data.append('img', img);
axios.post(url, data, {
   headers: {
        authtoken: Cookie.get('token') ? Cookie.get('token') : 0,
       'Content-Type': 'multipart/form-data'
}}).then(res => {
    if (typeof res.data.details !== "undefined") {
        setCallState('failed');
        let error = res.data.details[0].message;
        setError(error);
        setTimeout(() => {
            setError('');
        }, 3000);
        return false;
     }
     setId(res.data._id);
     setCallState('done');
}).catch(err => console.log(err));
```

**Comment by xt1991** [comment]
Same issue, same question

**Comment by HarshithaKP** [comment]
@marcosdipaolo I was able to recreate your issue, the problem is with reading file from disc in Axios client. That means client isn't sending file to server.
I have written Axios client for multer file upload, please find the code here : https://gist.github.com/HarshithaKP/ebc0e79800e5638fe827c157360378be

Let me know if it works for you.
@xt1991

**Comment by LinusU** [comment]
Seems like this was a client problem that can be solved by the code linked, happy to reopen if we should change something in Multer
