### ISSUE TITLE
fileFilter check for undefined file

### ISSUE THREAD

**Issue by robfr77** [expressjs/multer#804]
I want to ensure that a file is uploaded using a check like this:
(I noticed an undefined file is passing through)
```
fileFilter: (req, file, cb) => {
if (!file.length) {
      const error = new Error("File required.");
      req.uploadError = {
        msg: error.message,
        param: "notice",
        location: "file"
      };
      return cb(null, false, error);
    } 
```
But it's not working to check with either file or req.file

The following check works:
```
else if (!allowedExtensions.test(ext)) {
      const error = new Error(
        "Invalid file type! Please use: .jpg, .jpeg, .png, or .pdf."
      );
      req.uploadError = {
        value: ext,
        msg: error.message,
        param: "notice",
        location: "file"
      };
      return cb(null, false, error);
    }
```

**Comment by HarshithaKP** [comment]
@robfr77 can you please elaborate the problem you are facing, like what kind of files server should accept/reject ?

**Comment by robfr77** [comment]
This can be closed, I took the check out of fileFilter and put the upload callback first in the middleware before the validation, like this:
```
singleFileCb(req, res, multerErr => {
    if (multerErr) {
      return res.status(400)
    }
    next();
  });
```
The only remaining issue is for uploading multiple files, when testing with superagent it is not catching the undefined files and returning a 400, rather a 500. 
```
const singleFileCb = upload.single("notice");
const multipleFilesCb = upload.fields([{ name: "notice", maxCount: 12 }]);
```
Here is the code for the multipleFiles, working locally but failing using the documentation at http://visionmedia.github.io/superagent/#multipart-requests.
```
router.post("/multiple", (req, res, next) => {
  multipleFilesCb(req, res, multerErr => {
    if (multerErr) {
      return res.status(400)
    }
    next();
  });
});
```
I'm not totally sure of the difference between ```upload.single``` and ```upload.fields```, otherwise it's probably an issue for over there instead.
