### ISSUE TITLE
Upload files into array of objects

### ISSUE THREAD

**Issue by jdiegosierra** [expressjs/multer#805]
I have an array of objects like this:

    data: [
        {"image": File, "certificate": File},
        {"image": File, "certificate": File}
    ]

The way I'm taking to read the files on the server is doing a loop before send the POST request:

    ...
    const fd = new FormData();
    fd.append('image', data[0].image);
    fd.append('image', data[1].image);
    fd.append('certificate', data[0].certificate);
    fd.append('certificate', data[1].certificate);
    this.http.post('http://localhost:3000/upload', fd, options);

Then on the server side I do:

    upload.fields([{ name: 'image', maxCount: 2 }, { name: 'certificate', maxCount: 2 }])

So my question is... Is there a way that if I send the array like:

    fd.append('data', data)

so multer can take the files that are into the data field?

**Comment by justraman** [comment]
I am able to solve using multer().any();

then match the fieldname with files

**Comment by davidmashe** [comment]
There seems to be a solution, closing until further evidence of an issue arises.
