### ISSUE TITLE
Error: "message": "Unexpected field"

### ISSUE THREAD

**Issue by fabioplaka** [expressjs/multer#813]
Hello,
I am using **Multer** library for uploading photos, and according to official documentation everything is ok, but when I try from Postman gives me the error below in the picture.

![Capture](https://user-images.githubusercontent.com/32648013/70515746-1d2e9f00-1b36-11ea-86a7-38f439e14074.PNG)

The piece of code where I have used the library is:
`const multer  = require('multer');`
`const upload = multer({ dest: 'uploads/' });`
`router.post("/",  upload.single('avatar'), (req, res, next) => {`
      `...`
`}`

**Comment by HarshithaKP** [comment]
@fabioplaka https://github.com/expressjs/multer/issues/307#issuecomment-175652981 explained sending a request using postman. Can you please cross check and let me know if the problem still appears for you.

**Comment by fabioplaka** [comment]
I solve it.
