### ISSUE TITLE
localized text getting converted random charater

### ISSUE THREAD

**Issue by Ambay54** [expressjs/multer#822]
I am using multer's upload.single to extract a csv file from request. When converting the buffer given by multer upload to string I observed localized text characters (like À) is getting converted to some random chahracter( like ï¿½ ).The encoding which multer uses is 7bit. Is there any way to get data in utf-8 encoding.
Multer's file details:
  fieldname: 'file',
  originalname: 'SampleIncentive.csv',
  encoding: '7bit',
  mimetype: 'text/csv',

**Comment by jonchurch** [comment]
Maybe this issue can help https://github.com/expressjs/multer/issues/241
It suggests that multer does not detect or set the encoding itself, but that is set in the request you send. 

Also possibly related to https://github.com/expressjs/multer/issues/434

**Comment by Ambay54** [comment]
@jonchurch  I have have tried the suggestions mentioned in the issues tagged by you, but that did not help

**Comment by Ambay54** [comment]
I found a solution to the issue, When converting the buffer to string add 'latin1' as encoding

` request.file.buffer.toString('latin1')`

**Comment by HassanDev13** [comment]
when i try your code give me Cannot read property 'toString' of undefined
can u give me more info please i'am stock with it !

**Comment by HassanDev13** [comment]
> I found a solution to the issue, When converting the buffer to string add 'latin1' as encoding
> 
> ` request.file.buffer.toString('latin1')`

when i try your code give me Cannot read property 'toString' of undefined
can u give me more info please i'am stock with it !

**Comment by elliot40404** [comment]
You can use this
`file.originalname = Buffer.from(file.originalname, 'ascii').toString( 'utf8');`
