### ISSUE TITLE
returned error message

### ISSUE THREAD

**Issue by ShaoHong1120** [expressjs/multer#823]
I using var upload = multer({dest: './upload'}).array('photo', 3).

If upload 5 files, returned error message "files exceeding the limit 2"
If upload 7 files, returned error message "files exceeding the limit 4"

my code

```
var express = require('express');
var multer = require('multer');
var app = express();
var upload = multer({dest: './upload'}).array('photo', 3)
function uploadMiddleware(request, response, next) {
    upload(request, response, (err)=>{
        if (err) {
            console.log(err)
        } else {
            next();
        }
    })
}
app.post('/upload',uploadMiddleware, function (request, response) {

})
app.listen(8888)
```

I don't know what to do
Thanks very much!!

**Comment by jonchurch** [comment]
`.array('photo', 3)` is setting the max number of files you can upload at a time.

Uploading 5 exceeds that limit by 2, 7 by 4.

You can remove the `3` to not limit the max number of uploads, or increase the number.

**Comment by ShaoHong1120** [comment]
> `.array('photo', 3)` is setting the max number of files you can upload at a time.
> 
> Uploading 5 exceeds that limit by 2, 7 by 4.
> 
> You can remove the `3` to not limit the max number of uploads, or increase the number.

Thank for your reply!!
