### ISSUE TITLE
Test Cases not work & & Coverage Code not exist !!

### ISSUE THREAD

**Issue by 3imed-jaberi** [expressjs/multer#827]
This test is not the only one that fails, if you fix it, it will result in failure in other tests .. 
As for Coverage, it's not exsit ..

![image](https://user-images.githubusercontent.com/43971542/72666008-23a21780-3a0e-11ea-9a46-af81b80c7e8b.png)

**Comment by jonchurch** [comment]
Hello! Can you give me some more context around what issue you're experiencing?

When I run the test suite with `npm test` on master, all tests pass.

Are you experiencing failing tests on master?

**Comment by 3imed-jaberi** [comment]
> Hello! Can you give me some more context around what issue you're experiencing?
> 
> When I run the test suite with `npm test` on master, all tests pass.
> 
> Are you experiencing failing tests on master?

Yes, when i run a "npm run test", some tests don't pass ..

**Comment by jonchurch** [comment]
Ahhh now I understand what's happening! According to https://github.com/expressjs/multer/issues/181 the tests fail on Windows for reasons specified in that issue.

**Comment by ryhinchey** [comment]
@jonchurch as this is essentially a dupe of https://github.com/expressjs/multer/issues/181, can it be closed?

**Comment by 3imed-jaberi** [comment]
> ecified in that issue.

@jonchurch @ryhinchey thanks, let's go to the solution #832 ..I'm going to close this issue because it’s exist #181 ..
