### ISSUE TITLE
Request Content-Type capitalized?

### ISSUE THREAD

**Issue by mathoglu** [expressjs/multer#837]
Hey all,

First of all awesome project, thx everybody for making this happen.

after some debugging into why the middleware do not work for me, I found out that the type-is library is used to check that the request is valid before continuing. However, it includes a check whether or not the req.headers contains 'content-type' and after playing around a bit, this will make the multer middleware fail in case the header key is 'Content-Type'.

Am a bit confused and this might well be something obvious, but scrolling true the code I can't see any normalizer or similar fixing this? Reading through the documentation/issues I see some mention of using capitalized headers and cannot find any relevant info about this. So, is this and issue with the source-code or am I missing anything here?

Thx

**Comment by LinusU** [comment]
> First of all awesome project, thx everybody for making this happen.

Thx 🎉 

The header names are lower-cased by the built-in http Node.js module:

https://nodejs.org/docs/latest-v10.x/api/http.html#http_message_headers

Are you manually setting headers on `req.headers` in a middleware before Multer? In that case you need to lower-case your header name, or better yet, use the [`setHeader` method](https://nodejs.org/docs/latest-v10.x/api/http.html#http_request_setheader_name_value).
