### ISSUE TITLE
Multer doesnt save all the files.

### ISSUE THREAD

**Issue by andreibabos** [expressjs/multer#842]
I am uploading 2 pictures and it saves only one (always with one pictures less). when I am sending a formdata from FE. It works using postman.

Multer Config
const multer = require('multer')
const path = require('path')
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, 'uploads/')
    },
    filename: function (req, file, cb) {
        cb(null, file.fieldname + '-' + Date.now() + path.extname(file.originalname))
    }
})
const imageFilter = function (req, file, cb) {
    if (!file.originalname.match(/\.(jpg|JPG|jpeg|JPEG|png|PNG|gif|GIF)$/)) {
        return cb(null, false)
    }
    cb(null, true)
}
module.exports = multer({ storage: storage, fileFilter: imageFilter })
................................................................................

Server 
const upload = require('../../Utils/MulterConfig')
 router.post('/facilities', passport.authenticate('jwt', { session: false }), 
        upload.array('media', 5), (req, res) => {
       console.log(req.files.length)
})
..................................................................................
WEB
    [...item].forEach(arrayItem => formdata.append("media", arrayItem))

 "express": "^4.17.1"
  "multer": "^1.4.2",

**Comment by jonchurch** [comment]
This is an issue with your upload form

Try:

`formdata.append("media[]", arrayItem)`

Check out [this section](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) of the FormData API docs. Specifically the part about appending multiple items with the same key name.

**Comment by andreibabos** [comment]
Thanks for reply, it works only with "media", i was using for testing a picture that was filtered because of the mimetype .

**Comment by jonchurch** [comment]
So I understand properly, were you able to solve your issue without making the change I suggested? 

It sounds like you were seeing an image get filtered out because it did not have the proper mime-type, and that was the cause of the issue?

**Comment by andreibabos** [comment]
Exactly, i got confused because it seems i had the correct pictures in
postman collection(so it was working with it), but when I was choosing the
pictures from FE i always had a picture with a bad mime-type.
