### ISSUE TITLE
[Question] About the memory usage during uploading files.

### ISSUE THREAD

**Issue by sihunqu123** [expressjs/multer#845]
```
app.post('/photos/upload', upload.array('photos', 12), function (req, res, next) {
   // mark
  // req.files is array of `photos` files
  // req.body will contain the text fields, if there were any
})
```

1. Like the example given on the homepage, the callback, where I added a 'mark', won't be called until all files have been uploaded/saved in server-side, right?
2. When using DiskStorage(NOT the memoryStorage), during the uploading process, say, I have a 1GB file, multer will 
   A: read the whole 1GB file from the internet(the client) into memory, then write it to disk;
 OR
   B: read some data(like 2Mb), write 2Mb, then read 2MB, wirte 2MB.
 Which one will multer do?

**Comment by jonchurch** [comment]
1. Correct

2. It reads and writes the file as a stream, so B. We are using [busboy](https://github.com/mscdex/busboy) to deal with streaming the files from the upload.

Here's the relevant section of DiskStorage that pipes the filestream to disk:

https://github.com/expressjs/multer/blob/92d83c158d2eca0c9702bf24cdff6d6422ab6ad7/storage/disk.js#L38-L40

Feel free to close if that answers your questions  👍

**Comment by sihunqu123** [comment]
Thanks for your reply, it's very helpful!
