### ISSUE TITLE
Set multiples storage engines

### ISSUE THREAD

**Issue by theochampion** [expressjs/multer#850]
Hi there,

Awesome work with multer, saved me heaps of time <3

I was wondering, is there a way to set multiple storage engines (or chain them) to upload the file to multiple dest. For example, in my case, I need the file to be written on disk (using `DiskStorage`) and uploaded to S3 (using `multer-s3`) at the same time.

Is it possible ? 

Cheers!

**Comment by LinusU** [comment]
With the new API in Multer 2.x this should be really easy, see #399 for more information on the new API, and checkout out [this StackOverflow post on how to pipe to multiple targets](https://stackoverflow.com/questions/19553837/node-js-piping-the-same-readable-stream-into-multiple-writable-targets).

**Comment by jonchurch** [comment]
Closing as no response 👍
