### ISSUE TITLE
File names based on data available after processing the request

### ISSUE THREAD

**Issue by mercmobily** [expressjs/multer#852]
I have a common pattern: I want to allow users to upload a file and decide the final file name depending on the record Id -- which, in POST, I will only know _after_ processing the request.
So, I need the following:

* Know the value of certain NON-attachment posted fields (e.g. shipName, say `arietta`)
* Create a record on the database (e.g. a record with ID `100` is created)
* Make sure Multer saves the file named `100-arietta.pdf` onto the disk

However:
* If I run the multer middleware _before_ the record-creation middleware, the request won't have the body (see: I won't have access to `arietta` nor `100`, which the previous middleware would store in the request).
* If I run the multer middleware _after_ the record creation, the record-creation middleware won't have request.body -- and won't be able to create a record at all

THe only workable solution is to get multer to save the files with a temporary name, and then rename those files. This is a 2-step process I would rather not have.

A possible alternative is to get the record-creation to read the incoming stream, and work out the names/values of the NON-upload fields. However, this would mean doing the work twice.

The only "clean" solution then would be to add an option to multer, something like "preMiddleware", which would be called after reading the incoming data, but before writing the files onto the disk. However, I wonder if this is even possible since I assume Multer reads the incoming data as a stream and needs a "spot" (a file) to write things on "as data arrives".

So, is renaming my only option?

**Comment by jonchurch** [comment]
This is a lot easier to do in the [new version that's soon to be released](https://github.com/expressjs/multer/pull/399#issuecomment-591674599). The docs for the new version are currently on the [`explore-new-api`](https://github.com/expressjs/multer/tree/explore-new-api) branch. 

The latest version can be installed with `npm i multer@2.0.0-rc.1`

Essentially it gives you a stream on the `file` object to allow you to handle the files however you want. Here's a [codesandbox](https://codesandbox.io/s/serene-cray-75ouw) with an example of what I think you're trying to do. You can also checkout the example [here](https://github.com/jonchurch/multer-issue-reproduction/tree/852-rename-after-upload). 

I hope this helps ❤️

**Comment by mercmobily** [comment]
You are an absolute star. This is exactly what I will need.
I am restraining myself from asking "When is V2 out?". I really am.
However, I will go with the "renaming" route for now -- the project I am writing is in production and it's mission-critical, so I can't take risks...

**Comment by mercmobily** [comment]
I saw your code... I will switch to 2.0, it's too good not to be used. Thanks and I am glad I asked this question basically the day/week version 2 is being released!
Was it a rewrite?

**Comment by boy51** [comment]
This is a common scenario for me too. Should I switch to v2 now?

**Comment by LinusU** [comment]
I can absolutely recommend you to start using v2 today, just be aware that we are changing the default limits, so I would watch this PR 👉 #848 so that you know that it will work for you before going from `rc.1` to the final version.

That thing is the last piece of the puzzle before releasing 2.0 final 🚀

**Comment by mercmobily** [comment]
I am absolutely taking the advice. I am not too bothered by default limits. All good. :D
