### ISSUE TITLE
MulterError does not work with typescript

### ISSUE THREAD

**Issue by boy51** [expressjs/multer#853]
The docs say to handle errors we can do this:

```
app.post('/profile', function (req, res) {
  upload(req, res, function (err) {
    if (**err instanceof multer.MulterError**) {
      // A Multer error occurred when uploading.
    } else if (err) {
      // An unknown error occurred when uploading.
    }
    // Everything went fine.
  })
})
```

However, this gives this error: **Property 'MulterError' does not exist on type 'Multer'**.

That is because @types/multer does not have any multerError. MulterError is in node_modules/multer/lib/multer-error.js

Im importing like this: `import multer = require("multer");`
Anything else gives me errors.

Not sure if `@ts-ignore` will help.

**Comment by ryhinchey** [comment]
@boy51 here's a minimal repo I put together to demonstrate how to use the `MulterError` in typescript.  run `npm start` in the below repo to see it in use and you can run `npx tsx index.ts` to see it sucessfully compile to javascript.

https://github.com/ryhinchey/multer-issue-reproduction/tree/typescript

Here's what `index.ts` looks like:
```ts
import { MulterError } from 'multer';

const error = new Error('a custom error');
const multerError = new MulterError('a custom multer error');

console.log(error instanceof MulterError); // false
console.log(multerError instanceof MulterError); // true
```

**Comment by boy51** [comment]
I will try this, thanks. Importing from node_modules when there is the same module in @types is confusing.
