### ISSUE TITLE
Incorrect sequence of file names while accessing req.files.other_insurance_images while uploading multiple files.

### ISSUE THREAD

**Issue by chitra-patil** [expressjs/multer#855]
Used multer in filter while uploading images/files.
```
Route.filter('upload', async (req, res, next, path, ...fields) => {
    let upload = multer({
            storage: multer.diskStorage({
               destination: (r, f, c) => {
                    console.log("Field --> ", f.fieldname);
                    if (f.fieldname === 'insurance_image' || (f.fieldname === 'other_insurance_images') || f.fieldname === 'insurance_image') {
                        c(null, 'app/storage/images/driver/vehicle/insurance');
                    } else if (f.fieldname === 'registration_front_image' || f.fieldname === 'registration_back_image'
                        || (f.fieldname === 'other_registration_images')) {
                        c(null, path + '/registration');
                    } else {
                        c(null, path);
                    }
                },
                filename: (r, f, c) => c(null, `${AdminBaseController.randomNumber(10) + Date.now().toString()}.${f.originalname.split('.')[f.originalname.split('.').length - 1]}`)
            })
        }).fields(
        fields.map(v => {
            return {name: v, maxCount: 50}
        }))
    ;
    await upload(req, res, () => {
        next()
    })
});
```
Issue is occurring due to image sizes that are uploaded. Correct sequence of what I uploaded is as below :

[ { fieldname: 'file',
    originalname: 'file1.jpeg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'public/uploads',
    filename: 'file1.jpeg',
    path: 'public/uploads/file1.jpeg',
    size: 79299 } ]
[ { fieldname: 'file',
    originalname: 'file2.jpeg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'public/uploads',
    filename: 'file2.jpeg',
    path: 'public/uploads/file2.jpeg',
    size: 177608 } ]
[ { fieldname: 'file',
    originalname: 'file3.jpeg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    destination: 'public/uploads',
    filename: 'file3.jpeg',
    path: 'public/uploads/file3.jpeg',
    size: 117312 } ]

While retrieving,
console.log(req.files.other_insurance_images) I got incorrect sequence.

```What i expect : ['file1.jpeg','file2.jpeg','file3.jpeg']``` 
```What i got :['file1.jpeg','file3.jpeg','file2.jpeg']```

**Comment by ryhinchey** [comment]
@chitra-patil can you please add a minimal reproducible example that can show this issue happening with your images included in the example code? A sample repo would be helpful so I can clone and help you debug.

**Comment by ryhinchey** [comment]
I'm going to go ahead and close this issue.  If  a reproducible example can be included, feel free to reopen!
