### ISSUE TITLE
Abort uploading on server side

### ISSUE THREAD

**Issue by ifree92** [expressjs/multer#856]
Is it possible to abort/cancel uploading process?
It is mandatory for me to check authorization before, and only then approve for uploading stream.

I just cannot find a way to cancel uploading process. I need to respond to user 403/401 error before file will be uploaded completely.

`filename`, `fileFilter` callbacks are calling only after file has been uploaded.

When I'm using `req.destroy()` I cannot respond with some exactly error.
Would be happy to get some help on this. Thank you.

**Comment by boy51** [comment]
Are you using v2?

Version 2 makes this quite easy as you get access to the readstream and you can use it to write to the file system in your function. So you could check your authorization and if it fails pass an error to next which will exit out of your route function and not run your write stream.

**Comment by LinusU** [comment]
The easiest would probably be to have a middleware that runs before Multer that checks the authentication/authorisation. That would work with both v1 and v2

**Comment by davidmashe** [comment]
@LinusU seems to have provided an answer, no further activity. Closing for now, we can re-open if issue with multer itself is found.
