### ISSUE TITLE
Vulnerability spotted in minimist

### ISSUE THREAD

**Issue by el-DoloR** [expressjs/multer#859]
Hi,

Have you planned an update to multer to resolve the vulnerability of minimist <= 1.2.3

Best regards,

                       === npm audit security report ===                        

                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           

  Moderate        Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=1.2.3                                                       

  Dependency of   multer                                                        

  Path            multer > mkdirp > minimist                                    

  More info       https://npmjs.com/advisories/1179                             

found 1 moderate severity vulnerability in 327 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by LinusU** [comment]
This is fixed with the release of mkdirp 0.5.3, run `npm update mkdirp --depth=10` or delete your `node_modules` and `package-lock.json` file and run `npm install` again ☺️

**Comment by el-DoloR** [comment]
thanks for your answer, it's good for me

bye
