### ISSUE TITLE
Hangs on Upload

### ISSUE THREAD

**Issue by joelcdoyle** [expressjs/multer#86]
Trying to upload a JPEG and the server application just hangs. No error is logged to console. 
This is express js (4.9.5) running on Parse's Cloud Code platform.

```
// app.js
var multer = require('multer');

app.use(multer({
    dest: './uploads/',
    onError: function (error, next) {
      console.log(error);
      next(error);
    },
    onFileSizeLimit: function (file) {
      console.log('Failed: ', file.originalname);
      fs.unlink('./' + file.path); // delete the partially written file
    },
    onFieldsLimit: function () {
      console.log('Crossed fields limit!');
    },
    onPartsLimit: function () {
      console.log('Crossed parts limit!');
    } 
  }));
```

```
<!--  view.ejs -->
<form method="POST" action="/user/add" role="form" id="myForm" enctype="multipart/form-data" >
  <input type="file" name="avatar" id="avatar"/>
</form>
```

```
// controller.js
exports.add = function(req, res) {
  console.log(req.body);
  console.log(req.files);
}
```

**Comment by prabhash1785** [comment]
I am facing the same problem. I see multer uploads the file but the control never goes to the next middleware. Also I noticed that it does two retries and uploads the file twice before timing out.

Can someone let me know if this issue is resolved in multer ("multer": "^0.1.6")?

**Comment by jakerobers** [comment]
I am getting this same exact issue. It doesnt seem to be resolved yet with the newest version.

**Comment by jpfluger** [comment]
Maybe related to https://github.com/expressjs/multer/issues/72.

**Comment by LinusU** [comment]
The latests body-parser have removed the multipart handler and will not interfere with multer anymore. They have also deprecated using `bodyParser()` right off. Instead you should specify either `bodyParser.json()`, `bodyParser.urlencode()` or both.

Make sure that you are using the latest `body-parser` and feel free to reopen if you still have problems :)

**Comment by Gilthans** [comment]
If you're using Next.Js and this is happening to you, make sure you have the api bodyParser configured to false (see example [here](https://nextjs.org/docs/api-routes/api-middlewares#custom-config)).
Hope this saves someone else the time it took me...
