### ISSUE TITLE
Why the temp files are not removed from disk?

### ISSUE THREAD

**Issue by highfield** [expressjs/multer#861]
I have an app receiving uploads from several remote devices, as multipart form. Each upload includes a couple of images, and some plain-text field. Those data are briefly processed by the app, then sent to a specific storage.

What I see, is the temp folder full of temporary files, and I suspect they are created by Multer, but don't removed. I say that, because there's no other subject creating temporary files, and those names are matching the Multer pattern: 32 hex-digits, no extension. By the way, those files are the uploaded images, and the timestamp matches the actual upload moment.

I'm using Multer 1.4.2. 

The same code works 24/7 on Windows 7 and on Linux, and on both behave the same.

I'd expect that Multer should remove any temp file it creates, but for some reason that won't happen. What can I check in order to solve this problem?

For convienence, here is the TypeScript snippet of the upload service handler:

    //see: https://stackoverflow.com/questions/31881205/uploading-files-using-multer-without-knowing-the-their-fieldname
    app.post('...', context.upload.any(), (req, res) => {
        const imageFile = (req.files as Array<Express.Multer.File>)
            .find(f => f.fieldname === "x_full");

        if (!imageFile) {
            res.status(500).send("Image payload not found.");
        }
        else {
            fs.readFile(imageFile.path, async (err: NodeJS.ErrnoException, buffer: Buffer) => {
                if (err) {
                    res.status(500).send(err);
                }
                else {
                    const input = req.body as IPhotoUpload3;
                    try {
                        const info = new PhotoUploadInfo();
                        ...
                        info.fileName = input.x_fn;
                        info.fullImage = buffer;
                        await context.mediaStore.upsertFrameOriginalMedium(info);

                        res.send();
                    }
                    catch (err) {
                        res.status(500).send(err.message);
                    }
                    finally {
                        // ...
                    }
                }
            });
        }
    });

**Comment by LinusU** [comment]
It seems like you are reading up the entire file into memory, instead of using the `diskStorage` storage engine I would recommend using `memoryStorage` which will give you the buffer right away, saving an unnecessary write + read of the file.

The reason the files aren't deleted is that they aren't ment to be temporary, if you are using `diskStorage` you are ment to want to store the files on disk, and thus it would be counter intuitive if Multer removed the files...

**Comment by highfield** [comment]
> The reason the files aren't deleted is that they aren't ment to be temporary, if you are using `diskStorage` you are ment to want to store the files on disk, and thus it would be counter intuitive if Multer removed the files...

Ah!...so the diskstorage is meant for "definitive" storage, not just temporary! If so, how should I configure Multer in order to leverage the filesystem (e.g. very large files) but also having the ability to remove the files once they're moved to the proper location (cloud blob in my case)?

In other words, I would like to manage the concurrent upload of several images, but possibly avoid an useless memory overload. Disk caching would come to the rescue, but how to remove a file once it is not more useful?

BTW, I'll try the memorystorage as soon as possible, but I can't right now. I wish to test it over the whole weekend, and then I will tell you if that fits for my case.

**Comment by LinusU** [comment]
@highfield the 2.x release candidate got you covered, it does exactly what you describe ☺️ 

More info here: #399 

The final release should be going out very soon unless someone finds a blocker 🎉

**Comment by highfield** [comment]
Awesome!

I'll test the app with the memorystorage in the meantime.

Thanks!

**Comment by highfield** [comment]
Nope. It doesn't work with the memorystorage. Every single upload throws the following error:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
>     at Object.readFile (fs.js:295:10)
>     at /home/cdeveloper/ ... /http-upload.js:108:16
> ...
> 

and line 108 is the one with "fs.readFile" (see snippet above).

BTW, the Multer configuration was patched this way:

```
//init multer
const upload = multer({
    dest: os.tmpdir(),
    //storage: multer.memoryStorage(),
});

```
At this point, I've switched back to the disk storage way: it fills the temp folder, but at least it works well. I'll wait for the incoming next version, then.

**Comment by LinusU** [comment]
@highfield with the memory storage you get the data right away, so you don't have to call `fs.readFile`.

Instead of calling `fs.readFile` with `imageFile.path` and getting `buffer` in return, just directly use `imageFile.buffer`

**Comment by highfield** [comment]
Okay. I'll try nightly, when I can update the app.

**Comment by jonchurch** [comment]
Closing as resolved 🕺🏻
