### ISSUE TITLE
Vulnerability In Minimist 

### ISSUE THREAD

**Issue by Code-Vader** [expressjs/multer#865]
I recently did a npm audit fix yet it required a manual review which pointed out that there's a vulnerability through multer > mkdirp > minimist

**Comment by jonchurch** [comment]
Hey there, this has been addressed by mkdirp 0.5.3.

See these other issues for more info #858 #859 
This can be resolved for now with:
```
npm update mkdirp --depth=10
```

There's also a PR to bump mkdirp dep version for an unrelated issue #862

**Comment by Code-Vader** [comment]
Thank you this solved the problem.
