### ISSUE TITLE
Multiple upload only saves 2 files

### ISSUE THREAD

**Issue by avillarubia** [expressjs/multer#866]
Summary
Multiple uploads only upload 2 files and save to static folder and the rests are the loading animation never stops. Both client and server allow only a maximum of 5 files.
...

### How to reproduce
Below is my sample code the uses React

```js
import React from 'react'
import { FilePond, registerPlugin } from 'react-filepond'
import FilePondPluginFileEncode from 'filepond-plugin-file-encode'
import FilePondPluginImagePreview from 'filepond-plugin-image-preview'
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size'
import FilePondPluginFilePoster from 'filepond-plugin-file-poster'

import 'filepond/dist/filepond.min.css'
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'
import 'filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css'

registerPlugin(FilePondPluginImagePreview, FilePondPluginFileEncode, FilePondPluginFileValidateType, FilePondPluginFileValidateSize, FilePondPluginFilePoster)

const { REACT_APP_API_BASE_URL, REACT_APP_API_PORT } = process.env
const apiBase = `${REACT_APP_API_BASE_URL}:${REACT_APP_API_PORT}`

const Uploader = () => {
    return <>
        <FilePond
            allowFileSizeValidation={true}
            name='files'
            maxFiles={5}
            allowMultiple={true}
            allowFilePoster={true}
            labelIdle='Drag & Drop files or <span class="filepond--label-action">Browse</span>'
            server={`${apiBase}/api/uploads/`} />
    </>
}

export default Uploader
```

in my server is...
```js

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, uploadPath)
    },
    filename: function (req, file, cb) {
        const id = shortid.generate()
        cb(null, `${id}_${file.originalname}`)
    }
})

const mb = 50
const limits = {
    fileSize: mb * 1024 * 1024
}

const upload = multer({ storage, limits }).array('files', 5)

router.post('/', upload, (req, res) => { //TODO: auth before upload...
    console.log('uploading...')
})
```
...

### Expected behaviour
Should upload 5 files.
...

### Additional information
- I tested random files. For every batch to drop down will only pick 2 files and the rest still loading.
- Each files are not 50 mb above. Just dummy images and files were tested.
- Multer doesn't show errors. 
- Using .any() still the same issue.
...

| Environment  | Version
|------------- | -----------
| OS           |  Windows 10 64bit
| Browser      | Chrome Version 80.0.3987.149 (Official Build) (64-bit)
|react           | 16.8.6
|multer | 1.4.2

**Comment by jonchurch** [comment]
Using only the server code you supplied I wasn't able to reproduce the issue (I'm on Mac OS). That means it's most likely an issue with the client and not Multer. 

I see you've opened an issue with [filepond as well](https://github.com/pqina/filepond/issues/472). Just with the code provided, I don't think this is an issue with multer. Closing for now, but we can reopen this if your inquiry with filepond leads to a bug on our side 👍

**Comment by avillarubia** [comment]
@jonchurch ok I understand, thank you

**Comment by jonchurch** [comment]
With a basic html form I was able to upload all five files.
