### ISSUE TITLE
How to get each file's metadata?

### ISSUE THREAD

**Issue by avillarubia** [expressjs/multer#868]
Good day,

My uploader can set metadata in each file and sends to multer. In multer, I want to extract the metadata that is id of each file so that I can save the file uniquely. I saw a question 5 years ago related to this and the answer is not yet clear to me. https://github.com/expressjs/multer/issues/107

Thank you and keep safe everyone

**Comment by ryhinchey** [comment]
@avillarubia multer puts the following fields on the file object by default.  I'm not sure what metadata you're referring to but if you needed to add extra fields to your upload, you could certainly do that.

```
  fieldname:
  originalname
  encoding
  mimetype
  destination
  filename
  path
  size
```

If you have an example you can add including a file with metadata, then we can take a look. Until then, I'm going to close this issue as there's not currently anything we can do on the multer side.
