### ISSUE TITLE
multer is not working on conroller or function.

### ISSUE THREAD

**Issue by Narendra93** [expressjs/multer#871]
Hi
I am using express js and i have getting issue in multer image upload on function.
I have using function called time upload function used but folder is created uploads but image is not move in folder.
```
const matter = requires ('mother');

const upload = multer().single('image');

updateProfile: (req, res) => {
    upload(req, res, (err) => {
      console.log('error>>', err);
    });
}
```
I am using express js. Please let me know. if any have solve issue.

**Comment by LinusU** [comment]
I'm not sure I understand what the problem is. Can you elaborate? Are you seeing an error message?

Please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Narendra93** [comment]
> I'm not sure I understand what the problem is. Can you elaborate? Are you seeing an error message?
> 
> Please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

@LinusU Can you look at that issue.

**Comment by LinusU** [comment]
Which version of Multer are you using?

**Comment by Narendra93** [comment]
> Which version of Multer are you using?

@LinusU i am using this version.
```
"multer": "^1.4.2"
```

**Comment by LinusU** [comment]
I think that you might be missing to pass `{ dest: 'uploads/' }` to `multer`?

**Comment by Narendra93** [comment]
@LinusU 
I have put on multer function but can't working.
like this
```const upload = multer({ dest: 'uploads/' }).single('image');```

**Comment by LinusU** [comment]
Unfortunately I cannot reproduce the issue.

Could you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that I can run on my computer? The easiest is if you create a new Github repository, or you can upload a zip file in the comments here...

**Comment by Narendra93** [comment]
@LinusU I am passing in route. The post method in middlware is not working can you help me.
This is my code
```
const multer = require('multer');

const authMiddleware = (function () {
  const chain = connect();
  [formidableMiddleware(), adminTokenAuth].forEach((middleware) => {
    chain.use(middleware);
  });
  return chain;
}());

const imageUpload = (name, folder) => {
  const upload = multer({ dest: `uploads1/${folder}` });
  return upload.single(name);
};
router.post('/update-profile', [authMiddleware, imageUpload('image', 'user')], updateProfile);
```

**Comment by ryhinchey** [comment]
@Narendra93 could you please add a reproducible example we can run locally?  The code snippet above can not be run locally as is

**Comment by jonchurch** [comment]
The issue is that you're mixing two different form handling packages, formidable and multer. 

@LinusU has contributed to both, so correct me if I'm wrong, but these two can't be used together since they both consume the incoming form data. Use one or the other.

**Comment by LinusU** [comment]
@jonchurch that is correct, only one of those two middlewares can be used per request 👍
