### ISSUE TITLE
 TypeError: Cannot read property 'filename' of undefined (Multer)

### ISSUE THREAD

**Issue by davesantiarlom** [expressjs/multer#872]
const express = require('express');
const router = express.Router();
const path = require('path');
const multer = require('multer');
const Producto = require ('../models/producto');

const storage = multer.diskStorage({
    destination: path.join(__dirname, '../public/imagenes'),
    filename: (req, file, cb) => {
        cb(null, new Date().getTime() + path.extname(file.originalname));
    }
})
var upload =  multer({storage: storage});

//Obtener
router.get('/apirest', async (req, res) => {
    const productos = await Producto.find();
    res.json(productos);
});

//Obtener un especifico producto con su id
router.get('/apirest/:id', async (req, res) => {
    const producto = await Producto.findById(req.params.id);
    res.json(producto);
});

//Enviar
router.post('/apirest', upload.single('image'), async (req, res) => {
    const { nombre, material, tipo, marca, precio } = req.body;
    console.log(req.file)
    const imagePath = req.file.filename;
    const producto = new Producto({nombre, material, tipo, marca, precio, imagePath});
    await producto.save();
    res.json({status: 'Producto Guardado'});
});

//Actualizar
//router.put('/apirest/:id', async (req,res) =>{
//    const { nombre, material, tipo, marca, precio } = req.body;
//    const newProducto = { nombre, material, tipo, marca, precio };
//    await Producto.findByIdAndUpdate(req.params.id, newProducto);
//    res.json({status: 'Producto Actualizado'});
//});

//Eliminar
router.delete('/apirest/:id', async (req,res) =>{
    await Producto.findByIdAndRemove(req.params.id);
    res.json({status: 'Producto Eliminado'});
});

module.exports = router;

**Comment by davesantiarlom** [comment]
File: CreateProducto.js
import React, { Component } from 'react'
import axios from 'axios';

export default class CreateProducto extends Component {

    state = {
        nombre: '',
        material: '',
        tipo: '',
        marca: '',
        precio: '',
        selectedFile: null
    }

    onSubmit = async (e) => {
        e.preventDefault();
        const newProducto = {
            nombre: this.state.nombre,
            material: this.state.material,
            tipo: this.state.tipo,
            marca: this.state.marca,
            precio: this.state.precio,
            image: this.state.selectedFile
        };
        console.log(newProducto)
        await axios.post('http://localhost:4000/apirest', newProducto);
    }

    onInputChange = e => {
        this.setState({
            [e.target.name]: e.target.value
        })        
    }

    onChangeHandler = e =>{
        this.setState({
            selectedFile: e.target.files[0]
        })
    }

    render() {
        return (
            <div className="col-md-6 offset-md-3">
                <div className="card card-body">
                    <h4>Crear Producto</h4>

                    {/** Comentario*/}
                    <div className="form-group">
                        <input type="text" className="form-control" placeholder="Nombre" name="nombre" onChange={this.onInputChange}></input>
                    </div>
                    <div className="form-group">
                        <input type="text" className="form-control" placeholder="Material" name="material" onChange={this.onInputChange}></input>
                    </div>
                    <div className="form-group">
                        <input type="text" className="form-control" placeholder="Tipo" name="tipo" onChange={this.onInputChange}></input>
                    </div>
                    <div className="form-group">
                        <input type="text" className="form-control" placeholder="Marca" name="marca" onChange={this.onInputChange}></input>
                    </div>
                    <div className="form-group">
                        <input type="number" className="form-control" placeholder="Precio" name="precio" onChange={this.onInputChange}></input>
                    </div>
                    <div className="input-group mb-3">
                    <div className="custom-file">
                        <input type="file" className="custom-file-input" name="image"onChange={this.onChangeHandler} required></input>
                        <label className="custom-file-label" aria-describedby="inputGroupFileAddon02">Subir Imagen</label>
                        </div>
                    </div>
                        <form onSubmit={this.onSubmit} encType="multipart/form-data">
                            <button type="submit" className="btn btn-primary">
                                Enviar
                        </button>
                        </form>
                    </div>
                </div>
        )
    }
}

**Comment by ryhinchey** [comment]
Two questions for your post request to /apirest:

1. What does the req.file console log look?
2. can you please share the post request you’re making that includes the uploaded file?  Make sure you’re setting Content-Type header to multipart/form-data

**Comment by ryhinchey** [comment]
I saw your second example after I commented.  Check the Content-Type header that’s sent in your axios post

**Comment by ryhinchey** [comment]
Closing this issue as it doesn't seem to be related to multer
