### ISSUE TITLE
How to have a file name in req.body

### ISSUE THREAD

**Issue by kahwooi** [expressjs/multer#88]
I have a form:
```
     <tr>
      <td><input type="file" name="files"></td>
    </tr>
    <tr>
      <td><input type="text" name="files"></td>
    </tr>
```
With includeEmptyFields: true option, 

I am able to see empty fields, if I left the first one empty
```
files: [ '' ] 
```
How can I have the renamed file name in the req.body:
```
files: [ '', "2938918398132323.txt" ] 
```

**Comment by LinusU** [comment]
Form parsing has been revamped in `1.0.0`, please reopen if this is still an issue with the latest version.
