### ISSUE TITLE
multer not getting files and i am able to see the files in the req body .

### ISSUE THREAD

**Issue by AmirDoreh** [expressjs/multer#884]
i am using axios and FormData to send my files from client to server, on the server i am using multer for handling the datas, 
my client's code for sending is like:
the file's title(the first field of append) for pdf and image are the same as server,
<img width="703" alt="Screen Shot 2020-05-01 at 08 53 34" src="https://user-images.githubusercontent.com/45465967/80785671-bb74dd00-8b89-11ea-9f9d-ea8b91da77ff.png">
and when i send data on the server after multer that append a files to req, i am not able to get the files and its always undefined , the server code's looking like:
<img width="570" alt="Screen Shot 2020-05-01 at 08 54 54" src="https://user-images.githubusercontent.com/45465967/80785751-05f65980-8b8a-11ea-9381-9cc546d805a0.png">
<img width="934" alt="Screen Shot 2020-05-01 at 08 54 12" src="https://user-images.githubusercontent.com/45465967/80785757-0abb0d80-8b8a-11ea-9719-c53d155b375c.png">
`router.post('/uploadANewBook',cpUpload,userController.uploadANewBook);`

and the body of the request after requesting to server is like :
<img width="236" alt="Screen Shot 2020-05-01 at 08 55 27" src="https://user-images.githubusercontent.com/45465967/80785825-3b02ac00-8b8a-11ea-94f2-d71dcf7aa579.png">
How can i solve this?

**Comment by AmirDoreh** [comment]
i am stucked here guys please give me a hand @LinusU @jonchurch

**Comment by panphora** [comment]
Hi @AmirDoreh, I believe you're not appending the actual file to the `FormData`, but only the file path. I think you want something like this:

```
var bodyFormData = new FormData();
bodyFormData.append("myFileArray[0]", pdfDetail.file);
bodyFormData.append("myFileArray[1]", coverDetails.file);
```

Then you'll be able to access the files on the server under `req.body.myFileArray`

**Comment by jonchurch** [comment]
Closing as no response
