### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by ayushantiwal** [expressjs/multer#885]
router.post("/sell", upload.single('image'), (req, res) => {
	const { title, description, number, price } = req.body;
	let errors = [];

	// Check Required Fields/////////////////////////////////
	if (!title || !description || !number || !price) {
		errors.push({ msg: 'Please fill in all given fields.' })
	}

	// Description
	if (description > 70) {
		errors.push({ msg: 'description' })
	}

	if (number < 10) {
		errors.push({ msg: 'Please Number' })
	}
	if (price < 1) {
		errors.push({ msg: 'please Price.' })
	}

	const user = new Users({
		title: req.body.title,
		description: req.body.description,
		number: req.body.number,
		price: req.body.price,
		image: req.file.path

	});
	user.save()
	res.redirect("/")

});

**Comment by AmirDoreh** [comment]
can you put all your files in gist github and leave a link here?
