### ISSUE TITLE
Multer is not calling next middleware if video file is larger then 50 mb in ec2 instance t2 medium but works locally

### ISSUE THREAD

**Issue by shailu26** [expressjs/multer#887]
Hi,
i am getting issue in video file upload.

Multer is not calling next middleware if video file is larger then 50 mb in ec2 instance t2 medium but working totally fine in local development server.

here is my code
```
var storage = multer.diskStorage({
    destination: function(req, file, cb) {
        console.log('in destination common index.js');
        cb(null, 'uploads/')
    },
    filename: function(req, file, cb) {
        const otherDetails = JSON.parse(req.body.otherDetails);
        console.log('this is printing');
        cb(null, file.fieldname + '-' + Date.now() + `.${otherDetails.contentType}`)
    }
});
var upload = multer({ storage: storage });

router.post('/uploadVideo',upload.single('file'), function(req, res) {
  console.log('this is not printing');
});
```
Note:-
I am using pm2 for production i tried to use pm2 start server.js --watch --ignore-watch './uploads'

still no sucess.

Help!!!

**Comment by davidmashe** [comment]
We may not be able to help unless you can show us how this is a multer issue. We cannot debug your ec2 environment, alas, and hard to say if that is or is not the source of the problem. Closing issue for now, we can re-open if more information is given.
