### ISSUE TITLE
E11000 duplicate key error collection: New.users index: username_1 dup key: { username: null }',   [Symbol(mongoErrorContextSymbol)

### ISSUE THREAD

**Issue by ayushantiwal** [expressjs/multer#889]
const mongoose = require("mongoose");
const express = require("express");
const passportLocalMongoose = require("passport-local-mongoose");
const findOrCreate = require('mongoose-findorcreate');

const UserSchema = new mongoose.Schema({
	email: {
		type: String
	},

	passworld: {
		type: String
	},
	googleId: {
		type: String
	},

	title: {
		type: String,
		required: true
	},
	description: {
		type: String,
		required: true
	},
	number: {
		type: Number,
		required: true
	},
	price: {
		type: Number,
		required: true
	},
	date: {
		type: Date,
		default: Date.now
	},
	image: {
		type: String,
		required: true
	}

}
)

UserSchema.plugin(passportLocalMongoose);
UserSchema.plugin(findOrCreate);

const User = mongoose.model("User", UserSchema)

module.exports = User;

**Comment by LinusU** [comment]
This doesn't seem to be a problem with the `multer` package, did you mean to post this to `mongoose`?
