### ISSUE TITLE
Multer upload single req.file is always undefined

### ISSUE THREAD

**Issue by manuelpoelzl** [expressjs/multer#895]
I'm currently trying to integrate Multer into my project, but I can't get it to upload a file.

I have included the example code in my project, it looks like this:

The form:
<form enctype="multipart/form-data">
  <input type="file" name="image" />
</form>

Multer in the router:
var multer = require('multer')
var upload = multer({ dest: 'uploads/' })

The route:
myRouter.post('/create', upload.single('image'), (req, res, next)=> {
});

The upload folder is generated without any problems but I just don't get a file, neither req.file nor req.files is filled. Multer does not throw any errors or anything

**Comment by JoeyKo** [comment]
try `req.files.image`

**Comment by jonchurch** [comment]
Usually this type of issue has to do with your client and how you're sending the file. Make sure that the form or `FormData` you are submitting has a field named `image` (`name="image"` on an html form) since you're telling multer to look for that field when you call `upload.single('image')`.

Without seeing your client and server code, I won't be able to give any more advice than that.

**Comment by manuelpoelzl** [comment]
![image](https://user-images.githubusercontent.com/46539758/82148288-a53a7280-9853-11ea-8655-371d6c143a5a.png)

This is what my form looks like.

And this is how i submit my form to the server:
![image](https://user-images.githubusercontent.com/46539758/82148345-dadf5b80-9853-11ea-9de2-c601dab12c85.png)

**Comment by jonchurch** [comment]
The problem is using `URLSearchParams`. That transforms the form data into the `x-www-form-encoded` format, and multer works with `multipart/form-data`.

The `FormData` browser API already uses multipart and can be sent as a request body without any further processing:

```js
let artifactFormData = new FormData(document.querySelector("#addNewArtifactForm"))

fetch("/file", {
    method: "POST",
    body: artifactFormData
})

```
