### ISSUE TITLE
How to know when all files are uploaded

### ISSUE THREAD

**Issue by kahwooi** [expressjs/multer#90]
If I upload more then one file in a single page, how can I determine all are uploaded, and I get full req.files data before I save the data into the database.

I found out that the database insert started before I get a full list of req.files data. Am I right about this?

**Comment by dsalcedo** [comment]
Multer have function for do this and any more :D y hope this help you.

var express = require('express')
var multer  = require('multer')

var app = express()
var config={
onFileUploadComplete: function (file) {
  console.log(file.fieldname + ' uploaded to  ' + file.path)
},
//.... Do more please read Readme in this proyect

};
app.use(multer({ dest: './uploads/'}))

**Comment by windmaomao** [comment]
the trouble is that this event info is not accessible inside the route. Ex.

    router.post('/upload', function(req, res) {
      // I can find my req.body here
      // but can I get the status of file object ?

same thing, if i do 

    onFileUploadComplete: function(file) {
      // I can get the file object
      // but can i get the req.body here ?

I need some help, I need to pass some additional information to file, I just don't know how.

**Comment by windmaomao** [comment]
ok, i don't know how to change the source code. I wish dest: '\' can be a function call instead of a fixed string.

anyway I realized you can actually put a global variable like this, 

    var recentFile = {};
    app.use(multer({ dest: config.file,
        onFileUploadStart: function (file) {
            recentFile = file;
            recentFile.finished = false;
            console.log(file.originalname + ' is starting ...')
        },
        onFileUploadComplete: function (file) {
            recentFile.finished = true;
        }
    }));
    router.post('/upload', function(req, res) {
        if (recentFile.finished) {
            var parent = req.param('root');
            // move the file
            var loc = path.join(config.file, parent, recentFile.name);
            mv(recentFile.path, loc, {mkdirp: true}, function(err) {});
            console.log(file.fieldname + ' uploaded to  ' + loc);
            recentFile.finished = false;
        }
        res.json({result: 'high five !'});
    });


this way you can grab it and do whatever you want afterwards, it's still a mystery to me that all middleware finished the job before it reaches to my current route. I believe there's still some fishy things going on here, hopefully someone can sort that out here.

**Comment by jpfluger** [comment]
How about using `onParseEnd`? The params passed into the function will be `req` and `next`. Particularly look at `req.files` which will contain all 'file' properies. Then call `next()` to continue the processing flow. This is the safest way b/c `onParseEnd` is called after all form elements (both files and fields like text or radiobutton) have been processed. In this way, the `req` object will have all of it. 

Compare `onParseEnd` to `onFileUploadComplete`. `onFileUploadComplete` is called in the middle of processing the html form, thus there's the chance that not all html fields will have been parsed. Furthermore, the `file` param in `onFileUploadComplete(file)` is a copy, so if you manipulate it, changes won't be reflected in the final req.files structures. You won't have that issue with onParseEnd.

**Comment by windmaomao** [comment]
thank you jpfluger, I believe this is what I have been looking for. Will give onParseEnd a try. thanks.

**Comment by LinusU** [comment]
@windmaomao I just want to chime in and say that after mutler handles over to the next middleware (which could be the router) all the files and fields should have been parsed. Thus you don't need any extra events.

```javascript
var express = require('express')
var multer = require('multer')

var app = express()

app.use(multer())
app.post('/upload', function (req, res, next) {
  // req.files will be populated and finished here!
})
```
