### ISSUE TITLE
How do I get file field in body,not a buffer?

### ISSUE THREAD

**Issue by GengPeng951** [expressjs/multer#900]
The front-end  will send a formdata
```
const formData = new FormData()
formData.append('key1', 'abcdefg')  
//...  
//signatures or some fields required by the storage service
formData.append('image', file)
```

I tried the following code in express, I found that images can be found in req.files,
In fact, I don't need to parse the value of image , I just need to pass the formdata to another service，So how should I get the value of image in formdata

```
app.post(url,  upload.any(), async (req, res) => {
  const formData = new FormData();
  formData.append("key1", req.body.key1);
  //...  
  //signatures or some fields required by the storage service
  formData.append("image", req.body.image);
  return await axios.post(storageImgUrl, formData, { headers });
}

```

**Comment by GengPeng951** [comment]
If you are confused about the meaning of my project, let me explain that my service will verify cookies or other signatures. Therefore, the front end cannot directly call the storage service

**Comment by davidmashe** [comment]
Confused about how this is a multer problem? We might need more information to help. Closing this issue, it will re-open if you can show us more clearly how multer needs an update?
