### ISSUE TITLE
Upload to frontend folder

### ISSUE THREAD

**Issue by JMHurtadoB** [expressjs/multer#901]
Frontend in app.domain.com
Backend in api.domain.com

Is posible upload to a folder in app.domain.com?

**Comment by LinusU** [comment]
Hello @JMHurtadoB,

This depends on how your specific setup looks, but Multer can save the files anywhere so it's certainly possible...

Without more information I cannot really help you, and this request is really out of scope for this issue tracker. Maybe you could open a post at StackOverflow, where you describe your architectural setup and ask for advice?

Good luck!
