### ISSUE TITLE
Can I set the dest (upload folder as /upload/wakeword/${userid} ) dynamically in nestjs?

### ISSUE THREAD

**Issue by raviranjan551994** [expressjs/multer#902]
@Post('upload/wakeword')
    @ApiConsumes('multipart/form-data')
    @UseInterceptors(
        AnyFilesInterceptor({
            storage: diskStorage({
                destination: path.join(__dirname + '/upload/wakeword'),
                filename: editFileName,
            }),
            fileFilter: imageFileFilter,
        }),
    )
    async updateWakeWordUser(@Res() res, @UploadedFiles() files, @Body('userId') userID: string) {
        const response = [];
        files.forEach(file => {
            const fileReponse = {
                originalname: file.originalname,
                filename: file.filename,
                path: file.path
            };
            response.push(fileReponse);
        });
        //return response;
        const wakeWord = response
        const user = await this.userService.updateWakeWordUser(userID, wakeWord);
        if (!user) throw new NotFoundException('User does not exist!');
        return res.status(HttpStatus.OK).json({
            message: 'User has been successfully updated',
            user
        });
    }

**Comment by davidmashe** [comment]
@raviranjan551994 Unsure if this a multer issue or a nestjs issue? Closing issue for now, we are happy to re-open if you can provide a more concise example of what you are trying to do in multer.
