### ISSUE TITLE
confused about line 39 of https://github.com/expressjs/multer/blob/master/index.js

### ISSUE THREAD

**Issue by lisper** [expressjs/multer#903]
I don't understand line 39;  how is "if ((filesLeft[file.fieldname] || 0) <= 0)" intended to work?
(it looks like an attempt to turn off the test, but um...  I don't get it)

Am I confused?

(ugg.  ignore me.  i clearly don't understand booleans in javascript.  sorry)

**Comment by LinusU** [comment]
`filesLeft[file.fieldname]` could evaluate to `undefined`, and adding `|| 0` (`?? 0` in recent versions of Node.js) turns that `undefined` into `0`. Then the value is compared to `<= 0`
