### ISSUE TITLE
Multer type/interface is not exported

### ISSUE THREAD

**Issue by dopecodez** [expressjs/multer#905]
The return type of the normal multer function:
```
const upload = multer({storage, fileFilter});
```
is the class type `Multer` which is defined in `index.d.ts`.

Currently, trying to type the `upload` variable as `upload:Multer` throws a `Return type of exported function has or is using private name 'Multer'` error because the class in not exported from index.

What I'm proposing is to export an interface with this type so that multer can be abstracted and reused effectively when using TypeScript.

**Comment by mastermatt** [comment]
@dopecodez Multer does not currently bundle its own types. They are managed by the community over at Definitely Typed.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/multer
If you open a PR to update those types, the devs who have worked on them in the past will be pinged.

**Comment by dopecodez** [comment]
Thanks for the heads up, @mastermatt , I will raise the issue there as you suggested. Closing as issue not valid.
