### ISSUE TITLE
When using upload-files script, upload doesn't respond

### ISSUE THREAD

**Issue by Tzahile** [expressjs/multer#906]
Hello,
I'm using multer and never encountered problems with it and with the way I implemented it in my server.
Uploading files from web works well, and uploading via python script works well.

Lately I tried creating js script to upload files, and I noticed a strange behaviour;
I use multer.array, with `files` field and a big maxCount, using `diskStorage`.
Using node fs.readFileSync() or fs.readFile() or fs.createReadStream, my script succeeds only when trying to upload few files (5 files).
If I try uploading more than 5 files, upload(req, res, (error) => {...}) doesn't return.

```js
async function SetPathAndUpload(req, res, next) { 
  /* this is the middleware itself */
  try {
    let storage = SetMulterStorage(req, res);
    multerUpload = multer({ storage }).array("files", 600);
    await UploadPathAsync({
      req,
      res,
      multerUpload
    });
    console.log("after multer"); // We never get here
    next();
  } catch (error) {
    res.status(500).send(error.message); // Neither here
  }
}

function SetMulterStorage(req, res) {
  /* Setting the disk storage */
  let newDestination = GetFilesPath(); // Gets some path given from env variable
  return multer.diskStorage({
    destination(req, file, cb) {
      try {
        cb(null, newDestination);
      } catch (error) {
        cb(error); // I added cb(error) after I had read there's no delegation of errors,
      }           // But it didn't really help because everything is being set correctly
    },
    filename(req, file, cb) {
      try {
        cb(null, file.originalname);
      } catch (error) {
        cb(error);
      }
    },
  });
}

function UploadPathAsync({ req, res, multerUpload}) { 
  /* just a promisifed upload, not to deal with callbacks */
  return new Promise((resolve, reject) => {
    try {
      multerUpload(req, res, (error) => { // Debugger gets here
        error ? reject(error) : resolve();
      });
    } catch (error) {
      reject(error);
    }
  });
}
```

The curious part is that when I change my script to **work slower**, everything works fine!
```js

console.log("Uploading files...");
let formData = await AddFilesToForm();
const formHeaders = formData.getHeaders();
axios.post(
  `/api/getfiles`,
  formData,
  {
    headers: {
      ...formHeaders
    },
  }
);

async function AddFilesToForm() {
  let dirpath = "C:/Some/Path/";
  let form = new FormData(); // imported from form-data 
  let files = await AsyncReadDir(dirpath);
  for (let file of files) {
    let streamFile = readFileSync(path.join(dirpath, file), {
      encoding: "binary",
    });
    await Sleep();
    form.append("files", streamFile, file);
    console.log(file);
  }
  return form;
}

function Sleep() {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve("Sleeping..."), 675);
    // If timeout is set to be less than that, multer won't work
  });
}

function AsyncReadDir(path) { // promisifed fs.readdir
  return new Promise((resolve, reject) => {
    readdir(path, (error, files) => {
      if (error) reject(error);
      resolve(files);
    });
  });
}
```

The `Sleep()` function is the key to success here, waiting 675ms after each read makes it work.
As mentioned above, ideally I should use async fs.readFile or fs.createReadStream(), but then it's 'too fast' for multer to handle..

**Comment by ghinks** [comment]
Hello @Tzahile are you still having issues with this? Or did you already resolve the issue? Could you provide a small but complete working program that would demonstrate the issue you are having if it is still an issue.

**Comment by ghinks** [comment]
I hope you have resolved your issue. You did not provide a working example of the issue. I am closing this but will re-open it if requested to.

**Comment by Tzahile** [comment]
Hi, It doesn't happen when using web-client, only with a node-tester I use to mock the web-client.
I saw there were some complaints about the node `form-data` module.

Anyway, I'll try to provide something during the weekend..
Thanks.

**Comment by DiegoDevBittencourt** [comment]
I'm having this problem too, if I change network speed to Fast/Slow 3G on `developer network tab` from `chrome developer's mode` it sends my image file from client to server with no problem, but if I set the speed to `online` (normal) it just doesn't answers me anything and don't upload the image to database. How do you fixed it Tzahile?
