### ISSUE TITLE
Upload File to remote server

### ISSUE THREAD

**Issue by prabhash1785** [expressjs/multer#91]
Can multer be used to upload files on remote server? If yes, then where do I provide the host name, host credentials, etc?

**Comment by jpfluger** [comment]
No, multer will not automatically send uploaded files to a remote server. You could pass in a custom [onParseEnd](https://github.com/expressjs/multer#onparseendreq-next) function. Within it, you would write code to iterate over `req.files` and send to a remote server.

**Comment by prabhash1785** [comment]
Oh that makes sense. This answered my question. I can go ahead and close this issue.
