### ISSUE TITLE
Hangs on Safari 13.1.1

### ISSUE THREAD

**Issue by emauriciomoreno** [expressjs/multer#911]
I have the following code in server side:

<img width="640" alt="Captura de Pantalla 2020-06-24 a la(s) 14 54 26" src="https://user-images.githubusercontent.com/14843244/85621277-a026cb00-b62a-11ea-81cb-2d15baae8fe4.png">

...

<img width="427" alt="Captura de Pantalla 2020-06-24 a la(s) 14 55 21" src="https://user-images.githubusercontent.com/14843244/85621334-bfbdf380-b62a-11ea-97e4-150ccb354a82.png">

Using Chrome (v83.0.4103.116) and Edge (v83.0.478.54) everything works fine, the file uploads and the server sends the response. If I use Safari (v13.1.1) the multer middleware crashes (uploadImage), the file is created with zero size but, the callback function never executed, therefore the following middleware does not run and the server never issues a response. On the client side I use FormData.

**Comment by ghinks** [comment]
hello @emauriciomoreno we see your question. Please can you provide a really small and working piece of code that demonstrates this issue. The express eco system gets many requests a day and having a canned example of possible bugs really helps us.

**Comment by ghinks** [comment]
There has been no response for 5 days and I am closing this issue. I will re-open it upon your request.
