### ISSUE TITLE
diskStorage filename req.body is {}

### ISSUE THREAD

**Issue by greenking19** [expressjs/multer#914]
I want to get the value of req.body when filename(multer.diskStorage), but I found it to be empty. How to solve it?
``` javascript
// svae
const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'public/gltfs')
    },
    filename: (req, file, cb) => {
        //  here is null 😕😕
        console.log(req.body.name)

        let exts = file.originalname.split('.')
        let ext = exts[exts.length - 1]
        let name  = MD5(file.filename + 'gaba')

        cb(null, `${name }.${ext}`)
    }
})


const upload = multer({
    storage
})

// router post save
router.post('/save', upload.single('scene'), (req, res,) => {
    //But you can get it here 😛😛
    console.log(req.body.name)
})
```
The above is my code, I want to save the specified name according to the name in req.body. If it can be done?
😁😁

**Comment by wangfpp** [comment]
遇到了同样的问题

**Comment by wangfpp** [comment]
@greenking19   咱们就用汉语沟通吧  这个问题我解决了但是很奇怪 写代码表达吧：
```javascript
formData.append('type', this.state.videoType);
formData.append('id', this.props.subjectId);
formData.append('file', file);
axios.post(`/api`, formData)
// 上面的是可以在diskStorage的回调里可以获取的
```
### 就是file一定要再其他字段之前传入formdData里面才行
你参考下这个issue 
[官方的回复](https://github.com/expressjs/multer/issues/626)

**Comment by LinusU** [comment]
From the documentation:

> Note that `req.body` might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

I wish I had an easy solution for you but the only thing I can recommend is to manually reorder the fields with javascript to make sure that fields are sent before files.

This has come up a number of times before, e.g. #146 where the workaround is outlined...
