### ISSUE TITLE
I am trying to upload a post to my database using nodeJS but an error is displayed:- TypeError: Cannot read property 'mainimage' of undefined

### ISSUE THREAD

**Issue by Archish2000** [expressjs/multer#915]
TypeError: Cannot read property 'mainimage' of undefined
    at C:\projects\nodejs\nodeblog\routes\posts.js:43:18

posts.js:-

var express = require('express');
var router = express.Router();
var mongo = require('mongodb');
var db = require('monk')('localhost/nodeblog');
var multer = require('multer');

/*router.get('/show/:id', function(req, res, next) {

    var posts = db.get('posts');

    posts.findById(req.params.id, function(err, post){
        res.render('show',{
            "post": post
        });
    });
});
*/

router.get('/add', function(req, res, next) {

    var categories = db.get('categories');

     categories.find({},{}, function(err, categories){
        res.render('addpost',{
            "title": "Add Post",
            "categories": categories
        });
    });
});

//router.post('/add', multer({ dest: './uploads/'}).single('myimage'), function(req,res,next){

router.post('/add', function(req, res, next){
    // Ger form values
    var title    = req.body.title;
    var category = req.body.category;
    var body     = req.body.body;
    var author   = req.body.author;
    var date     = new Date();

    if(req.files.mainimage){               //line 43
            console.log('Uploading files...');

        var mainImageOriginalName = req.files.mainimage.originalname;
        var mainImageName         = req.files.mainimage.name;
        var mainImageMime         = req.files.mainimage.mimetype;
        var mainImagePath         = req.files.mainimage.path;
        var mainImageExt          = req.files.mainimage.extension;
        var mainImageSize         = req.files.mainimage.size;
    } else {
        var mainImageName = 'noimage.png';
    }

addpost.jade:-

extends layout

block content
    h1=title
    ul.errors
        if errors
            each error, i in errors
                li.alert.alert-danger #{error.msg}
    form(method='post', action='/posts/add', enctype="multipart/form-data")
        .form-group
            label Title:
            input.form-control(name='title', type='text')
        .form-group
            label Category:
            select.form-control(name='category')  
                each category, i in categories
                    option(value='#{category.title}') #{category.title}   
        .form-group
            label Body:
            textarea.form-control(name='body', id='body')  
        .form-group
            label Main Image:
            input.form-control(name='mainimage', type='file')
        .form-group
            label Author:
            select.form-control(name='author')
                option(value='Brad Traversy') Brad Travers
                option(value='John Doe') John Doe
        input.btn.btn-default(name='submit', type='submit', value='Save')
        script(src='/ckeditor/ckeditor.js')
        script
            | CKEDITOR.replace('body');
            
app.js:-
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var expressValidator = require('express-validator');

var session = require('express-session');

var bodyParser = require('body-parser');
var mongo = require('mongodb');
var db = require('monk')('localhost/nodeblog');
var multer = require('multer');
var flash = require('connect-flash');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var posts = require('./routes/posts');

var app = express();

app.locals.moment = require('moment');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// Handle file uploads
var multer = require('multer');
var upload = multer({ dest: './public/images/uploads' });

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Handle Express Sessions
app.use(session({
    secret:'secret',
    saveUninitialized: true,
    resave: true
}));

// Validator
app.use(expressValidator({
  errorFormatter: function(param, msg, value) {
      var namespace = param.split('.')
      , root    = namespace.shift()
      , formParam = root;

    while(namespace.length) {
      formParam += '[' + namespace.shift() + ']';
    }
    return {
      param : formParam,
      msg   : msg,
      value : value
    };
  }
}));

app.use(express.static(path.join(__dirname, 'public')));

app.use(flash());
app.use(function (req, res, next) {
  res.locals.messages = require('express-messages')(req, res);
  next();
});

// Make database accessible to router
app.use(function(req, res, next) {
  req.db =  db;
  next();
});

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/posts', posts);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

**Comment by LinusU** [comment]
It seems like you are using `upload.single`, but then are trying to access `req.files.mainimage`. Change the latter to `req.file` instead, and it should work 👍
