### ISSUE TITLE
Handling multiple "related" files

### ISSUE THREAD

**Issue by amirh715** [expressjs/multer#919]
Multer provides files in arrays or fields with arrays.
I'm building a REST API for a music upload and streaming service.
There's an `api.example.com/artist` endpoint that should store an artist's image, her albums' cover images, albums' audio files, plus single tracks by the artist.
The number of albums and singles are variable.
How can I determine which files belong to which albums? Which files are single tracks and which files are their cover images?

**Comment by davidmashe** [comment]
@amirh715 are you having any issues with multer itself? This strikes me as more of an API design question than an issue wih multer.

**Comment by amirh715** [comment]
> @amirh715 are you having any issues with multer itself? This strikes me as more of an API design question than an issue wih multer.

No it's not an issue with Multer. But it can be enhanced to address this feature.

**Comment by davidmashe** [comment]
I am going to close as an API design issue over a multer issue. @amirh715 if you would like to propose a new multer feature in a new issue, we'd be happy to evaluate it.
