### ISSUE TITLE
multer is not working for large files (>100mb)

### ISSUE THREAD

**Issue by AshishPoonia18** [expressjs/multer#920]
hey I'm trying to upload videos on my server using multer in Node js, For video file less than 100mb is working perfectly fine but when size is greater than 100 Mb videos is not got uploaded as well as it's not giving any error (limit is not set).
here I'm sharing code snippet 

    // Index.js File
    router.post('/upload-video', MEDIA.addPostVideo, MEDIA.afterPostVideoUpload);

    // Meadia file

    const postMediaStorage = multer.diskStorage({
        destination: (req, file, cb) => {
            cb(null, dirPath);
        },
        filename: (req, file, cb) => {
            let extension = path.extname(file.originalname) || '.jpg';
            cb(null, file.fieldname + '-' + Date.now() + extension);
        }
    });

    module.exports.addPostVideo = multer({ storage: postMediaStorage }).single('file');

If it's not enough information plz let me know , i will provide more.

i know my writing skill is not good. 
Thank You in advance

**Comment by ghinks** [comment]
It would obviously be best if a fully working example were provided. Is the upload failing from a client browser etc?

I'm not the subject matter expert here, but until one of the multer maintainers steps in I would suggest looking at the timeout of your client sending the data.

How long before it fails?

**Comment by helio-frota** [comment]
I tested locally using this example https://github.com/helio-frota/hold-my-file/tree/multer-920 and it is working fine. 
Of course locally has no network interference but you can checkout this specific branch to take a look :+1:

**Comment by ghinks** [comment]
I think that we will close this @AshishPoonia18. If you provide further information we will naturally re-open the issue but I believe the investigation by @helio-frota means this is a client issue and very likely to do with timing.
