### ISSUE TITLE
documentation is weird about creating custom errors 

### ISSUE THREAD

**Issue by TheGreatDaniad** [expressjs/multer#924]
After three days of struggling with codes and asking in communities, I finally found out that I need to create custom errors in the storage strategy scope using the first argument of cb() function. There was no mention in the documentation, though! 
The documentation is really poor about error handling.

**Comment by ghinks** [comment]
For the multer maintainers to make progress with this discussion about improving the documentation could you provide a small but complete example of your issue that is not covered by current documentation.

**Comment by davidmashe** [comment]
@TheGreatDaniad closing issue for now, we can re-open when an example is provided.
