### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by Jahazielvaz** [expressjs/multer#927]
I've encountered this bug before. I guess there is a chance I'm not doing something right, but multer was working on previous projects and it no longer works. It recognizes req.file, but when I try to persist the target file into the database, this is what I get "Cannot read property 'path' of undefined". I've already updated every version of all the packages I'm using but it's still not working. Any ideas?

**Comment by ghinks** [comment]
Please can you provide a minimal working example for the maintainers. We can investigate a working issue. This is really a forum for issues. But without a small minimal working example of the issue in question it is difficult to address issues resulting in 'undefined'

**Comment by Jahazielvaz** [comment]
Here's my app.js file. I'm removing all irrelevant code
`
const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const photoRoutes = require('./api/photos');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));

mongoose.connect(`mongodb+srv://jazzy:${process.env.PASSWORD}@journal.26ukp.mongodb.net/photo-uploader?retryWrites=true&w=majority`, {
  useNewUrlParser: true,
  useUnifiedTopology: true
})

app.use('/photos', photoRoutes);


module.exports = app;

`

Heres my photos file, which contains the routes. I'm only showing the post route because that's the only relevant one right now. 
`
const express = require('express');
const router = express.Router();
const multer = require('multer');
const mongoose = require('mongoose');

const Photo = require('./photosModel');

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, './uploads/')
  },
  filename: (req, file, cb) => {
    cb(null, new Date().toISOString() + file.originalname)
  }
});

const upload = multer({
  destination: storage,
  limits: {fileSize: 1200 * 1200 * 5}
})


router.post('/', upload.single('imageId'), (req, res, next) => {
  const photo = new Photo({
    _id: new mongoose.Types.ObjectId(),
    imageId: req.file.path
  });

  photo.save()
    .then(result => {
      res.status(200).json(photo)
    })
    .catch(err => {
      res.status(500).json({
        error: err
      })
    })
});

module.exports = router;

`

Here's my model (photosModel.js) which will persist my data to the db
`
const mongoose = require('mongoose');

const photoSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  imageId: {type: String, required: true}
}, {collection: 'photos'});

module.exports = mongoose.model('Photo', photoSchema);

`
Let me know if you need anything else. Thank you

**Comment by davidmashe** [comment]
@Jahazielvaz Thank you for the code, but can you show how you have isolated the issue to point to multer as the problem? We cannot debug code for every issue, but if you can show us that the bug comes from multer, we can take this further.

**Comment by davidmashe** [comment]
Closing this issue, @Jahazielvaz we are happy to re-open if you can provide evidence that indicates the framework is the source of the error.
