### ISSUE TITLE
Cannot change default Icon.

### ISSUE THREAD

**Issue by DevChrisDev** [expressjs/multer#928]
Functionality of having the option to change the icon would be very nice.

**Comment by LinusU** [comment]
Hmm, are you sure that you opened this issue on the correct repository? What icon are you trying to change? Multer is an Express middleware for file uploads, and doesn't present anything graphical in itself...

**Comment by davidmashe** [comment]
Closing issue for now, @DevChrisDev we can re-open after confirming multer is the correct repository and is the source of the issue.
