### ISSUE TITLE
How to save defined amount of images before submitting

### ISSUE THREAD

**Issue by tempo220496** [expressjs/multer#932]
Hello my issue is that how multer can save definitely amount of images. For example in my project when a user upload several images in the near block those images display with image tags, every action happens before submitting form and if a user wants to delete one of images it must be saved on the multer without deleted image before submitting, I defined there with value definedImages when clicking delete in client side and submit it sends to server, after that when it pushes defined images in the directory it saves incorrectly but correct amount of files.I pointed out that it saves files immediately. How can it be done?

**Comment by davidmashe** [comment]
Might need some code to understand your request.

**Comment by davidmashe** [comment]
Closing until issue with multer can be demonstrated
