### ISSUE TITLE
Handling "File too large" properly

### ISSUE THREAD

**Issue by NorteX-dev** [expressjs/multer#938]
So, I'm using this code:
```js
const multer = require(`multer`);
let storage = multer.diskStorage({
	destination: function (req, file, cb) {
		cb(null, 'usercontent/avatar/')
	},
})
const upload = multer({
	storage,
	limits: {
		fileSize: 2000000,
		files: 1,
	}
});
```
Now, that __works__. However, when a user inputs a file bigger than 2000000 bytes (2MB) the only thing that happens is an error stack in the console.

How could I display the error to the end-user by either: sending back JSON content or redirecting and silence the error in the console?
Checking if `!req.file` in the POST request won't suffice, as the field is optional and **can be blank** (which is expected and checked for). I tried to try/catch both the `upload` variable and the post request but the error sits somewhere deeper.

If I could use a function to verify the file size before the saving occurs (just like in `destination` or `filename`), then this wouldn't be a problem but is currently, as the object only takes a plain number (__correct me if wrong__).

**Comment by NorteX-dev** [comment]
Bump

**Comment by NorteX-dev** [comment]
Ok, since nobody is responding and this thread is basically I'm closing it and I will attempt to fix it myself in the source code.

**Comment by pcdependency** [comment]
You figure something out?

**Comment by NorteX-dev** [comment]
No, I switched libraries.

**Comment by simondixit** [comment]
Hey there! I set this in my middlewares and it does work! =)

```
    this.server.use(
      '/api/v1/upload',
      (req: express.Request, res: express.Response, next: express.NextFunction) => {
        upload(req, res, (err: any) => {
          if (err) {
            res.status(500).json(err)
          }
          next()
        })
    })
```
