### ISSUE TITLE
Line Break Requirements - Empty Request Body

### ISSUE THREAD

**Issue by chhatch** [expressjs/multer#939]
I'm in a situation where I have to construct multipart/form-data request bodies manually. I have been struggling, at my wits end, for the past two days to get Multer to parse the data instead of giving me an empty object. I have finally discovered that the issue was that the line breaks in my request body were `\n` while they apparently need to be `\r\n`. A couple of quick searches through the [multipart/form-data spec](https://www.ietf.org/rfc/rfc2388.txt) didn't yield any results, nor did I find anything in the documentation here. I'd happily submit a pull request, but I don't know what the rules actually are.

Also, thanks for the great library! It made handling multipart form data very easy until I recently had to move away from using FormData on my front end.

**Comment by dougwilson** [comment]
RFC 2388 was not well written back in 1998. Thankfully is is irrelevant as it has been obsoleted by https://tools.ietf.org/html/rfc7578 which I believe has the rules you were looking to find.

**Comment by chhatch** [comment]
"As with other multipart types, the parts are delimited with a boundary delimiter, constructed using **CRLF**, '--', and the value of the 'boundary' parameter."
— RFC 7578

You are correct. Thanks for the response!
