### ISSUE TITLE
onParseEnd find out file.path

### ISSUE THREAD

**Issue by marcodpt** [expressjs/multer#94]
If I don't use rename function, is there an easy way to see file.path when I call next() on function "on Parse End"? I'm asking that because I can't figure out a way to find out the file that was just uploaded to update my database. Amazing module anyway!!!

**Comment by marcodpt** [comment]
Sorry for my question... I already find that you can access req.body.files with full file information!

**Comment by mkozjak** [comment]
It's req.files, actually. :)
