### ISSUE TITLE
Node 14.15.0 Unable to send files with multipart formdata

### ISSUE THREAD

**Issue by superheri** [expressjs/multer#955]
* **Multer version**: 1.4.2
* **Platform**: Windows 10 2004
* **Subsystem**:

### What steps will reproduce the bug?

Uploading a file using express with multer is not working anymore. The file is most of the time (sometimes it works, don't know why) not really sended correctly to the server.

It's not giving any error, just jamming there without log.

### What is the expected behavior?

I expect the file to be on the webserver and my middlewares to continue the request with the file.

### What do you see instead?

It it jamming at a point I don't know. All I can see is that if I use a temporary folder, the file is only there partly.

### Additional information

The only way for me to get it working is now to downgrade the version of node to 12... Not much interesting.

**Comment by shreyasg-git** [comment]
Hey @superheri  can you show the code which is dealing with Multer? I have recently implemented file uploads using Multer  and it is working perfectly fine !

**Comment by superheri** [comment]
@shreyasg-git In my case, I'm not even doing anything special :

```js
const multer = require('multer');
const router = require('express').Router();
module.exports = router;

router.post('/upload/', 
//Some middlewares checking access rights
multer().any(),
//Other middlewares
);
```

It works pefectly fine with Node 12.X, but at the second I try using Node 14.X it fails most of the time. (some rare times it works, it's weird)

**Comment by mwoodsy** [comment]
I'm having the exact same issue, I posted on stackoverflow but not responses yet
[Express Multer does not work when using node version 14.15.1](https://stackoverflow.com/questions/64938967/express-multer-does-not-work-when-using-node-version-14-15-1)

**Comment by superheri** [comment]
Tried creating an issue in express : expressjs/express#4458 but they don' seem to want to help
Also created an issur in node directly but no answer there nodejs/node#35980

**Comment by mwoodsy** [comment]
Good news I found whats causing the issue for me but I haven't found a fix yet. I have a block of code that looks like this:

`app.use(function (req, res, next) {
  res.locals = {
    version: '1'
  };
  next();
});

app.use('/', indexRouter);`

if I comment out that `res.local ...` line the upload works.

**Comment by mwoodsy** [comment]
I was able to resolve my problem by only setting `res.locals` during a GET

```
app.use(function (req, res, next) {
  if (req.method == 'GET') {
    console.log("this is a get")
    res.locals = {
      version: 'version'
    };
  } else {
    console.log("this is a", req.method)
  }
  next();
});
```

**Comment by superheri** [comment]
This mostly seems like a workaround... In my case it's not really possible because I need to use the res.locals to keep infos about my connection to the database.

Maybe it can help debug the problem though.

**Comment by mwoodsy** [comment]
i have a connection to the database too but i keep that tied to the request not the response. I removed it from my code above to not confuse you.

```

app.use(function (req, res, next) {
  req.db = connection // this is my database connection
  if (req.method == 'GET') {
    console.log("this is a get")
    res.locals = {
      version: 'version'
    };
  } 
  next();
});

```

**Comment by superheri** [comment]
No matter how we handle our data in req/res should not be causing problems with file imports. It was working fine with node 12.X.

And res.locals should be possible to use to store local data for the response.

I use so much different flags or other data in res.locals that it's not possible for me to remove all that. That workaround does not work for me sadly.

**Comment by mwoodsy** [comment]
Just one, more thing I forgot I changed. I originally had my database connection tied to the request and it was called `req.connection` I changed that to `req.dbconn` 

When testing that seemed to make a difference too.

**Comment by superheri** [comment]
In that case, if it really is the fact of overriding req.connection, this should be my problem in this case... I'll have to try it but sadly I won't be able to answer on this soon...

**Comment by superheri** [comment]
Sorry for the delay, but I tested it more, and the problem is really overriding req.connection. Since it is not a bug with multer, but a bad usage, I'm closing this.
