### ISSUE TITLE
Access other post param values

### ISSUE THREAD

**Issue by longieirl** [expressjs/multer#96]
Hi,

Have been using multer and find it a great module. Wondering how I can post a third param to a post form-data object i.e I'm uploading two files each with the key called 'file', I would like to add a third filed isLink which will be read by the controller and apply some logic. However, when I access req.files or req.params I cant see the param.

Any help is appreciated.

Thanks.

J

**Comment by aneihousepsw** [comment]
Non-file fields are under req.body.<field name>.

A

**Comment by dsalcedo** [comment]
Use this for see al options ;)
 var files = req.files
console.log(files)

**Comment by jpfluger** [comment]
In addition to @dsalcedo, I'll add that with multiple file fields, you might want to set options.putSingleFilesInArray : true`. This way you'll be guaranteed that req.files will be returned as an array.  Currently, if multer senses the field-file is singular, req.files is not an array of objects but is a singular object.

**Comment by LinusU** [comment]
@longieirl As @aneihousepsw said I what you want is to access `req.body.isLink`.

`req.params` is populated from the express path (e.g. `/hello/:name` => `req.params.name`).

`req.files` is only for files.

`req.body` contains the parsed fields that isn't files.

**Comment by MChelik** [comment]
Hello guys,
I'm encountering very weird problem. `req` has `body` and it has the `apiKey` parameter that client sends via file upload as you can see in console.log
![image](https://user-images.githubusercontent.com/6281698/49170354-fea39e80-f34c-11e8-8866-d57817524615.png)
But req.body.apiKey is undefined. When I trt to JSON.stringify(req.body), I get "Converting circular structure to JSON" error.
Do you have any idea how can I access client's parameters?
Thank you

**Comment by MChelik** [comment]
Nevermind, I changed order of apiKey before the image. Now everything is fine. I hope this helps someone some day. Sorry for notifications.
Have a nice day

**Comment by PulkitAgg** [comment]
@MChelik Its work but don't understand how it works. Do you have any idea about it?

**Comment by MChelik** [comment]
@PulkitAgg don't touch a thing that works ;]
no idea btw

**Comment by devqazi** [comment]
@PulkitAgg  @BloodhoundAllfather  (Hey another apex legends fan!). It works because form is posted to server by browser as a stream and chaning the order of fields makes it so the browser sends the id to the server. This behavior is because a multipart form data is actually streamed over time to server so if you put the field after the file inuput it is sent after file is pushed to the server.
