### ISSUE TITLE
can't access to file in error handler

### ISSUE THREAD

**Issue by shahrairenayaty** [expressjs/multer#960]
I need size of the rejected file in error handler , how can i get it ? req.file return undefined in error handler.
`    
      var multer = require('multer')
var upload = multer().single('avatar')
app.post('/profile', function (req, res) {
  upload(req, res, function (err) {
    if (err instanceof multer.MulterError) {
         const size = req.file.size
      // A Multer error occurred when uploading.
    } else if (err) {
      // An unknown error occurred when uploading.
    }
    // Everything went fine.
  })
})`

**Comment by up-the-dev** [comment]
two types of error multer returns .
1.Error while parsing file through multer middleware.
2.Error when file is being uploading to the destination.
If error comes from 1st case then file object is not get attached to req object , so you cannot access file object . This is what happened in your case . You can't use req.file.size . please first configure storage . after that if error  comes then file is attached with req so you can use req.file.size
