### ISSUE TITLE
DigitalOcean

### ISSUE THREAD

**Issue by CrackerakiUA** [expressjs/multer#98]
Well this is not a problem of multer, but i don't know what to do. I have tried multer on my local and my personal server and it's work great, but when i upload my project to https://cloud.digitalocean.com i found out that any upload i made report me that file is created successfully but file don't appear on the server. Any idea what they could change in server setup (Ubuntu)? I have added all kind of permissions to user which is holding the application.

**Comment by alist** [comment]
Some people have [had issues] (https://www.digitalocean.com/community/questions/file-system-went-read-only-after-adding-ssh-key) with DO and filesystem write permissions. You may see whether a new DO instance makes a difference. 
Have you tried inspecting the output after setting inMemory = true on the Multer file object?

``` node
app.use(multer({inMemory: true, onFileUploadComplete: function(file, req, res){
console.log(file);
}}))
```

**Comment by CrackerakiUA** [comment]
i have solved this, and sorry for didn't reply here. I changed the config path of "./files" where was the the folder files with full path "/home/td/project/files"

**Comment by alist** [comment]
Great! Go-ahead and close the issue when you get a chance.
