### ISSUE TITLE
When using fileFilter callback req.body is null

### ISSUE THREAD

**Issue by meisamrce** [expressjs/multer#980]
When using fileFilter callback
If we send the information in this way req.body is null
let file = document.querySelector('#file');
let formData = new FormData();
formData.append("file", file.files[0]);
formData.append("username", 'meisam');

But if we send in the following order, the correct information will be received

let file = document.querySelector('#file');
let formData = new FormData();
formData.append("username", 'meisam');
formData.append("file", file.files[0]);

Please fix this problem!

my code :

async function upload_check(req, file, cb) 
{
    try {
        let user = userAuth.get('user');
        if( !isUndefined(user.file) && user.file !== "")
        {   
            req.validationErrors = {"result":"alredy file upload!"};
            cb(null, false);
            return;
        }
        let username = safeString(req.body.username);        
        let username = await model.checkUsername(username);
        if(username > 0)
        {
            req.validationErrors = {"result":"username is alredy"};
            cb(null, false);
            return;
        }
        req.validationErrors = "";
        fileFilter(req,file,cb)
    } catch (e) {
    }
};
const uploader = multer({storage: storage, fileFilter: upload_check});
let uploadFile = uploader.fields([{ name: 'file',maxCount: 1 }]);
router.post('/upload',isAuth,uploadFile,async (req,res)=>{
    try{
        if(!isUndefined(req.validationErrors) && req.validationErrors != "")
        {   
            res.json(req.validationErrors);
            return;
        }
        else
        {
            var isUpload = Object.keys(req.files).length;
            if(isUpload == 0)
            {
                res.json({"result":"file not send"});
                return;
            }
            else
            {   
                let file;
                let username = safeString(req.body.username);        
                if(req.files && Object.keys(req.files).length > 0 && !isUndefined(req.files.file))
                {
                    let filename = req.files.file[0].filename;
                    file = `file/${filename}`;
                }  
                res.json({"result":"ok"});                        
            }   
        }
    }
    catch (e)
    {
    }
});

**Comment by AbdeenM** [comment]
Thanks @meisamrce was facing the issue of `req.body` not being populated and couldnt figure out the issue.
To anyone facing this, make sure your `file` data are the last `append` made to the form data.
