### ISSUE TITLE
Solved!

### ISSUE THREAD

**Issue by anantt-08** [expressjs/multer#985]
@devserkan Hey, I had forgotten this issue out of frustration but saw your comment a while back and had an a-ha moment ... I think you are correct, this is intended behavior of the hot-reloader when it detects that a new file has been entered into the project. I've noticed the same refreshing when I have added photos manually to an open React project that I am working on. I think the issue is the refresh occurring in the middle of a fetch() call which never really resolves properly, giving this error, and producing an inconsistency on whether the backend server successfully pushes that file through and does all necessary logics. Somewhat shamefully I haven't actually tried to disable hot-reloader or even run the app in prod mode, but I believe that this issue may be solved when hot reloader is not in play as you mentioned. So good thinking :D

_Originally posted by @Mikhail-MM in https://github.com/expressjs/multer/issues/566#issuecomment-408275408_

**Comment by lucasraziel** [comment]
OK, It seems this issue is already solved. Thanks.
