### ISSUE TITLE
Properties never on req.body, so not parsed

### ISSUE THREAD

**Issue by knownasilya** [expressjs/multer#99]
According to [this](https://github.com/expressjs/multer/blob/master/index.js#L57) if the value is on `req.body`, then it gets parsed.

I do a formdata post, and the `fieldname` is `exercise[muscles]` which is an array, but it's not on `req.body` (it's `{}`)... So it never gets passed as an array, but a comma separated string..

**Comment by LinusU** [comment]
Multer only parses `multipart/form-data`, are you sure that your data isn't arriving as urlencoded since there isn't any files attached?

You could try to add the following code to see the content-type that is sent to the server.

```javascript
app.use(function (req, res, next) {
  console.log(req.get('Content-Type'))
  next()
})
```

Feel free to reopen if you find more info :)
