### ISSUE TITLE
res.file undefined using multer in node.js

### ISSUE THREAD

**Issue by prem-jethwa** [expressjs/multer#997]
Postman its work proper with 201 status but while requesting with fetch using form-data its showes req.file undefine in node console. stuck with this since last 2 days done many search not find any solution.
please help

**Comment by prem-jethwa** [comment]
```
Back-end code:

require('./db/mongoose');
const express = require('express');
const app = express();
const port = process.env.PORT || 3000;
const userRouter = require('./routers/user');
const cors = require('cors');
const multer = require('multer');

// middleware
app.use(cors());
app.use(express.urlencoded({extended: false}));
app.use(express.json());
app.use(userRouter);
```
const uploadImage = multer({
  limits: {
    fileSize: 1000000,
  },
  fileFilter: function (req, file, cb) {
    if (!file.originalname.match(/\.(png|jpeg|jpg)$/))
      return cb(new Error({type: 'error', message: 'File must be .png OR .jpg'}));
    cb(null, true);
  },
});
// Avatar Router
router.post(
  '/avatar',
  uploadImage.single('userAvatar'),
  async (req, res) => {
    console.log(req.files); // undefined

    res.send();
  },
  (err, req, res, next) => {
    res.status(400).send({type: 'error', message: err.message});
  }
);


app.listen(port, () => console.log(`Server is Running on PORT:${port}`));

**Comment by prem-jethwa** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form enctype="multipart/form-data">
      <input id="imgFile" type="file" name="avatar" />

      <img src="" alt="" class="image" />
    </form>

    <script>

      const form = document.querySelector('form');
      const input = document.getElementById('imgFile');
      const image = document.querySelector('.image');

      const sendToServer = async function (formData) {
        const data = await fetch('http://localhost:3000/avatar', {
          method: 'POST',
          // mode: 'cors',
          // cache: 'no-cache',
          // credentials: 'same-origin',
          headers: {
            'Connection': 'keep-alive',
            'Accept': '*/*',
            'Content-Type': 'multipart/form-data; boundary=helldfkljksf',
          },
          body: formData,
        });

        console.log(data.json());
      };

      input.addEventListener('change', async () => {
        const file = input.files[0];

        // const formData = {userAvatar: file};
        var formData = new FormData();
        formData.append('userAvatar', file, file.name);

        const data = Object.fromEntries([...formData]);
        const arrData = Array.from(formData);

        console.log(data, formData, arrData, file);
        await sendToServer(formData);
      });
    </script>
  </body>
</html>``

**Comment by jwigley** [comment]
```js
...
async (req, res) => {
  console.log(req.file); // req.file when using "single"

  res.send();
},
```

**Comment by prem-jethwa** [comment]
> Use `req.file` instead of `req.files` when using multer single().
> ```js
> ...
> async (req, res) => {
>   console.log(req.file); // req.file when using "single"
> 
>   res.send();
> },
> ```

Yes i have used req.file not req.files copy paste mistake

**Comment by jwigley** [comment]
Are you saying it's still not working (even with `req.file`)?

I was able to cut and paste your backend code, make that `req.file` change, and it worked. I was only testing making requests via Postman though, so did not test your frontend POST request.

**Comment by prem-jethwa** [comment]
> 
> 
> Are you saying it's still not working (even with `req.file`)?
> 
> I was able to cut and paste your backend code, make that `req.file` change, and it worked. I was only testing making requests via Postman though, so did not test your frontend POST request.

yes its still not working . i don't know what is the problem a (new FormData()) constructed properly or file does not encoding in server .. etc

**Comment by jwigley** [comment]
Maybe first verify the backend works with Postman or curl.

```shell
curl --request POST 'http://localhost:3000/avatar' \
--form 'userAvatar=@"/path/to/your/file.png"'
```
If that works, then you can definitely narrow it down to the frontend.

The code you have doesn't look much different from what Postman generates for fetch:
```js
var formdata = new FormData();
formdata.append("userAvatar", fileInput.files[0], "file.png");

var requestOptions = {
  method: 'POST',
  body: formdata,
  redirects: 'follow'
};

fetch("http://localhost:3000/avatar", requestOptions)
  .then( ...
```

Good luck!

**Comment by prem-jethwa** [comment]
> Maybe first verify the backend works with Postman or curl.
> 
> ```shell
> curl --request POST 'http://localhost:3000/avatar' \
> --form 'userAvatar=@"/path/to/your/file.png"'
> ```
> 
> If that works, then you can definitely narrow it down to the frontend.
> 
> The code you have doesn't look much different from what Postman generates for fetch:
> 
> ```js
> var formdata = new FormData();
> formdata.append("userAvatar", fileInput.files[0], "file.png");
> 
> var requestOptions = {
>   method: 'POST',
>   body: formdata,
>   redirects: 'follow'
> };
> 
> fetch("http://localhost:3000/avatar", requestOptions)
>   .then( ...
> ```
> 
> Good luck!
in postman it works fine, some mistake in frontend .. not getting whats the mistake

**Comment by prem-jethwa** [comment]
My problem had been solved, the problem was the header of my client where I have set the "Content-Type : multipart/form-data boundary=---some-random-string" becouse of this boundary server side does not have access to my form-data.
To make this work I have removed the "Content-Type" from header in client side.

**Comment by abadrangui** [comment]
Note if you're using Firebase Functions,

Turns out multer doesn't work with Firebase functions like forever ([stackoverflow](https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase))

So you need to use other packages.
I'm using express-multipart-file-parser for now

**Comment by rajkumardongre** [comment]
Thankyou @abadrangui works for me 🤝
