### ISSUE TITLE
My req.body is empty. What did I do wrong?

### ISSUE THREAD

**Issue by DragonOsman** [expressjs/multer#999]
Hi, everyone.  I need someone help with an issue I'm facing with using Multer for a project challenge for FreeCodeCamp.

The challenge page on FreeCodeCamp is [here](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice).

[This](https://github.com/DragonOsman/filemetadata-project) is what I have right now.  You only need to look at the HTML code and the server.js file (the `app.post` method which starts on line 21, for the latter).  I'm mainly just editing the server.js file, though.  I only made minor changes to the HTML after cloning the [boilerplate repository](https://github.com/freeCodeCamp/boilerplate-project-filemetadata/) from the [FreeCodeCamp GitHub](https://github.com/freeCodeCamp).  

Anyway, right now the `req.body` that I get from the `console.log` call on line 22 in the server.js file is empty.  I don't know what went wrong.  Would someone help me see what I did wrong?  I wanted to print the body to the console first so I could see what's there and how I could access it.

Thanks in advance for any replies.

**Comment by jwigley** [comment]
I had a quick look at your form (https://github.com/DragonOsman/filemetadata-project/blob/gomix/views/index.html) and it looks like you only upload a file, no other text inputs. 

The file uploaded will be available at `req.file`.
If you add some text inputs to your form, those would appear under `req.body`.

**Comment by DragonOsman** [comment]
Alright, thanks.  I should've looked into Request objects more, I guess.
